### ISSUE TITLE
Control beep

### ISSUE THREAD

**Issue by mehmetu61** [joBr99/nspanel-lovelace-ui#100]
Hello, can you control the integrated speaker?

**Comment by joBr99** [comment]
what do you want to do with the buzzer?

you can control it over tasmota commands

`buzzer 10,1`

**Comment by mehmetu61** [comment]
when I click on something it makes a soft beep

**Comment by bkbartk** [comment]
You could check tasmota rules. 
“buzzer” 
Makes the device beeb if BuzzerPWM is enabled

**Comment by mehmetu61** [comment]
thx

**Comment by chrislauyp** [comment]
@mehmetu61 
Hi there, did you manage to get the 'beep on touch' automation working?  Pls can you share your codes, thanks

**Comment by joBr99** [comment]
See #462
