### ISSUE TITLE
[BUG] Implement weather forecast via service

### ISSUE THREAD

**Issue by WhistleMaster** [joBr99/nspanel-lovelace-ui#1001]
### PROBLEM DESCRIPTION
The weather forecast is not displayed.

### REQUESTED INFORMATION
- [X] Provide your apps.yaml (or your config):
```
nspanel:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota/RESULT"
    panelSendTopic: "cmnd/tasmota/CustomSend"
    sleepTimeout: 20
    sleepBrightness:
      - time: "07:00:00"
        value: 10
      - time: "22:30:00"
        value: 0
    screensaver:
      entity: weather.forecast_tempest
```

- [X] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
2023-10-25 20:19:44.829451 WARNING nspanel: ------------------------------------------------------------
2023-10-25 20:19:44.829627 WARNING nspanel: Unexpected error in worker for App nspanel:
25 20:19:44.829779 WARNING nspanel: Worker Ags: {'id': '8900bddc9e354793a43a8c4e6611d76c', 'name': 'nspanel', 'objectid': '4657051707ee42ea8a2936d39a0af1b3', 'type': 'state', 'function': <bound method LuiController.state_change_callback of <luibackend.controller.LuiController object at 0x7f3cd7035ea0>>, 'attribute': 'all', 'entity': 'weather.forecast_tempest', 'new_state': {'entity_id': 'weather.forecast_tempest', 'state': 'rainy', 'attributes': {'temperature': 12.8, 'dew_point': 8.9, 'temperature_unit': '°C', 'humidity': 77, 'pressure': 1003.4, 'pressure_unit': 'hPa', 'wind_bearing': 178, 'wind_gust_speed': 15.84, 'wind_speed': 7.2, 'wind_speed_unit': 'km/h', 'visibility_unit': 'km', 'precipitation_unit': 'mm', 'attribution': 'Weather data delivered by WeatherFlow', 'friendly_name': 'Forecast Tempest', 'supported_features': 3}, 'last_changed': '2023-10-25T16:16:43.809644+00:00', 'last_updated': '2023-10-25T18:19:44.811657+00:00', 'context': {'id': '01HDM10Q9BV3YV0338ZADFPBF0', 'parent_id': None, 'user_id': None}}, 'old_state': {'entity_id': 'weather.forecast_tempest', 'state': 'rainy', 'attributes': {'temperature': 12.7, 'dew_point': 8.8, 'temperature_unit': '°C', 'humidity': 77, 'pressure': 1003.3, 'pressure_unit': 'hPa', 'wind_bearing': 192, 'wind_gust_speed': 10.08, 'wind_speed': 5.4, 'wind_speed_unit': 'km/h', 'visibility_unit': 'km', 'precipitation_unit': 'mm', 'attribution': 'Weather data delivered by WeatherFlow', 'friendly_name': 'Forecast Tempest', 'supported_features': 3}, 'last_changed': '2023-10-25T16:16:43.809644+00:00', 'last_updated': '2023-10-25T18:17:43.880747+00:00', 'context': {'id': '01HDM0X168K8TCPFQ01F9D12JG', 'parent_id': None, 'user_id': None}}, 'pin_app': True, 'pin_thread': 1, 'kwargs': {'attribute': 'all', '__thread_id': 'thread-1'}}
2023-10-25 20:19:44.829918 WARNING nspanel: ------------------------------------------------------------
2023-10-25 20:19:44.830098 WARNING nspanel: Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/appdaemon/threading.py", line 1045, in worker

    funcref(

  File "/conf/apps/nspanel-lovelace-ui/luibackend/controller.py", line 167, in state_change_callback

    #apis.ha_api.log(f"test124 items: {entities_on_card.items()} names: {names}")

  File "/conf/apps/nspanel-lovelace-ui/luibackend/pages.py", line 741, in render_card

    if card.cardType == "cardThermo":

  File "/conf/apps/nspanel-lovelace-ui/luibackend/pages.py", line 144, in update_screensaver_weather

    item_str += self.generate_entities_item(item, "cardEntities", mask=["type", "entityId"])

  File "/conf/apps/nspanel-lovelace-ui/luibackend/pages.py", line 371, in generate_entities_item

    elif entityType == "weather":

AttributeError: 'AttrDict' object has no attribute 'forecast'
```

### TO REPRODUCE
n/a

### EXPECTED BEHAVIOUR
Weather forecast to be displayed.

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
I'm using the following integration to provide the weather forecast: https://github.com/briis/weatherflow_forecast

According to Home Assistant documentation:

> Weather integrations which support weather forecasts expose the forecast using services. The services provided by weather entities are described below

> Some integrations may not support the weather.get_forecast service, but instead expose weather forecasts as a state attribute named forecast. This behavior is deprecated and will be removed in a future release of Home Assistant Core.

Weather forecast will not be an attribute in the future and therefore the service to get the forecast should be used instead. As an example:

```
service: weather.get_forecast
target:
  entity_id: weather.home
data:
  type: daily
response_variable: weather_forecast
```

### PANEL / FIRMWARE VERION
nspanel v4.3.1
Panel Version: 53
EU

**Comment by joBr99** [comment]
Hey, weather forecasts via services are a thing that has been added to homeassistant very recently. 
This project is still using the forecast provided by the forecast attribute. If your integration dropped the forecast attribute it's currently not compatible.

**Comment by Sn00kiT** [comment]
> Hey, weather forecasts via services are a thing that has been added to homeassistant very recently. This project is still using the forecast provided by the forecast attribute. If your integration dropped the forecast attribute it's currently not compatible.

Problem is that every weather addon dropped the forecast attribute :-) since a few days. I didn´t find any that still works for Europe :-). Dumbest change since ages from the home assistant team to change the forecast system.

**Comment by joBr99** [comment]
Both the default integration and openweathermap do still have the forecast attribute, at least on my home assistant instances.

**Comment by joBr99** [comment]
Blocked by upstream issue https://github.com/AppDaemon/appdaemon/issues/1837

A template sensor like this could be a workaround:

https://www.home-assistant.io/integrations/template/#trigger-based-handling-of-service-response-data

**Comment by joBr99** [comment]
done in #1058

**Comment by jacekowski** [comment]
Current version uses deprecated weather.get_forecast, this should be replaced with weather.get_forecasts instead

**Comment by Dattel** [comment]
> Current version uses deprecated weather.get_forecast, this should be replaced with weather.get_forecasts instead, it doesn't really change much (entity id is added to response)

nothing happend since then? Homeassistant still penetrates me with a depredicated warning for weather.get_forecast

**Comment by geduxas** [comment]
nspanel stoped showing wather after latest update.. Any plans for this topic?

**Comment by joBr99** [comment]
see pinned issue #1204
