### ISSUE TITLE
[Feature Request] Static background image 

### ISSUE THREAD

**Issue by afarago** [joBr99/nspanel-lovelace-ui#1010]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._
I would love to use a static background image instead of the solid color background.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
I have started to adjust the hmi for testing purposes, yet understood that bco is heavily used all over.
I am aware that the NSPanel is only able to use static assets in hmi/tft. I would be happy with any simple background.
It would add the potential to replace, re-compile and costumize.
Similar to this one: https://community.openhab.org/t/sonoff-nspanel-setup/131770/36?page=2

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
53.EU

**Comment by joBr99** [comment]
You need to adjust your HMI and build your own with a image that's the only way. As it's not possible to transfer pictures on runtime. bco is mainly used to change background color, you need to remove that code with an image.
