### ISSUE TITLE
Parameter count mismatch: screensaver color command and function HandleScreensaverColors() in NsPanelTs.ts

### ISSUE THREAD

**Issue by laluz742** [joBr99/nspanel-lovelace-ui#1013]
Are these 4 additional (white) a mistake as the HMI code is different taking 16 params instead of 20
https://github.com/joBr99/nspanel-lovelace-ui/blob/55447d724c843a823722d0760e259c25a63dd91c/ioBroker/NsPanelTs.ts#L7477
https://github.com/joBr99/nspanel-lovelace-ui/blob/55447d724c843a823722d0760e259c25a63dd91c/ioBroker/NsPanelTs.ts#L7478
https://github.com/joBr99/nspanel-lovelace-ui/blob/55447d724c843a823722d0760e259c25a63dd91c/ioBroker/NsPanelTs.ts#L7479
https://github.com/joBr99/nspanel-lovelace-ui/blob/55447d724c843a823722d0760e259c25a63dd91c/ioBroker/NsPanelTs.ts#L7480

**Comment by Armilar** [comment]
Yes 

color~background~tTime~timeAMPM~tDate~tMainText~tForecast1~tForecast2~tForecast3~tForecast4~tForecast1Val~tForecast2Val~tForecast3Val~tForecast4Val~bar~tMainTextAlt2~tTimeAdd

The Fix (4.3.3) will be:

let payloadString = 'color'                     + '~' +
                            scrSvrBGCol                 + '~' +      //background
                            rgb_dec565(sctime)          + '~' +      //time
                            rgb_dec565(sctimeAMPM)      + '~' +      //timeAMPM~
                            rgb_dec565(scdate)          + '~' +      //date~
                            rgb_dec565(sctMainText)     + '~' +      //tMainText~
                            rgb_dec565(sctForecast1)    + '~' +      //tForecast1~
                            rgb_dec565(sctForecast2)    + '~' +      //tForecast2~
                            rgb_dec565(sctForecast3)    + '~' +      //tForecast3~
                            rgb_dec565(sctForecast4)    + '~' +      //tForecast4~
    //                        rgb_dec565(White)           + '~' +      //tF1Icon~         rgb_dec565(sctF1Icon)
    //                        rgb_dec565(White)           + '~' +      //tF2Icon~         rgb_dec565(sctF2Icon)
    //                        rgb_dec565(White)           + '~' +      //tF3Icon~         rgb_dec565(sctF3Icon)
    //                        rgb_dec565(White)           + '~' +      //tF4Icon~         rgb_dec565(sctF4Icon)
                            rgb_dec565(sctForecast1Val) + '~' +      //tForecast1Val~
                            rgb_dec565(sctForecast2Val) + '~' +      //tForecast2Val~
                            rgb_dec565(sctForecast3Val) + '~' +      //tForecast3Val~
                            rgb_dec565(sctForecast4Val) + '~' +      //tForecast4Val~
                            rgb_dec565(scbar)           + '~' +      //bar~
                            rgb_dec565(sctMainTextAlt)  + '~' +      //tMainTextAlt
    //                        rgb_dec565(White)           + '~' +
                            rgb_dec565(sctTimeAdd);

**Comment by Armilar** [comment]
Tomorrow by @tt-tom17
