### ISSUE TITLE
[Feature Request] statusIcon colors for heater

### ISSUE THREAD

**Issue by YeeYek** [joBr99/nspanel-lovelace-ui#1018]
### FEATURE DESCRIPTION
The statusIcon or heating now has two colors: gray for off and on but idle, and yellow for heating.
Is it possible to introduce a new color:
gray - disabled
yellow - turned on but idle
red - heating
On entity card is also two colors...
### ADDITIONAL CONTEXT
screensaver, entity card

### PANEL / FIRMWARE VERION
Panel/Firmware Version EU/4.3.3

**Comment by joBr99** [comment]
https://docs.nspanel.pky.eu/entities/#override-icons-or-names

You can configure this with dynamic color overwrites using homeassistant templates:

```
         - entity: navigate.cardThermo_wohnzimmer
            status: climate.wohnzimmer_boden
            icon: mdi:thermometer
            color: '{{iif(states("climate.wohnzimmer_boden") == "heat", iif(state_attr("climate.wohnzimmer_boden", "hvac_action") == "idle", "[255,255,0]", "[255,0,0]"), "[128,128,128]")}}'


```
