### ISSUE TITLE
[Bug] Date update missing

### ISSUE THREAD

**Issue by bkbartk** [joBr99/nspanel-lovelace-ui#102]
Hello. 
for some reason sometimes my date doesn’t update correctly. It was Saturday for 3 days in a row. And now it’s Tuesday for the 2nd day in a row. First I thought it had to do wit dst. But now I think some updates aren’t coming through.

**Comment by joBr99** [comment]
![image](https://user-images.githubusercontent.com/29555657/160932583-43027d1e-b216-479f-b34e-d3670002b510.png)

What does the data in HomeAssistant look like?

Do you see weatherUpdate Messages in the AppDaemon Container Log (every 15 minutes and every time the screensaver is opened)

**Comment by bkbartk** [comment]
![1CE63BC2-FB02-4761-8F8D-DA5F99839574](https://user-images.githubusercontent.com/17070805/160936025-899d0f3f-03ae-40ec-8e16-367fbe5b4906.png)

![686248C1-D4D5-432C-BA69-453372B4B0DE](https://user-images.githubusercontent.com/17070805/160936039-73373d2e-fb8d-4832-a13d-a84fb2461022.png)

My appdeamon sends weather updates which are working. However unreadable. I noticed that todays weather never is available only now and tomorrow. 
but it’s the same in home assistant. So I guess this is a HA issue.

**Comment by joBr99** [comment]
it's only pulling the data from HomeAssistant, so if it's not working there it an HA issue

**Comment by bkbartk** [comment]
I know. That’s the weather issue. It’s just not available in HA. 
but the date is correct again after restarting the screen. 
no idea why this won’t always update.

**Comment by joBr99** [comment]
o.O thought you are talking about the weather in the first place

will check that tomorrow, I guess the code for the daily date update got lost an some point

**Comment by joBr99** [comment]
nevermind, just checked looks like the daily update is indeed missing

https://github.com/joBr99/nspanel-lovelace-ui/commit/b4075826f36cd577fd9238a29543f888fcae416a

**Comment by hatran0884** [comment]
yes, I also have the same issue of date not being updated frequently. so now I just redownload the appdaemon backend to have it fixed ?

**Comment by bkbartk** [comment]
@joBr99 when you asked about the weather I thought the current date would be extracted from the forecast date😉. 

@hatran0884 i think you have to wait for release 2.2.x

**Comment by joBr99** [comment]
fixed in v2.2.2
