### ISSUE TITLE
[BUG] page screensaver/screensaver2

### ISSUE THREAD

**Issue by laluz742** [joBr99/nspanel-lovelace-ui#1033]
### PROBLEM DESCRIPTION
_time_ command does not turn visibility of tAMPM back on

### TO REPRODUCE
```
time~11:22
time~11:22~AM
```

@see tmSerial in page screensavers
```
 if(tInstruction.txt=="time")
            {
              click m0,1
              //get set time to global variable
              spstr strCommand.txt,pageIcons.vaTime.txt,"~",1
              spstr pageIcons.vaTime.txt,tTime.txt,"?",0
              spstr pageIcons.vaTime.txt,tAMPM.txt,"?",1
              if(tAMPM.txt=="")
              {
                vis tAMPM,0
              }
              spstr strCommand.txt,tTimeAdd.txt,"~",2
              ref tIcon1
              ref tIcon2
            }
```

### EXPECTED BEHAVIOUR
tAMPM gets visible again

### PANEL / FIRMWARE VERION
53 eu

**Comment by joBr99** [comment]
I'm sending the panel to pageStartup on every config change to get the panel back into a defined state, so this isn't an issue for me - if you need this we can implement it.
