### ISSUE TITLE
Nextion2text diff - Possible to ignore "known" differences

### ISSUE THREAD

**Issue by jmbinette** [joBr99/nspanel-lovelace-ui#104]
I am not a diff specialist but would there be a way to have a "ignore-diff.txt" file that could be passed as a regex argument to the diff command to ignore "known" differences ?

This would greatly help when comparing EU/US versions

**Comment by joBr99** [comment]
I guess we have to search and replace the blocks before passing it into diff, my try with grep didn't work out that well because it was not searching for a whole block and replaced all matching lines.

**Comment by joBr99** [comment]
so after some experiments and thinking, i guess the easiest sulution is the thrid one

3 possible solutions

- filter input before diff
- filter output of the diff
- create a diff of the diff between a known good version and show only addions

**Comment by joBr99** [comment]
I've added the diff to the pipeline

https://github.com/joBr99/nspanel-lovelace-ui/blob/main/HMI/US/portrait/diff-filtered.txt
