### ISSUE TITLE
How do I know which version of TFT is flashed? Add way to read that out

### ISSUE THREAD

**Issue by stleusc** [joBr99/nspanel-lovelace-ui#1041]
### FEATURE DESCRIPTION
Add a way to read out what version of TFT is flashed. Unless I missed it, I don't know what version is on which of my panels. And with more than one in my house it is hard to track.
Add way to read that info back

### PANEL / FIRMWARE VERION
all

**Comment by joBr99** [comment]
If there is an update available for the display it's going to show a message.

You can configure it to auto-update aswell:
https://docs.nspanel.pky.eu/config-overview/?h=update

**Comment by stleusc** [comment]
A message where? The link you provided seems to be for AppDaemon. I am trying to use ioBroker.
In either case, somehting is triggering the 'message'. Could you share what that is?
Anything on MQTT? Or via Tasmota console?
Plus, NONE of my panels have internet access, so how would they know?

**Comment by joBr99** [comment]
I don't know how this is implemented on ioBroker, but I'm pretty sure that there is an mechanism too.

The panel send's the internal version of the display firmware during the Waiting for Content Screen.
`{"CustomRecv":"event,startup,39,eu"}`

**Comment by stleusc** [comment]
> The panel send's the internal version of the display firmware during the Waiting for Content Screen.
> `{"CustomRecv":"event,startup,39,eu"}`

What was the info I was looking for... So I could restart it and wait for that message, correct?

**Comment by joBr99** [comment]
yes, or run `CustomSend pageType~pageStartup` in the tasmota console
