### ISSUE TITLE
[Help] Nextion Firmware Update doesn't work

### ISSUE THREAD

**Issue by BroekerFrank** [joBr99/nspanel-lovelace-ui#1044]
### PROBLEM DESCRIPTION
I could not update the Nextion Firmware.
I want to update the firmware with the command: <FlashNextion http://nspanel.pky.eu/lui-release.tft>

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
This is the message in TASMOTA, after starting the Firmware Update:

15:13:24.713 CMD: FlashNextion http://nspanel.pky.eu/lui-release.tft
15:13:24.725 MQT: stat/NSPanel2/RESULT = {"FlashNextion":"Done"}
15:13:24.770 FLH: host: nspanel.pky.eu, port: 80, get: /lui-release.tft
15:13:26.948 FLH: Send (High Speed) flash start
15:13:27.299 BRY: Exception> 'type_error' - unsupported operand type(s) for <: 'nil' and 'int'

Output on the NSPanel Sceen:
USART Update...
   921600
Size:
       0
writing Data...

Bar with no progress

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
Firmware Version: EU

**Comment by joBr99** [comment]
This happens if tasmota doesn't have internet access check if you have the following things:

- Valid DNS Server
- Vaild Default Gateway
- Internet Access (Blocked by a firewall or something like that)

**Comment by BroekerFrank** [comment]
Perfect.
The DNS Server Adress was not valid.
I changed it and now it works!!

Thank you very much.

BR
Frank
