### ISSUE TITLE
ioBroker - add support for on/off icon and text on screensaver

### ISSUE THREAD

**Issue by stleusc** [joBr99/nspanel-lovelace-ui#1045]
### FEATURE DESCRIPTION
Add support for:
```
ScreensaverEntityOnColor: color
ScreensaverEntityOffColor: color
ScreensaverEntityOnText: "Is ON"
ScreensaverEntityOffText: "Not ON"
```

### ADDITIONAL CONTEXT
Currently the icon can be changed based on the state but not the icon color!
Also, it would come in very handy to be able to customize the displayed value.

Today:

```
let val = getState(config.indicatorScreensaverEntity[i].ScreensaverEntity).val;
```

ScreensaverEntityOnText/ScreensaverEntityOffText would be used as a replacement for 'val'.

To make this work, the current simple check for boolean with ```else if (typeof(val) == 'boolean') {``` would not be enough.
Certain Strings should be converted to boolean. The obvious would be (ignoring case):
- yes/no
- true/false
- on/off
- up/down
So these strings would be parsed and then interpreted as boolean (first on is the 'true' value, second the 'false').
More could be added.

That allows devices that have binary states that just don't show with a boolean type to be used for the On/Off feature.

This change to detect strings with binary meaning, combined with the On/Off Text, Icon and Color allow total freedom.

I believe this should be very easy to implement to be honest.
A simple function that parses and converts to boolean would have to be called around each getState().val.
The function simply should return the original value and type if there is no match.
Then., that function can be expaned in the future to support more binary strings if needed.

Of course, these strings should be the translated versions..... (well all but true/false as string)

### PANEL / FIRMWARE VERION
all

**Comment by Armilar** [comment]
Please look at the icon in the bottom left corner (Applies to all screensaver layouts)

Boolean (false)
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/102996011/51facf85-3087-4119-9a89-418221819432)

Boolean (true)
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/102996011/640cbc53-1cea-491f-93e4-bd076b4f4156)

    bottomScreensaverEntity :  
        [
            // bottomScreensaverEntity 1
            {
                ScreensaverEntity: 'alias.0.Haus.Erdgeschoss.Gaeste_WC.Licht.Deckenstrahler.ACTUAL',
                ScreensaverEntityIconOn: 'coach-lamp-variant',
                ScreensaverEntityText: 'Street',
                ScreensaverEntityOnColor: Yellow,
                ScreensaverEntityOffColor: White,
                ScreensaverEntityOnText: 'Is ON',
                ScreensaverEntityOffText: 'Not ON'
            },

v4.3.3.9
