### ISSUE TITLE
Is there documentation regarding the communication protocol used via MQTT

### ISSUE THREAD

**Issue by stleusc** [joBr99/nspanel-lovelace-ui#1051]
### PROBLEM DESCRIPTION
I am thinking about creating some very streamlined tool to communicate with NSPanel and update things I need.
However, I would have to reverse engineer all the code to find out how the MQTT content works.

### REQUESTED INFORMATION
Is there any document or place I can read that explains or lists all the content used in CustomSend?

### PANEL / FIRMWARE VERION
All

**Comment by joBr99** [comment]
https://github.com/joBr99/nspanel-lovelace-ui/blob/main/HMI/README.md

Which home automation tool are you using? What are you thinking about to build?

**Comment by stleusc** [comment]
Well, I am using HA and currently have AppDaemon running.
My ONLY issue with it is responsiveness...
Sometimes navigating around on the panel feels sluggish. So I was trying ioBroker that is getting my data from HA but controls the panel. And honestly, it felt WAY more responsive. But ioBroker is still lacking some features I was using in AppDaemon, so I can not directly switch.
But then I realized, I have a specific, limited config that I want to support and was thinking if some native compiled code that handles it would be more responsive.
I honestly like the way AppDaemon config works. I really do.... I just wish it was not so sluggish. None of that is related to your code directly. I think it is just the AppDaemon code itself causing delays.

If there are ways to improve that, I would not have to do anything.
I just believe, an HMI where the screen updates like half a second after pressing a button does not meet my needs.

At one point I was trying the NSPanel Blueprint thing, and it was way faster, but I hated the looks and the restrictions. Your implementation is far superior IN MY OPINION!

Maybe instead of doing sormthing myself there is a way to speed-up AppDaemon.

I mean, I have HA and AppDaemon both running on an actual Laptop with a fairly modern Core-i7! CPU performance and RAM should definitely not be an issue. But I don't know AppDaemon well enough to know if it can be tuned.

Open for any advice though.

Love what you did for the panel! Oh, thanks for the link btw....

**Comment by joBr99** [comment]
I stated a rewrite of the backend without appdaemon yesterday; do you have discord?

**Comment by stleusc** [comment]
yes I do.... NOW I am excited!!! If I can help in any way I'd be happy to do so....

**Comment by joBr99** [comment]
join this server and 'll find you :)

https://discord.gg/98V7qp4
