### ISSUE TITLE
tDate.txtmaxl value must be at least 35 for the Spanish language

### ISSUE THREAD

**Issue by xviti** [joBr99/nspanel-lovelace-ui#106]
hi
 GREAT Project (words are unnecessary), I follow your project from its beginning.

 I have four nextion screens, the first intelligent 5", the second enhanced 5", the third enhanced 3.5" and the fourth basic 2.4" and I have installed nspanel on all of them. in the first versions I adapted the nspanel.HMI file to run on my panels with the appropriate dimensions of the elements, oh my god... this works like a charm.

In the screensaver page the tDate.txtmaxl value must be at least 35 for the Spanish language, look at the possibly longest string that babel full returns for es_ES:
miercoles, 22 de septiembre de 2022

I have tried to import the nanosans font to make the icons bigger for the 50" screens. I have spent a few hours experimenting with no avail, I only get the font with no icons.

where do i get that font?
or maybe you can send me the font with icons size 160

Thanks

**Comment by joBr99** [comment]
Hey, 
I'm using the fonts from openhasp, looks like creating iconfonts with text is a huge pain, stopped looking into it after got pointed to theese fonts. If you have questions to the font stuff, ask on Unoffical Nextion Discord, the people who worked on the font stuff can proably tell you more about it.

https://github.com/aderusha/Generate-HASP-Fonts

I will increase the max value for the date :)

**Comment by xviti** [comment]
love you

**Comment by joBr99** [comment]
@xviti I've generated the MDI Font with the newest Icons aswell as an updated cheatsheet, hit me up on discord if you need them, it will take some time before I update the font in the nextion project. 

https://discord.com/invite/98V7qp4
