### ISSUE TITLE
Setup Successful screen, suppress via panels.yaml

### ISSUE THREAD

**Issue by kamsvag** [joBr99/nspanel-lovelace-ui#1067]
### FEATURE DESCRIPTION
I get the 'Setup Successful' notification poping up and it doesn't go away. I would suggest an option in the panel.yaml to supress this screen.

### ADDITIONAL CONTEXT
I might just have missed something, if so, please point me in the right direction and remove this Feature request.

### PANEL / FIRMWARE VERION
EU panel, Tasmota 13.2.0.2(nspanel), NSPanel Lovelace UI Addon 4.7.39

**Comment by joBr99** [comment]
??????

The Homeassistent addon is pretty much an alpha right now and not documented anywhere. 

Also it currently doesn't have an setup successful screen - do you have the appdaemon app running in parallel?

**Comment by kamsvag** [comment]
I did, and now I turned it off. I don't get the Setup screen now, but I get a blank screen and nothing more.

**Comment by joBr99** [comment]
Sounds like you configured something wrong or used something that isn't implemented.

**Comment by kamsvag** [comment]
These are my panel.yaml settings.
Apart from that I followed the instructions .. I could reflash the device to see if something is off.

Tasmota - 13.2.0.2

nspanels:
  tasmota_nspdev2:
    name: test
    panelRecvTopic: "tele/NSPANEL/RESULT"
    panelSendTopic: "cmnd/NSPANEL/CustomSend"
    timeFormat: "%H:%M"
    timeZone: "Europe/Stockholm"
    dateFormat: "full"
    locale: "en_SE"
    screensaver:
      entities:
        - entity: weather.smhi_home
          name: SMHI
          icon: mdi:flower-outline
        - entity: sensor.outside
          name: Outside
          icon: mdi:flower-outline
        - entity: sensor.pool_temp_tasmota
          name: Poll
          icon: mdi:pool
        - entity: sensor.temp_boden_temperature
          name: Garage
          icon: mdi:garage
        - entity: sensor.temp_allrum_temperature
          name: Allrum
          icon: mdi:home-floor-1
    cards:
      - type: cardEntities
        title: Guest Room
        entities:
          - entity: switch.uttag_replampa_17
            name: Replampan
            icon: mdi:ceiling-light
          - entity: light.guest_tak
            name: Taklampa
            icon: mdi:spotlight-beam
          - entity: sensor.garage_temperature_ds18b20_temperature
            name: Temperature
          - entity: switch.uttag_arkad_15
            name: Arcade machine
            icon: mdi:controller-classic
      - type: cardEntities
        title: 1st Floor
        entities:
          - entity: input_boolean.livingroom
            name: Livingroom
          - entity: input_boolean.hall
            name: Hallway
          - entity: input_boolean.kitchen
            name: Kitchen
          - entity: input_boolean.laundry
            name: Laundry
          - entity: input_boolean.playroom
            name: Playroom
          - entity: input_boolean.guest
            name: Guestroom
          - entity: input_boolean.bathroom
            name: Bathroom
      - type: cardEntities
        title: 2nd Floor
        entities:
          - entity: input_boolean.allrum
            name: Commonspace
          - entity: input_boolean.master_bedroom
            name: Master bedroom
          - entity: input_boolean.idun_s_bedroom
            name: Iduns bedroom
          - entity: input_boolean.david_s_bedroom
            name: Davids bedroom
          - entity: input_boolean.bathroomup
            name: Bathroom
      - type: cardGrid
        title: Test Entities Card3
        entities:
          - entity: vacuum.5_fifth_floor
          - entity: navigate.test

**Comment by joBr99** [comment]
Yes, since yesterday evening you also need the latest development firmware on the panel.

So `FlashNextion http://nspanel.pky.eu/lui.tft` for the EU Panel

**Comment by kamsvag** [comment]
After flashing, problem solved. :D Awesome, thanks!
