### ISSUE TITLE
[Feature Request] Possible to use this with a standalone Nextion Display and ESP32?

### ISSUE THREAD

**Issue by NOTORIOUSVR** [joBr99/nspanel-lovelace-ui#1081]
### FEATURE DESCRIPTION
Wondering if it is possible to run this project on an almost identical Nextion display w/ just an ESP32 connected to it

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
Nextion NX4832K035

Thank you

**Comment by joBr99** [comment]
yes, of course you can do that - even on other nextion nextions if you adopt the nextion project (search in the issues of this projects there are people who did that before)
