### ISSUE TITLE
[Feature Request] - Ability to change background

### ISSUE THREAD

**Issue by leacho73** [joBr99/nspanel-lovelace-ui#1092]
### FEATURE DESCRIPTION
Apologies if this is already possible and I have missed it in the docs, but would it be possible to change the background image on the NSPanel?

### ADDITIONAL CONTEXT
This would be useful for dynamic content via templates etc, for example, if its raining outside, put a rain background up, and a sun one for sunny

### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
It's not possible to transfer images dynamically to the panel and it also doesn't support transparency. There a various issues where this has been discussed previously.
