### ISSUE TITLE
[Feature Request] Slider checkbox für QR Page WLan ein und ausschalten

### ISSUE THREAD

**Issue by SurfGargano** [joBr99/nspanel-lovelace-ui#1099]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._

Auf QR Page sind 2 Slider Checkboxen vorhanden.
Die werden aber nicht angezeigt.
Kann eine Checkbox bitte angezeigt werden, damit ich Gäste Wlan ein und ausschalten kann.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/70272783/a65cb5be-ea1d-4ddc-a37b-1ac6df892d19)

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
Panel Version 53 EU

**Comment by joBr99** [comment]
Das funktioniert exakt genauso wie auf cardEntities, wenn ein switch oder light beim panel ankommt wird der switch angezeigt. 

Würde mich wundern, wenn das bei ioBroker nicht schon implementiert ist o.O

Da kann man ja wie an vielen Stellen die gleiche Funktion wiederverwenden um das entity zu generieren.

**Comment by SurfGargano** [comment]
Ist in iobroker noch nicht implementiert. 
Ich kann nur entweder Text oder Switch wählen, keinen extra Switch?

**Comment by joBr99** [comment]
Ja bText1/2 verschwindet wenn der OnOff Button angezeigt wird, da die auf cardEntities überlappen.
(und die entity definition hat 0/1 in dem Feld welches bei text für den Text verwendet wird)

**Comment by Armilar** [comment]
@joBr99 wir hatten die harte Variante drin - QRCode Scannen oder abtippen ;-)

Kommt mit der v.4.3.3.25

**Comment by joBr99** [comment]
Die Seite kann light, switch, button und text

**Comment by Armilar** [comment]
v4.3.3.25
