### ISSUE TITLE
Howto include Service Menu

### ISSUE THREAD

**Issue by rmikulasch** [joBr99/nspanel-lovelace-ui#1101]
Hi joBr99,

how can I integrate the Service Menu Content ?
Must this be done also in the apps.yaml?
Is this only available if using ioBroker?

Thanks Ralph

**Comment by joBr99** [comment]
There is no service menu on home assistant

**Comment by rmikulasch** [comment]
but on the Panel or?

**Comment by joBr99** [comment]
no, there is no service menu with the home assistant backend
