### ISSUE TITLE
[Feature Request] - Text String rather than StatusIcon

### ISSUE THREAD

**Issue by leacho73** [joBr99/nspanel-lovelace-ui#1102]
### FEATURE DESCRIPTION
The ability to display a text string rather than a statusicon for [statusIcon1] and [statusIcon2]
### ADDITIONAL CONTEXT
A text string rather than an icon would be helpful when labelling what the push buttons do when pressed - for example 'Bedroom Light'

### PANEL / FIRMWARE VERION
EU

**Comment by rossi75** [comment]
![DSC_1451](https://github.com/joBr99/nspanel-lovelace-ui/assets/91349581/b799b48e-24fe-4c65-ba9c-5aea7a37de65)
Still possible

**Comment by leacho73** [comment]
@rossi75 can you share your code on how you achieved this please - if it's already possible I'll close this FR 😀

**Comment by rossi75** [comment]
> @rossi75 can you share your code on how you achieved this please - if it's already possible I'll close this FR 😀

Edited my post

**Comment by leacho73** [comment]
> > @rossi75 can you share your code on how you achieved this please - if it's already possible I'll close this FR 😀
> 
> 
> 
> Edited my post

This is excellent - thank you @rossi75

**Comment by rossi75** [comment]
The 0, 10, 10 are only for debug purposes at the Moment. Will be changed to 0, 0, 0 as soon as all works fine
