### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by nabilxp** [joBr99/nspanel-lovelace-ui#1104]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide a screenshot of your tasmota mqtt configuration:

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/9931339/43ab4d27-4e7e-4925-85b2-4418ba5660f7)

- [x] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/9931339/aa95869c-66d9-4c40-b0bb-4f272bd1743d)

```

- [x] Provide your apps.yaml:
```
  apps.yaml here:

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/9931339/096d389d-b25f-49f2-b731-1759bb105d66)

```
- [x] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/9931339/f112134d-2799-4a25-a9b0-eb2a66a93bd2)

```

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_

I use the Ass_on AppDaemon of HomeAssistant 
thank you for your help, everything worked well before, but since the loss of my HM SD card, nothing works, despite the reconfiguration of all the modules, and 2 months of research

i think problem come from communication between AppDaemon and mqtt

**Comment by joBr99** [comment]
You've posted the log from mosquitto - not from appdaemon

**Comment by nabilxp** [comment]
you are right, I just updated my comment, I first found that appdeamn was not starting because of a problem accessing the secret file, I commented on the line about using the secret file , it started well, but still same problem

**Comment by joBr99** [comment]
First of all you need to fix this error with the mqtt configuration of appdaemon:

`2023-12-2s CRITICAL Enrr: due to Not Authorised Could not ccztpiete MQTT Plugin initializaticn, for Connection was refused`

Mosquitto log might provide you additional context on the issue.

(Also seen another issue, but please fix the MQTT one first, one step after another)

**Comment by nabilxp** [comment]
thnks for your help,I use a user that I created in homa assistant, I have to put quotes in the appdeam file configuration, for the user and the password?

**Comment by joBr99** [comment]
it doesn't hurt to have `"` quotes - but in general you don't need them

https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml

**Comment by nabilxp** [comment]
I checked login and password 10 times, each time restarting HA, but without success, 
can i use an other acount ,than the on from HA ?
what is the http parameter, url of the appdeamon configuration  for? What should I put as url?

**Comment by nabilxp** [comment]
I have something weird in the Mosquitto broker log, New connection from 172.xx.xx.1:49574 on port 1883, this IP address is not mine, it's as if appdeamon is trying to connect to an external address, and why port 49574? I will offer you coffee if you can find my problem :)

**Comment by joBr99** [comment]
this is fine; 172.XX is the IP Address of the appdaemon container and 49574 is the client/source port of the connection

you can safely ignore the http stuff from appdaemon - it's not used

You can configure a username password in the mosquitto configuration.

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/1f0f99a9-ac10-450c-ada1-e0f7f23261cd)

**Comment by nabilxp** [comment]
It finally works, I had to add: broker: "core-mosquitto" in the appdaemon conf file

**Comment by nabilxp** [comment]
I found this in a forum, someone had the same problem as me :)

**Comment by joBr99** [comment]
Is your app starting now? Please provide the appdaemon log again if it isn't.

**Comment by nabilxp** [comment]
It's working now thanks
