### ISSUE TITLE
Temp display changes with display brightness

### ISSUE THREAD

**Issue by westado** [joBr99/nspanel-lovelace-ui#1107]
When I set the sleepBrightness in Apps.Yaml:
      - time: "13:00:00"
        value: 100
      - time: "18:00:00"
        value: 3
At certain times the temperature display also changes
![Zwischenablage01](https://github.com/joBr99/nspanel-lovelace-ui/assets/69120129/687396ce-32ba-41ee-8f0b-59cc53d117ff)

**Comment by Armilar** [comment]
https://github.com/joBr99/nspanel-lovelace-ui/issues/144

Take a look here. I think you'll find your answer...

But it's not a bug in HA or ioBroker

**Comment by joBr99** [comment]
Yes this is a known issue, the nspanel hardware is crap, but nothing that we can fix.

**Comment by westado** [comment]
> #144
> 
> Schauen Sie hier vorbei. Ich denke, Sie werden Ihre Antwort finden ...
> 
> Aber es ist kein Fehler in HA oder ioBroker


Thank you for the info. Then it is due to the temperature of the display that the values ​​always change when the display is dimmed up or down

**Comment by westado** [comment]
> Yes this is a known issue, the nspanel hardware is crap, but nothing that we can fix. The heat produced by the panel is influencing the temp sensor. Staying between 0-10 in the screensaver works good enough for me.

Danke wie immer bekomme ich die richtigen Antworten von dir. Aber sonst ist die Firmware für das NS Panel mega. Habe das ganze Haus mit denen ausgestattet.  Eine Frage hätte ich noch an dich. Da ja seit kurzem App Deamon der Ordner auserhalb von HA ist komme ich nur über das Netzlaufwerk an die apps. yaml oder gibt es auch einen anderen weg?

**Comment by joBr99** [comment]
Vscode funktioniert auch File Open, da kannst du den Ordner auswählen

**Comment by joBr99** [comment]
Du kannst die apps.yaml auch zurück an den alten ort konfigurieren, das ist auch der einzige Weg über den Updates durch hacs funktionieren - da das nächste release ohne appdaemon sein wird aber egal.

**Comment by westado** [comment]
> Du kannst die apps.yaml auch zurück an den alten ort konfigurieren, das ist auch der einzige Weg über den Updates durch hacs funktionieren - da das nächste release ohne appdaemon sein wird aber egal.

Das wäre mir noch viel lieber. Wie kann ich das am besten machen.

**Comment by joBr99** [comment]
See #1029.

Tldr die Zeile mit dem apps dir zur appdaemon.yaml hinzufügen und den apps Ordner an den alten ort verschieben
