### ISSUE TITLE
[BUG] Cardmedia Alexa in Verbindung mit Echo Dot 4.Gen

### ISSUE THREAD

**Issue by wod71** [joBr99/nspanel-lovelace-ui#1115]
### PROBLEM DESCRIPTION
Ein Echo Dot 4.Gen lässt sich nicht komplett über den CardMedia Alexa steuern.

Funktioniert nicht:
- Ein/Aus geht nicht
- Lauter/Leiser geht nicht
- Anzeige des abspielenden Titels bleibt leer

Funktioniert:
- Senderauswahl

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
let Alexa: PageType =
{
    'type': 'cardMedia',
    'heading': 'Alexa',
    'items': [<PageItem>{   
                id: AliasPath + 'Media.PlayerAlexa', 
                adapterPlayerInstance: 'alexa2.0.',
                mediaDevice: 'G091EUxxxxxxxxxx', // Eigene Seriennummer des primären Device einstellen
                speakerList: ['Hobby','Wohnzimmer'],
                //analog alexa2 Music-Provider
                //Mögliche Playlists:
                playList: ['TuneIn.Radio 91.2',
                           'TuneIn.Radio Bob Rock',
                           'TuneIn.NDR2',
                           'TuneIn.Antenne Unna',
                           'TuneIn.Radio Lippe Welle Hamm',
                           'TuneIn.Radio FFN',
                           'TuneIn.EinsLive'],
                equalizerList: ['Bassboost','Klassik','Dance', 'Deep', 'Electronic', 'Flat', 'Hip-Hop', 'Rock', 
                                'Metal', 'Jazz', 'Latin', 'Tonstärke', 'Lounge', 'Piano'],
                colorMediaIcon: colorAlexa,
                colorMediaArtist: Yellow,
                colorMediaTitle: Yellow,
                alwaysOnDisplay: true,
                autoCreateALias : true
             }]
};


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by Armilar** [comment]
* Welche Script-Version ist installiert? v4.3.3.30?
* nur beim Echo Dot 4. Gen oder ist das jetzt nur das benutzte Modell?

**Comment by wod71** [comment]
Script-Version 4.3.3.30
Fehler ist nur beim Echo Dot 4. Gen - ein Dot 2 oder Echo Show 8 (1.Gen) funktioniert

**Comment by Armilar** [comment]
Nur im Austausch der Seriennummer? Oder mit einem anderen Alias?

**Comment by Armilar** [comment]
Das <PageItem> aus dem Alias entfernen. Hat aber nichts mit der Funktionalität zu tun...

Habe auch 2 x Echo Dot 4. Gen und laufen perfekt

Sonst mal kurz einen Auszug des Alias senden...

**Comment by Armilar** [comment]
Für den Fall, dass die beiden Devices "Echo Dot 2" oder "Echo Show 8 (1.Gen)" mit anderen Panels (also abweichenden Aliassen) betrieben wird, einfach mal den kompletten Media-Alias vom "Echo Dot 4. Gen" Panel wegwerfen und vom Script neu anlegen lassen.

**Comment by wod71** [comment]
Alias neu anlegen lassen war die Lösung.

Vielen Dank
