### ISSUE TITLE
[Feature Request]  language date screensaver [FR]

### ISSUE THREAD

**Issue by nabilxp** [joBr99/nspanel-lovelace-ui#1120]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._

Hello,
I wanted to know if it was possible to change the language of the date displayed on the screensaver default screen.
Thanks for your help

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/9931339/047bf902-74de-4e45-94e8-f80f8fec8ebb)

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
Please see the documentation:

https://docs.nspanel.pky.eu/stable/prepare_ha/?h=babel#add-babel-package-to-appdaemon-container-optional

https://docs.nspanel.pky.eu/stable/config-overview/?h=lang#supported-keys-for-locale-config

**Comment by nabilxp** [comment]
i have add babel 
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/9931339/ffa8fab7-641a-4465-bc58-efcb3f782011)
and locale: "fr_FR" in 'apps.yaml' but still nothing
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/9931339/663c6cf5-0de9-46c9-821f-8082622f7bc5)

**Comment by nabilxp** [comment]
It's working now ,after a reboot 
Thanks for help
