### ISSUE TITLE
Character set

### ISSUE THREAD

**Issue by ladousek** [joBr99/nspanel-lovelace-ui#113]
Hello, would it be possible to enhance characters sets for ISO 8859-2? I would like to use in screen cs_CZ localization, unfortunately special characters are not supported now. Just idea for future. It is nice to have only :-)

> (á, č, ď, é, ě, í, ň, ó, ř, š, ť, ú, ů, ý, ž, Á, Č, Ď, É, Ě, Í, Ň, Ó, Ř, Š, Ť, Ú, Ů, Ý, Ž)

**Comment by joBr99** [comment]
Nope sadly, it's impossible to transfer thoose characters over serial to the nextion display. This is a limitation from nextion, where I cannot do anything.
