### ISSUE TITLE
[Feature Request] NSPanel Pro

### ISSUE THREAD

**Issue by danielewyss** [joBr99/nspanel-lovelace-ui#1135]
### FEATURE DESCRIPTION
Is it on the pipe to support the  NSPanel Pro EU

### PANEL / FIRMWARE VERION
NSPanel Pro EU / NA

**Comment by joBr99** [comment]
no, NSpanel pro is a completely different thing as it's based on android - you have way more options with nspanel pro as you can just use the homeassistant webinterface in a kiosk browser
