### ISSUE TITLE
Support for other devices than NSPanel

### ISSUE THREAD

**Issue by bzumik1** [joBr99/nspanel-lovelace-ui#1148]
### FEATURE DESCRIPTION
I would like to request support for a device based on GT911, specifically this model: [GT911-based device on AliExpress](https://a.aliexpress.com/_EwCtt1n). The device appears to be a promising alternative to the NSPanel, especially for users who do not require physical buttons. It would be great to have compatibility with this device in our system.

### ADDITIONAL CONTEXT
This device could offer a more streamlined and customizable interface for users who prefer a fully digital control panel. Its integration could enhance the flexibility of our system in adapting to different user preferences and setups.

### PANEL / FIRMWARE VERION
Not relevant.

**Comment by joBr99** [comment]
this product has a completely different screen and doesn't have much in common with the nspanel and it's nextion screen

**Comment by bzumik1** [comment]
Ok, thx for explanation.
