### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by Arnulf22** [joBr99/nspanel-lovelace-ui#1158]
### FEATURE DESCRIPTION
To make the entities of the screensaver much more flexible, it would be nice, if I am able to use a data point in addition to fixed values

example
current definition:

`        // bottomScreensaverEntity 1
        {
            ScreensaverEntity: 'accuweather.0.Daily.Day1.Sunrise',
            ScreensaverEntityFactor: 1,
            ScreensaverEntityDecimalPlaces: 0,
            ScreensaverEntityDateFormat: {hour: '2-digit', minute: '2-digit'}, // Description at Wiki-Pages
            ScreensaverEntityIconOn: 'weather-sunset-up',
            ScreensaverEntityIconOff: null,
            ScreensaverEntityText: 'Sonne',
            ScreensaverEntityUnitText: '%',
            ScreensaverEntityIconColor: MSYellow //{'val_min': 0, 'val_max': 100}
        },
`

possible solution:

`        // bottomScreensaverEntity 1
        {
            ScreensaverEntity: 'accuweather.0.Daily.Day1.Sunrise',
            ScreensaverEntityFactor: 1,
            ScreensaverEntityDecimalPlaces: 0,
            ScreensaverEntityDateFormat: {hour: '2-digit', minute: '2-digit'}, // Description at Wiki-Pages
            ScreensaverEntityIconOn: 0_userdata.0.NSPanel.NSPanel_Arbeitszimmer.1.userdata.icon_something,
            ScreensaverEntityIconOff: null,
            ScreensaverEntityText: 'Sonne',
            ScreensaverEntityUnitText: '%',
            ScreensaverEntityIconColor: 0_userdata.0.NSPanel.NSPanel_Arbeitszimmer.1.userdata.color_something
        },
`

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
Panel: EU version
TFT firmware 4.3.3
scriptVersion v4.3.3.39
berry driver: 9

**Comment by tt-tom17** [comment]
bitte Version im DEV Ordner testen -> https://github.com/joBr99/nspanel-lovelace-ui/blob/main/ioBroker/DEV/NSPanelTs.ts
im Datenpunkt muss eine Zahl im Format für HMINextion stehen, diese kann hier -> https://nodtem66.github.io/nextion-hmi-color-convert/index.html ermittelt werden.

**Comment by tt-tom17** [comment]
ist in der Release jetzt enthalten.
