### ISSUE TITLE
[Feature Request] Support for Cyrillic and Chars from ISO 8859-2

### ISSUE THREAD

**Issue by ibalabozov** [joBr99/nspanel-lovelace-ui#116]
When name of the pages (for example "Example page" is "Примерна страница") nothing is displayed.
Please add support for Cyrillic symbols.

**Comment by joBr99** [comment]
See #113, sadly impossible with nextions screens

**Comment by ibalabozov** [comment]
OK. Thank you!

**Comment by joBr99** [comment]
might be not completly true that it's impossible have to investigate that

**Comment by ladousek** [comment]
Perfect, I try during week it :)

**Comment by ibalabozov** [comment]
@joBr99 you make great progress of the project. It will be great if Cyrillic is supported!
You have a coffee by me :)

**Comment by joBr99** [comment]
It will have support for cyrillic chars with the next release, if you want to have it before the release update to the current development version :)

https://github.com/joBr99/nspanel-lovelace-ui#how-to-upgrade-from-a-release-to-the-current-development-version

**Comment by Chreece** [comment]
Sorry for intervening.

That means that the Greek fellas also can have their letters on screen?

**Comment by joBr99** [comment]
Yes, should also be included, I've only excluded Japanese, Chinese and Korean Characters due to space limitations.

**Comment by joBr99** [comment]
2.6.0 has been released
