### ISSUE TITLE
[BUG] Dimmer Switch not working on cardEntities

### ISSUE THREAD

**Issue by Bart1909** [joBr99/nspanel-lovelace-ui#1160]
### PROBLEM DESCRIPTION

I've created an alias device from type "Dimmer" and assigned the states:
![grafik](https://github.com/joBr99/nspanel-lovelace-ui/assets/14097923/7035ce83-ac55-4a46-8a71-d502ac14612c)

Now, when I enter this device on a cardEntities page, the toggle switch is not working.
If the light is on, the switch represents this. Then I touch the switch and the light goes off. But then, the switch steps back to activated and I cannot control the light anymore.
If I click on the light name to enter the details page, the switch there is working as expected. Also the slider for the brightness is working fine.
In addition, when the light is off, the switch on the page is also activated.

### REQUESTED INFORMATION

```
let startSeite: PageType =
    {
        'type': 'cardEntities',
        'heading': '',
        'useColor': true,
        'items': [
            { id: 'alias.0.NSPanel.Devices.Rollladen.BueroTobi', icon: "window-shutter", name: "Fenster", interpolateColor: true},
            { id: 'alias.0.NSPanel.Devices.Rollladen.BueroTobiBodentief', icon: "window-shutter", name: "Tür", interpolateColor: true},
            { id: 'alias.0.NSPanel.Devices.Lichter.BüroTobi', icon: 'lightbulb', name: 'Lampe', interpolateColor: true},
            { navigate: true, id: 'Buero_Themostat', icon: 'thermostat', name: 'Thermostat', buttonText: 'Einstellen'},
        ]
    };
```

### TO REPRODUCE

Create the alias device and put it on a cardEntities page. Then try to control it with the switch.

### EXPECTED BEHAVIOUR

The switch on the cardEntities page should work and represent the current state of the light.

### ADDITIONAL CONTEXT

Working with ioBroker.

### PANEL / FIRMWARE VERION
NSPanel EU
Script Version: v4.3.3.39
Tasmota Version: 13.3.0
TFT-Version: 4.3.3

**Comment by tt-tom17** [comment]
Hallo, 
könntest du bitte den Alias / Gerät noch einmal löschen und neu anlegen.
Welche Version vom Device-Adapter nutzt du?

**Comment by Bart1909** [comment]
Das hat tatsächlich funktioniert.

vielleicht hatte ich beim ersten Mal was falsch gemacht, war das erste Gerät, was ich eingebunden hatte
