### ISSUE TITLE
[Feature Request] Send MQTT call to set screen brightness

### ISSUE THREAD

**Issue by mixedbreed** [joBr99/nspanel-lovelace-ui#1161]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._

Be able to set screen brightness through MQTT command.
Tried following command through NodeRed:
{"topic":"cmnd/nspanel2mqtt/Backlog","payload_template":"CustomSend pageType~screensaver; screenBrightness 0"}

Result is a blink on the screen.
### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
Hey, the screenbrightness ist set with a command like this: `CustomSend dimmode~0~100` - however setting the screenBrightness directly over mqtt doesn't really work if you have a backend that is controlling the screen like the homeassistant one or the iobroker one.

For homeassistant there are ways to use a value from an input_number:
https://docs.nspanel.pky.eu/stable/config-overview/
