### ISSUE TITLE
[Feature Request] cardGrid with 9 elements for US version

### ISSUE THREAD

**Issue by starwarsfan** [joBr99/nspanel-lovelace-ui#1167]
### FEATURE DESCRIPTION
The current cardGrid2 can hold 8 entries, which is fine so far. But on the NsPanel US version that leads to 2 rows with 3 entries and a 3rd row with only 2 entries. I'd like to use all available space, so it would be very nice if there could be 9 entries at all.

### ADDITIONAL CONTEXT
I already implemented cardGrid3 on my NsPanelTs.ts file but as soon as I activate that layout, the entries are displayed as a list like with the cardEntities layout, so I assume that there are changes on the firmware required too!?

### PANEL / FIRMWARE VERION
- US-P 
- Tasmota 13.3.0
- Berry 9
- Nextion-TFT 53 / v4.3.3

**Comment by Armilar** [comment]
I set additional labels for HMI and HA. I think this is initially a topic for an additional cardGrid3. Can you provide your cardGrid3?

**Comment by joBr99** [comment]
There are already 9 Buttons on cardGrid2 on US-P, maybe this is a bug.

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/7bb86ca8-b7e6-4d16-a8aa-e0f32d161fd8)

**Comment by Armilar** [comment]
Then it is correct. @tt-tom17 has already implemented it for the ioBroker. 

@ joBr99 - da ist noch ein weiterer Bug im Screensaver in der DEV TFT... Wenn du auf iner carLChart bist und dder Screensaver wird aufgeschaltet, kommst du nicht zurück auf die cardLChart... Für den Fall das du in der HMI Änderungen machst...

**Comment by starwarsfan** [comment]
Hey guys,

thx for the reply but:

> Then it is correct. @tt-tom17 has already implemented it for the ioBroker.

Now I'm confused. Is it correct or is it wrong? What exactly is correct a/o what is wrong?

If I put 8 entries into cardGrid2, everything is fine. If I put 9 entries into cardGrid2, I got this error message:

`
Source has 9 element(s) but target allows only 8.
`

How should I go ahead now? Do you need more details from my side? Do you still need my version with the experiment on implementing cardGrid3?

**Comment by joBr99** [comment]
Can you please try to patch this limitation in the script to 9 elements? 
This way we can figure out if it's an issue in the HMI or the ioBroker script.

**Comment by starwarsfan** [comment]
Already tried this but the error stays the same.

**Comment by joBr99** [comment]
What's the tft you've installed? Can you try to flash the dev version of the tft?

`FlashNextion http://nspanel.pky.eu/lui-us-p.tft`

I can see that there's code for the 9th entity, need to check if it's actually working or not.

**Comment by starwarsfan** [comment]
> What's the tft you've installed? Can you try to flash the dev version of the tft?

See my initial posting, all versions written there.

> `FlashNextion http://nspanel.pky.eu/lui-us-p.tft`

After doing so, the version seems to be the same. Still 53/v4.3.3.

**Comment by starwarsfan** [comment]
To clarify:

> Can you please try to patch this limitation in the script to 9 elements?

I changed

```typescript
            case 'cardGrid2':
                maxItems = 8;
                break;
```
to
```ts
            case 'cardGrid2':
                maxItems = 9;
                break;
```
Is that what you meant to patch?

**Comment by tt-tom17** [comment]
Wenn das Script für iobroker genutzt wird muss auch der Typ angepasst werden. Patch kommt heute Nacht.

**Comment by starwarsfan** [comment]
Hi

Ich bin noch nicht so tief drin, wie die einzelnen Komponenten miteinander spielen.

> Wenn das Script für iobroker genutzt wird muss auch der Typ angepasst werden.

Von welchem "Typ" sprichst Du hier konkret?

> Patch kommt heute Nacht.

Sehr cool, thx a lot! 

PS: Hab' da gleich noch zwei PRs für Kleinigkeiten gemacht, die mir so ins Auge gesprungen sind...

**Comment by tt-tom17** [comment]
bitte die DEV Version testen.

**Comment by starwarsfan** [comment]
Hi

Super, damit funktioniert es nun mit neun Einträgen im cardGrid2. 

Ich musste jedoch https://github.com/joBr99/nspanel-lovelace-ui/blob/main/ioBroker/DEV/NSPanelTs.ts#L5796 zu 

```
if (Debug) log("Length: " + JSON.stringify(out_msgs).length);
```

ändern, da es den Fehler 

```
ERROR: Argument of type 'number' is not assignable to parameter of type 'string'
```

gab. Danach liess sich diese Version deployen.
