### ISSUE TITLE
CardThermo Alias erweiterung für Zusatzicons 

### ISSUE THREAD

**Issue by c3b69** [joBr99/nspanel-lovelace-ui#1168]
Um eine cardThermo zu nutzen, ohne ein reales Thermostat zu haben, sollte man  zu den schon vorhandenen Funktionen den alias so configurieren können um auch die Zusatzfunktionen richtig nutzen zu können.

Aktuelle Temp und einzustellender Wert funktioniert gut.
Verbleibt noch die Zuweisung des Zustand. Man kann im alias zwar Zustände hinzufügen, sie werden aber nicht gespeichert.
Die Icons im unteren Bereich können zwar angesprochen werden, die Zuweisung für power wird aber im alias immer wieder gelöscht. Unter Objekten ist er auch nicht aufgeführt.
Das Icon für humidity wird farbig und zeigt ein %-Zeichen an. Dort sollte sicher der Wert stehen. 
Es passen insgesamt 8 Icons unten auf das Panel. Alle weiteren fallen nach rechts raus. Wir organisiert man eine Reihenfolge und wie bekommt man sie wieder ausgeblendet? Auch diese sind in den Objekten nicht aufgeführt.

Benutzt wird ein NS Panel mit Firmware:
Tasmota 13.3.0
Berry-Driver 9
Nextion-TFT 53/v4.3.3
Skript v4.3.3.39

**Comment by tt-tom17** [comment]
Das humidityIcon ist ein Icon mit Prozent Zeichen, möchtest du dort jetzt eine Zahl oder ein Icon haben?
Die Reihenfolge wird durch das Script organisiert, ausgeblendet werden sie durch löschen / nicht vorhanden sein des Datenpunktes.
folgende Datenpunkte werden in dieser Reihenfolge angezeigt:

- AUTOMATIC
- MANUAL
- PARTY
- VACATION
- BOOOST
- HUMIDITY
- LOWBAT
- MAINTAIN
- UNREACH
- POWER
- ERROR
- WORKING
- WINDOWOPEN

alle Datenpunkte bis auf HUMIDITY sind vom Typ boolean, HUMIDITY ist vom Type number.
zusätzlich besteht die Beschränkung auf 9 Icon

**Comment by c3b69** [comment]
Hi
Ich möchte da nicht unbedingt eine Zahl haben. Dachte nur, dass da eine hin sollte, da dort schon ein %-Zeichen steht.
Wozu soll das icon dann sein? Wenn der humidity-Wert zwischen zwei bestimmten Werten steht? Z.B zwischen 40% und 60%?
Wenn ich im alias die variablen lösche, sind alle icons verschwunden. sobald ich die power-Variable zuweise, sehe ich wieder das Partyicon, das boosticon, das humidityicon und das Powericon. Warum ist das so? Der Zusammenhang ergibt sich mir noch nicht.
Ich habe eine Variable für power angelegt und diese im alias zugewiesen. Jetz kann ich sie über das powericon schalten. Ist der Wert true und der Birdschirmschoner erscheint, funktioniert es auch weiterhin. Ist der Wert false, kann ich den Wert schalten, er bleibt aber grau, sobald der Bildschirmschoner eingeschaltet war. Setze ich ihn wieder true (trotz ausgegraut) funktioniert es wieder.
Auto und Manu kann ich zuweisen. Boost und vacation bekomme ich nicht hin. Ich bin davon ausgegangen, dass ich im alias unter Zustand noch weitere hinzufügen kann. Das funktioniert aber nicht. Ich kann zwar weitere Zustände hinzufügen, aber nicht speicher.

LG aus dem Sauerland
Jörg

**Comment by tt-tom17** [comment]
Das Icon ändert seine Farbe, wenn sich der Wert in einem bestimmten Bereich sich befindet. 
```
 < 30 rot
 < 40 gelb
 >= 40 Grün
 > 65 gelb
 > 75 rot
```

> Wenn ich im alias die variablen lösche, sind alle icons verschwunden.

Welche Variable löscht du im Alias, kann dir da nicht ganz folgen. Oder meinst du mit Variable einen Datenpunkt?
Wie und wo löscht du diese Variable?

> Auto und Manu kann ich zuweisen. Boost und vacation bekomme ich nicht hin. Ich bin davon ausgegangen, dass ich im alias unter Zustand noch weitere hinzufügen kann.

Du meinst den Datenpunkt Mode?  Dieser erkennt die Zahlen 0 -> Auto oder 1 -> Manual und wird als Text im Display unter Zustand angezeigt.
**ABER** diese Datenpunkte überschreiben den Zustand, wenn sie aktiv sind. die Prioritäten sind in der Reihenfolge aufsteigend, heisst wenn BOOST true ist sind die anderen Werte für die Anzeige egal, dann steht BOOST unter Zustand. 
* AUTOMATIC
* MANUAL
* PARTY
* VACATION
* BOOST
Sie überschreiben auch den Werte von Mode. Also wenn in Mode Manual steht, überschreibt der Datenpunkt AUTOMATIC ihn mit Auto.  
  
Das sind alle Datenpunkte die die Card auswerten kann.
<img width="1462" alt="Bildschirmfoto 2024-02-13 um 10 24 18" src="https://github.com/joBr99/nspanel-lovelace-ui/assets/101348966/28ec4b6f-4e86-4e7f-ba31-9abd3721b231">
  
hier noch ein Paar Infos zu den Alias Datenpunkten, das Thermostat ist Punkt 23.  
https://github.com/joBr99/nspanel-lovelace-ui/wiki/ioBroker-ALIAS-Table

**Comment by c3b69** [comment]
Hi
Danke für deine/eure Bemühungen. Den link kenne ich. Hab ich auch schon mehr als einmal gelesen. Nur verstanden anscheinend nicht.
Ich habe die icons Party und Boost immer angezeigt bekommen. Die Daten im alias waren aber glöscht. Da hat nur das löschen des ompletten alias geholfen.
Ich habe mich mit der aktualisierung richtig ins Boxhorn jagen lassen. Die power-Funktion aktualisiert sich sofort. Heißt es wird grau bei false und grün bei true.
Bei allen anderen (mode und icons) aktualisieren sie sich erst, wenn ich entweder das Panel neu starte oder ich wechsele einmal die Seite.

Soweit ist das jetzt auch klar. Hab ein paar kleine skripts geschrieben, welche meine händisch angelegten DP mit true und false beschreiben. Diese DP habe ich in dem alias zugeordnet. Somit kann ich die Zustände ändern. Ich hoffe das ist jetzt so weit richtig.

Kann man an der aktualisierung etwas machen? Oder bin ich immer noch auf dem falschen Dampfer?

LG aus dem Sauerland
Jörg

**Comment by tt-tom17** [comment]
> Kann man an der aktualisierung etwas machen? Oder bin ich immer noch auf dem falschen Dampfer?

Ich sehe mir nochmal an, welche Datenpunkte live aktualisiert werden und welche nur beim öffnen der Seite gelesen werden.

**Comment by Armilar** [comment]
@c3b69

Soll die cardThermo denn als AOD (Always On Display) betrieben werden, dass heißt gänzlich ohne Screensaver? So dass die cardThermo immer im Vordergrund ist?

Dafür wurde sie im ioBroker nicht konzipiert... aber dennoch mit etwas Aufwand machbar...

Die Seite wird im aktuellen Skript nur nach Screensaver oder Seitenwechsel neu gerendert. Ebenso, wenn eine "Aktionstaste" wie Boost, Mode-Umstellung, On/Off gedrückt wurde. Wir sind bislang davon ausgegangen, dass die cardThermo nicht dauerhaft offen bleibt, was sie aber bei einem 100% Thermostatersatz ja bleiben würde.

Im Adapter wurde bereits berücksichtigt, das jede Card AOD-Eigenschaften haben kann...

**Comment by tt-tom17** [comment]
@c3b69  kann der Issue jetzt geschlossen werden?
