### ISSUE TITLE
[BUG] False Time, 

### ISSUE THREAD

**Issue by freed40** [joBr99/nspanel-lovelace-ui#1175]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
I habe the problem, that it shows me 16:00, but it is 17:00. I have a us model, but i am from germany, i hope thats not a problem.
![Bildschirmfoto 2024-02-11 um 17 14 41](https://github.com/joBr99/nspanel-lovelace-ui/assets/25461127/095214d4-c596-49c9-bb72-393606199c7a)

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
the time_zone config line belongs into appdaemon.yaml not apps.yaml

**Comment by freed40** [comment]
Ok but my appdaemon.yaml is ok:
appdaemon:
  latitude: 50.9847679
  longitude: 11.0298799
  elevation: 30
  time_zone: Europe/Berlin
  plugins:
    HASS:

but the terminal shows me this:

2024-02-11 17:35:00.942894 INFO nspanel-1: Sending MQTT Message: time~16:35~

2024-02-11 17:35:41.914052 INFO AppDaemon: New client Admin Client connected

2024-02-11 17:36:00.948363 INFO nspanel-1: Sending MQTT Message: time~16:36~

**Comment by joBr99** [comment]
time is taken from the docker container's timezone - this should be the timezone of your home assistant installation

It is possible to overwrite the timezone in apps.yaml with this configuration:

`timezone: Europe/Berlin`

However you might need to switch to the dev version for this to work. Not sure if it is part of the lastest release.
https://docs.nspanel.pky.eu/stable/faq/#how-to-upgrade-from-a-release-to-the-current-development-version
Upgrading the tft firmware is not required.

**Comment by freed40** [comment]
ok, thanks, i dont know but it dosnt work, at my setup

**Comment by joBr99** [comment]
did you upgrade to the dev version and did you restart appdaemon afterwards?

**Comment by freed40** [comment]
no, i dont now but it wont update, i have 4.3.1, i want to update with hacs, but it dont made it

**Comment by joBr99** [comment]
was? wie kannst du denn 4.3.1 haben, hat sich jetzt für mich eher so angehört als ob du das gerade erst installiert hast
