### ISSUE TITLE
[Feature Request] (HMI) Please allow changing an icon in the popupLight

### ISSUE THREAD

**Issue by Armilar** [joBr99/nspanel-lovelace-ui#1178]
### FEATURE DESCRIPTION
```
entityUpdateDetail~entityName~*ignored*~*iconColor*~*buttonState*~*sliderBrightnessPos*~*sliderColorTempPos*~*colorMode*~*color_translation*~*color_temp_translation*~*brightness_translation*
```
The icon is marked as ignored in the description of the serial protocol. I would like to have it changeable in ioBroker.

### PANEL / FIRMWARE VERSION
EU, US-L and US-P

**Comment by joBr99** [comment]
icon is now parsed in case it's not an empty string
