### ISSUE TITLE
[Feature Request] Roadmap for what is coming/in work

### ISSUE THREAD

**Issue by cekosss** [joBr99/nspanel-lovelace-ui#1197]
### FEATURE DESCRIPTION
This is not a specific feature request for the panel, but I (and other people too) would really appreciate something like a roadmap, where we can see features in work/planned etc., maybe the possible release date and so on. This could for example be a google doc or an online kanban board.

### ADDITIONAL CONTEXT
-/-

### PANEL / FIRMWARE VERSION
-/-

**Comment by joBr99** [comment]
This project is taking a lot of time that I don't have - so it's ready when it's ready.

But you are welcome to contribute and implement stuff in a Pull Request :)
