### ISSUE TITLE
[Feature Request] How to get notification button presses?

### ISSUE THREAD

**Issue by gosoares** [joBr99/nspanel-lovelace-ui#1200]
### FEATURE DESCRIPTION
In the [notifications documentation](https://docs.nspanel.pky.eu/notifications/#notification-on-screensaver) it is shown how to send a notification to the nspanel in a separate page, with the possibility of adding buttons to it. But when these buttons are pressed, nothing happens. The notification continues to shown at the nspanel and no event or state change are sent to home assistant. How can i get theses button presses in home assistant to use it in a automation?

### PANEL / FIRMWARE VERSION
US-P

**Comment by rossi75** [comment]
Hi Gosoares,

I struggled along this also  long time. The result is that easy.... But let's start from the beginning...

You push a notification towards the panel, and the left softbutton replies with a NO, the right softutton with a YES. So let's have a look in the MQTT logs given by the NSPanels Console:
![grafik](https://github.com/joBr99/nspanel-lovelace-ui/assets/91349581/45036a4a-1c1e-4520-bf63-e9b6a2453ff8)

Now that we found the string, where does it go to? Simply place an event trigger in your automation:
![grafik](https://github.com/joBr99/nspanel-lovelace-ui/assets/91349581/3fc59481-6293-4a21-b7e9-4f3efb6bc819)

Hence you can proceed with your automation... for example to cancel the popup message:
![grafik](https://github.com/joBr99/nspanel-lovelace-ui/assets/91349581/01512771-818f-4189-9370-695fd16fb3e1)

which will be shown in the NSPanel Console as this:
![grafik](https://github.com/joBr99/nspanel-lovelace-ui/assets/91349581/ad8b941e-a048-44ee-a169-5f148806cc09)


Hope that helps and answers your question...

**Comment by gosoares** [comment]
Thanks @rossi75.

I am away from home for a few days so i cant test this right now, but i believe its what i need. Much appreciated.
