### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by nuiler** [joBr99/nspanel-lovelace-ui#1202]
I am looking for the stock firmware portrait for the NSPanel US
where can I find a link to it?

**Comment by joBr99** [comment]
https://github.com/masto/NSPanel-Demo-Files/issues/4

You need to put it onto a HTTP Server for flashing, you cannot directly flash it from the discord URL.

**Comment by nuiler** [comment]
This content is no longer available.

**Comment by joBr99** [comment]
maybe you need to join the discord server for downloading the file

https://unofficialnextion.com/t/welcome-to-the-unofficial-nextion-tjc-user-forum/8
