### ISSUE TITLE
[BUG] Icons missing / not working

### ISSUE THREAD

**Issue by joke24** [joBr99/nspanel-lovelace-ui#1205]
### PROBLEM DESCRIPTION
I used the latest version of branch main and flashed it on my nspanel.
I send the following commands to MQTT CustomSend Topic:

`pageType~cardGrid`

`entityUpd~LightTest~button~navigate.prev~<~65535~~~button~navigate.next~>~65535~~~light~light.bed_light~lightbulb~17299~Bed Light~0~light~light.ceiling_lights~abacus~52231~Ceiling Lights~1~switch~switch.ac~rocket~17299~AC~0~switch~switch.decorative_lights~sack~65222~Decorative Lights~1`

The nspanel shows the grid layout with the single items, but the items show without the icons. 
The icon-name is written in text in big letters.
I took the icon-names from the website https://docs.nspanel.pky.eu/icon-cheatsheet.html

### EXPECTED BEHAVIOUR
Icons are shown

### SCREENSHOTS
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/19669309/f2b5c966-84db-44c9-840f-fa97b90dc506)

### ADDITIONAL CONTEXT
Manual messages with MQTT explorer and Mosquitto message broker

### PANEL / FIRMWARE VERSION
NSPANEL EU 
Latest main, downloaded on 30.03.2024
Tasmota 13.4.0.3 (71e6664-nspanel)

**Comment by joke24** [comment]
This was fast, just after rechecking the third time i went to https://docs.nspanel.pky.eu/icon-cheatsheet.html again and clicked on the little U button beside the icon. This copied a strange code to the clipboard and i tried it with that. 
It worked -.-

**Comment by joBr99** [comment]
yep, works as expected - it's showing the text you are sending - the icons are just chars

| 14 | First Entity | Entity Definition | type          | light           |
|----|:------------:|:-----------------:|---------------|-----------------|
| 15 |              |                   | intNameEntity | light.bed_light |
| 16 |              |                   | icon          | lightbulb       |
| 17 |              |                   | iconColor     | 17299           |
| 18 |              |                   | displayName   | Bed Light       |
| 19 |              |                   | optionalValue | 0               |
