### ISSUE TITLE
[BUG]  Unexpected error in worker for App

### ISSUE THREAD

**Issue by dabrain-cpu** [joBr99/nspanel-lovelace-ui#1206]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
NSpanel was working fine without any issue's. Suddenly it "lost" it connection. The NSpanel is now waiting for content.
Strange thing is that there was no update in Home assistant available or done which could break something. Did a restart off Appdeamon, Restarted home assitant completely no luck.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:
`nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel/RESULT"
    panelSendTopic: "cmnd/nspanel/CustomSend"
    model: eu
    sleepTimeout: 20
    sleepBrightness:
      - time: "10:00:00"
        value: 10
      - time: "22:0S0:00"
        value: 0
    locale: "nl_NL"
    screensaver:
      entities:
        - entity: weather.buienradar
        - entity: weather.buienradar
          type: 0
        - entity: weather.buienradar
          type: 1
        - entity: sensor.buienradar_wind_force
        - entity: delete
        - entity: sensor.nspanel_bedroom_temperature
          icon: mdi:home-thermometer-outline
    cards:
      - type: cardGrid
        title: Slaapkamer
        entities:
          - entity: light.lamp_brian
          - entity: light.lamp_melanie
          - entity: light.beneden_verlichting
          - entity: navigate.cover
            icon: mdi:window
      - type: cardThermo
        title: Airco Slaapkamer
        entity: climate.slaapkamer
      - type: Badkamer
        entity: media_player.spotify
    hiddenCards:
      - type: cardGrid
        title: Covers
        entities:
          - entity: cover.raam1
          - entity: cover.raam2
          - entity: cover.raam3
          - entity: cover.achterdeur
          - entity: cover.keukenraam
          - entity: cover.keukendeur
          - entity: cover.garageraam
        key: cover
`

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
`2024-04-01 22:36:48.774754 WARNING nspanel-1: ------------------------------------------------------------
2024-04-01 22:36:48.774861 WARNING nspanel-1: Unexpected error in worker for App nspanel-1:
2024-04-01 22:36:48.774951 WARNING nspanel-1: Worker Ags: {}
2024-04-01 22:36:48.775030 WARNING nspanel-1: ------------------------------------------------------------
2024-04-01 22:36:48.775477 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 162, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 31, in initialize
    mqttsender = self._mqttsender = LuiMqttSender(apis.ha_api, use_api, topic_send, api_panel_name, quiet)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LuiMqttSender.__init__() takes 3 positional arguments but 6 were given

2024-04-01 22:36:48.775587 WARNING nspanel-1: ------------------------------------------------------------`

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Constantly happening

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_
NSpanel runs on ESPhome, using home assistant

### PANEL / FIRMWARE VERSION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU

**Comment by meneerhenk** [comment]
I just had the same issue after updating.
Setup is home assistant os as VM with all the rest there in docker (some default image setup with updates rolled out).
Rebooting the VM solved this issue. Restarting home assistant or hacs itself didn't do the trick for me.

**Comment by dabrain-cpu** [comment]
Yes that's it, was running on vm as well. Restarting the complete vm did the trick.
Thank you
________________________________
Van: meneerhenk ***@***.***>
Verzonden: woensdag 3 april 2024 16:01
Aan: joBr99/nspanel-lovelace-ui ***@***.***>
CC: dabrain-cpu ***@***.***>; Author ***@***.***>
Onderwerp: Re: [joBr99/nspanel-lovelace-ui] [BUG] Unexpected error in worker for App (Issue #1206)


I just had the same issue after updating.
Setup is home assistant os as VM with all the rest there in docker (some default image setup with updates rolled out).
Rebooting the VM solved this issue. Restarting home assistant or hacs itself didn't do the trick for me.
