### ISSUE TITLE
[BUG] Error when adding HA 2024.4 weather forecast workaround

### ISSUE THREAD

**Issue by smartmatic** [joBr99/nspanel-lovelace-ui#1207]
### PROBLEM DESCRIPTION
I am not able to add provided HA 2024.4 weather workaround as described here:
https://docs.nspanel.pky.eu/stable/prepare_ha/#installing-lovelace-appdaemon-backend-application

I have splitted my configuration.yaml to a template.yaml and a sensor.yaml. How to apply the workaround in this case?

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
Install HA 2024.4 and splitt workaround to a template.yaml and sensor.yaml

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
![Bildschirmfoto 2024-04-02 um 15 27 39](https://github.com/joBr99/nspanel-lovelace-ui/assets/74932663/a69d289d-7617-400f-8064-6857fb8660bd)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERSION
EU panel, Tasmota 13.3.0, HA 2024.3.3

**Comment by joBr99** [comment]
just remove the `template:` line shift everything to the left and add it to your template.yaml

**Comment by smartmatic** [comment]
Then i get this
![Bildschirmfoto 2024-04-02 um 15 39 07](https://github.com/joBr99/nspanel-lovelace-ui/assets/74932663/7bf51041-ed97-4f53-b033-6bb51500076d)

**Comment by joBr99** [comment]
you need to move every line to the left to fix the indentation not only the first one

**Comment by smartmatic** [comment]
Thanks its working!

**Comment by rossi75** [comment]
> Thanks its working!

I am struggling at a similar point. Issue with my configuration is, that the other entities template.yaml will then be only executed every hour. Can you share a screenshot of your template.yaml?

**Comment by smartmatic** [comment]
yes, sure

![Bildschirmfoto 2024-04-05 um 08 54 42](https://github.com/joBr99/nspanel-lovelace-ui/assets/74932663/50ec60b0-b8ef-412e-84a4-ac4ef49eb8af)
