### ISSUE TITLE
[Feature Request] Preview of rendering apps.yaml

### ISSUE THREAD

**Issue by Najihel** [joBr99/nspanel-lovelace-ui#1216]
### FEATURE DESCRIPTION
Capability to preview the rendering of the apps.yaml configuration.

### ADDITIONAL CONTEXT
Hello,

When you are editing apps.yaml without the NSPanel near you it could be nice to view the rendering.

Maybe it already possible but I didn't find information on the documentation.

Thanks

### PANEL / FIRMWARE VERSION
NSpanel EU

**Comment by joBr99** [comment]
with a spare esp32 and the nextion editor you can build yourself an emulator

https://github.com/joBr99/nspanel-lovelace-ui/wiki/NSPanel-Nextion-Editor

**Comment by Najihel** [comment]
Hello @joBr99 

Did you think it's possible to emulate NsPanel through https://wokwi.com ?

**Comment by joBr99** [comment]
No, I don't think so - you need a serial device on your computer that talks to the backend via mqtt. This doesn't have to be an ESP32, however it's the easiest option.
