### ISSUE TITLE
[Feature Request] Change font color under icons on screensaver

### ISSUE THREAD

**Issue by YeeYek** [joBr99/nspanel-lovelace-ui#1225]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._
Please add posiibility to hide text (change color)  under entity icon - PFA
### ADDITIONAL CONTEXT
_Add any other context about the problem here._
Description of the entity statte is inadequate. 
### PANEL / FIRMWARE VERSION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU v.4.4.0
![20240517_111701](https://github.com/joBr99/nspanel-lovelace-ui/assets/77362116/fa3250ce-f30b-4117-a812-31b97c2d5599)

**Comment by joBr99** [comment]
Those are normal entities, you can override the color and value:

https://docs.nspanel.pky.eu/stable/entities/
