### ISSUE TITLE
[Feature request] screensaver item callbacks / cleanup

### ISSUE THREAD

**Issue by gerard33** [joBr99/nspanel-lovelace-ui#123]
Can you add support for the callbacks of entities which override the weather forecast?

- The entities from `screensaver:` are currently not registered in `register_callbacks` function in controller.py via `get_all_entity_names` in config.py.
- When the screensaver is open the current card is not recognized as screensaver in `state_change_callback` in controller.py.
- And maybe the weather entity can also be part of the callback, so the weather info on the screensaver updates when there is a change instead of the current 15 minutes interval.

**Comment by joBr99** [comment]
with some refactoring the screensaver could get a "normal" page that's also stored in current_page

**Comment by joBr99** [comment]
@gerard33 screensaver is now stored in current_card and the cards are pushed/poped to previous_cards on entering/exiting screensaver

(didn't do mutch testing with it, I might missed something)
