### ISSUE TITLE
Adding NSPanel buttons to Home Assistant as entites

### ISSUE THREAD

**Issue by mkaflowski** [joBr99/nspanel-lovelace-ui#1231]
Is it possible to add NSPanel buttons to Home Assistant as entites?
I need to control power states of nspanel for some autiomations like turning on light.

**Comment by joBr99** [comment]
You can decouple the buttons from the relay, if you need to do so:
https://docs.nspanel.pky.eu/stable/phys-btn/#decouple-buttons-from-controlling-power-outputs

**Comment by mkaflowski** [comment]
SetOption19 0 fixed the issue

**Comment by joBr99** [comment]
`SetOption19 0` is the default and `SetOption19 1` is no longer included in release binaries of tasmota, did you configure this in earlier versions?
