### ISSUE TITLE
[Feature Request]  A card that can display a static image from a URL

### ISSUE THREAD

**Issue by kennism** [joBr99/nspanel-lovelace-ui#1235]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._
Add a card to display a static image from a http location.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
For example, to have a card where a static snapshot image from a camera is shown.

### PANEL / FIRMWARE VERSION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
There is no way to transfer images to the nextion screen - all images have to be baked into the next ion firmware / TFT file.
