### ISSUE TITLE
[BUG]  Error: Cannot find module 'dayjs' - ioBroker

### ISSUE THREAD

**Issue by MeierAlex** [joBr99/nspanel-lovelace-ui#1241]
### PROBLEM DESCRIPTION
When running the script NSPanelTs.ts in the JavaScript instance of my ioBroker I get the following error:

script.js.common.NsPanel.NsPanel_1: Error: Cannot find module 'dayjs'

This is the configuration of the JavaScript adapter:

![image](https://github.com/user-attachments/assets/8d00acc0-e56f-4236-889a-3f8c6c84d343)

dayjs is installed:
![image](https://github.com/user-attachments/assets/e02e92fb-dd15-4fec-803e-0a52ba298b54)

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide your apps.yaml (or your config):
```
  apps.yaml here:
Not applicable here.

```
- [x] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
Not applicable here.

```

### TO REPRODUCE
See this discussion on the ioBroker forum:
https://213.136.68.177/topic/58170/sonoff-nspanel-mit-lovelace-ui/6047?lang=en-GB&page=302

### EXPECTED BEHAVIOUR
Script runs without errors and does not spam log.

### SCREENSHOTS
See above

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_
ioBroker setup information:
CPU: 17,93 %
RAM: 57 %
Uptime: 13h
Available: 6.0.9
Installed: 6.0.9
Events: ⇥22 / ↦13
Platform: linux
operating system: linux
Architecture: x64
CPUs: 2
Speed: 2396 MHz
Model: Intel(R) Celeron(R) J4105 CPU @ 1.50GHz
RAM: 4 GB
System uptime: 14:08:18
Node.js: v18.20.4
time: 1723367155248
timeOffset: -120
NPM: 10.8.2
adapters count: 540
Disk size: 31.2 GB
Disk free: 25.9 GB
Active instances: 21
Path: /opt/iobroker/
Uptime: 13:15:48
alive: true
_nodeCurrent: 18.20.4
_nodeNewest: 18.20.4
_nodeNewestNext: 20.16.0
_npmCurrent: 10.8.2
_npmNewest: 10.7.0
_npmNewestNext: 10.8.1

### PANEL / FIRMWARE VERSION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
Version: EU
NsPanel with firware V 4.4.0

**Comment by Armilar** [comment]
day.js removed
