### ISSUE TITLE
[BUG] can't flash tft with latest Tasmota (14.2.0)

### ISSUE THREAD

**Issue by mokkin** [joBr99/nspanel-lovelace-ui#1246]
I was not able to flash the tft file with the latest tasmota on the ns panel. After downgrading to tasmota 13.3 it worked as described in the documenation.

**Comment by joBr99** [comment]
I just tried with 14.1.0, can you confirm that this version is working?

https://ota.tasmota.com/tasmota32/release-14.1.0/tasmota32-nspanel.bin

**Comment by janprive** [comment]
I’m on 14.1.0 and used it to flash tft beta on my nspanels. All went fine!Groeten!Jan Boeren(Verstuurd vanaf mijn telefoon)Op 22 aug 2024 om 19:43 heeft Johannes ***@***.***> het volgende geschreven:﻿
I just tried with 14.1.0, can you confirm that this version is working?
https://ota.tasmota.com/tasmota32/release-14.1.0/tasmota32-nspanel.bin

**Comment by sanderpqr** [comment]
I had the same issue, with Tasmota 14.2.0 I could not flash the Development panel firmware.

Tasmota console:

> CMD: FlashNextion http://nspanel.pky.eu/lui.tft
> MQT: stat/nsptasmota/RESULT = {"FlashNextion":"Done"}
> FLH: host: nspanel.pky.eu, port: 80, get: /lui.tft
> FLH: Send (High Speed) flash start
> FLH: Something has gone wrong flashing display firmware [bytes('85')]

And the screen was stuck on:

> USART Update...
> 	921600
> SIZE:
> 	8373568
> writing DATA....
> 
> [..............................]

Or, the console would report a successful flash, but then the screen would be stuck on:

> Model does not match
> Device Model:
> NX4832F035_011C

However, after downgrading to 14.1.0 I could flash the Development TFT.

**Comment by LenoDuan** [comment]
I am not able to flash tft with latest version ,![information](https://github.com/user-attachments/assets/0b4dc385-7dd8-4e4d-a1f9-29a8ce43d9e3)


05:38:58.481 FLH: host: nspanel.pky.eu, port: 80, get: /lui-release.tft
05:39:00.055 FLH: Send (High Speed) flash start
05:39:00.503 FLH: Something has gone wrong flashing display firmware [bytes('0A')]

the screen is freeze after display writing DATA

**Comment by joBr99** [comment]
Please downgrade to 

https://ota.tasmota.com/tasmota32/release-14.1.0/tasmota32-nspanel.bin

**Comment by LenoDuan** [comment]
> Please downgrade to
> 
> https://ota.tasmota.com/tasmota32/release-14.1.0/tasmota32-nspanel.bin

how can I downgrade,When I tried from the OTA firmware and input the source URL,it seems downgrade faild,should I use another solution?sorry it's my first time use tasmota

**Comment by janprive** [comment]
Download the bin file from the url and flash it local. Not ota.Groeten!Jan Boeren(Verstuurd vanaf mijn telefoon)Op 27 aug 2024 om 08:51 heeft LenoDuan ***@***.***> het volgende geschreven:﻿

Please downgrade to
https://ota.tasmota.com/tasmota32/release-14.1.0/tasmota32-nspanel.bin

how can I downgrade,When I tried from the OTA firmware and input the source URL,it seems downgrade faild,should I use another solution?sorry it's my first time use tasmota

**Comment by LenoDuan** [comment]
> Download the bin file from the url and flash it local. Not ota.Groeten!Jan Boeren(Verstuurd vanaf mijn telefoon)Op 27 aug 2024 om 08:51 heeft LenoDuan ***@***.***> het volgende geschreven:﻿ Please downgrade to https://ota.tasmota.com/tasmota32/release-14.1.0/tasmota32-nspanel.bin how can I downgrade,When I tried from the OTA firmware and input the source URL,it seems downgrade faild,should I use another solution?sorry it's my first time use tasmota —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
![flashing](https://github.com/user-attachments/assets/d7754319-e6f0-4fe4-98f3-cace85b766f7)

I tried to flash it,but unable to bootup(I am not sure,but no wifi hotspot)，
I am only able to flash this bin file (https://ota.tasmota.com/tasmota32/release/tasmota32-nspanel.factory.bin) and works properly,but not able to flash tft,with any else bin file,the nspanel is not able to find wifi hotspot

**Comment by Lantoit** [comment]
Same problem, I've downgraded by OTA, than the screen was blocked.
After power down/up the firmware was minimal that i'had upgraded by local file.

**Comment by luetty** [comment]
Had the same issue.
Got now Tasmota 14.3.0 and flashed tft siccessfully. :-)

**Comment by Armilar** [comment]
Use Tasmota >=14.3.0

**Comment by joBr99** [comment]
Fixed by https://github.com/arendst/Tasmota/pull/21657 / https://github.com/arendst/Tasmota/pull/22057
