### ISSUE TITLE
[Help] Does HACS 2.0.0 release impact nspanel-lovelace-ui?

### ISSUE THREAD

**Issue by axi92** [joBr99/nspanel-lovelace-ui#1247]
### PROBLEM DESCRIPTION

HACS had a major update
https://github.com/hacs/integration/releases/2.0.0
Does this impact NSPanel Lovelace UI Backend?

If not should I be able to update HACS without creating issues with my nspanel?

[] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide a screenshot of your tasmota mqtt configuration:

- [ ] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:


```

- [ ] Provide your apps.yaml:
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:


```

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_

**Comment by joBr99** [comment]
I've no clue, seen the announcement, but haven't upgraded so far.

**Comment by joBr99** [comment]
From the breaking changes I cannot see anything that would be an issue.

**Comment by hiscorebob** [comment]
I used HACS 2.0 to install nspanel-lovelace-ui, no issues encountered.
