### ISSUE TITLE
[Feature Request] Screensaverpopup switch off

### ISSUE THREAD

**Issue by sascha-g** [joBr99/nspanel-lovelace-ui#1249]
### FEATURE DESCRIPTION
I would like to be able to switch off the screensaverpopup again via a data point. Previously it was possible with an empty string of popupNotifyHeading and popupNotifyText.

### ADDITIONAL CONTEXT
https://forum.iobroker.net/topic/58170/sonoff-nspanel-mit-lovelace-ui/6232

### PANEL / FIRMWARE VERSION
TFT 53 / v4.4.0 EU_Panel

**Comment by joBr99** [comment]
Code for notification on screensaver didn't change:

https://github.com/joBr99/nspanel-lovelace-ui/blob/main/HMI/n2t-out/screensaver.txt#L699

Empty Strings for both should clear the notification

**Comment by tt-tom17** [comment]
Lösungsvorschlag aus dem Forum wird geprüft und ggf. umgesetzt. [Form Post ](https://forum.iobroker.net/post/1195620)

**Comment by tt-tom17** [comment]
Lösung geprüft und im Wiki mit auf genommen
