### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by rossi75** [joBr99/nspanel-lovelace-ui#1250]
### PROBLEM DESCRIPTION
documentation link does not work anymore
https://docs.nspanel.pky.eu/ loads until timeout
![image](https://github.com/user-attachments/assets/bc2e3182-4a4e-40d9-a2d3-3999d40ba337)

Ping results in:
![image](https://github.com/user-attachments/assets/6632f47a-6532-416f-9aaa-5b1a4e5aa004)

### TO REPRODUCE
just put the link in your browser

### EXPECTED BEHAVIOUR
loading the documentation

**Comment by joBr99** [comment]
Working fine for me

https://downforeveryoneorjustme.com/docs.nspanel.pky.eu?proto=https
