### ISSUE TITLE
[Feature Request] Page Variable - remote activate / deactivate pages - iobroker

### ISSUE THREAD

**Issue by Ilovegym66** [joBr99/nspanel-lovelace-ui#1254]
See https://forum.iobroker.net/post/1200299

To deactivate some pages, if nobody is at home, for security reasons, or to activate in special cases a page or more pages, it should be fine, if for every page it's possible to create a boolean variable in userdata.0/nspanelx/pages, which can switched from other scripts. ( Presence, Security, Night/Day, Primecontrol etc.)

**Comment by Armilar** [comment]
Function implemented in DEV version at:
https://github.com/joBr99/nspanel-lovelace-ui/blob/main/ioBroker/DEV/NSPanelTs.ts

Described at:
https://forum.iobroker.net/post/1201018
