### ISSUE TITLE
Github issue

### ISSUE THREAD

**Issue by jmbinette** [joBr99/nspanel-lovelace-ui#126]
Sorry I am not an expert with github.
I forked to help with the US portrait version and every time I push commits, it seems like the actions (Nextion2text) create new files afterwards and I am always 1 commit ahead of the main.

Any idea on what is the correct way to prevent this ?

Thanks again,

**Comment by joBr99** [comment]
Hit me up on discord, might be better to discuss things releated to the portrait version there
https://discord.gg/98V7qp4

but in general this shouldn't be an issue, the action is adding the changes oft the hmi as new commit, but it's also doing this on pull requests, so this shouldn't be an issue

**Comment by joBr99** [comment]
moving communication around us portrait version to discord
