### ISSUE TITLE
[BUG] timeoutScreensaver and activeBrightness do not have expected behavior

### ISSUE THREAD

**Issue by Subnum12** [joBr99/nspanel-lovelace-ui#1266]
### PROBLEM DESCRIPTION
setting `0_userdata.0.NSPanel.1.Config.Screensaver.timeoutScreensaver` to 0 to disable Screensaver requires a reboot of the script to take effect.

### REQUESTED INFORMATION
https://forum.iobroker.net/post/1208407

### TO REPRODUCE
set `0_userdata.0.NSPanel.1.Config.Screensaver.timeoutScreensaver` from 10 to 0 via mqtt, screensaver will come up again.
restart script, screensaver will remain disabled.

### EXPECTED BEHAVIOUR
set `0_userdata.0.NSPanel.1.Config.Screensaver.timeoutScreensaver` from 10 to 0 via mqtt, screensaver will will remain disabled.

### ADDITIONAL CONTEXT
TFT: 53 / v4.4.0
Javascript: v8.8.3
NodeJS: v20.18.0
Script: 4.4.0.5
Tasmota: 14.2.0

Similar issue with `0_userdata.0.NSPanel.1.ScreensaverInfo.activeBrightness`, that will not get synced at all (change on display does not lead to change in mqtt, and update via mqtt does not lead to any change on display)

### PANEL / FIRMWARE VERSION
-

**Comment by Armilar** [comment]
Fix by @tt-tom17  —> next Version

**Comment by Armilar** [comment]
![image](https://github.com/user-attachments/assets/960f1571-5090-47f1-8afb-9f98d24a79ac)
