### ISSUE TITLE
[BUG] Please add documentation about how to backup the original sonoff nextion firmware and be able to restore it.

### ISSUE THREAD

**Issue by damocles-dev** [joBr99/nspanel-lovelace-ui#1267]
### PROBLEM DESCRIPTION

Hi, I installed nspanel thinking I could revert it, but stupid me I flashed the nextion firmware and it seems that it is not possible to recover the original firmware if a backup was not made before.

Please put a clear notice in the instructions so that no one takes the risk and regrets it later.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERSION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
The nextion firmware isn't easily backupable - you need to connect with the correct tools directly to the hardware chip and read out the raw flash. Afterwards you need to extract the tft file from the flash dump.

Please reach out to me on The UNUF Discord.

https://unofficialnextion.com/t/welcome-to-the-unofficial-nextion-tjc-user-forum/8

**Comment by damocles-dev** [comment]
Sorry if I wasn't clear.

I'm talking about the firmware on the nextion display. I updated it thinking I could get the original back. My fault, but a warning in the procedure would have prevented me from doing that.

**Comment by joBr99** [comment]
You can easily get back to the stock firmware - you just need the tft file from sonoff. There might be some links on the internet that are still online - however just join UNUF.
