### ISSUE TITLE
request for cardCamera

### ISSUE THREAD

**Issue by Llntrvr** [joBr99/nspanel-lovelace-ui#127]
Would be awsome if there was a way to either load an image into the background of a card or to have a cardCamera with an entity that points to camera item in HA, i mainly want to load a static image but would be nice to have an option of how often the image needs to be refreshed.

**Comment by joBr99** [comment]
The nextion discovery screen inside of nspanel doesn't allow you to transfer pictures on runtime, they have to be baked into the firmware, so this isn't possible.
