### ISSUE TITLE
[Help]  Values ​​without decimal places

### ISSUE THREAD

**Issue by emddummi** [joBr99/nspanel-lovelace-ui#1279]
I would like to display the values ​​on the far left of the icons in Screensaver2, just without dacimal places. How can I set this?

>  screensaver:
     type: screensaver2
      entities:
        - entity: weather.forecast_home
        - entity: sensor.strom_bkw_power //This one
          icon: mdi:solar-power-variant-outline
        - entity: sensor.netzbezug_total_active_power //This one
          icon: mdi:home-lightning-bolt-outline`   

Thanks for help

**Comment by joBr99** [comment]
something like this:

``` 
        - entity: sensor.temp_kueche_temperature
          value: '{{states("sensor.temp_kueche_temperature") | round(1)}}°C'
          icon: mdi:home-thermometer-outline

```
