### ISSUE TITLE
new value for popupNotify is active

### ISSUE THREAD

**Issue by Subnum12** [joBr99/nspanel-lovelace-ui#1281]
### FEATURE DESCRIPTION
a new variable `.popupNotify.popupNotifyActive` is required

### ADDITIONAL CONTEXT
Currently there is no way to know if `popupNotify` appears on display. If you shoot an popup to nspanel you may check `popupNotifyAction` for the result of closing popup . However, the popup can be closed without using button 1 or 2 e.g. X got hit or by timeout.
To know a popup got closed on nspanel there should be some kind of information for that.

**Comment by Armilar** [comment]
When loading a page, however, there is a change under: "0_userdata.0.NSPanel.X.ActivePage" that could be used.

The NSPanel (HMI) does not return any events when the "x" is pressed. That would be a change for the HMI.

**Comment by joBr99** [comment]
Hey, pressing x should send this message:

event,buttonPress2,popupNotify,bExit

**Comment by Armilar** [comment]
That's actually true.

`event,renderCurrentPage`

comes so quickly that it seems that `bExit` wasn't there.

We'll include the popupNotify in the ActivePage data point.

**Comment by Subnum12** [comment]
`0_userdata.0.NSPanel.X.ActivePage` does not get updated with popupNotify at all, it keeps the page below the popup.

`0_userdata.0.NSPanel.X.Event.Button.Action` does change to bExit only it it does not has this value already.  No indication for timeout...

**Comment by Armilar** [comment]
we will implement it --> Next Version

**Comment by Armilar** [comment]
![image](https://github.com/user-attachments/assets/f64c4ff5-c96d-462e-bc60-0034fd9eea85)

**Comment by Subnum12** [comment]
🥇 great job and much faster as expected! I do not understand the project is marked as 
![grafik](https://github.com/user-attachments/assets/7f6e5574-a045-4f4c-9431-b424506b8315)
 on landing page...? Maybe people hesitate to use this script for no reason...

**Comment by joBr99** [comment]
Fixed!

**Comment by Armilar** [comment]
> Maybe people hesitate to use this script for no reason...

The main traffic here is:

https://forum.iobroker.net/topic/58170/sonoff-nspanel-mit-lovelace-ui/6597

![image](https://github.com/user-attachments/assets/a14cd1d5-9750-4cdd-b39c-0e2344ceef1c)

With almost 1.5 million views
