### ISSUE TITLE
possibility to close popupNotify

### ISSUE THREAD

**Issue by Subnum12** [joBr99/nspanel-lovelace-ui#1284]
FEATURE DESCRIPTION
currently there is no way to just close the popupNotify. If there was a warning it does not exist anymore you maybe want to remove the popup.

There are different possibility's to get rid of this. You maybe implement a new variable for this or provide the current page information somewhere. 
With existing `0_userdata.0.NSPanel.x.PageNavi` you could also close the `popupNotify` by pushing current page information. However, you do not provide necessary page information (pagetype, pageId) somewhere.
`0_userdata.0.NSPanel.x.ActivePage` does contain page information but not the one required for `PageNavi` (type, Id0) has a different meaning here.

**Comment by Armilar** [comment]
Write `exitPopup` directly to the MQTT data point `CustomSend`

**Comment by Subnum12** [comment]
works perfect, thanks! 👍
