### ISSUE TITLE
[Feature Request] Input / Edit Time and Display

### ISSUE THREAD

**Issue by san-code** [joBr99/nspanel-lovelace-ui#1285]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._
I want a cardEntities that shows a time with a subpage for editing. the time should be written back to ibroker.
like:
Weckzeit 10:15 Uhr

  ↑  ↑
10:15
  ↓  ↓

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERSION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
Display: EU/53
ioBrokerScript: 4.4.0.12

**Comment by Armilar** [comment]
Do you mean something like that?

https://forum.iobroker.net/post/1092494

It already exists --> popupTimer

**Comment by Armilar** [comment]
**Quick guide**

Use this script:
https://github.com/joBr99/nspanel-lovelace-ui/blob/main/ioBroker/Blockly/Alarm_clock.ts

All data points and alias channels are created automatically

Add a PageItem with the alarm clock alias (your NSPanelTs.ts --> cardEntities or cardGrid))
{ id: 'alias.0.NSPanel.AlarmTime', icon: 'alarm', name: 'Wecker', onColor: Red, offColor: Green, useColor: true },

**Comment by san-code** [comment]
Super, Danke, dass ist genau was ich gesucht habe.

**Comment by tt-tom17** [comment]
erledigt
