### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by dadcoachengineer** [joBr99/nspanel-lovelace-ui#129]
Johannes....thank you for creating this project.

I would love to request a few additional icons in the next release.

e768 ceiling-light
e6b4 lamp

Also.....is there a method for triggering a script or scene as an entity?

Thank you!
Jason

**Comment by Twit123** [comment]
Hi,

I didn't want to create a whole new Feature Request but I've looked through the above mentioned link and WOW that's alot of icons being added but could you also add mdi:lightning-bolt? It's the default "energy" icon in HA (I think), at the moment I'm using mdi:flash but that's the on/off flash in HA so doesn't look correct on the panel (In my eyes).

Thanks for all the great work you have done.

Simon

**Comment by joBr99** [comment]
Hey, 
the Icons are included in the font I'm using, I'm currently not planning to mess with generating a new one, but I've never looked into acually generating them because aderusa told me that is was a huge pain. If you want to look into it this repo contains the font aswell as the scripts to generate them.

https://github.com/aderusha/Generate-HASP-Fonts

**Comment by joBr99** [comment]
@Twit123 Checked what to do to update the Material Design Icon Font, aderusa did a great job with that powershell script, however generating the cheetsheet is still painful, would increase the already huge firmware by another 2MB :/ But it would still fit within the flash of the nspanel.

**Comment by dadcoachengineer** [comment]
@joBr99 - Updated easy and I now have a super simple beautiful panel. Thanks for all of your hard work on this project!

**Comment by joBr99** [comment]
@Twit123 current development version has the lightning-bolt icon included

Cheatsheet in the readme still points to the old version to avoid confusion, use this one until the next release:

https://htmlpreview.github.io/?https://github.com/jobr99/Generate-HASP-Fonts/blob/master/cheatsheet.html



https://github.com/joBr99/nspanel-lovelace-ui/#how-to-upgrade-from-a-release-to-the-current-development-version

**Comment by Twit123** [comment]
Thanks, you're a star.

Simon
