### ISSUE TITLE
heating icon in the thermostats page

### ISSUE THREAD

**Issue by hatran0884** [joBr99/nspanel-lovelace-ui#132]
Hi

my AC has a heating mode, but when it shows on the thermostat page, it is at the last position in the line of modes, while it should be at the first position. moreover, it is not localized as Làm Ấm (Vietnamese), but still be "heating". pls see some photos below for your illustration
one more issue, i found the button "press" is not localized either, so it is intentional to be left as Press.  pls check. 
![JPEG image 7](https://user-images.githubusercontent.com/58875735/162583155-82842d0f-d906-43d0-be48-2d95bfcd5ce0.jpeg)
![JPEG image 5](https://user-images.githubusercontent.com/58875735/162583161-0f52026c-f2df-4b93-b8a9-e7ac9afdd416.jpeg)
![JPEG image 6](https://user-images.githubusercontent.com/58875735/162583162-57c6613c-ce8f-43fb-be62-e54dfeacc017.jpeg)

**Comment by joBr99** [comment]
Hey, 
the translations are generated from the offical homeassistant frontend translations. (Is it translated in the webinterface o.O?)

https://github.com/home-assistant/frontend/blob/dev/translations/frontend/vi.json

The correct way to fix this would be a pull request to the HA frontend repo.

See https://github.com/home-assistant/frontend/blob/dev/translations/frontend/en.json, it contains string for heating aswell as for press.

The order of the icons should be in the order they are coming from homeassiant API / states, not sure if there is addional sorting somewhere on the frontend in HA. On my climate items the order is the same on the api as on the gui. Please check order of your havc_modes in the dev tools.

```
hvac_modes:
  - auto
  - heat
  - 'off'
```

**Comment by hatran0884** [comment]
yes, you are right about the order of modes in HA, i changed the order in HA, now the NSPanel shows a correct order. thanks

**Comment by joBr99** [comment]
o.O How do you change the order in ha?, wasn't aware that this is possible

**Comment by hatran0884** [comment]
actually, i am using a Tuya Tasmota-reflashed IR device that can control my AC in 2 ways using MQTT broker. so the modes, fan speeds all can be changed in YAML config file.

**Comment by joBr99** [comment]
What's with the localization, are they translated in Homeassistent's UI?

**Comment by hatran0884** [comment]
My home assistant is still in English, it does not matter if NSPanel shows Vietnamese or English. so i am okay that minor issue.

**Comment by joBr99** [comment]
Would be interesting what's showing in HA if you change the language there, my guess is that you are seeing the same baviour there.

**Comment by hatran0884** [comment]
yes, i think so. i could try to change the language and let you know the outcome.

**Comment by joBr99** [comment]
Looking into HA Documentation I guess the correct way to add this is to contribute it on their Lokalise [frontend translation team](https://lokalise.com/signup/3420425759f6d6d241f598.13594006/all/)

https://developers.home-assistant.io/docs/translations/

I didn't try waht happens after signup, but keep me posted if you are doing something on this.
