### ISSUE TITLE
Info in IObroker eingefügt

### ISSUE THREAD

**Issue by MacSchlack** [joBr99/nspanel-lovelace-ui#142]
Hallo,

ich habe die Infoanzeige in das  Iobroker script eingefügt.

An sich habe ich nur die Zeilen vom case "thermostat": kopiert und leicht angepasst. 

Hiermit habe ich mir einen Müllkalender mit den verbleibenden Tage realisieren können.

![IMG_20220413_072448](https://user-images.githubusercontent.com/98868655/163121763-1f45b99c-8aed-4435-84bb-09f42093ed55.JPG)

Auch habe ich in einem  ScreensaverEntity eine Anzeige welche Mülltonne als nächstes ansteht.
Leider reicht dort nicht der Platz um Gelbe Tonne auszuschreiben.  Kann man die Symbole im Screensaver umfärben, so dass ,am die Überschrift Müll und das Symbol dementsprechend in der passenden Farbe umfärbt?

const Yellow: RGB = { red: 253, green: 216, blue: 53 };
const Green: RGB = { red: 96, green: 176, blue: 62 }
const Braun: RGB = { red: 139, green: 69, blue: 69 }
const Grau: RGB = { red: 69, green: 69, blue: 69 }

var Müll: PageEntities =
{
    "type": "cardEntities",
    "heading": "Müllkalender",
    "useColor": true,
    "items": [
        <PageItem>{ id: "alias.0.WzNsPanel.Müll.Bio_Tonne"      ,icon: "trash-can",onColor: Braun},
        <PageItem>{ id: "alias.0.WzNsPanel.Müll.Graue_Tonne"    ,icon: "trash-can",onColor: Grau},
        <PageItem>{ id: "alias.0.WzNsPanel.Müll.Grüne_Tonne"    ,icon: "trash-can",onColor: Green},
        <PageItem>{ id: "alias.0.WzNsPanel.Müll.Gelbe_Tonne"    ,icon: "trash-can",onColor: Yellow}
    ]
};

            case "info":
                type = "text";
                iconId = pageItem.icon !== undefined ? Icons.GetIcon(pageItem.icon) :  Icons.GetIcon("information-outline");
                let unit_info = "";
                var optVal = "0"
                
                if (existsState(pageItem.id + ".ACTUAL")) {
                    optVal = getState(pageItem.id + ".ACTUAL").val;
                    unit_info = GetUnitOfMeasurement(pageItem.id + ".ACTUAL");
              
                }
                iconColor = GetIconColor(pageItem, parseInt(optVal), useColors);

                return "~" + type + "~" + pageItem.id + "~" + iconId + "~" + iconColor + "~" + name + "~" + optVal + " " + unit_info;

**Comment by joBr99** [comment]
aktuell nicht, nen feature request dafür gibt es schon #99

**Comment by joBr99** [comment]
die aktuelle dev firmware hat jetzt einen command, um die farbe von den elementen auf dem screensaver zu ändern

`color~background~time~timeAMPM~date~tMainIcon~tMainText~tForecast1~tForecast2~tForecast3~tForecast4~tF1Icon~tF2Icon~tF3Icon~tF4Icon~tForecast1Val~tForecast2Val~tForecast3Val~tForecast4Val~bar~tMainIconAlt~tMainTextAlt~tMRIcon~tMR`

**Comment by joBr99** [comment]
![image](https://user-images.githubusercontent.com/29555657/163268824-65c27286-6fbb-4e5d-8fab-84388d7e01e8.png)

**Comment by britzelpuf** [comment]
Moin moin MacSchlack, erstmal sehr coole Idee mit den Tonnen. Der Mehrwert ist da nicht von der Hand zu weisen.
Allerdings bin ein wenig irritiert, weil eigentlich war der "info" Typ schon eingebaut. Funktionierte der nicht?

Zu den Farben würde ich sagen schlichte Eleganz,  aber das ist mein persönlicher Geschmack und joBr99 war sowieso schon schneller und hat das mal eben eingebaut. Da müsste man jetzt überlegen, ob man die Farben jedes Mal setzt oder nur auf Bedarf. Vorstellen könnte ich mir, dass man die Farben in das Screensaver Config Element mit integriert, dann die Farben einmalig setzt und nur bei Änderung diese wieder setzt, wobei man dann wieder überlegen muss wodurch eine Farbänderung ausgelöst wird.

**Comment by joBr99** [comment]
for clarification, grunsätzlich musst du die Farben, immer mitschicken, wenn sich die Seite öffnet, also zu dem Zeitpunkt wo du auch das weatherUpdate sendest, die Farben sind nicht persistent wie z.B. das Datum

**Comment by MacSchlack** [comment]
@britzelpuf 
Hallo britzelpuf,

vielen Dank.

Ja du hast recht. Die Info kommt auch an wenn ich meine Änderung ausblende.  
Ich bin total verblüfft. Ich verstehe nicht, wie bei einer Info aus dem case "Info": der Return ausgegeben wird.
https://github.com/joBr99/nspanel-lovelace-ui/blob/4cd5fa9d6d386d361454aa94a67f7422a1b939e2/ioBroker/NsPanelTs.ts#L342

Blende ich das case "info" aus, so funktioniert es nicht.

Bis heute dachte ich echt ich verstehe ein Bisschen etwas vom Programmieren aber ich habe mich wohl echt getäuscht

**Comment by britzelpuf** [comment]
Das ist einfach erklärt. Wenn mehrere case untereinander stehen sind die mit Oder verknüpft.
Somit wird wenn info, value.temperature oder thermostat zutrifft die Anweisung bis zum return oder break ausgeführt.

**Comment by MacSchlack** [comment]
Danke dir, das mit den break hatte ich nicht so ganz auf dem schirm.
Was sind deine nächsten Pläne?
Ich werde bei mir mal versuchen die ganzen Funktionen zu exportieren, dass man es einfach updaten kann ohne die Config ändern zu müssen.
Auch überlege ich, ob ich die ScreensaverEntity alle paar Sekunden austausche.
Erst Wetter, dann Stromverbrauch, Müllkalender, ...

Auch hatte ich im type PageItem = {  unit: (string | undefined)} eingefügt, um bei meinem Müllkalender die "days" manuell zu Tagen ändern zu können.
Leider musste ich ein Backup laden und diese Änderung ist weg.

Ich bin leider im github nicht so ganz fit.
soll ich sinnvolle Anpassungen an dich schicken oder in Github hochladen?

**Comment by joBr99** [comment]
GitHub workflow ist grundsätzlich
1. Branch erzeugen
2. Änderungen machen
3. Pull Request

Unter dem pull request kann man das dann auch noch weiter diskutieren und wenn du weitere Änderungen an dem branch machst landen die auch im PR

Und @britzelpuf hat dann den Hut auf fürs mergen etc. 😅

**Comment by MacSchlack** [comment]
Danke joBr99,
kompliziert 😅
Ich werde es mal versuchen.

**Comment by britzelpuf** [comment]
> Danke dir, das mit den break hatte ich nicht so ganz auf dem schirm. Was sind deine nächsten Pläne? Ich werde bei mir mal versuchen die ganzen Funktionen zu exportieren, dass man es einfach updaten kann ohne die Config ändern zu müssen. Auch überlege ich, ob ich die ScreensaverEntity alle paar Sekunden austausche. Erst Wetter, dann Stromverbrauch, Müllkalender, ...
> 
> Auch hatte ich im type PageItem = { unit: (string | undefined)} eingefügt, um bei meinem Müllkalender die "days" manuell zu Tagen ändern zu können. Leider musste ich ein Backup laden und diese Änderung ist weg.
> 
> Ich bin leider im github nicht so ganz fit. soll ich sinnvolle Anpassungen an dich schicken oder in Github hochladen?

Im Moment plane ich, dass ganze mal in einen Adapter fallen zu lassen, da ich etwas unglücklich damit bin, dass alle Dinge in einem Skript sind und somit die Wartung immer schwerer wird. Der große Nachteil ist auch, dass alle im global hinterlegten Skripte an alle anderen Skripte angehängt werden. Somit ist der Icon Selector auch in jedem anderen Skript verfügbar, aber sicherlich nicht notwendig. Vor allem aber kann man dann eine Gui für die Config bauen.

Ansonsten hoffe ich, dass ich das Problem mit dem Media Alias im ioBroker mal gelöst bekomme, dann kann man da auch die Page problemlos anbinden. Da wurde ja auch schon fleißig erweitert und das kann man dafür sicher wiederverwenden.

Und natürlich das bunte Wetterupdate ;-)

Aber da meine Zeit sehr eingeschränkt ist, kann sich das alles noch ein bisschen ziehen.
