### ISSUE TITLE
correct AdcParam

### ISSUE THREAD

**Issue by bkbartk** [joBr99/nspanel-lovelace-ui#144]
Hello,

this is more like a Tasmota question then it is for nspanel-lovelace-ui but has anyone actually figgered out the correct values for "AdcParam1" The value in the manual is copied from blakadder. But In my case it's off,
It says it's 22 degrees C, but it's not that warm in here.
My thermostat says 17.

When I try something like this
`AdcParam1 2,13650,10000,3350`
I'm getting close
but so does
`AdcParam1 2,13150,10000,2950`
And then I'm only playing around with 2 of the 3 parameters.

I think all should be correct because air pressure end humidity and stuff.
The manual is clear about what the values mean
https://tasmota.github.io/docs/ADC/#timers
but applying them is a lot harder then reading the manual.

**Comment by britzelpuf** [comment]
Hi @bkbartk,

I use this values 2,14800,10000,3950.

The biggest problem is the heat generation by the display itself. If it is set to full brightness the sensor reading will be 2-4°C higher or even more. I usally use a dim value of 8. There is a mod which exposes the sensor completly but they don't look very good, as the sensor is fully visible. I bend the sensor as much as possible to the outside. It is not visible but I think it is more exposed to the outer air.  

Best Regards 

Britzelpuf

**Comment by bkbartk** [comment]
thanks for the replay,
I tried your value but then the temperature is to low with 1 degree C.
my brightness defers from 1 to 4 depending on the time. If there is a lot of daylight the display should be brighter else I cannot read it.

If what you are saying is true, the params should depend on dimlevel and/or ESP32 temperature which makes one and an other a lot harder.
As far as I understand people don't have this issue with the default sonoff firmware, I never used this.
but that firmware only has 2 dimlevels.
I can be that they made some kind of calculation for this, or everyone flashed the device before they noticed the issue.

**Comment by joBr99** [comment]
Actually I've seen comments on Kickstarter about a feature request to set a calibration offset on the stock fw. But I've no idea if they also have this problem with the heat from the display.

**Comment by joBr99** [comment]
I've bought some Zigbee Temperature Sensors to check the temperature of my NsPanels

I'm using `2,14100,10000,3950` on the nspanel on my Kitchen (looking at the graph, this one seems to be one degree off)

And I'm using `2,15300,10000,3950` on the nspanel in my bathroom.

![image](https://user-images.githubusercontent.com/29555657/163538695-82f3427a-ccdc-4bdf-889a-14315fa6c5a0.png)

**Comment by bkbartk** [comment]
who is to tell those zigbee sensors are accurate ;)
but this is interesting, I noticed that everyone is using 10000 for " NTC Resistance in Ohms" I didn't touch it during my tests and I actually don't know why, but it seems like no one does.

I was thinking about adding an additional sensor and whenever that one changes a value, check wich list of AdcParams come to the same result. But this requires development and at the moment I don't have time to dive in to this.

when I use "2,14100,10000,3950" it seems to be 0.5 degrees off, but the other way as in your screenshot.
Also I'm wondering if the values might work within the tempwindow they are set, and whenever the temp increases/decreases a lot the difference will be higher.

**Comment by joBr99** [comment]
yeah, sure they don't have to be accurate, but I trust them more than the nspanel temp sensor

the tempwindow thing was the main reason why i wanted to plot that

**Comment by radioelf** [comment]
HI.

The biggest problem is the heat generation by the display itself, as comment britzelpu, i have placed a DS18B20 in GPIO02 and you can see the result.
![mod_DS18B20](https://user-images.githubusercontent.com/6136608/166862207-05b7374a-dafe-41f3-b478-c839f7cd1d3f.png)
![error_temp](https://user-images.githubusercontent.com/6136608/166862219-6f3fd2de-e404-4907-be3f-b92ab75fd118.jpg)

**Comment by joBr99** [comment]
![image](https://user-images.githubusercontent.com/29555657/169665790-d40a9922-9d3a-4fb7-b213-00a890053314.png)

SONOFF TECH Store on AliExpress 😂

**Comment by feedbagg** [comment]
same "issue" here.

I've unsoldered the NTC and measured the Resistance parallel with a Fluke Multimeter and a Temperature sensor at different locations.
at -10,6°C it was 61,30kOhm
25,9°C = 9,93kOhm  (approx 25,0°=9,99kOhm, so it is a "10k NTC")
56,0°C = 2,56kOhm

i've researched to get the correct "NTC Beta Coefficient" and got dome values between 4200 and 4000
The Resistor for "NTC Voltage bridge resistor in Ohms" i've measured on the PCB was about 10,1kOhm.

so the real "Measured" values have to be:
AdcParam1 2,10100,9990,4100
but it was not accurate enough, so i've changed them (for Compensation reasons) to:

`AdcParam1 2,12000,9900,3950`
those Parameters get me a PERFECT sync on the deep-Freezer with -11,5°C (NSPanel and parallel the Fluke) after a half an hour.
and currently at 27,0°C at the Fluke the NSPanel measures 29,3°C.

hope it helps someone :)
greets FeedBagg

**Comment by dameq1** [comment]
@feedbagg If this would be only a static error then it wasn't be a problem. But the error value changes when you change the screen brightness. I'm using my nspanel in the bedroom and the screen is off at night. My error compared to other sensor is 1°C at night and 1.9°C during day. This can't be compensated by adcparam :(

**Comment by soyxan** [comment]
Hi,
I can confirm what you guys commented: With the screen brightness low the temperature is quite accurate (compared with a external calibrated thermometer), so I am planning to make a Berry script that tweaks the temperature value when the screen brightness is high. Do you now how to get the screen brightness level from Berry?

BTW, my AdcParam values are: adcparam1 2,15000,10000,3950,0

Thanks!

**Comment by nikos445** [comment]
I use AdcParam1 2,11900,9999,3950

**Comment by rossi75** [comment]
only as a hint, has anyone noticed the two unpopulated pads in this picture at the top?

![Image](https://github.com/user-attachments/assets/41681007-6d6c-4537-add2-83a8a7fc6556)
https://blakadder.com/assets/images/nspanel/touchfront.jpg

could they have been prepared for having a humidity or light sensor.... ? Okay, there is no outlet at the housing, but that's sth that could have been done....
