### ISSUE TITLE
[Feature Request] Display Percentage of cover slider on the cover page

### ISSUE THREAD

**Issue by hatran0884** [joBr99/nspanel-lovelace-ui#145]
Hi 

Can you add an indicator of percentage below the cover slider in the cover page for ease of choosing how many percent of cover opening ? 

![B6B8A972-36AA-4530-A57F-44FF014F4041](https://user-images.githubusercontent.com/58875735/163369721-b5135d2c-5591-422f-9d3b-c051ca2a7c49.jpeg)

**Comment by kroon040** [comment]
or maybe as a second entity row? 
![shutter](https://user-images.githubusercontent.com/40452265/166122762-6843271b-e4d0-45ae-aceb-d38a9e26b2df.png)

**Comment by joBr99** [comment]
added in 2.8.2

**Comment by hatran0884** [comment]
Just tested and works just fine. Thank you
