### ISSUE TITLE
[Bug] config parameters are overridden by latest configured panel

### ISSUE THREAD

**Issue by hatran0884** [joBr99/nspanel-lovelace-ui#150]
Hi 

after updating to 2.7.2 on both 02 nspanels, both 2 displays show same content. The content will be of the one that is defined last in app.yaml.

Is there something wrong i did? I updated both display firmware and berry driver. Also restart appdaemon.

**Comment by joBr99** [comment]
hey, can you update to 2.7.3 and try again?

there was a bug in my config class, strange that this didn't cause issues ealier

**Comment by hatran0884** [comment]
Yes, i confirm 2.7.3 fixed my issue. Thanks
