### ISSUE TITLE
[Feature Request] Show notifications on screensaver

### ISSUE THREAD

**Issue by TBSniller** [joBr99/nspanel-lovelace-ui#152]
Hey there, 
of course firstly thank you for this awesome modification for our panels! It's working great and is very simple to maintain.

I don't know how easy this woud be, but I think it would be a pretty cool enhancement to display notifications on the screensaver. I could imagin that if a notification is displayed, the forecast is replaced by this. Touching the display, which causes normal screensaver disable behaviour, would simply discard the notification, so the forecast is displayed, when it goes back to the screensaver again. In addition a notification counter would be pretty nice to have, if there were 2+ notification since the last discard(=screensaver touch).
A much much more enhancement (maybe as notification 2.0) would be to have an extra notification card, which for example displays the last x notifications.

I think the simple dirty way to get the first one working, would be to just have a text helper item, which stores the notification string. After clicking the screensaver this simply would be set to "", so the forecast is displayed when the string is "".
Better way of doing this would be to have a notify integration (https://www.home-assistant.io/integrations/notify/), so we can use the HA services for notifications.

Hopefully my english is clear enough to understand what I mean. Otherwise I can explain it in german again. 

Thank you very much!

**Comment by joBr99** [comment]
Hey, are you aware of the existing notification page? (Not on screensaver)

**Comment by TBSniller** [comment]
No I'm not. Just checked the readme again, isn't it mentioned?

**Comment by joBr99** [comment]
Not it isn't. It's used internally for the update notifications. Check the Readme in the HMI Folder and the nodered folder, there is an example.

To sum up you've to send this via mqtt to the customsend topic:

`pageType~popupNotify`
`entityUpdateDetail~*internalName*~*tHeading*~*tHeadingColor*~*b1*~*tB1Color*~*b2*~*tB2Color*~*tText*~*tTextColor*~*sleepTimeout`

**Comment by joBr99** [comment]
If you want to use the notify integration with it, you can probably create an mqtt config for it.
https://www.home-assistant.io/examples/notify.mqtt/

**Comment by TBSniller** [comment]
Just checked this out and yeah this already is a really nice solution I can work with. This pretty much works in a way I have imagined on and its looking nice. Thanks! :)

Do you regardless plan to integrate this much more?

**Comment by joBr99** [comment]
Well, you cannot do a a vertikal scrollable list or so with nextion. 
And nextion isn't able to do any line wrapping. (send a neotifcation with a longer text and you will see it)

**Comment by TBSniller** [comment]
Are you sure about this line wrapping thing? Just tested it out and I think it does. 
![IMG_20220417_195848](https://user-images.githubusercontent.com/51515147/163726657-b3084fce-ca73-4784-9900-28720c06b439.jpg)

**Comment by joBr99** [comment]
yes, but it cannot handle words

try this:

entityUpdateDetail~*Name*~*Head*~65535~*teext*~65535~*textb2*~65535~Franz jagt im komplett verwahrlosten Taxi quer durch Bayern Franz jagt im komplett verwahrlosten Taxi quer durch Bayern~65535~10

**Comment by TBSniller** [comment]
Ahhhhh okay I see..
I think a workaround would be to have a upper and a lower textfield with a fixed max letter length - after letter x the rest would be replaced with for example ...
I also think that notifications wouldn't be this long - for example my needings are washing maschine finished, or things like that.

**Comment by joBr99** [comment]
run this in command in tasmota console to flash the display to current dev version

`FlashNextion http://nspanel.pky.eu/lui.tft`

and the try this command

`CustomSend notify~TestHeading~TestText`

a touch event or an empty message will clear the notification

`CustomSend notify~~`

**Comment by TBSniller** [comment]
Wow man nice, thank you! It looks really nice! <3 Thank you for your fast responses! :)

**Comment by TBSniller** [comment]
Just adding my configuration. Maybe its useful for someone in the future or use in docs.

Script with some notification sound: 
`alias: Notification to NSPanel
sequence:
  - service: mqtt.publish
    data:
      topic: cmnd/{{ target }}/CustomSend
      payload: notify~{{ heading }}~{{ message }}
  - service: mqtt.publish
    data:
      topic: cmnd/{{ target }}/Buzzer
      payload: 2,2,2
mode: queued
icon: mdi:message-badge
max: 2`

Deleting notification:
`alias: Clear notification from NSPanel
sequence:
  - service: mqtt.publish
    data:
      topic: cmnd/{{ target }}/CustomSend
      payload: notify~~
mode: single
icon: mdi:message-badge-outline`

Use service call to generate message and beeper:
`service: script.notification_to_nspanel
    data:
      target: my-panel-01
      heading: Testheading
      message: This is a testmessage`

Use service call to clear message:
`service: script.clear_notification_from_nspanel
    data:
      target: my-panel-01`

**Comment by joBr99** [comment]
If you want to shorten this a bit, it should be possible to combine multiple tasmota commands like this:
```
      topic: cmnd/{{ target }}/Backlog
      payload: CustomSend notify~{{ heading }}~{{ message }}; Buzzer 2,2,2
 ```

**Comment by TBSniller** [comment]
Oh cool, nice to know thanks :)
