### ISSUE TITLE
Cover : IKEA

### ISSUE THREAD

**Issue by MonSeb81** [joBr99/nspanel-lovelace-ui#156]
Hi,
Thanks for your amazing work.
I have an issue with the cover card. I am using Ikea cover and it appears nothing is happening when pressing the button "Down".
The UP and STOP button send an MQTT message but nothing happen anyway.
Same the slider doesn't run.
Do you have an idea on how to solve the issue?

thanks in advance

**Comment by joBr99** [comment]
Hey, 
just checked with my IKEA Frytur (conntected via zigbee2mqtt), they are working fine.

Please check the AppDaemon Log for errors while pressing the buttons.

**Comment by joBr99** [comment]
also check your entity name, there's currently a limit of 50 chars for it (maybe also 70 have to check)

**Comment by MonSeb81** [comment]
thanks, I will check it
I created a group and it works fine.
So I think you the entity name is the issue
I have another question.
When i use light entity and play with the brightness or color the NsPanel freeze and i am not able to go back to the Grid card.
Have you experience the issue?
Have a nice evening

**Comment by joBr99** [comment]
Have to see the AppDeamon log while it's doing that.
(Also check if the entity name is below 50 chars on your light)

**Comment by joBr99** [comment]
@MonSeb81 How long is the ID of your cover? 
Thinking about if it's worth it building complex workarounds in the appdaemon script or just increasing the text field in nextion.

**Comment by MonSeb81** [comment]
cover.ikea_of_sweden_fyrtur_block_out_roller_blind_c43fbafe_window_covering

I know it is long, I have the bad habit to keep the default ID. But know I can see how painful it is.

**Comment by MonSeb81** [comment]
I double check and change the entity ID of the light but the screen still freeze when playing with the color brightness. 
it is funny because all the rest seems to run in a background

**Comment by joBr99** [comment]
check the appdaemon log, there has to be an error in the log

increaseing the fields to 80 shouldn't be a big issue, I reclaimed a log of memory with v2.6, so this should be fine

Available Memory: 3584
Page:cardEntities Memory Occupied:232+2208=2440
Page:cardEntities Memory Occupied:296+2256=2552

**Comment by MonSeb81** [comment]
Thanks for all
I will have a look tomorrow

**Comment by joBr99** [comment]
which version are you using?

if you are using the eu version flash the current dev version, increased the entn vars to 80 chars:

`FlashNextion http://nspanel.pky.eu/lui.tft`

**Comment by MonSeb81** [comment]
I am flashing the Nspanel right now 
I am using the v2.7.3 of your automation

**Comment by joBr99** [comment]
yeah, that's fine there shouldn't be any breaking changes in the serial protocol between the current dev firmware and the current release app
