### ISSUE TITLE
[Help] Appdaeom initialize_error

### ISSUE THREAD

**Issue by maginator** [joBr99/nspanel-lovelace-ui#157]
Hi,
```
i got the Following Error when AppDaemon is starting:
2022-04-18 23:37:40.289484 WARNING NSPanel1: ------------------------------------------------------------
2022-04-18 23:37:40.290122 WARNING NSPanel1: Unexpected error running initialize() for NSPanel1
2022-04-18 23:37:40.290468 WARNING NSPanel1: ------------------------------------------------------------
2022-04-18 23:37:40.292184 WARNING NSPanel1: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/app_management.py", line 165, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.9/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 26, in initialize
    mqtt_api.mqtt_publish(topic_send.replace("CustomSend", "GetDriverVersion"), "x")
AttributeError: 'NoneType' object has no attribute 'mqtt_publish'
2022-04-18 23:37:40.292576 WARNING NSPanel1: ------------------------------------------------------------
2022-04-18 23:37:40.293967 INFO AppDaemon: App initialization complete
```
**My AppDaemon.yaml:**
```
---
secrets: /config/secrets.yaml
appdaemon:
  latitude: 52.379189
  longitude: 4.899431
  elevation: 2
  time_zone: Europe/Amsterdam
  plugins:
    HASS:
      type: hass
  MQTT:
    type: mqtt
    namespace: mqtt
    client_host: "broker.home.test"
    client_port: 1883
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
```
And my **App.yaml:**

---
NSPanel1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_your_mqtt_topic/RESULT"
    panelSendTopic: "cmnd/tasmota_your_mqtt_topic/CustomSend"
    updateMode: "auto-notify"
    sleepTimeout: 20
    #sleepBrightness: 10
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "22:00:00"
        value: 0
    locale: "de_DE" # used for translations in translations.py and for localized date if babel python package is installed
    screensaver:
      entity: weather.home
    cards:
      - type: cardGrid
        entities:
          - entity: light.magnurgb
          - entity: switch.strom1
          - entity: delete # delete at the end is optional
        title: Exmaple Gird
      - type: cardThermo
        entity: climate.hmip_etrv_2_000a1d8991e794
      - type: cardMedia
        entity: media_player.schlafzimmer

Maybe im just stupid but i dont know what im doing wrong
Can you hlep me? :)

**Comment by joBr99** [comment]
looks like your identation in the appdaemon.yaml is wrong

should look like this:

```yaml
---
secrets: /config/secrets.yaml
appdaemon:
  latitude: 52.0
  longitude: 4.0
  elevation: 2
  time_zone: Europe/Berlin
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      client_host: 192.168.75.30
      client_port: 1883
      client_user: "mqttuser"
      client_password: "mqttpassword"
      client_topics: NONE
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
```


https://raw.githubusercontent.com/joBr99/nspanel-lovelace-ui/main/appdaemon/appdaemon.yaml
https://github.com/joBr99/nspanel-lovelace-ui/blob/main/appdaemon/appdaemon.yaml

**Comment by joBr99** [comment]
Hey @maginator is your issue fixed?

**Comment by maginator** [comment]
Oh yeah it was just the wrong MQTT Configuration as you say.

Sry i forgot to close the issue :)

Thank for your Help and verry Nice Project :)
