### ISSUE TITLE
[Feature Request] Screen/mode thermostat  working without communication

### ISSUE THREAD

**Issue by copilador** [joBr99/nspanel-lovelace-ui#161]
It would be possible to use the thermostat mode if the network connection fails or does not communicate with Appdaemon. Thanks

**Comment by joBr99** [comment]
you should be able to configure tasmota to do so, but I've never tried

https://tasmota.github.io/docs/Thermostat/

**Comment by bkbartk** [comment]
I actually don't think you can,
you might can bypass the appdeamon, but if there is no network communication at all, there is no way to communicate with the actual thermostat. 
you only have 2 physical switches you might can use to power on/off the heater or some other device, but a real communication like a thermostat does

**Comment by joBr99** [comment]
the ui control's definitly won't work, but if tasmota is handling the thermostat stuff it will still function without connection to HA, alternatively you can use the physical buttons for power on/off like @bkbartk said

**Comment by copilador** [comment]
Hi, Thanks
