### ISSUE TITLE
CustomSend not working on panel

### ISSUE THREAD

**Issue by andriuskr** [joBr99/nspanel-lovelace-ui#168]
Hello,

Trying to set screen brigthness on nspanel, but nothing changes. MQTT command is send, i can see it in MQTT explorer, and in console of nspanel it reports as done. What i am doing wrong ?
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/13429780/164958954-e6e48956-fe85-40c0-a4e5-d0ff6644e127.png">

**Comment by joBr99** [comment]
What are u trying to archive? 
You should configure the brigness in apps.yaml instead of sending this mqtt message. You can configure it to a static number, a schedule (with sun support) and also to follow an input_number if you want to control it from HA.

**Comment by andriuskr** [comment]
I am trying to automate screen sleep at night or when no one at home. And to wake the screen by external motion sensor in the room. 
As per this issue, i found that this can be controlled by mqtt https://github.com/joBr99/nspanel-lovelace-ui/issues/78

**Comment by andriuskr** [comment]
I even tried to add      brightnessScreensaverTracking: device_tracker.andriaus_iphone_pro to config, but screen of panel is not turning off when i set the trecker to not_home.  I am on dev version (i think)

`---
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_nspanel1/RESULT"
    panelSendTopic: "cmnd/tasmota_nspanel1/CustomSend"
    updateMode: "auto-notify"
    sleepTimeout: 20
    #sleepBrightness: 10
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 0
    brightnessScreensaverTracking: device_tracker.andriaus_iphone_pro
    locale: "en_US" # used for translations in translations.py and for localized date if babel python package is installed
    screensaver:
      entity: weather.smarter_home
    cards:`

**Comment by joBr99** [comment]
The easiest way to archive this is probably to configure sleepBrightness and sleepTracking (sleepTracking will force the dimvalue to 0 in case the state of the configured entities changes to not_home) [in the current dev version also if the state changes to off]

![image](https://user-images.githubusercontent.com/29555657/164964806-103bfdfa-39f3-4de8-9b1d-519ba0d36f98.png)

for more complex automations like following a lux sensor value you can configure it to an input_number (from 0-100) and change the input number from your automations

**Comment by joBr99** [comment]
brightnessScreensaverTracking does no longer exist and has been replaced with sleepTracking, take a look at tables for possible config keys

**Comment by andriuskr** [comment]
Thanks! With sleepTracking: device_tracker.andriaus_iphone_pro it is workig.

Maybe you know where i can find the example on complex automation with input_number ?

And what about sending messages to panel  Is it possible ?

**Comment by joBr99** [comment]
you can configure it to an input_number

`sleepBrightness: input_number.brightness_nspanel`

defined in your home_assistant config

```
input_number:
  brightness_nspanel:
    initial: 20
    min: 0
    max: 100
```

this allows you to do any custom automations on the brightness, just by changeing the input_number in you automation

sending messages to the panel is possible, but doesn't make a lot of sense for this use-case, because appdaemon will override your messages, take a look at the nodered folder for an example on sending notifications to the panel

**Comment by andriuskr** [comment]
Thanks, screen brightness control is working
