### ISSUE TITLE
Unable to Flash Firmware to Nextion Screen

### ISSUE THREAD

**Issue by woody166** [joBr99/nspanel-lovelace-ui#169]
Following instruction as per your Github page, when I get to the point of flashing the firmware to the Nextion screen either using local (Home Assistant) web server or your link, I receive the following error:

BRY: Exception> 'syntax_error' - input:1: 'FlashNextion' undeclared (first use in this function)

I have tried from both Mac & Windows systems and Chrome browser (not that I think this is where the issue lays).

Device flashed with latest tasmota32-nspanel.bin (showing 11.1.0.1 once flashed) file and Berry driver (via your link)

Appreciate any assistance

**Comment by joBr99** [comment]
Hey, did you install/update the autoexec.be on your panel? 
You can check for loading errors in the berry console (type `load('autoexec.be')` to force loading manually)

In case it loads successfully and still doesn't find the FlashNextion Command, try to delete the "autoexec.be" file

**Comment by woody166** [comment]
Hiya, yeah installed the latest autoexec.be file as well, in the device console it shows the it was loaded successfully and running the above command returns 'true'

forgot to mention that I had ESPHome previously flashed on the device, if that has anything to do with it.

**Comment by joBr99** [comment]
Sorry, try to remove the autoexec.bec file not autoexec.be

**Comment by woody166** [comment]
Hiya, yep tried that, no luck

**Comment by joBr99** [comment]
Even after a restart of tasmota? The autoexec.be from this repo contains the FlashNextion Command, so as long it's loading successfully you should have the flashing command

**Comment by woody166** [comment]
Hiya, yeah, even after restarting (switch off/on)

Any other commands I can try?

**Comment by joBr99** [comment]
Ah wait

BRY: Exception> 'syntax_error' - input:1: 'FlashNextion' undeclared (first use in this function)

This is from the berry console right? You have to run that command from the tasmota command console

**Comment by woody166** [comment]
Bingo, Doh! it had to be something simple, I thought I'd already tried running the command from there but would seem to not be the case.

It's going through the update now, thank you very much for your quick response and superb assistance.

**Comment by joBr99** [comment]
np, lucky you that I'm in San Francisco this week, wouldn't be that fast in Germany, it's in the middle of the night there ;)

**Comment by woody166** [comment]
it is indeed lucky, although I'm in the UK so not too far behind your TZ in Germany :-) many thanks again 👍

**Comment by joBr99** [comment]
lol, good night, also pretty late there
