### ISSUE TITLE
[Feature Request] add fan speed in thermostat page

### ISSUE THREAD

**Issue by hatran0884** [joBr99/nspanel-lovelace-ui#173]
Hi 
is it possible to have some space for a selection of fan speed in the thermostat page ? i have 4 fan speeds to be selected. everytime i want to change the fan speed, i still have to use phone to do. 
moreover, it would be better if the distance between icons (cool, dry, hot) is a bit further so i will not mispress the mode i desire.
again thank you for a fantastic work.

**Comment by joBr99** [comment]
Can you send a screenshot of the widget with the fan speed selection

**Comment by hatran0884** [comment]
Here you go bro!
![78AAD143-F14E-4A9C-98D9-4271612AD7A0](https://user-images.githubusercontent.com/58875735/166086705-deb3a1d1-1181-4f3c-8c3f-9f5254abd5fe.png)
![BB129C04-FCA0-4796-82D3-40BBB0682A3B](https://user-images.githubusercontent.com/58875735/166086707-182a7f8a-da75-4a7f-9ceb-00154d1ad580.png)

**Comment by joBr99** [comment]
Hmm, have to see, cannot do drop-downs on nextion

**Comment by antibill51** [comment]
Hi, 
If it's possible, can you also add preset mode? 

```
preset_modes:
  - none
  - away
  - eco
  - boost
  - comfort
  - sleep
```

At least Eco and Comfort?

**Comment by hatran0884** [comment]
Just a kind reminder, is this feature still in your plan?

**Comment by hatran0884** [comment]
Another gentle reminder if this feature is still in your to-do list?

**Comment by joBr99** [comment]
There is no space to do this on the climate/thermostat page. There is a new fan popup page, that might be used in future for this, but the fan page does not yet support to select any modes.

**Comment by hatran0884** [comment]
The problem is the fan speed is part of the air conditioner, i am not sure if i can separate it as an independent fan to be used as a fan entity?

**Comment by nelim** [comment]
Just an idea about preset_mode, when there is supported_modes option now, there is some space for preset_modes left
So everyone can choose what to appear below the thermostat.
I mean, if you remove all or add only 2(some) supported modes, there will be space for some preset_modes or fan speeds under thermostat.

**Comment by joBr99** [comment]
![image](https://user-images.githubusercontent.com/29555657/197404966-bf10ae78-87b1-4eaa-acd0-5b3a7da5396a.png)

little preview

**Comment by joBr99** [comment]
![image](https://user-images.githubusercontent.com/29555657/197416271-bb5a5d9a-2f4d-4c73-9f4e-43432b7d433f.png)

![image](https://user-images.githubusercontent.com/29555657/197416280-610ce810-aaf4-412f-a7b7-ff993d511d8b.png)

![image](https://user-images.githubusercontent.com/29555657/197416462-77e1da38-8db2-410f-9204-86fa821404a3.png)

![image](https://user-images.githubusercontent.com/29555657/197416477-bff13a91-9848-4486-947f-6a9942d2318c.png)

![image](https://user-images.githubusercontent.com/29555657/197416515-4443b439-9217-407f-8e34-c5d486241496.png)


Has been implemented in latest dev version.

**Comment by pbvdven** [comment]
Question i updated to latest main version i but i dont get these option do i need some extra config?
on 2 A/C i only see swing mode but not options and one A/C shows fan mode without option. i would really like fan mode to work. thanks. 

      - type: cardThermo
        entity: climate.hal_ac
        title: Hal A/C
        key: clislaapkmracKey

![image](https://user-images.githubusercontent.com/39600990/203141363-11ab6486-5d75-4a6a-8619-7b5b2614ecd4.png)

![IMG_2104](https://user-images.githubusercontent.com/39600990/203141447-816ee832-8bc6-4687-9111-39c57e3a003d.jpg)
![IMG_2105](https://user-images.githubusercontent.com/39600990/203141452-0027d495-50d0-4f16-9723-8ca74ef699aa.jpg)

**Comment by joBr99** [comment]
please restart appdaemon and provide the appdaemon logs that are generated during opening that detail page

**Comment by pbvdven** [comment]
> please restart appdaemon and provide the appdaemon logs that are generated during opening that detail page

Here is the appdeamon log when opening the detail page.


`2022-11-22 14:46:49.981173 INFO nspanel-1: MQTT callback for: {'topic': 'tele/tasmota_7E0388/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,pageOpenDetail,popupThermo,climate.hal_ac"}'}
2022-11-22 14:46:49.983474 INFO nspanel-1: Received Message from Screen: event,pageOpenDetail,popupThermo,climate.hal_ac
2022-11-22 14:46:50.039686 INFO nspanel-1: Sending MQTT Message: entityUpdateDetail~climate.hal_ac~���~64512~Swingmodus~swing_modes~off~on?off~Ventilatormodus~fan_modes~high~auto?quiet?low?medium?high~`

**Comment by joBr99** [comment]
hal_ac shows up like this:

![image](https://user-images.githubusercontent.com/29555657/203331894-c5fb126e-6a02-40f5-bd80-c2057c38f5a5.png)

Are you sure that you are on the latest display firmware?

https://docs.nspanel.pky.eu/faq/#how-to-upgrade-from-a-release-to-the-current-development-version

**Comment by pbvdven** [comment]
i feel so stupid right now haha. sorry for wasting your time. thanks for helping

**Comment by blubbel42** [comment]
Hello there, sorry to drag this up. I'm using Shelly TRVs, these have preset_modes. I can't figure out if those are supported or not. And If they are, how to use them. I'm on latest dev, with appdaemon and firmware.
Any hint would be appreciated.
greetings, and thanks for the great work with this project!
