### ISSUE TITLE
[Feature Request] lock in the nspanel-ui

### ISSUE THREAD

**Issue by kroon040** [joBr99/nspanel-lovelace-ui#174]
Hi,

Is there also an option to add lock into the nspanel-ui

the lock and unlock option.

**Comment by joBr99** [comment]
You can activate a "double-tap" to exit the screensaver. How should a "lock" look like?

**Comment by kroon040** [comment]
Locked  (ontgrendelen = unlock)
![locekd](https://user-images.githubusercontent.com/40452265/166122290-feaba64c-c0d9-4358-9b4f-47172670aeb1.png)
Unlocked (vergrendelen = lock)
![unlocked](https://user-images.githubusercontent.com/40452265/166122292-54dd968b-fd93-4da6-9f3a-2f9b8b141a44.png)

**Comment by joBr99** [comment]
Ah ok, got you thought you mean locking the display itself

**Comment by joBr99** [comment]
@kroon040 can you send me a screenshot of the data/states of the lock from the dev tools of homeassistant

**Comment by kroon040** [comment]
![unlock1](https://user-images.githubusercontent.com/40452265/167080049-31d53092-8c2f-4cae-a7ac-58de4503891b.png)


![locked1](https://user-images.githubusercontent.com/40452265/167080112-f5aad956-d4d4-4ffa-9cbb-0daec2650d97.png)

**Comment by joBr99** [comment]
@kroon040 

Update your app in HACS to main and restart AppDaemon, locks should be implemented, you don't need to do the firmware update to test this feature

https://github.com/joBr99/nspanel-lovelace-ui#how-to-upgrade-from-a-release-to-the-current-development-version

**Comment by kroon040** [comment]
Hi,

I installed it manually. In HACS, I don't see the nspanel if I choose for intergrations and explorer &  downoad repositories. How should I add this one in HACS?

**Comment by joBr99** [comment]
I guess should missed the step where you have to enable appdameon in hacs

Click on Configuration on the left menu bar in Home Assistant Web UI
Select Devices & Services
Select Integrations
Find HACS and click on Configure
In the window that opens, make sure that Enable AppDaemon apps discovery & tracking is checked, or check it and click Submit

**Comment by kroon040** [comment]
Yes, that  missed.

I have removed and isntalled it form hacs the MAIN. I Added in the apps.yaml

          - entity: lock.schuurdeur

but it gives on the display !error , so not yet working

**Comment by joBr99** [comment]
did you restart appdaemon after downloading main?

also check if the changes are really there hacs is sometimes a bit stange if you are downloading main

https://github.com/joBr99/nspanel-lovelace-ui/blob/0b660e96b18e51182f5c70ae6bc5ce9a5a42780f/apps/nspanel-lovelace-ui/luibackend/pages.py#L174

**Comment by kroon040** [comment]
I remove again, restarted appdaemon, installed again en restart appdaemon and now it works

thnx for the heklp and adding this
