### ISSUE TITLE
Background colors / images

### ISSUE THREAD

**Issue by Lux-WorldPC** [joBr99/nspanel-lovelace-ui#177]
Hello
I did not find how to set an for background color or image for cardEntities, cardGrid, cardThermo
juste saw something for screensaver, but did not test yet.
Is that possible ?      are there some syntax examples ?
thx for help

**Comment by joBr99** [comment]
Hey, 
setting a background image or color isn't possible, due to the lack of transparency support of the display in the nspanel. See #124 . You can adjust the colors of every item on the screensaver, including the background, but it's not available as config option.

**Comment by Lux-WorldPC** [comment]
ok thanks    you mean on # 99.         but now I saw result on # 124 picture.      is it possible to have this syntax for testing ?

**Comment by joBr99** [comment]
It isn't possible to transfer a picture to the panel on runtime, you have to modify the firmware for that
