### ISSUE TITLE
[Bug] localization is broken

### ISSUE THREAD

**Issue by kroon040** [joBr99/nspanel-lovelace-ui#183]
Hi,

I have set dutch in de panel, and it works in the screensaver , but I still have english in entities page.

There is see RUN where is should expect UITVOEREN with script
On the locks I see LOCK, where I expect VERGRENDELEN.

 Is this in the enities page possible to have also the language yo want?

**Comment by joBr99** [comment]
Hey, 
update to 2.8.3, should be fixed
