### ISSUE TITLE
[Feature Request] Configure volume steps in media_player card

### ISSUE THREAD

**Issue by matrixx567** [joBr99/nspanel-lovelace-ui#185]
Hy,

## Problem

I am using the media_player card to control a Sonos media player. If you press the `volume up`or `volume down` button within the media player card the volume will be changed by 5 (This is hardcoded within the HMI). Most of the time on a Sonos media player this increase will be too much.

## Possible solution

Add a configuration entry `volume_step_size` to the YAML configuration that will be used by the HMI.

Thanks
Martin

**Comment by joBr99** [comment]
I personally don't have a problem to change this within the HMI to 1 or 2, bigger changes should be done with the slider anyways. What do you think?

**Comment by matrixx567** [comment]
This will be the easiest and simplest solution. For the Sonos system 1 would be the best option, but I can also live with 2.

**Comment by joBr99** [comment]
I will chage it to 1 after your changes are merged

**Comment by matrixx567** [comment]
Thank you

**Comment by joBr99** [comment]
changed the steps to 1
