### ISSUE TITLE
Screensaver PM Time "AM/PM" over minute number

### ISSUE THREAD

**Issue by e2m32** [joBr99/nspanel-lovelace-ui#188]
Screensaver in AM/PM time mode; the "AM/PM" overwrites the minute number.
![screensaver](https://user-images.githubusercontent.com/10486510/168449490-07515ff1-6c6c-4910-b9a5-2b801ccef71b.jpg)

**Comment by joBr99** [comment]
hey, what did you use for the timeFormat config key?

the time is centered for the mode without am/pm, so you have to add some more spaces before the question mark

`timeFormat: "%I:%M   ?%p"`

**Comment by e2m32** [comment]
Ahh. That makes perfect sense. Thank you. I only had one space. I just copy/pasted it from the ReadMe.

**Comment by joBr99** [comment]
Fixed the readme :)
