### ISSUE TITLE
Screen time burn-in

### ISSUE THREAD

**Issue by zanaca** [joBr99/nspanel-lovelace-ui#191]
Is there any reliable information regarding to pixel burn-in  with Nextion?  

It would work like a priority handler to think about a "live" screen saver, like changing clock and weather position over time or something like that.

By the way, great work!

**Comment by joBr99** [comment]
Changing Positions of elements during runtime isn't possible with nextion.

This is a quote from @aderusha, developer of the HASwitchPlate Project, which is also using a Nextion Screen.

> In regards to screen burn, I have several panels that have been running for a few years now with no signs of it, but Nextion has been known to switch around the LCD panels they ship without telling anyone about it, so I cannot confidently state that it can never happen. Modern LCDs generally don’t have a huge problem w/ screen burn, so it’s probably not going to happen but… I don’t control that part list as we all buy the screens as an assembly without datasheets specifying screen lifetime.
