### ISSUE TITLE
[feature-request] Having waveform or graph page

### ISSUE THREAD

**Issue by 0x414c49** [joBr99/nspanel-lovelace-ui#192]
I was checking Nexticon editor yesterday and I found out there is a waveform and gauge component. I'm not sure if that's possible to feed these components from the backend (maybe due to a limitation from HMI), but is there a reason we don't have it? like a limitation or do you think it's possible.

![image](https://user-images.githubusercontent.com/57097646/168760620-cbdee927-53ba-49a5-b240-046faef3a3df.png)

**Comment by joBr99** [comment]
Well, the waveform looks terrible and isn't customizable. 
For the gauge I never had a use case, no clue if it's working good enough, for what and where do you want to use it?

**Comment by 0x414c49** [comment]
Off-topic here:
The only thing, I'm doing some research on is the QRCode. Maybe a QRCode page might be good, I see that people with Aurdiono are making the HMI QRCode dynamic. I thought maybe we can have a page like Wifi share for the guests.

As an example, I have a Guest Wifi SSID for my friends.

**Comment by joBr99** [comment]
Drawing qr code on runtime is possible (even if it's not officially supported or documented by nextion ...)

What do you have in mind, a separate page with a qr code?

**Comment by 0x414c49** [comment]
Yeah, something like that. I was trying to create a page with two text fields but I found it a little difficult to do, especially if the password is a little long (like 3-4 words). I thought an information page that supports QR Code would something nice, idk wifi share or something.

**Comment by joBr99** [comment]
Yes, please open an feature request for it
