### ISSUE TITLE
[Feature Request] Wifi share information page with QR Code

### ISSUE THREAD

**Issue by 0x414c49** [joBr99/nspanel-lovelace-ui#194]
I think this could be a good option, so by defining an SSID and Password for Guests, they can easily connect to the home wifi. Sharing the wifi could be in two different ways, just simply showing SSID and Password on the page, but sometimes password can be longer than it is, like all my SSIDs at home.

The QRCode is easy to use and luckily it's not a big one! As an example, this website easily can generate a Wifi QR Code sample.

![image](https://user-images.githubusercontent.com/57097646/169358182-ec645efc-00bb-432c-b898-7c3af99f111a.png)

https://www.qr-code-generator.com/solutions/wifi-qr-code/

**Comment by joBr99** [comment]
still a long way to go, but I guess it will look like this

![image](https://user-images.githubusercontent.com/29555657/169364324-277dcd5f-c7db-46fe-a896-72b2e2175fd8.png)

**Comment by joBr99** [comment]
![image](https://user-images.githubusercontent.com/29555657/169655532-d9d683e4-c725-44bc-9f08-81f5ff3798c8.png)

**Comment by joBr99** [comment]
implemented in all current development version and synced to all firmware versions

**Comment by 0x414c49** [comment]
Ah, nice man! You are awesome. Can't wait to try it.
