### ISSUE TITLE
[Feature Request] Ability to show another date next to default date

### ISSUE THREAD

**Issue by 0x414c49** [joBr99/nspanel-lovelace-ui#195]
On the screen saver below the time, we have a date of the day. Some countries in the world such as Iran, China, etc also have their own calendar system and it would be nice if there is an option that we can supply this to the date.

To test it, I modified the backend code and I happened [Persian Calendar](https://en.wikipedia.org/wiki/Iranian_calendars) next to date and looks, Georges so there is enough space for a date with yyyy/mm/dd 

I think it would be easier if we can bind it to an entity or something in HA.

**Comment by 0x414c49** [comment]
I forgot to mention that I can make the PR for it, and it does not require any changes to HMI file :)

**Comment by joBr99** [comment]
hey, can you share a picture of the result on the panel and your changes in this issue?

**Comment by 0x414c49** [comment]
@joBr99 yeah, here you are:

![photo_2022-05-19_19-50-23](https://user-images.githubusercontent.com/57097646/169365287-9c9fb695-3aac-4910-b59f-ec53ba33a5a3.jpg)

**Comment by 0x414c49** [comment]
and the code changes, in the `pages.py` in the `update_date` method:

```
        self._send_mqtt_msg(f"date~{date} - {alternative_date}")
```

Of course this code is just for my need and I always supply the date, but in case we go on this path, some small conditions is needed.

**Comment by joBr99** [comment]
I'm more currious about how you are getting the alternative_date variable.

Do you have the babel package installed? (no clue how far their localization support goes, didn't check)

https://github.com/joBr99/nspanel-lovelace-ui#installing-appdaemon

**Comment by 0x414c49** [comment]
@joBr99 babel itself doesn't support for example Persian calendar. I tried to use babel first but it just translated Georgian calendar names into Persian. For the alternate date, it can bind to an input text helper in HA.

For myself, I used an external Python library called "Persian tools" and I got the date with that:

```
        persian_date = JalaliDate.today().strftime("%Y/%m/%d")
        self._send_mqtt_msg(f"date~{date} - {persian_date}")
```

There is also another workaround, we can add a new option as an alternate date or additional date system for screen-saver so the user can define for example Persian, Chinese, etc as the options.

**Comment by joBr99** [comment]
does homeassistant have an easy way to get the persian calendar date?

**Comment by 0x414c49** [comment]
Not, as far as I know, I doubled check source code of the HA. The only way is to create a sensor for it.

**Comment by joBr99** [comment]
yeah, but the sensor also needs to get the information from somewhere

**Comment by 0x414c49** [comment]
@joBr99 true, here is an example for the Lunar calendar:

https://github.com/whtsky/home-assistant-chinese-calendar

**Comment by joBr99** [comment]
implemented a config option for a HomeAssistant Template, that will be evaluated and appended to the date

```
    dateAdditonalTemplate: " - {{ states('sun.sun') }}"
```

**Comment by 0x414c49** [comment]
That's a nice feature, I'll test it and let you know.
