### ISSUE TITLE
[Feature Request] Cover - Show End-Position's on Up/Down Buttons

### ISSUE THREAD

**Issue by joBr99** [joBr99/nspanel-lovelace-ui#196]
![image](https://user-images.githubusercontent.com/29555657/169561799-145b41f6-400b-4493-8a38-a4bc40f8b82a.png)

**Comment by wvalko** [comment]
Setup your work today, great stuff!  Noted this with my two garage controllers. indifferent states regardless of being open / closed.   Again great work, thank you!

**Comment by joBr99** [comment]
if you are using the EU version of the panel you can try this now with the current development version

**Comment by joBr99** [comment]
now also in US-P
