### ISSUE TITLE
Unlink buttons from relays

### ISSUE THREAD

**Issue by illuzn** [joBr99/nspanel-lovelace-ui#198]
Hi,

I know this isn't supposed to be a tech support forum. But do you know if the buttons are physically linked in some way to the relays or is this done programmatically.

I have a smart light attached to Relay 1 which I want always on (it turns itself on/ off internally). I would love to have the buttons thus be "soft" buttons and trigger HA to toggle the light colour or turn on the heater. Is this even possible?

**Comment by joBr99** [comment]
Hey, 
please see #190 this should answer your question.
