### ISSUE TITLE
[Feature Request] Correct Handling of covers which have open/ closed sensors rather than position

### ISSUE THREAD

**Issue by illuzn** [joBr99/nspanel-lovelace-ui#199]
Currently the cover control works great for my blinds which have position sensors built in.

However, the cover control work correctly for my gate or my garage door which has open/ closed/ opening/ closing as its states rather than a position sensor. To be clear the buttons work as intended but are non sensical for my gate which opens and closes rather than going up and down.

I've tested with the latest development release and because the position reads incorrectly the new feature which disables the relevant button per #196 doesn't work.

Picture attached for reference. In this example the garage is closed but position is detected as 50%.
![20220522_005419](https://user-images.githubusercontent.com/57167030/169660702-3284049f-a150-4859-9883-a520a056c50c.jpg)

**Comment by joBr99** [comment]
Hey, 
can you post a picutre of the states of your garage door from the Homeassistant Developer Tools?

**Comment by illuzn** [comment]
Do you mean this?

![image](https://user-images.githubusercontent.com/57167030/169660946-8c4671fe-2280-4b2d-8e8f-d0b0f7eec00c.png)

**Comment by joBr99** [comment]
yes, thank you

I've added a fix for showing the state instead of the position in case there is no position, however I cannot test this, please try the current development firmware

**Comment by illuzn** [comment]
This is what I see now. I have updated to the latest development US portrait nextion firmware but I gather I might need the relevant patch from the EU firmware?

![20220522_021713](https://user-images.githubusercontent.com/57167030/169661350-41b49645-64e4-4a72-817a-7977115fd82c.jpg)

**Comment by joBr99** [comment]
no, please redownload main again I think I spotted the error

https://github.com/joBr99/nspanel-lovelace-ui/commit/4626702a455d34a77ee8c44876f0c0474da829fe

**Comment by joBr99** [comment]
![image](https://user-images.githubusercontent.com/29555657/169662983-1f2ff82d-611e-4401-b2cf-41935a10b9e5.png)

**Comment by wvalko** [comment]
Anyway to add a stop as optional? (Garage controllers in the US just have open and close function, not a stop.)  Cheers

**Comment by joBr99** [comment]
how is it displayed in homeassistant? "supported_features: 11" indicates that it supports OPEN, CLOSE and STOP

**Comment by wvalko** [comment]
Here are the action options I have with my Zwave Garage door controller: 

![image](https://user-images.githubusercontent.com/29451850/169671191-45ff7c45-d1b4-433f-8066-b8adc9182767.png)
![image](https://user-images.githubusercontent.com/29451850/169671183-d15c5fee-bf7a-4c67-bdcf-3c99365936a6.png)

**Comment by illuzn** [comment]
Can confirm working in build e650b7d.

**Comment by illuzn** [comment]
> Here are the action options I have with my Zwave Garage door controller:
> 
Go to developer tools on the left hand side of your home assistant dashboard and show us what it shows for your supported features per my screenshot in post 3
