### ISSUE TITLE
[Bug Report] cardEntities incorrectly handles scripts

### ISSUE THREAD

**Issue by illuzn** [joBr99/nspanel-lovelace-ui#200]
cardEntities is incorrectly handling scripts on my US portrait device.
![20220522_010852](https://user-images.githubusercontent.com/57167030/169660740-58019a45-faf7-4316-8bdb-3eac67e16628.jpg)
.

Everything appears as it should however pressing the text, icon or run does nothing.

I note that putting a script in a cardGrid works correctly.

**Comment by joBr99** [comment]
Please try this in the current development version, this could be already fixed

**Comment by joBr99** [comment]
https://github.com/joBr99/nspanel-lovelace-ui#how-to-upgrade-from-a-release-to-the-current-development-version

**Comment by illuzn** [comment]
Can confirm fixed in current development version. Sorry should have checked that first.
