### ISSUE TITLE
No Touch Responsiveness from my NSPanel

### ISSUE THREAD

**Issue by Astogems** [joBr99/nspanel-lovelace-ui#201]
Hello,

I have configured everything properly. The dashboard is showing up on my NSPanel and the states are reflecting. This means that my AppDaemon and my MQTT Set-Up was done correctly.

However, it seems that I am not able to use the touchscreen function at all. I couldn't swipe to another page, nor toggle any lights. When it is in sleep mode, touching does not even turn on the display. I have only downloaded the berry autoexec.be. 

Is there something that I might be missing?

**Comment by joBr99** [comment]
There was somebody in the HomeAssistant Forum being unable to exit screensaver with a non working touch, which was solved after reseating the panel.

https://community.home-assistant.io/t/sonoff-nspanel-smart-scene-wall-switch-by-itead-coming-soon-on-kickstarter/332962/723?u=jobraun

Also if you are using the US portrait version, please udpate to the current development firmware, to fix an bug on the entities page preventing to use the buttons.

**Comment by Astogems** [comment]
Thank you for the speedy reply, I will give it a try. I am currently trying to use my own webserver to upload nspanel.tft

**Comment by Astogems** [comment]
Update: I have just tried both.

Checked my pins, they were all sitting right. I am using the EU Version.

**Comment by joBr99** [comment]
then please check the appdaemon log for errors

**Comment by Astogems** [comment]
![image](https://user-images.githubusercontent.com/92814513/169668633-917a9974-c7e9-4616-8786-0116a6b35cc1.png)

Im not seeing anything weird except for that my Tasmota Driver Version is None

**Comment by Astogems** [comment]
![image](https://user-images.githubusercontent.com/92814513/169668690-afb70df7-05b1-44c4-b444-771ab4f240ee.png)
There are also instances where my Tasmota Driver is 4

**Comment by joBr99** [comment]
Both fine, I would use the log in the Add-Ons instead and also what do you see in your log after touching the screen?

For example touching the screensaver should create messages containing `screensaver,bExit`

![image](https://user-images.githubusercontent.com/29555657/169668757-94f970a3-2b30-4491-952c-f6469a2e3760.png)

**Comment by Astogems** [comment]
I have checked the logs, I am not getting any feedback on the logs whatsoever when I tap the screen on the NSPanel.

One mistake that I made while booting up with FTDI was I accidentally flipped 5v and neutral pins (the 8pins at the back). Flipped it back and tasmota was launched. Could that have damaged the board in anyway?

**Comment by joBr99** [comment]
do you see CustomRecv lines like this in your tasmota log?

`22:03:17.195 MQT: tele/tasmota_nspkueche/RESULT = {"CustomRecv":"event,buttonPress2,screensaver,bExit,2"}`

**Comment by Astogems** [comment]
I have never ever seen anything like that on my Tasmota Log from the start.

**Comment by Astogems** [comment]
![image](https://user-images.githubusercontent.com/92814513/169669010-f873c46c-8402-48fd-8a69-0bc7b2836ec4.png)
I do get feedback by clicking one of the 2 buttons below the screen. I never ever gotten feedbacks from tapping the screen.

**Comment by Astogems** [comment]
![image](https://user-images.githubusercontent.com/92814513/169669045-88989bc8-f967-4eaf-bd90-02260a89f49c.png)
Here is a screenshot of my apps.yaml

**Comment by joBr99** [comment]
The two buttons are directly connected to the esp32.
The display is connected via serial to the esp32 over that flex cable, sounds like you are not receiving any serial data from the panel to the esp32. Maybe try to reseat the cable within the panel.

**Comment by joBr99** [comment]
I also have a small test firmware that I've used during development of the flashing command in tasmota, it contains some buttons to change the display color and to send serial messages. So if you want to test the touch itself you could do this with it. But if there is only one-way communication between esp and nextion panel, flashing also shouldn't work.

`FlashNextion http://nspanel.pky.eu/test.tft`

**Comment by Astogems** [comment]
I have tried reseating the cables multiple times. To no avail...

**Comment by Astogems** [comment]
Testing with the test.tft does not work as well. Could I possibly be looking at a defective unit somehow?

**Comment by Astogems** [comment]
Perhaps one consideration if it matters is that I am testing this using a power cord directly to my Socket. Live + Neutral at the back

**Comment by joBr99** [comment]
were you able to flash the test.tft? this would indicate that your serial is working in both directions

**Comment by Astogems** [comment]
![WIN_20220522_05_33_34_Pro](https://user-images.githubusercontent.com/92814513/169669691-10a29169-90f4-4811-9f6c-fe0ccb53e76a.jpg)

Yes I was able to flash the test.tft

**Comment by Astogems** [comment]
But none of the buttons work

**Comment by joBr99** [comment]
also not the red/green/blue ones?

**Comment by Astogems** [comment]
I see... ah shutss

**Comment by joBr99** [comment]
just flash the stock firmware back to the display and shoot the sonoff support an mail with an video

**Comment by Astogems** [comment]
Im trying to reseat the thin film for the LCD Panel to the ESP Board. If all fails, i will reorder a new set. I currently do not have the stock firmware as I did not make a backup...

**Comment by Astogems** [comment]
You have been so helpful thus far, I am truly thankful.

**Comment by joBr99** [comment]
you cannot simply make a backup of the tft file, get it from here

you will need to put it on a webserver which supports http (https doesn't work)

https://github.com/masto/NSPanel-Demo-Files/issues/4

**Comment by Astogems** [comment]
Awesome, I will use my homeassistant to do that. Thank you thus far!

**Comment by joBr99** [comment]
yes, homeassistant www folder is fine

**Comment by Astogems** [comment]
![image](https://user-images.githubusercontent.com/92814513/169669954-09b0e10c-176e-4d49-a8e4-ceb440df0629.png)


Just to check, these reds are okay right?

**Comment by joBr99** [comment]
mine looks like this

![image](https://user-images.githubusercontent.com/29555657/169669992-233ffaa2-a134-45a8-9c0e-9d0abed047b1.png)

**Comment by Astogems** [comment]
Ah yes. Same as mine, I guess I am an unlucky batch that got a defective unit. Currently flashing back the stock firmware. Hope to get a replacement set. Once everything is working well. I will definitely buy you a pizza!
