### ISSUE TITLE
[Feature Request] Breadcrumb Option to include next / previous page to <- and -> Top Navigation Arrows

### ISSUE THREAD

**Issue by diginfo** [joBr99/nspanel-lovelace-ui#212]
In the header It would be nice to be able to see what is in the next and previous pages cards:

```
<- Home              Info                     Lights ->
<- Info              Lights                   Heating ->
```

**Comment by illuzn** [comment]
Good idea in principle.

I assume you have the us landscape device? The display format is relatively the same between eu (square), us portrait and us landscape. I'm afraid implementing this won't fit on eu and us portrait (or will require making the font size extremely small).

**Comment by diginfo** [comment]
No I have EU format, but you could have an abbreviation attribute (4 chars ?) rather than the full description, which I agree would not be practicable.

**Comment by joBr99** [comment]
Hmm, yeah there isn't much space in the title at for this, especially not on the us portrait version.

How about using the navigate feature.
You could build a cardGrid with links to 6 pages with it.

**Comment by diginfo** [comment]
The thing is, this will be used by airbnb guests so it has to be "no instructions necessary" :-)

The QRcode for guest wifi is pretty much essential for me.

**Comment by diginfo** [comment]
Yes, that would work.

I also tried adding this card again:

```
      - type: cardQR
        title: Guest Wifi
        key: qr
        qrCode: "WIFI:S:test_ssid;T:WPA;P:test_pw;;"
        entities:
          - entity: iText.Name.test_ssid
            icon: wifi
          - entity: iText.Password.test_pw
            icon: key
```

But just got a blank screen so I guess its not implemented yet.

**Comment by joBr99** [comment]
That are upcoming features, you need to update to the current dev version.

https://github.com/joBr99/nspanel-lovelace-ui#how-to-upgrade-from-a-release-to-the-current-development-version

**Comment by diginfo** [comment]
Yep, that's what I did as mentioned above:

"I update the last ***MAIN *** version & downloaded "FlashNextion http://nspanel.pky.eu/lui.tft" "

**Comment by Dattel** [comment]
Update it again through hacs... 
As @joBr99 points out: HACS is a bit strange on downloading main..
i ran into that situation multiple... a blackscreen on QR page points to an 2 days old implementation state without essential keyparts of the code.. 

i also had that experience with the QR page

**Comment by diginfo** [comment]
Thanks, I just:

1) re-downloaded hacs automation NSPanel main
2) re-started appdaemon
3) Re-ran FlashNextion http://nspanel.pky.eu/lui.tft

the nspanel download started at 97%, it always seems to do that ??

```
08:17:36.894 CMD: FlashNextion http://nspanel.pky.eu/lui.tft
08:17:36.911 MQT: stat/nspanel-54cc/RESULT = {"FlashNextion":"Done"}
08:17:36.970 FLH: host: nspanel.pky.eu, port: 80, get: /lui.tft
08:17:39.170 FLH: Send (High Speed) flash start
08:17:39.584 MQT: tele/nspanel-54cc/RESULT = {"Flashing":{"complete": 0, "time_elapsed": 0}}
08:17:40.173 FLH: host: nspanel.pky.eu, port: 80, get: /lui.tft
08:17:41.860 MQT: tele/nspanel-54cc/RESULT = {"Flashing":{"complete": 94, "time_elapsed": 2}}
08:17:45.632 MQT: tele/nspanel-54cc/RESULT = {"Flashing":{"complete": 95, "time_elapsed": 6}}
08:17:49.502 MQT: tele/nspanel-54cc/RESULT = {"Flashing":{"complete": 96, "time_elapsed": 10}}
08:17:53.228 MQT: tele/nspanel-54cc/RESULT = {"Flashing":{"complete": 97, "time_elapsed": 14}}
08:17:57.221 MQT: tele/nspanel-54cc/RESULT = {"Flashing":{"complete": 98, "time_elapsed": 18}}
08:18:00.118 MQT: stat/nspanel-54cc/RESULT = {"CustomSend":"Done"}
08:18:01.051 MQT: tele/nspanel-54cc/RESULT = {"Flashing":{"complete": 99, "time_elapsed": 21}}
```

And I still have a blank QR code screen and no colours on the screensaver weather page.

**Comment by joBr99** [comment]
starting at 97% is normal, do you have theme.py in your luibackend folder? If not you've downloaded the lastest release. Wait a few seconds in the redownload dialog after selecting main, before clicking download.

**Comment by joBr99** [comment]
yeah, you can also display an input_text or a switch from home assistant there

**Comment by diginfo** [comment]
apologies for all the feedback, but I am actively testing.

using "sunrise" and "sunset" in the dimmer crashes my panel:

```
    sleepBrightness:
      - time: "sunrise"
        value: 30
      - time: "19:00:00"
        value: 10
```

**Comment by joBr99** [comment]
> is "AutoWeather" working ? - I have it enabled but all icons in the forecast are all still white, even though rain, clouds etc are forecast
```
    screensaver:
      entity: weather.k3ll3r
      theme:
        AutoWeather: auto
```

> using "sunrise" and "sunset" in the dimmer crashes my panel:

works fine for me, please check the appdaemon log for errors and post it here

**Comment by diginfo** [comment]
```AutoWeather: auto```  instead of  ```AutoWeather: True``` works.

regarding sunset / sunrise, I just get the "waiting for content" spinner forever.

There are no error messages at the time I save the file, only this in the logs:

```
2022-05-24 18:26:40.801286 WARNING nspanel-1: Coroutine (<coroutine object ADAPI.run_daily at 0x7ff2b801cac0>) took too long (10 seconds), cancelling the task...
```

**Comment by diginfo** [comment]
Ahh, more info:
```
2022-05-24 18:29:23.115956 WARNING nspanel-1: Coroutine (<coroutine object ADAPI.run_daily at 0x7ff2b8064b40>) took too long (10 seconds), cancelling the task...
2022-05-24 18:29:33.121681 WARNING nspanel-1: Coroutine (<coroutine object ADAPI.parse_time at 0x7ff2b801c140>) took too long (10 seconds), cancelling the task...
2022-05-24 18:29:43.137504 WARNING nspanel-1: Coroutine (<coroutine object ADAPI.parse_time at 0x7ff2b801cb40>) took too long (10 seconds), cancelling the task...
2022-05-24 18:30:02.165194 WARNING nspanel-1: ------------------------------------------------------------
2022-05-24 18:30:02.165851 WARNING nspanel-1: Unexpected error in worker for App nspanel-1:
2022-05-24 18:30:02.165963 WARNING nspanel-1: Worker Ags: {}
2022-05-24 18:30:02.166061 WARNING nspanel-1: ------------------------------------------------------------
2022-05-24 18:30:02.166328 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/app_management.py", line 165, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.9/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 25, in initialize
    controller = LuiController(self, cfg, send_mqtt_msg)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 39, in __init__
    self.current_screensaver_brightness = self.calc_current_screensaver_brightness()
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 92, in calc_current_screensaver_brightness
    sorted_timesets = sorted(sleep_brightness_config, key=lambda d: self._ha_api.parse_time(d['time']))
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
2022-05-24 18:30:02.166407 WARNING nspanel-1: ------------------------------------------------------------
2022-05-24 18:30:02.173063 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-05-24 18:30:02.177028 INFO nspanel-1: Sending MQTT Message: time~18:30
```

**Comment by joBr99** [comment]
do you have longitude and latitude configured in appdaemon.yaml?

**Comment by diginfo** [comment]
Yes, I do, but I prefer not to give my exact coordinates.

**Comment by diginfo** [comment]
I have a feature request, should I create a new ticket ??

It would be most helpful to be able to display a horizontal bar above the "hard switches" indicating whether they are toggle on or off.

Even if not connected to the relays, it would be nice to see the state of these switches on all cards, kind of like a card footer.

**Comment by diginfo** [comment]
could it be a locale issue ?

**Comment by illuzn** [comment]
> is "AutoWeather" working ? - I have it enabled but all icons in the forecast are all still white, even though rain, clouds etc are forecast

That's on me and my spaghetti coding. Please note a breaking change is going to be pushed that changes the config to `autoWeather` note capitalisation and argument to `true` rather than auto.

> regarding sunset / sunrise, I just get the "waiting for content" spinner forever.

Works for me in en_AU.

Here is my suspicion. You have babel installed but haven't configured a `locale` (or perhaps you don't have babel installed but you have configured a `locale`). This throws up similar but not the same errors when I do that.

**Comment by joBr99** [comment]
I don't see how this should be releated to the locate

**Comment by diginfo** [comment]
Here you go:

```
2022-05-25 07:16:59.603231 INFO suntest: Test sunset/sunrise:
2022-05-25 07:17:09.608698 WARNING suntest: Coroutine (<coroutine object ADAPI.parse_time at 0x7ff165252cc0>) took too long (10 seconds), cancelling the task...
2022-05-25 07:17:09.619427 INFO suntest: None
2022-05-25 07:17:19.635244 WARNING suntest: Coroutine (<coroutine object ADAPI.parse_time at 0x7ff165252dc0>) took too long (10 seconds), cancelling the task...
2022-05-25 07:17:19.640658 INFO suntest: None
```

**Comment by joBr99** [comment]
Good, confirmed that this is an AppDeamon issue. Do you mind opening a ticket with this minimal example on the appdeamon project? 

https://github.com/AppDaemon/appdaemon

**Comment by diginfo** [comment]
https://github.com/AppDaemon/appdaemon/issues/1514
