### ISSUE TITLE
Hard Button Status 

### ISSUE THREAD

**Issue by diginfo** [joBr99/nspanel-lovelace-ui#221]
It would be most helpful to be able to display a horizontal bar above the "hard switches" indicating whether they are toggle on or off, as in the original unmodified version.

Even if not connected to the relays, it would be nice to see the state of these switches on all cards, kind of like a card footer.

I realise that doing this would reduce the vertical area which is already quite limited, but the status bars only need to be 10 pixels or less. 

If you were able to switch this on / off would be a bonus.

_Originally posted by @diginfo in https://github.com/joBr99/nspanel-lovelace-ui/issues/212#issuecomment-1135869661_

**Comment by joBr99** [comment]
@diginfo see #233
Allows to display the state and also allows to indicate what the state acually indicates through the icon

**Comment by diginfo** [comment]
Thanks, great, but personally I am not a fan of the location of these icons, to me it looks to 'cluttered' around that area, and they look a little out of place :-)

Would it be possible to have an option to have them in the Top left and Right corners where's there's nothing else ?

Also, if you set a background colour, but don't use the icons, then they are shown as black sqlares.
<img width="748" alt="Screenshot 2022-05-28 at 8 29 23 AM" src="https://user-images.githubusercontent.com/6010010/170802653-f3046781-8829-4659-b5a3-76c52e68a1d0.png">

**Comment by joBr99** [comment]
background color is fixed, top right and left doesn't work because they overlap with the time box, it decrease the size of the text box for testing and moved the icons to the top
