### ISSUE TITLE
[Feature Request] Possibility to send an alert message to the screen

### ISSUE THREAD

**Issue by pabutterworth** [joBr99/nspanel-lovelace-ui#223]
Hi,

I would love to be able to send an alert message to popup on screen, which would disappear on a tap of the screen. 

I would use it for things like 'Boiler needs fuel', 'Dogs need monthly tablets' etc.

Would that be useful to others too?

Cheers
Paul

**Comment by joBr99** [comment]
I've added some documentation about it.

https://github.com/joBr99/nspanel-lovelace-ui/blob/main/README.md#sending-notifications-to-the-panel

also see #152

**Comment by illuzn** [comment]
N.B. The Buzzer may not be connected to the panel.
