### ISSUE TITLE
[Feature Request] Adjustment request - Light Color Selector Layout US-p

### ISSUE THREAD

**Issue by wvalko** [joBr99/nspanel-lovelace-ui#225]
Please see dirty mockup I did of US light color selector.  Would a format like this be possible for us-p?  As you can see currently the color wheel is quite small and lots of non utilized space. 

Thanks! 

<img width="1522" alt="image" src="https://user-images.githubusercontent.com/29451850/170137039-59f33dee-9de3-4c06-8230-58bfdc77a166.png">

**Comment by wvalko** [comment]
Is this doable?

**Comment by joBr99** [comment]
yes

**Comment by joBr99** [comment]
Please checkout the current development verion, I changed it in firmware, serial protocol and in the appdaemon app. The color wheel should be bigger now.

**Comment by wvalko** [comment]
Hey @joBr99 , big improvement!  Here is current view with the updates.   Anyway to nudge the brightness element down some? 

![image](https://user-images.githubusercontent.com/29451850/170844325-b03126b3-7b97-4cb6-91a0-f132720aad1e.png)

**Comment by joBr99** [comment]
didn't notice that, moved it

**Comment by wvalko** [comment]
Great,  Thank you!!
![image](https://user-images.githubusercontent.com/29451850/170844623-acfe8b32-1afd-4b83-99a5-168308427f8c.png)

**Comment by wvalko** [comment]
Odd, playing with the colorwheel itself, the functionality has diminished 80%.  Like the X/Y axis is off now or something.  I can get white, a red/orange, but that's about it. 

Standing side by side, controlling same light group with 2 switches.  one on 2.9.0 and one on 2.9.3

**Comment by joBr99** [comment]
You have to update the appdameon app to the current dev version and also the firmware, mismatch will break the color mapping.

**Comment by wvalko** [comment]
I look to be 2.9.3 on both Firmware (done manually) and AppDaemon
![image](https://user-images.githubusercontent.com/29451850/170872579-5048ada4-f797-434c-b336-4197a11b2348.png)

**Comment by joBr99** [comment]
2.9.3 is not the current development version

https://github.com/joBr99/nspanel-lovelace-ui#how-to-upgrade-from-a-release-to-the-current-development-version
