### ISSUE TITLE
[bug] No auto icon on climate card

### ISSUE THREAD

**Issue by kroon040** [joBr99/nspanel-lovelace-ui#230]
Hi,

On version 2.9.0 is see now all the icons thnx for that, but only with mode heat_cool , I get an ! as icon. This is the auto mode, and should expect auto icon. Here the example in Homeassistant, 4th icon

![climate3](https://user-images.githubusercontent.com/40452265/170738647-eae2e4a5-2277-486a-aed3-386115ceaac1.png)

**Comment by joBr99** [comment]
please check if this change solves your problem

https://github.com/joBr99/nspanel-lovelace-ui/blob/35e4819213a592c7a2047bc49a581b0a2df67dbb/apps/nspanel-lovelace-ui/luibackend/pages.py#L281
