### ISSUE TITLE
Currently and state in climate not translated

### ISSUE THREAD

**Issue by kroon040** [joBr99/nspanel-lovelace-ui#232]
Hi,

On the new climate card 2.9.0, I noticed that the words Currently and State are not translated. The value of state has been translated

**Comment by joBr99** [comment]
yes this has to be implemented

https://github.com/joBr99/nspanel-lovelace-ui/blob/main/apps/nspanel-lovelace-ui/luibackend/pages.py#L308

**Comment by joBr99** [comment]
implemented in v2.9.1
