### ISSUE TITLE
[Feature Request] add a media control on screen saver

### ISSUE THREAD

**Issue by hatran0884** [joBr99/nspanel-lovelace-ui#234]
it is possible to have a space to add a media control (maybe only next song and previous song control) on the screen saver, this media control will only appear when the media page is active. additionally, the title of the song will appear above the date. so it would be easier to control the songs being played. 

let me know your thought if it can be implemented or you are interested in working on it. 
I am using US-L btw

**Comment by joBr99** [comment]
I don't see a spot for adding this on the screensaver, also buttons on the screensaver are colliding with the wake/dimmode functionally of the screensaver.

**Comment by hatran0884** [comment]
![IMG_6353](https://user-images.githubusercontent.com/58875735/170860811-d575eabf-7457-46ae-b028-cc9dd3cd1f57.jpeg)
it will look like this, we can use button when taptounlock is enabled. ?

**Comment by joBr99** [comment]
You can configure the default card to get faster to cardMedia while media is playing, I'm not planning to implement additional buttons/controls on this screensaver page.
```
      defaultCard: '{{ "navigate.cardMedia_test123" if is_state("media.test123", "playing") else "navigate.cardGird_test123" }}'
```

**Comment by joBr99** [comment]
Displaying the currently playing title on the date line is also possible with `dateAdditonalTemplate` config option.

**Comment by hatran0884** [comment]
> Displaying the currently playing title on the date line is also possible with `dateAdditonalTemplate` config option.

I cannot find a guide to configure this, could you link me there. ?

**Comment by joBr99** [comment]
it's a homeasstiant template, you can test them in the templates tab of HA Dev tools

https://www.home-assistant.io/docs/configuration/templating/

```
{{ " - "+state_attr('media_player.spotify', 'media_title') if is_state('media_player.spotify', "playing") else "" }}```
