### ISSUE TITLE
[Bug] swipe gesture is not working on the first page

### ISSUE THREAD

**Issue by hatran0884** [joBr99/nspanel-lovelace-ui#235]
I have weird issue with swipe gesture not working on the first page, it have tested on 02 panels, both having same issue, the next pages onward working well with swipe gesture.

**Comment by joBr99** [comment]
What's the Typen of the Page?

**Comment by hatran0884** [comment]
it is cardentity on first panel and cardgrid on the second panel

**Comment by joBr99** [comment]
@matrixx567

I guess the content of tId.txt is changing on this two types of pages. 

>//The navigation text is stored as local variable within tld.txt

This isn't true the content of tId can change anytime, it only contains that information right after parsing the navigate parameter.

I think removing the checks in the edge swipe buttons and adding `tsw b0,0` / `tsw b0,1`commands would solve this issue.

**Comment by joBr99** [comment]
changed the implementation in all firmware versions, @hatran0884 please flash current dev version and test

**Comment by hatran0884** [comment]
yes, I confirm it works fine now. thanks
