### ISSUE TITLE
[BUG] Icon as Text not working

### ISSUE THREAD

**Issue by hatran0884** [joBr99/nspanel-lovelace-ui#237]
Hi, I configured an icon as Text as what you guided, but it is not working, below is what I configured an entity to be a script of changing a TV channel: 

      - type: cardGrid
        entities:
          - entity: script.vtv3_hd
            icon: text:VTV3
        title: TV

anything wrong here ?

**Comment by joBr99** [comment]
is your appdamon app on the newest dev version? this is part of release 3.0.X, works fine for me

**Comment by hatran0884** [comment]
Yes, i am using main version

**Comment by joBr99** [comment]
![16538358374779148627805831099099](https://user-images.githubusercontent.com/29555657/170875667-41142be8-7381-4228-9e02-d46dcc0a4f97.jpg)

works fine for me, also with script on lastest version

**Comment by hatran0884** [comment]
![314F75E5-3425-4C09-98FE-52F861DBC395](https://user-images.githubusercontent.com/58875735/170876620-9bb6a6c7-4989-405b-af56-5e6765f6dd57.jpeg)

mine shows this. No idea whats wrong here

**Comment by joBr99** [comment]
on which version are you ...?

![image](https://user-images.githubusercontent.com/29555657/170876875-bc27738c-adb7-4f3e-80d8-97fb65f0ca1c.png)

https://github.com/joBr99/nspanel-lovelace-ui/blob/f1a5ad475cb406e70b933822fe8cdd050428322e/apps/nspanel-lovelace-ui/luibackend/icon_mapping.py#L6902

**Comment by hatran0884** [comment]
Oh, i forgot to restart appdaemon. After restarting, working now. Thanks :)
