### ISSUE TITLE
[Feature Request] set brightness the same way as sleepBrightness

### ISSUE THREAD

**Issue by bkbartk** [joBr99/nspanel-lovelace-ui#239]
Is it possible to set the screen brightness the same way as de sleep brightness?
I mean, when I want to adjust the dimmer on my bedroom there is coming so much light from the screen that I almost don't need the light at all. So at some moments I would like the default brightness to be lower.

**Panel / Firmware Version**
EU

**Comment by illuzn** [comment]
How would you propose that this work? is it similar to #243 where you would have a light sensor and the screen brightness would scale with the light sensor?

**Comment by bkbartk** [comment]
that would be really cool,
but since I don't own a lux sensor and don't expect a lot of people to own this I would suggest to do it time based,
or sunset bases as as it is done now for the screensaver
https://github.com/joBr99/nspanel-lovelace-ui#schedule-sleep-brightness

**Comment by joBr99** [comment]
@illuzn this is about the normal brightness, which is currently hardcoded to 100, I started to modify the dimmode command to add a second parameter which is adjusting this value

**Comment by joBr99** [comment]
besides `sleepBrightness` the current dev version has now a `screenBrightness` config key that should allow you to set the brightness
