### ISSUE TITLE
[Feature Request] add tilt position in details pages for Covers

### ISSUE THREAD

**Issue by stresli** [joBr99/nspanel-lovelace-ui#240]
Hi

is it possible in Detail Page for Covers with tilt add tilt position (cover.set_cover_tilt_position)?

<img width="298" alt="2022-05-29_21-22-48" src="https://user-images.githubusercontent.com/85819870/170888114-ee58737e-de5e-46aa-98a8-507dce293fe5.png">

thank you for a fantastic work.

Panel / Firmware Version
EU

**Comment by joBr99** [comment]
added very early and basic support for tilt on current development version and the EU firmware

**Comment by jrspowers** [comment]
hello should i send this link to my nspanel ?

**Comment by joBr99** [comment]
no it's the link to the documentation how to update to the develeopment version

**Comment by jrspowers** [comment]
an okay that means that I can develop with it or what?

**Comment by joBr99** [comment]
no it is the latest version including changes that are not yet released

**Comment by jrspowers** [comment]
a oke well leuk zal ins bekijken hoe doe ik dat gewoon die link in tasmota verzenden ?

**Comment by joBr99** [comment]
It's well documented how to update to the development version, if you have to ask questions about it please stay away from this version. It can be broken at any time, contain untested and unstable changes.

**Comment by jrspowers** [comment]
ok good thanks
