### ISSUE TITLE
[BUG] Climate Card does not seem to work properly

### ISSUE THREAD

**Issue by Astogems** [joBr99/nspanel-lovelace-ui#244]
**Describe the bug**

The climate card for the NSPanel when using my Daikin AC does not seem to pull data correctly. It can turn on, but not off. It cannot set the temperature at all.

**To Reproduce**

I had used my Daikin AC which is integrated into home assistant through their integration and just added the entitiy id into the card config.

**Screenshots**

![WhatsApp Image 2022-05-31 at 5 08 39 AM](https://user-images.githubusercontent.com/92814513/171062052-1a768384-789f-4fdb-8d31-d6b7934f1c29.jpeg)

**AppDaemon Logs**

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/92814513/171062123-89a4f11a-8af6-4a78-b644-53d166f6e94e.png">

**Additional context**

**Comment by joBr99** [comment]
looks like you are running an old version of the appdaemon app with a newer firmware

**Comment by Astogems** [comment]
I am running  AppDaemon 4.2.1 and it seems like it is the latest version for me.

**Comment by joBr99** [comment]
no, not appdaemon itself, the nspanel app in the hacs store

**Comment by Astogems** [comment]
Ahhh. Let me try that!

**Comment by Astogems** [comment]
Awesome! You fixed it!

As promised, your pizza will be coming real soon!

**Comment by Astogems** [comment]
Do you think this will work with a Sensibo as well? It has climate domain.

**Comment by joBr99** [comment]
no clue, probably yes 

there are some limitations like setting a lower and upper temperature not yet supported, but no idea if this applies to this specific device

**Comment by Astogems** [comment]
It is great for now, at least in Singapore we hardly use that feature.
