### ISSUE TITLE
[Feature Request] If US and 12h format, can we display...

### ISSUE THREAD

**Issue by wvalko** [joBr99/nspanel-lovelace-ui#247]
Currently if 12h format (AM/PM) the screensaver display shows the preceding 0.  IE right now it's 06:11 PM.  Anyway to eliminate the preceding 0?

**Comment by joBr99** [comment]
%-I	Hour (12-hour clock) as a decimal number.	1, 2, … 12

Try to put a dash before the letters.

https://www.geeksforgeeks.org/python-strftime-function/
