### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by FrancescoDalan** [joBr99/nspanel-lovelace-ui#265]
Hello,
thank you for the great great job!!

I must have some mistake but I can't find it, the temperature of the thermo card is multiplied by 100. 

Here the screen 
![IMG_3582](https://user-images.githubusercontent.com/5870660/172310921-b01806b6-9784-452a-9084-5b4b965b6cf2.jpg)

and here the Appdaemon logs
<img width="1798" alt="Screenshot 2022-06-07 at 08 29 38" src="https://user-images.githubusercontent.com/5870660/172311233-8afe5d19-9f4f-4e2b-9641-bdd4ac0c2f48.png">

Can you help me?
Thank you

**Comment by bkbartk** [comment]
Multiplied by 19 I guess?
I had a similar issue. It turned oud I needed to restart the appdeamon after an update. 
for me also some texts were missing. I don’t zee that in your screenshot.

**Comment by joBr99** [comment]
wired, but yeah try to restart appdaemon in older versions that value had to be multiplied by 10

**Comment by FrancescoDalan** [comment]
Thank you very much, 
after restart the temperature is correct.

Bye
