### ISSUE TITLE
[Feature Request] Documentation

### ISSUE THREAD

**Issue by illuzn** [joBr99/nspanel-lovelace-ui#267]
**Describe the solution you'd like**
[Enable GitHub pages](https://docs.github.com/en/pages/getting-started-with-github-pages)

**Additional context**
The documentation is starting to get pretty extensive and out of hand. It could really benefit from being broken down into several sections to make it navigable.

I am happy to spearhead this part of the repository because of how useful this is for me. I know this will require me to be added as a contributor but I undertake not to commit to any of the other directories of the repository except /docs/

**Panel / Firmware Version**
Not Applicable

**Comment by joBr99** [comment]
I'm open for this, also no issue adding you as cb, never used GitHub pages extensively, can't you make a PR adding files for this?

**Comment by illuzn** [comment]
Yes I think I can use PR to change/ update docs if that is what you prefer. I guess I will just have a development mirror or some such in my forked repo while this is a major work in progress - actually, that's not much more hassle for me so perhaps lets do that.

Let me go ahead with mocking up the documents this weekend and I will link it in here for you to consider.

**Comment by joBr99** [comment]
@illuzn 
I added github pages based on mkdocs to this repo.

Index is in mkdocs.yml and markdown files are in the docs folder.

https://jobr99.github.io/nspanel-lovelace-ui/configure_mqtt/

**Comment by joBr99** [comment]
moved existing docs
