### ISSUE TITLE
[BUG] tasmota32-nspanel.bin link dead

### ISSUE THREAD

**Issue by cmeissl** [joBr99/nspanel-lovelace-ui#269]
**Describe the bug**
The link in the README to [tasmota32-nspanel.bin](https://github.com/tasmota/install/raw/main/firmware/unofficial/tasmota32-nspanel.bin) is dead.
It looks like everything has been upstreamed. I have flashed the standard tasmota32 build and everything
seems to work fine so far.

**To Reproduce**
Click on [tasmota32-nspanel.bin](https://github.com/tasmota/install/raw/main/firmware/unofficial/tasmota32-nspanel.bin)

**Screenshots**
N/A

**AppDaemon Logs**
N/A

**Additional context**
N/A

**Comment by joBr99** [comment]
I guess it's related to this change

https://github.com/arendst/Tasmota/pull/15733

Also something new, I've not seen so far, there separate are factory images, for flashing over serial with esptool.

http://ota.tasmota.com/tasmota32/

**Comment by cmeissl** [comment]
So, should I update to <https://github.com/tasmota/install/blob/main/firmware/development/tasmota32-nspanel.bin>?
Currently my NsPanel runs with normal tasmota32.bin.

**Comment by joBr99** [comment]
No you don't have to current version of the berry driver should work fine with tasmota32.bin

**Comment by Armilar** [comment]
I also use the tasmota32.bin and it works great

**Comment by joBr99** [comment]
tasmota web installer is flashing the factory image

https://tasmota.github.io/install/manifest_ext/development.tasmota32-nspanel.manifest.json

**Comment by Jason2866** [comment]
The NsPanel has PSRAM not connected to standard GPIOs. So using the NSPanel with standard Tasmota32 can not activate PSRAM. The NSPanel Tasmota build uses a special Arduino version which supports the PSRAM of the  NSPanel
