### ISSUE TITLE
[Feature Request] Double click support for the physical buttons

### ISSUE THREAD

**Issue by ivdimitro** [joBr99/nspanel-lovelace-ui#273]
**Describe the solution you'd like**
Could you please provide the configuration options/template to enable the double click support for the physical buttons. 
From the reading I did it seems this is controlled by tasmota itself but I couldn't figure out what should be the combination of template options, command, siwtchOptions, etc.  
Here is the topic I can't strictly get: [multupress-switches](https://tasmota.github.io/docs/Buttons-and-Switches/#multi-press-functions) 

**Panel / Firmware Version**
Please add the Panel/Firmware Version you are using (EU)

**Comment by djasonb** [comment]
You can acheive this already using automations in home assistant. You will need to decouple the buttons as described in the guide.
![decouple buttons](https://user-images.githubusercontent.com/37401009/173065406-327b4bfe-7a3d-4068-a38c-98c6e2a99e22.PNG)
.

**Comment by joBr99** [comment]
Please see

https://github.com/joBr99/nspanel-lovelace-ui#decouple-buttons-from-controlling-power-outputs

and tasmota documentation.

#190 might provide additional context
