### ISSUE TITLE
Sensors from device to MQTT/Home Assistant [Feature Request] 

### ISSUE THREAD

**Issue by e2m32** [joBr99/nspanel-lovelace-ui#274]
**Describe the solution you'd like**
Sensors from device to pull into HA via MQTT discovery would be awesome. I see that the temperature sensors are reporting on `tele/<device_name>/SENSOR`, and button presses are reporting on ` stat/<device_name>/POWER<x>`, and it looks like there is something that may be in the works for different calls on if the buttons are pressed on different screens 🤓

> MQT: tele/nspanel_2/RESULT = {"CustomRecv":"event,buttonPress2,screensaver,bExit,1"}

**Additional context**

**Panel / Firmware Version**
US-P

**Comment by joBr99** [comment]
The backend is communicating with the firmware over the CustomSend and the RESULT channel with these messages. They are documented in the Readme of the HMI Folder. Sensor and Power are coming from tasmota and created as entities by Homeassistent's tasmota integration.

Which sensors do you mean?

**Comment by joBr99** [comment]
please clairfy this

**Comment by e2m32** [comment]
Sorry for the late reply. I forgot about the tasmota integration. I haven't added any tasmota devices since that was released. Just installed the addon and the panels popped in with their buttons and sensors. Thank you 👍

**Comment by joBr99** [comment]
perfect :)
