### ISSUE TITLE
[BUG] None in Time and Date line

### ISSUE THREAD

**Issue by salopette** [joBr99/nspanel-lovelace-ui#282]
Hi, ich habe None unter der Uhr und hinter dem Datum stehen.
Womit hängt das zusammen?

- screensaver:
      entity: weather.home
      theme: !include /config/appdaemon/apps/screensaver-theme.yaml
      autoWeather: true
      alternativeLayout: false
      doubleTapToUnlock: false
      dateFormatBabel: "full"
      statusIcon1:
          entity: switch.3d_licht
      statusIcon2:
           entity: switch.3d_licht

![sshot-2](https://user-images.githubusercontent.com/32480002/173428065-215bb792-e890-49de-a82f-d7394123b087.jpg)
![sshot-1](https://user-images.githubusercontent.com/32480002/173428073-18526e2d-4690-4660-96b5-920eca5cc934.jpg)

**Comment by joBr99** [comment]
ups, da hat was für den fix von #281 gefehlt, sollte in v3.0.4 gefixt sein

**Comment by salopette** [comment]
Jop! Danke!
Alles wieder gut!
