### ISSUE TITLE
[BUG] Sub-Page closes on Button Action

### ISSUE THREAD

**Issue by Grrzzz** [joBr99/nspanel-lovelace-ui#283]
Known bug from current release - easy fix/hack:

Add "|| subPage_open" on 2nd line:

```
function RegisterEntityWatcher(id: string): void {
    if (subscriptions.hasOwnProperty(id) || subPage_open) {
        return;
    }
    subscriptions[id] = (on({ id: id, change: 'any' }, function (data) {
        if(pageId >= 0)
            SendToPanel({ payload: GeneratePageElements(config.pages[pageId]) });
        if(pageId == -1 && config.button1Page != undefined)
            SendToPanel({ payload: GeneratePageElements(config.button1Page) });
        if(pageId == -2 && config.button2Page != undefined)
            SendToPanel({ payload: GeneratePageElements(config.button2Page) });
    }))
}
```

**Comment by Grrzzz** [comment]
Also fixed Sub-Page Navigation:

Complete Change as Diff here:
https://www.textcompare.org/javascript/?id=62a89094249201c8254bfc38

Note that example conf need to be extended for all pages as new attribute "parent" was introduced.

**Comment by Armilar** [comment]
really nice. I've just skimmed it and I think it's a very good solution. I'll do a few tests tomorrow and then put it into the script.
Do you have a complete script, including the config?

**Comment by Armilar** [comment]
I've already tested it. Really a very successful solution. I'll upload the script with the changes and close the issue
