### ISSUE TITLE
[Feature Request] add input_select entity

### ISSUE THREAD

**Issue by finipini** [joBr99/nspanel-lovelace-ui#301]
### FEATURE DESCRIPTION
Hello, I think  it would be nice to add input_select entities in the cardGrid and maybe cardEntities too.

### ADDITIONAL CONTEXT
By default it shoud show the current select option and the tap_action should be the service   `input_select.select_next`  ( would be cool to that the long_press be `input_select.select_first` but that would be secondary)

This could have a lot of uses, i can show what would be mine : 

 In Home assistant i have a card that have the rooms i would like to vacuum, and the many repeats per room, and with an input-select per room i can select 0; 1; 2; or 3 repeats and that will show a diferent icon per selection .  

![Screenshot_63](https://user-images.githubusercontent.com/49859284/174897881-a6885b10-58f2-4052-be51-be764dc484fb.jpg)

As we already have the possibility to have a diferent icon per state , just missing the option to have an input_select entity.

Could be used like this ( like in the photo )

```
     - type: cardGrid
        title: aspirar
        entities:
          - entity: input_select.aspirar_sala
            icon:
              "0": mdi:sofa
              "1": mdi:numeric-1-box
              "2": mdi:numeric-2-box
              "3": mdi:numeric-3-box
```

### PANEL / FIRMWARE VERION
I am using the nspanel EU version

**Comment by esdcmc** [comment]
I can join in for this request: the lack of input_select and input_number entities limits the capabilities of this (otherwise fantastic) UI

**Comment by joBr99** [comment]
@finipini input_select has been implemented in current dev version

@esdcmc input_number should also work (within the limitations of nextion)


https://docs.nspanel.pky.eu/faq/#how-to-upgrade-from-a-release-to-the-current-development-version

**Comment by finipini** [comment]
Ok @joBr99 i just updated and it worked, it now accpets input_select and by tapping it goes to next state....

Just an issue here , this shouldn,t work?
`          - entity: input_select.aspirar_sala
            icon:
                "0": sofa
                "1": numeric-1-box
                "2": numeric-2-box
                "3": numeric-3-box`

if i choose one static icon it works well but one per state doesn,t work. My entity has this attributes:
![Screenshot_75](https://user-images.githubusercontent.com/49859284/182041572-c971b420-37ff-4648-b522-171953ee9ecd.jpg)

**Comment by joBr99** [comment]
hey try updating, this should fix it

https://github.com/joBr99/nspanel-lovelace-ui/commit/e35436a37501dcf2fc85e06ce605530eeb3d03d3

**Comment by finipini** [comment]
> hey try updating, this should fix it
> 
> [e35436a](https://github.com/joBr99/nspanel-lovelace-ui/commit/e35436a37501dcf2fc85e06ce605530eeb3d03d3)

Yes, that fixed it, awsome.

Thanks.
