### ISSUE TITLE
[Feature Request]  - Second QR Code for URL Links

### ISSUE THREAD

**Issue by diginfo** [joBr99/nspanel-lovelace-ui#303]
### FEATURE DESCRIPTION
Add a second QR Code for url link

### ADDITIONAL CONTEXT
I realise that memory is limited and that QR codes are a memory behemoth, but It would be really helpful to be able to display a QR Code with a url link in a card to a web page.

I am preparing my house for AirBNB and the ability to have QRcodes on the panel where the guest could access more information, to me would be invaluable.

### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
What do you mean? You don't have to display an wifi qr code on that page you can use it for any qr code

**Comment by diginfo** [comment]
Oh, I thought it was hard-coded to setup wifi ?

**Comment by diginfo** [comment]
I just found this: https://en.wikipedia.org/wiki/MeCard_(QR_code)

so I am guessing that this should work:

```
"URL:https://www.johndoe.com/"
```

**Comment by diginfo** [comment]
Yes it works - excellent 

 :-)

Maybe you can add this to the documentation page ?

**Comment by joBr99** [comment]
I guess you don't even need the `URL:`
The variable just contains the text for the QR-Code. I guess it's enough to prefix it with https:// for qrcode readers to recognize it as url.
