### ISSUE TITLE
[BUG] Flicker

### ISSUE THREAD

**Issue by erugaman** [joBr99/nspanel-lovelace-ui#307]
### PROBLEM DESCRIPTION

Hi, after implementing the statusIcon1 and statusIcon2 option at the screensaver I found that there is a flicker (actually twice) , this is weird because previous to the flicker the icons appear at the desire status.

### SCREENSHOTS
I have a small video that shows the flicker: https://user-images.githubusercontent.com/54918424/175370243-3e6fd9b0-6e5a-4b8f-a2ae-e6db5bb05f44.mp4

**Comment by joBr99** [comment]
Please please provide your apps.yaml and the AppDeamon log while this happens

**Comment by erugaman** [comment]
> Please please provide your apps.yaml and the AppDeamon log while this happens
[apps.yaml.txt](https://github.com/joBr99/nspanel-lovelace-ui/files/8970155/apps.yaml.txt)

I'll attach the log later, I'm out of home at this moment...

**Comment by erugaman** [comment]
Here you have!

[AppDeamon.log.txt](https://github.com/joBr99/nspanel-lovelace-ui/files/8970382/AppDeamon.log.txt)

**Comment by joBr99** [comment]
Hey, please update your Firmware to the current development version and check if your issue is solved, changed the implementation of the refreshing of the background color on screensaver.

`FlashNextion http://nspanel.pky.eu/lui-us-p.tft`

**Comment by kambiumdt** [comment]
> Here you have!
> 
> [AppDeamon.log.txt](https://github.com/joBr99/nspanel-lovelace-ui/files/8970382/AppDeamon.log.txt)

i think that you should change the pass of your WiFi :) - thats is wissible on apps.

**Comment by joBr99** [comment]
Well in reality, using WEP is more or less the same than using no password in 2022.

**Comment by erugaman** [comment]
You're right, it is a separate guest wifi with no much bandwith in it, thanks for the advice!

**Comment by erugaman** [comment]
I've upgrade the firmware, no more flicker but now I can see two small grey squares where the icons are going to appear, is there a way to darken them?

Thanks!

**Comment by joBr99** [comment]
please add a picture

**Comment by joBr99** [comment]
nevermind, found the issue

**Comment by joBr99** [comment]
pushed a fix, update again

**Comment by erugaman** [comment]
Wow you're fast!
Now is 100%, thank!!!
