### ISSUE TITLE
[Feature Request] Add Latin Extended Additional to Font

### ISSUE THREAD

**Issue by joBr99** [joBr99/nspanel-lovelace-ui#308]

**Comment by illuzn** [comment]
![20220625_111010](https://user-images.githubusercontent.com/57167030/175753526-de04132f-5297-470d-8ee5-ce68d67cd174.jpg)

Also missing the ℃ symbol (which strangely used to be present)... From older dev firmware:

![20220522_202155](https://user-images.githubusercontent.com/57167030/175753590-9650feb3-2a76-4e13-ba40-bc581fb4a15e.jpg)

Thanks for your hard work

**Comment by joBr99** [comment]
Do you need the ℃ Char? Just tested °C as two seperate Chars which works toally fine

**Comment by joBr99** [comment]
on a closer look it turns out that the Combining Diacritical Marks Block is missing
https://www.compart.com/en/unicode/block/U+0300

I've just added it to the font, please give it a try.
