### ISSUE TITLE
[Feature Request] [iobroker] Seperation of code

### ISSUE THREAD

**Issue by Grrzzz** [joBr99/nspanel-lovelace-ui#309]
### FEATURE DESCRIPTION
Currently, we have 3 files in iobroker:

1. [icon_mapping.ts](https://github.com/joBr99/nspanel-lovelace-ui/blob/main/ioBroker/icon_mapping.ts)
2. [NsPanelTs.ts](https://github.com/joBr99/nspanel-lovelace-ui/blob/main/ioBroker/NsPanelTs.ts)
3. [ioBroker_NSPanel_locales.json](https://github.com/joBr99/nspanel-lovelace-ui/blob/main/ioBroker/ioBroker_NSPanel_locales.json)

File 1 placed in global directory (can be "resused")
File 3 downloaded on the fly (this should also be changed to a global file in my opionion, as you cannot take internet access for granted; different story...)

File 2 being the main issue with **BOTH** a custom **configuration** and the **main code**.

So:
Please seperate nsPanelTs.ts in (at least) two files, being:

1. nsPanelTs.ts as global script / object placed in global script directory just as icon_mapping.ts
2. nsPanelTsCustom.ts in "local" script folder, only including page description and "Config" object.

By doing this, you can call the main script as a reference when using more than one panel with different configurations.

### ADDITIONAL CONTEXT
Updating is a pain in the a##. given that you have more than one panel.

Also, it gets really hard if you want to place custom code in "your" base code (cannot extend the object easily), e.g. if you want button1 and button2 to trigger custom routines.

Also, the separation will make updates much easier, as well as community input.

### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
has been discussed many times; there should be an adapter for ioBroker, which takes time, but I don't think that we have to keep an issue for this
