### ISSUE TITLE
Stuck in "Waiting for content"

### ISSUE THREAD

**Issue by Gitrowsky** [joBr99/nspanel-lovelace-ui#31]
Hi Johannes,

i am stuck in the "Waiting for content" loading animation.
Both, nspanel and appdeamon are connected to the broker

core_mosquitto log

> 1647034017: New client connected from 192.168.0.85 as DVES_7DECA4 (p2, c1, k30, u'tasmota').
> ...
> 1647034738: New client connected from 172.30.32.1 as appdaemon (p2, c1, k60, u'tasmota').

apps.yaml

> nspanel-1:
>   module: nspanel-lovelance-ui
>   class: NsPanelLovelanceUIManager
>   config:
>     panelRecvTopic: "tele/tasmota_nspkueche/RESULT"
>     panelSendTopic: "cmnd/tasmota_nspkueche/CustomSend"

tasmota mqtt config

> topic: tasmota_nspkueche
> full topic: %prefix%/%topic%/

I can "see" appdaemon sending a time payload every minute on cmnd/tasmota_nspkueche/CustomSend
> Nachricht 0 empfangen auf cmnd/tasmota_nspkueche/CustomSend um 23:00:
> time,23:00
> QoS: 0 - Retain: false

I am currently really helpless. Do you have an idea what could be wrong?

Edit: used of quotes for better readability

**Comment by joBr99** [comment]
nspanel is also sending something on a regular base in the loading screen (which you should see in tasmota log)

![image](https://user-images.githubusercontent.com/29555657/157980085-0d277d93-26da-43c8-b2a9-369c4fe93ba1.png)

How does your tasmota log look like and do you see thoose messages on your mqtt?

**Comment by Gitrowsky** [comment]
This could be a point.
> 23:24:10.316 MQT: tele/tasmota_nspkueche/STATE = {"Time":"2022-03-11T23:24:10","Uptime":"0T00:45:17","UptimeSec":2717,"Heap":161,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Berry":{"HeapUsed":3,"Objects":49},"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"xxxxx","BSSId":"1C:ED:6F:5F:A2:15","Channel":6,"Mode":"11n","RSSI":96,"Signal":-52,"LinkCount":1,"Downtime":"0T00:00:06"}}
> 23:24:10.338 MQT: tele/tasmota_nspkueche/SENSOR = {"Time":"2022-03-11T23:24:10","ANALOG":{"Temperature1":0.2},"ESP32":{"Temperature":60.0},"TempUnit":"C"}
> 23:24:59.933 MQT: stat/tasmota_nspkueche/RESULT = {"Command":"Unknown"}
> 23:26:00.112 MQT: stat/tasmota_nspkueche/RESULT = {"Command":"Unknown"}

this messages are repeating

**Comment by joBr99** [comment]
indeed, witch tasmota berry driver do you have installed?

The CustomSend command is defined in the last line

**Comment by Gitrowsky** [comment]
I checked and overwrite it with your current version. The were no differences in the files. 
What could be important: I had problems while flashing the nextion panel. I chunked the firmware and loaded it. Running on Program Version | 10.1.0(tasmota)

**Comment by joBr99** [comment]
chunked?

For flashing related issue, make sure to use the [tasmota32-nspanel.bin](https://github.com/tasmota/install/raw/main/firmware/unofficial/tasmota32-nspanel.bin) tasmota build.

Please update to the current tasmota version/this build and also check tasmota berry console on loading issues of the driver.

You should also be able to send commands on tasmota console like this `CustomSend wake`

**Comment by Gitrowsky** [comment]
My fault was to use the standard tasmota32. I got rid of the loading screen. Now I got a flickering. I can only see the content for a very short time while tipping the panel.

**Comment by joBr99** [comment]
Do you have the most recent display firmware flashed and the lastest appdeamon app installed?

**Comment by Gitrowsky** [comment]
I updates the appdeamon app about an hour ago. But the display firmware was yesterday's version. It is working now. Thank you so much!

**Comment by joBr99** [comment]
This makes total sense, I changed the behaviour of the timout/sleep stuff a few hours ago. With this combination your timeout for the screensaver was set to 20ms instead of 20 seconds :)
