### ISSUE TITLE
[BUG] bizarre artifacts

### ISSUE THREAD

**Issue by illuzn** [joBr99/nspanel-lovelace-ui#310]
### PROBLEM DESCRIPTION
Some bizarre artifacts are showing up for me on popupShutter, entitiespage

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide your apps.yaml:
```
Not applicable

```
- [x] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log during your issue/bug occurs:
```
Not applicable
```

### TO REPRODUCE
Have popupShutter page or entitiespage with unconfigured entries

### EXPECTED BEHAVIOUR
No artifacts

### SCREENSHOTS
![20220625_110932](https://user-images.githubusercontent.com/57167030/175753722-18b27485-130c-4613-a03d-3228fbb53240.jpg)
![20220625_110922](https://user-images.githubusercontent.com/57167030/175753727-fb0c7314-7161-4140-93d5-62fec6335560.jpg)

### ADDITIONAL CONTEXT
This creeped in in the last week. One of the dev versions but I'm not sure which hmi firmware caused this. 

### PANEL / FIRMWARE VERION
US-P

**Comment by joBr99** [comment]
You are using the dev version, that are features not yet fully implemented.

**Comment by illuzn** [comment]
Can't wait to see what's coming

**Comment by joBr99** [comment]
The buttons/text on the cover detail page are buttons for the tilt position.
