### ISSUE TITLE
[BUG] Fan Slider is not working correctly

### ISSUE THREAD

**Issue by hatran0884** [joBr99/nspanel-lovelace-ui#313]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
i have a ceiling fan controlled by a Broadlink HF remote, it has 6 speeds corresponding to 6 percentages: 16 33 50 66 83 and 100% (percentage step of 16.6) based on the document of fan template. but when i put it onto NSpanel as an entity, the fan slider is not working like on HASS. the fan slider moves from 0 all the way to 100, it is not moving based on percentage step of 16,6. so it would be very hard to move the slider which is very small to the correct values. so do you have any way to solve this issue ? 

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml:
```
  apps.yaml here:
      - type: cardEntities
        entities:
          - entity: cover.curtain_1
            name: Rèm 1
          - entity: cover.curtain_2
            name: Rèm 2
          - entity: fan.ceiling_fan
          - entity: delete
        title: Rèm/Quạt

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
2022-06-26 23:21:40.768467 INFO xnspanel: Button Press Event; entity_id: fan.ceiling_fan; button_type: number-set; value: 100
--
2022-06-26 23:21:40.764560 INFO xnspanel: Received Message from Screen: event,buttonPress2,fan.ceiling_fan,number-set,100
2022-06-26 23:21:40.759837 INFO xnspanel: MQTT callback for: {'topic': 'tele/nspanel/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,fan.ceiling_fan,number-set,100"}'}
2022-06-26 23:21:38.758875 INFO xnspanel: Button Press Event; entity_id: fan.ceiling_fan; button_type: number-set; value: 63
2022-06-26 23:21:38.755135 INFO xnspanel: Received Message from Screen: event,buttonPress2,fan.ceiling_fan,number-set,63
2022-06-26 23:21:38.751459 INFO xnspanel: MQTT callback for: {'topic': 'tele/nspanel/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,fan.ceiling_fan,number-set,63"}'}
2022-06-26 23:21:32.740956 INFO xnspanel: Button Press Event; entity_id: fan.ceiling_fan; button_type: number-set; value: 0
2022-06-26 23:21:32.737240 INFO xnspanel: Received Message from Screen: event,buttonPress2,fan.ceiling_fan,number-set,0

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
the fan slider will move based on percentage step of 16,6 or whatever getting from HASS. 

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._
![Ảnh chụp màn hình 2022-06-26 231424](https://user-images.githubusercontent.com/58875735/175824255-c815edef-ada0-4ec3-b280-276c891b6b78.png)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
US-L

**Comment by joBr99** [comment]
I don't have a fan to test with, so no clue how it behaves on Homeassistent UI, but there is no way to make the slider sticky around the 16, 33, 50 values, maybe it's possible to change the value range of the slider on nspannel to 1-6 and then scale it back and forth in the backend. I will try this approach and let you know once it's implemented.

**Comment by hatran0884** [comment]
yes, i think it should be fixed because there is no fan having the speed changing from 0 all the way 100. the speeds of a fan normally are 3 to 6.

**Comment by markuserlacher** [comment]
it would be better have 4 buttons instead of a slider.  The for buttons are OFF (0%), LOW (33%), MED (66%) and HIGH (100%) as most fan controller like iFan3/3 from sonoff only have 4 relais..

**Comment by joBr99** [comment]
I'm going to change the implemention of fans on the cardEntity Page to a switch with a detail page in the next release

![image](https://user-images.githubusercontent.com/29555657/176272974-3251c0e7-8f86-4a0f-9764-533f4c509b07.png)

I will close this issue in favour of #326

**Comment by hatran0884** [comment]
> @hatran0884
> 
> What happens if you are setting the percentage to an arbitrary value between the percentages?
> 
> ![image](https://user-images.githubusercontent.com/29555657/176233676-5fd56ad7-5324-4545-9312-680c525af6f7.png)

I have just tested and it behaves exactly the same way as NSPanel now, meaning, if i set a random speed, the fan will not work, and it only works if i set the exact speed that already set based on percentage step of 16.6
