### ISSUE TITLE
[Feature Request] Pincode on Screensaver 

### ISSUE THREAD

**Issue by strato345** [joBr99/nspanel-lovelace-ui#318]
### FEATURE DESCRIPTION

Is it possible to protect the screen with a pincode maybe also in the future ?

Could you show a stream from a surveillance camera?

### PANEL / FIRMWARE VERION

I am using the nspanel EU version

**Comment by illuzn** [comment]
> Could you show a stream from a surveillance camera?
No, this is impossible - the hardware doesn't support it.

**Comment by joBr99** [comment]
closing this in favour of #449, since 449 is more general also covers this feature
