### ISSUE TITLE
[Feature Request] - adding groups-functionality

### ISSUE THREAD

**Issue by sn00zerman** [joBr99/nspanel-lovelace-ui#319]
### FEATURE DESCRIPTION
_Can you please add groups-functionality ?
I have several groups with multiple devices in it, and for now, I need to create "scenes" to control this multiple devices at once.
So, instead of having one button, I always have 2 buttons: one for turning all those devices on, and one for turning all those devices off. When I would be able to use "groups", only one button will do, to turn a group of devices on or off.
._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_EU / 1.8.3_

**Comment by joBr99** [comment]
Why are you not using the groups feature of homeassistant?

https://www.home-assistant.io/integrations/group/

**Comment by sn00zerman** [comment]
I'm using groups for a long time already in Home Assistant, but when I try to add these in the NSPanel, I'm getting a "not supported", instead of a clickable icon ?

**Comment by sn00zerman** [comment]
I'm using groups for a long time already in Home Assistant, but when I try to add these in the NSPanel, I'm getting a "not supported", instead of a clickable icon ....

I re-created my groups, and now it works fine :-) thank you !

**Comment by sn00zerman** [comment]
I'm using groups for a long time already in Home Assistant, but when I try to add these in the NSPanel, I'm getting a "not supported", instead of a clickable icon ....

I re-created my groups, and now it works fine :-) thank you !

**Comment by Jeoffreybauvin** [comment]
Same issue here.

**Comment by joBr99** [comment]
groups are working perfectly fine; you just need to use the newer groups instead of the old style groups

https://www.home-assistant.io/integrations/group/
