### ISSUE TITLE
Error on autoexec.be loading

### ISSUE THREAD

**Issue by kinselp** [joBr99/nspanel-lovelace-ui#320]
hi, great project but am getting the followign error when trying to get to the point of flashign the nextion unit

00:00:00.168 BRY: Berry initialized, RAM used=3731 bytes
00:00:00.190 Project tasmota - Tasmota Version 12.0.2.2(nspanel)-2_0_3(2022-06-27T19:45:09)
00:00:00.265 BRY: failed to load '/autoexec.be' (syntax_error - /autoexec.be:8: unexpected symbol near '<')

can anyone help?

**Comment by joBr99** [comment]
you need to copy the content of this file, there is no < in line 8 so, most likely you did copy something different into the berry script

https://raw.githubusercontent.com/joBr99/nspanel-lovelace-ui/main/tasmota/autoexec.be
