### ISSUE TITLE
[Feature Request] Show the Status of Hardware Button on Screen

### ISSUE THREAD

**Issue by markuserlacher** [joBr99/nspanel-lovelace-ui#324]
### FEATURE DESCRIPTION
It would be great to see the active Status of the Hardware Switches on Screen.

### ADDITIONAL CONTEXT
Looking like this:

![default_off](https://user-images.githubusercontent.com/38162885/176206677-6aa92d21-c41d-46fa-9dc4-b7701a4ce3a4.jpg)

![default_on](https://user-images.githubusercontent.com/38162885/176206738-3efdb4cd-539c-4309-9ece-831766fc9845.jpg)

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
use statusIcon1&2 for this, there is config example on the end of the page

https://docs.nspanel.pky.eu/config-screensaver/#possible-configuration-values-for-screensaver-theme-config

**Comment by markuserlacher** [comment]
Thank you for the tip... good hidden secret...
