### ISSUE TITLE
[Feature Request] Own Entity Type for Fan

### ISSUE THREAD

**Issue by markuserlacher** [joBr99/nspanel-lovelace-ui#325]
### FEATURE DESCRIPTION
If we add a Fan as Entity to the Card a simple Slider is showing.

As most fan anyway only have 3 or max 4 speeds it would be great to have Buttons with fix percentages set to each button:
![image](https://user-images.githubusercontent.com/38162885/176222617-564d2092-bb73-48b4-a4be-8ebbf32f1213.png)

OFF = 0%
LOW = 33%
MED = 66%
HIGH = 100%

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
US_L

**Comment by joBr99** [comment]
@jmbinette are you planning to add back the 6th entity row in US-P Firmware at some point in the future?

**Comment by jmbinette** [comment]
I don't think so, 5 seems like enough and 6 too compact !

**Comment by joBr99** [comment]
I'm going to change the implemention of fans on the cardEntity Page to a switch with a detail page in the next release

![image](https://user-images.githubusercontent.com/29555657/176272974-3251c0e7-8f86-4a0f-9764-533f4c509b07.png)

I will close this issue in favour of #326
