### ISSUE TITLE
[Feature Request] Redesign Fan on entityPage and add detail Page

### ISSUE THREAD

**Issue by joBr99** [joBr99/nspanel-lovelace-ui#326]
![image](https://user-images.githubusercontent.com/29555657/176273156-4491b536-fe2e-40be-a621-8ed6d4f9bcae.png)

**Comment by hatran0884** [comment]
For me, configuring the fan entity as a slider is fine, i can slide it all the way to 0 to turn it off and rather convenient to control right from the entity page. I only wish the slider is bigger for easy of selecting fan speed. Designing another detailed page of fan will mean another step to be able to control the fan. 
but, i am okay with a fan entity as a switch, my fan can turn on and off like a switch in HA. So up to you

**Comment by erugaman** [comment]
This is my last modification to my fan and cardEntities, it’s much of what you pretend to do

![7632202F-0E69-461C-B96B-3BD840B81CDE](https://user-images.githubusercontent.com/54918424/176461530-268aac7e-5efb-4d8e-a01c-171e8d53cb4e.jpeg)

**Comment by joBr99** [comment]
Hmm, I will have a look if I can make it configureable.

**Comment by joBr99** [comment]
added detail page for fans, presets are not implemented in current version

slider still feels bad on nextion, because it doesn't snap to the steps, but this is a nextion limitation
