### ISSUE TITLE
unable to Flash nextion screen due to - Berry: Failing to load autoexec.be [BUG] 

### ISSUE THREAD

**Issue by kinselp** [joBr99/nspanel-lovelace-ui#328]
### PROBLEM DESCRIPTION
Unable to flash nextion screen, as the berry driver seems to be failing during loading (syntax error)

### REQUESTED INFORMATION

this isnt a yaml issue - seems to be tasmota related or autoexec.be

- [x ] Provide your apps.yaml:
```
  apps.yaml here: -


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
```

this isnt a AppDaemon issue - seems to be tasmota related or autoexec.be

### TO REPRODUCE
have tried legacy autoexec.be but no success

### EXPECTED BEHAVIOUR
autoexec.be needs to be loading otherwise cannot flash nextion screen

### SCREENSHOTS

00:00:00.387 BRY: Berry initialized, RAM used=3731 bytes
00:00:00.416 Project tasmota - Tasmota Version 12.0.2.2(nspanel)-2_0_3(2022-06-27T19:45:09)
00:00:00.725 BRY: failed to load '/autoexec.be' (syntax_error - /autoexec.be:8: unexpected symbol near '<')

### ADDITIONAL CONTEXT
Panel seems to run fine with the tasmota / blackadder packages, just not with the autoexec.be for Lovelace UI

### PANEL / FIRMWARE VERION
US-L

**Comment by joBr99** [comment]
> 00:00:00.725 BRY: failed to load '/autoexec.be' (syntax_error - /autoexec.be:8: unexpected symbol near '<')

There is no < in line 8, are you sure that you've copied the right content?

https://raw.githubusercontent.com/joBr99/nspanel-lovelace-ui/main/tasmota/autoexec.be


Sounds like you have copied the html source of the github page

![image](https://user-images.githubusercontent.com/29555657/176306615-7cd4b0a0-cb0e-4252-8ce2-d4d2f1fca906.png)

**Comment by kinselp** [comment]
@joBr99 so sorry mate, I'm a complete moron.  Just created the file again and all good.

apologies and thank you for all the hard work on this
