### ISSUE TITLE
[Feature Request] Change the page displayed on the screen programmatically

### ISSUE THREAD

**Issue by spike886** [joBr99/nspanel-lovelace-ui#331]
### FEATURE DESCRIPTION
It would be nice to be able to manage the current page displayed on the screen. Also, I am not sure if this is possible today, it would be nice to navigate to the expanded page on an entity.
I think this could be done by sending a command to the screen (specially useful if you have esphome)

### ADDITIONAL CONTEXT
I would love to be able to click on the physical button of the nsPanel (it will switch the light on) and automatically show on the screen the card for that entity.

### PANEL / FIRMWARE VERION
I have the v3.1.1 US-P and I have it working with esphome

**Comment by joBr99** [comment]
see #224 and #190 

you can completly remote control the panel with mqtt messages

to navigate to pages, send the payload for a navigate button press to the result topic

for detail pages you can send the pageType command to the customsend topic
