### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by 0St0n30** [joBr99/nspanel-lovelace-ui#339]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._

Hello, is there any posibility of adding a diagram? Like Power Usage etc? That would be very nice in case you use your SmartMeter and/or using photovoltaic.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

Im new to things like this in Home Automation, so any Info would be appreciated.

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

EU

**Comment by joBr99** [comment]
> Hello, is there any posibility of adding a diagram? Like Power Usage etc? That would be very nice in case you use your SmartMeter and/or using photovoltaic.

There is an waveform component in nextoin, but it looks awful, so I' not planning to implement this.

![image](https://user-images.githubusercontent.com/29555657/177626061-8fbd40ad-16c5-482b-bde0-acce4e4518aa.png)
