### ISSUE TITLE
Improve Flashing in Berry Driver

### ISSUE THREAD

**Issue by kris2k2** [joBr99/nspanel-lovelace-ui#34]
Simply FYI;  the Nextion Flash process isn't robust against bricked/incomplete-flashed displays.

I managed to fix the issue using this library: 
https://github.com/peepshow-21/ns-flash/blob/master/berry/nxpanel.be

**Comment by joBr99** [comment]
mikey put way more energy into implementing flashing and he's using a complely differnet approach to get around the limitations of esp32, I might have to see what I can improve on my flashing process

but in general, rebooting the tasmota should bring the display in the state where it show's "System Data Error" or something like this, in this stage it should be possible to just restart the flashing

**Comment by kris2k2** [comment]
Confirming that I was able to flash using your Berry methods after restart and submitting the Nextion Flash command twice.

**Comment by joBr99** [comment]
try this version, I didn't not do much testing with it so far

https://github.com/joBr99/nspanel-lovelace-ui/blob/main/tasmota/autoexec-beta.be

**Comment by joBr99** [comment]
solved with the newest release, default berry driver is now the modified version from @peepshow-21
