### ISSUE TITLE
[Feature Request] Update MDI Icons

### ISSUE THREAD

**Issue by illuzn** [joBr99/nspanel-lovelace-ui#341]
### FEATURE DESCRIPTION
Update MDI Icons to v 6.9.96

### ADDITIONAL CONTEXT
[This mirrors HA 2022.7](https://www.home-assistant.io/blog/2022/07/06/release-20227/#other-noteworthy-changes)

This is merely a reminder... obviously low on the priority scale.

### PANEL / FIRMWARE VERION
Not Applicable

**Comment by joBr99** [comment]
The Nextion Font I'm generating is based on this Font, which didn't get any updates for the last 6 Month, we will have to wait for an updated version of the font.

https://github.com/Templarian/MaterialDesign-Font
