### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by dzidzior** [joBr99/nspanel-lovelace-ui#343]
### PROBLEM DESCRIPTION
Cannot find the repository in HACS. When trying to manually add custom repo, the HACS reports error:
"<Plugin joBr99/nspanel-lovelace-ui> Repository structure for v3.1.1 is not compliant"

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml:
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
Search for "NSPanel" repository in HACS when trying to add it.

**Comment by joBr99** [comment]
https://docs.nspanel.pky.eu/prepare_ha/#installing-lovelace-appdaemon-backend-application

Click on Configuration on the left menu bar in Home Assistant Web UI
Select Devices & Services
Select Integrations
Find HACS and click on Configure
In the window that opens, make sure that Enable AppDaemon apps discovery & tracking is checked, or check it and click Submit

You have to enable appdaemon Apps in HACS, as noted in the installation docs.
