### ISSUE TITLE
Wrong font number in Nextion firmware 

### ISSUE THREAD

**Issue by Bootsik2** [joBr99/nspanel-lovelace-ui#346]
In "us-l" Nextion firmware font number "1" is selected in some text fields, but should be "2". Because of this, localization does not work in the following lines:
Screensaver card: tDate
Entities card: tHeading
Perhaps moreover there are text fields with this error , I did not check everything.

**Comment by joBr99** [comment]
cosing this, next release will require to create us-l version from scratch/eu, so this will be included
