### ISSUE TITLE
autoexec.be ... load error

### ISSUE THREAD

**Issue by pploume** [joBr99/nspanel-lovelace-ui#349]
Hi,

download "autoexec.be" from your repo.
Error when loading (at reboot / manually form BConsole)
_BRY: Exception> 'syntax_error' - autoexec.be:234: 'tcpclient' undeclared (first use in this function)
stack traceback:
	<native>: in native function
	<unknown source>: in function `load`
	<unknown source>: in function `load`
	<unknown source>: in function 'main'_

I read from another post something like "Make sure your Tasmota is latest version with the tcpclient bug fix" ...
The Tasmota (tasmota32-nspanel.bin) -downloaded from "https://docs.nspanel.pky.eu/prepare_nspanel/" is
version 10.0.0.1 
Build Date & Time	2021-10-30T23:37:21
Core/SDK Version	2_0_1_rc/v4.4-dev-3558-gbb80dbca6

How to ensure it's bug fixed (or not ...), and where to download the good version of the tasmota-nspanel.bin ?
For what I understand, this Tasmota version is old ... before last chrismas.

thanks for your help ...
and btw, where are you today ? california, germany or somewhere else ?
:)

**Comment by joBr99** [comment]
Update your tasmota to the latest release, the link in the readme pointed to the latest development version (newest you can get), but this is no longer needed, so I just changed it to the lastest release.

Just update your tasmota to the latest release preferable the nspanel version (but it should also work with the normal version)
http://ota.tasmota.com/tasmota32/release/


I'm living in germany.

**Comment by pploume** [comment]
I Will try that and let you Know.
Thanks.
P

**Comment by pploume** [comment]
Hi,

Tasmota console shows :
20:14:35.966 RSL: RESULT = {"Flashing":{"complete": 99, "time_elapsed":
318}}
20:14:44.161 RSL: RESULT = {"CustomRecv":"event,startup,38,eu"}
20:14:44.167 NXP: Screen Initialized
20:14:49.957 RSL: RESULT = {"CustomRecv":"event,startup,38,eu"}
...
20:22:10.781 RSL: RESULT = {"CustomRecv":"event,startup,38,eu"}
(12 minutes ...)

NSPanel screen display :
witing for content
this is taking longer than usual
please chek your backend configuration


Any idea ?

**Comment by joBr99** [comment]
check this:
https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

if it doesn't work after checking this, open an issue for it and fill out the template
