### ISSUE TITLE
[Feature Request] Now Playing on Screensaver

### ISSUE THREAD

**Issue by scoobydoofus** [joBr99/nspanel-lovelace-ui#353]
### FEATURE DESCRIPTION
I don't really care about the weather info on the screensaver, but I would like to see what's currently playing on my speakers without tapping in through different screens. Would it be possible to replace the weather with maybe a music note icon and then the now playing info eg track name on one line and artist on the next line?

### ADDITIONAL CONTEXT
Perhaps this could be conditional, show the weather if nothing is playing. It might also be useful to still allow one or two sensor entities to be displayed as well, if possible. Not sure if there's enough space for that.

### PANEL / FIRMWARE VERION
NSPanel EU

**Comment by joBr99** [comment]
Hey you can configure an addional line below the time that will be update with the time.

```
timeAdditionalTemplate: " Playing: {{ state_attr('media_player.spotify_xxx', 'media_title') if is_state('media_player.spotify_xxx', 'playing') }} "
```

**Comment by scoobydoofus** [comment]
Thanks, I managed to find that line in config.py and it works, but it doesn't look great in that spot, in my opinion. And I'd really want the artist to show up as well and there's not much room on a single line, really. I'll stick with the weather forecast for now!

**Comment by joBr99** [comment]
You can display notifications instead of the weather on the screensaver, but you will need to build an HA Automation or a NodeRed Flow for this.

https://docs.nspanel.pky.eu/notifications/#seperate-page

![image](https://user-images.githubusercontent.com/29555657/179262063-1bf9e842-f0f8-48d0-b9cd-b69c52dfccf0.png)
