### ISSUE TITLE
[Feature Request]  Better shutters graphics , date change in other languages actual temperature

### ISSUE THREAD

**Issue by MattiaFontanaErrepinet** [joBr99/nspanel-lovelace-ui#354]
### FEATURE DESCRIPTION
Better shutters graphics for example only button for go UP and Down and date change in other languages for screen saver because show only on english. And if possibile to see actual temperature from original sensor or other sensor

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
I'm using US Landscape

**Comment by joBr99** [comment]
> Better shutters graphics for example only button for go UP and Down
I'm working on this and it already works on the detail page in current development version #240

> and date change in other languages for screen saver because show only on english. 

Just install babel
https://docs.nspanel.pky.eu/prepare_ha/?h=babel#add-babel-package-to-appdaemon-container-optional

> And if possibile to see actual temperature from original sensor or other sensor

temperate sensors are available though the tasmota integration in homeassistant, you can use and display them as any other sensors
