### ISSUE TITLE
[Feature Request] Icon Color, customIcon, cardGrid

### ISSUE THREAD

**Issue by MattiaFontanaErrepinet** [joBr99/nspanel-lovelace-ui#355]
### FEATURE DESCRIPTION
Hi this is possible to make?
Possibility to change the color of the customIcon (if it is really possible to change it according to the value type for example on/off)
Possibility to show one value in the customIcon (for example indoor temperature)
Possibility to show custom icon base of value of sensor (for example climate Heat,Cool,Dry etc)

### PANEL / FIRMWARE VERION
Latest firmware NSPanel US Landscape

**Comment by joBr99** [comment]
Please check the documentation before opening issues.

Overwrite Icons:
https://docs.nspanel.pky.eu/entities/#override-icons-or-names

Overwrite color with color config key:
https://docs.nspanel.pky.eu/entities/#possible-configuration-values-for-entities-key

Open Issue for overwriting color based on state:
https://github.com/joBr99/nspanel-lovelace-ui/issues/295

Displaying Sensor value as icon is only possible on cardGrid

**Comment by MattiaFontanaErrepinet** [comment]
I have tried to show icon base of value on cardGrid but not working

**Comment by joBr99** [comment]
cardGrid automatically shows the Sensor value on the icon position, no need to configure anything

**Comment by MattiaFontanaErrepinet** [comment]
I want show icon base of value. For example if value is cool i want show snowflake

**Comment by joBr99** [comment]
You can do binary_sensors and show different icons based on the state, but with sensors it's not possible.
