### ISSUE TITLE
status icons only appear when it is in ON state

### ISSUE THREAD

**Issue by hatran0884** [joBr99/nspanel-lovelace-ui#363]
Hi 

is it possible if the status icons (Switches) will only appear when it is in ON state and disappear when in OFF state? it would find it more convenient and easier to be recognized than the current way of leaving the icons on top of screensaver all the time.

it is similar to a status bar on iphone, mac os or android phone where the status icons will only appear when a mess or an event occurs.

**Comment by joBr99** [comment]
yes, just configure an icon overwrite with the off icon as an empty text
