### ISSUE TITLE
[Feature Request] status icons only appear when in ON states

### ISSUE THREAD

**Issue by hatran0884** [joBr99/nspanel-lovelace-ui#364]
### FEATURE DESCRIPTION
Hi

is it possible if the status icons (Switches) will only appear when it is in ON state and disappear when in OFF state? it would find it more convenient and easier to be recognized than the current way of leaving the icons on top of screensaver all the time.

it is similar to a status bar on iphone, mac os or android phone where the status icons will only appear when a mess or an event occurs.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
US-L

**Comment by joBr99** [comment]
yes, just configure an icon overwrite with the off icon as an empty text

https://docs.nspanel.pky.eu/entities/#override-icons-or-names

            icon:
                "on": mdi:lightbulb
                "off": text:

**Comment by hatran0884** [comment]
no, it does not work this way, here is what i configured: 

    screensaver:
      entity: weather.home
      statusIcon1: 
         entity: switch.bedroom_water_boiler
         icon: 
             "on": water-boiler-alert
             "off": text:

but the screen hangs

so i wonder whether it is only available in developing version ?

**Comment by hatran0884** [comment]
Yes, it works now. Thank you
