### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by jjwork** [joBr99/nspanel-lovelace-ui#367]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide a screenshot of your tasmota mqtt configuration:
![Tasmota MQTT of Panel](https://user-images.githubusercontent.com/5220788/180600388-d4b2ecae-a329-4625-bae9-ecf263d6e6a5.jpg)

- [ ] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:

[appdaemon yaml.txt](https://github.com/joBr99/nspanel-lovelace-ui/files/9173507/appdaemon.yaml.txt)

```

- [ ] Provide your apps.yaml:
```
  apps.yaml here:
[apps yaml.txt](https://github.com/joBr99/nspanel-lovelace-ui/files/9173508/apps.yaml.txt)


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:

[appdaemon log.txt](https://github.com/joBr99/nspanel-lovelace-ui/files/9173509/appdaemon.log.txt)

```

**Comment by joBr99** [comment]
Hey, 
I don't see any obvious config erros.

```
aiohttp.client_exceptions.ClientResponseError: 502, message='Bad Gateway', url=URL('http://supervisor/core/api/services')
2022-07-23 11:49:09.211153 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-07-23 11:49:09.235223 WARNING AppDaemon: Excessive time spent in utility loop: 2228.0ms, 2228.0ms in check_app_updates(), 0.0ms in other
2022-07-23 11:49:19.424809 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-07-23 11:49:26.177240 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-07-23 11:49:31.206242 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-07-23 11:49:36.235932 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-07-23 11:49:42.658259 INFO HASS: Connected to Home Assistant 2022.7.6
```

Your connection from AppDaemon to HomeAssistant doesn't seem to be stable, which is a litte bit strange.

```
AttributeError: 'NoneType' object has no attribute 'mqtt_publish'
```

There is something wrong with MQTT, sadly the MQTT Plugin Inizialisation is missing in your logfile. You should see this in the log right after restarting AppDaemon, the log of your MQTT Broker might also be helpful.

**Comment by jjwork** [comment]
Thank you for the pointers !!!  

I will go and investigate !!!!

**Comment by jjwork** [comment]
Got it working .. I am using docker on Windows and needed to do this step as you rightfully pointed out .. re the Tokens !

Thank you so much for your help !

https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html#hass-authentication
