### ISSUE TITLE
[Feature Request] Open RGB color choose on cardGrid

### ISSUE THREAD

**Issue by KotMorderca** [joBr99/nspanel-lovelace-ui#368]
### FEATURE DESCRIPTION
It would be nice to be able to set the color of RGB light not only from cardEntities but also from cardGrid

### ADDITIONAL CONTEXT
Nothing to add

### PANEL / FIRMWARE VERION
v3.1.1 Panel EU

**Comment by joBr99** [comment]
just doa long click/press on the icon
