### ISSUE TITLE
[Feature Request] Be able to run automation form panel

### ISSUE THREAD

**Issue by KotMorderca** [joBr99/nspanel-lovelace-ui#369]
### FEATURE DESCRIPTION
Currently there is only option to turn on/off automation. It would be great to also has an option to run it.

### ADDITIONAL CONTEXT
Nothing to add

### PANEL / FIRMWARE VERION
v3.1.1 Panel EU

**Comment by iaah05** [comment]
I can call scripts from the buttons on NSPanel, so could you create a script that then ran an automation?

**Comment by bdonnell** [comment]
Create a helper button, trigger the automation on the helper button, put the helper button on the NSPanel.  Boom, NSPanel button to run automation.

**Comment by joBr99** [comment]
I guess createing a helper button is the way to GUI, this works on the panel and on the UI.

With #253 there will be a way to call services directly, so you can also configure a button directly calling the run service.
