### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by sn00zerman** [joBr99/nspanel-lovelace-ui#370]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._
Make physical button state visible on screensaver screen.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
Hello,

I'm looking for a way, to have an indication of the state of the 2 physical buttons, on the screensaver screen.
(like with the original firmware => there are 2 small lines at the bottom of the screen, that are used as an indicator)
Those indications may be shown left and right, next to the clock or date.
I know there is an option to have extra icons on the screensaver, but I don't know how to couple these with the physical button state ...

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU, latest firmware version

**Comment by joBr99** [comment]
Hey, 
you need to have the tasmota integration on homeassistant installed, with this integration you the the two relays from tasmota will appear in your homeassistant. You can use as any other switch in apps.yaml


    screensaver:
        statusIcon1:
          entity: switch.switch1_from_tasmota
        statusIcon2:
          entity: switch.switch2_from_tasmota
