### ISSUE TITLE
[Feature Request] allow 4 characters only for MQTT

### ISSUE THREAD

**Issue by thundergreen** [joBr99/nspanel-lovelace-ui#372]
### FEATURE DESCRIPTION
_I have my MQTT server configured with a only 4 character password and the MQTT settings want 5. Problem here: some devices are flashed and I cannot change the password as it is hardcoded in the flash :( possible to allow only 4 characters for this please. If not I will have a bunch of devices to reflash ._

### ADDITIONAL CONTEXT
_nothing_

### PANEL / FIRMWARE VERION
_ Panel/Firmware VersionEU_

**Comment by joBr99** [comment]
this is the wrong repo for this issue

mqtt is configured in appdaemon and tasmota
https://github.com/AppDaemon/appdaemon
https://github.com/arendst/Tasmota


but in general, just create a second user on your mqtt broker
