### ISSUE TITLE
[Feature Request] Set sleepbrightness to 0 via mqtt

### ISSUE THREAD

**Issue by oastBloke** [joBr99/nspanel-lovelace-ui#374]
### FEATURE DESCRIPTION
It would be great to be able to set sleepbrightness to 0 via an mqtt message or link it to the state of a home assistant sensor

### ADDITIONAL CONTEXT
The room the panel is in has presence detection so it would be nice to turn the display off when there’s no one in the room

### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
Hey, take a look at the sleepTracking option in the docs.

https://docs.nspanel.pky.eu/config-overview/

It forces the brightness to zero if the configured entity state is "off" or "not_home"
