### ISSUE TITLE
[Feature Request] Auto navigate notification

### ISSUE THREAD

**Issue by PhillipRt** [joBr99/nspanel-lovelace-ui#375]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._
It would be nice to have a possibility to wake up the NSPanel and navigate to a certain page automatically. I think the easiest way to implement this would be with another type of notification that just takes the MQTT target, the navigate Key and a custom timeout for how long the page should stay open.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
I would like to use this to open the alarm page if the entry timeout starts.
Here are some other use cases I can think of right now:
- Navigating to a personal page that is otherwise hidden (based on presence detection)
- displaying the music player page if a new song starts playing.  
- displaying the thermostat page if the target temperature is changed. (Similar to the nest thermostat display)

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
Does not apply.

**Comment by joBr99** [comment]
Hey, you can use the navigate feature to remotely change pages.

https://docs.nspanel.pky.eu/subpages/?h=navigate

You just have to send the payload a navigate button would send to the RESULT topic.

See this:

https://github.com/joBr99/nspanel-lovelace-ui/issues/190#issuecomment-1127493458
