### ISSUE TITLE
[Feature Request] Add alarm clock to display

### ISSUE THREAD

**Issue by thundergreen** [joBr99/nspanel-lovelace-ui#378]
### FEATURE DESCRIPTION
_I thought due to the small buzzer it would be nice having a alarm clock built in which can be set on the display._
### ADDITIONAL CONTEXT
_Is it possible to adjust the volume of the buzzer?._

### PANEL / FIRMWARE VERION
_3.2.0 EU_

**Comment by joBr99** [comment]
> Is it possible to adjust the volume of the buzzer?.

You can try set the BuzzerPwm Option in the Tasmota Console, this might increase the volume of the buzzer:
 `BuzzerPwm 1`

**Comment by thundergreen** [comment]
would you mind sharing the complete MQTT command to acitvate the buzzer. like this I can use HA with an automation to set an alarm clock :)  What are the vlid values for BuzzerPwn ?

**Comment by joBr99** [comment]
![image](https://user-images.githubusercontent.com/29555657/208752525-4f5a8ae0-6eb0-4f34-9b48-584bdda826f2.png)

![image](https://user-images.githubusercontent.com/29555657/208752566-98a11b87-865b-4140-9339-1a2f5f08f833.png)


ToDo: 
- Implement Button Action
- Implement Translations

**Comment by thundergreen** [comment]
can you please update the docs how to implement the timer :)

**Comment by joBr99** [comment]
you need to have one configured in HA 
https://www.home-assistant.io/integrations/timer/
