### ISSUE TITLE
[Feature Request] sleepTracking activation also for other known zones

### ISSUE THREAD

**Issue by Japander** [joBr99/nspanel-lovelace-ui#380]
### FEATURE DESCRIPTION
For sleepTracking Feature, currently the screen goes of when my tracked person has the status off or not_home. I created zones for example for work. If i`m in my zone "Work", then atm the sleepTracking turns the display on again. I want it to not do that :)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
EU/3.2.1

**Comment by joBr99** [comment]
Hey,
this is an easy one.

```
    sleepTracking: device_tracker.s21_von_johannes_4
    sleepTrackingZones: ["not_home", "off"]
```

Update to main in HACS and restart AppDaemon, no need to update the display firmware.
https://docs.nspanel.pky.eu/faq/#how-to-upgrade-from-a-release-to-the-current-development-version

**Comment by Japander** [comment]
Thank you :) i just tested it, and it worked :)

I just wonder... wouldn`t it make sense to do it the other way around? 
With sleep tracking on, dont go to sleep when status is "home" (or customizable zones), else turn off?

Anyway, it solved my need, thank you for your really cool work here.
