### ISSUE TITLE
[BUG] Timebased sleepbrightness is broke

### ISSUE THREAD

**Issue by bkbartk** [joBr99/nspanel-lovelace-ui#381]
### PROBLEM DESCRIPTION
When using time based screenbrightness, the screensaver stays black.
I use this yaml part
```
    sleepBrightness:
      - time: "5:15:00"
         value: 4
      - time: "19:00:00"
         value: 1
       - time: "00:00:00"
         value: 0
```
it's not 20:13 but the screensaver stays black.

In v 3.1.1 all was ok, but is v3.2.1 is seems to be broken.
a hotfix is to just use
`sleepBrightness: 1`
that one works
### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ V] Provide your apps.yaml:
```
      sleepBrightness: 1
    # sleepBrightness:
    #   - time: "5:15:00"
    #     value: 4
    #   - time: "19:00:00"
    #     value: 1
    #   - time: "00:00:00"
    #     value: 0


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log during your issue/bug occurs:
```
  2022-07-31 20:18:35.967937 INFO nspanel-kamer: Sending MQTT Message: weatherUpdate~���~21.5��C~zo~���~24.7��C~ma~���~25.0��C~di~���~26.3��C~wo~���~30.0��C~~
2022-07-31 20:18:36.030067 INFO nspanel-kamer: MQTT callback for: {'topic': 'tele/tasmota_NSPanel_kamer/RESULT', 'wildcard': None, 'payload': '{"nlui_driver_version":"4"}'}
2022-07-31 20:18:36.036498 INFO nspanel-kamer: Update Pre-Check sucessful Tasmota Driver Version: 4 Panel Version: 39


```
the output is unrelated

### TO REPRODUCE
use my yaml with time base screenbrightness

### EXPECTED BEHAVIOUR
the screensaver should show up

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
Try to change the config from
`- time: "00:00:00"`
to
`- time: "23:59:59"`


This is related to the implementation of the function to calculate the current brightness, so this occures only after config changes or restart of appdaemon, callbacks should be fine.

In this release fackback behaviour changed it is now taking the last value in case it wasn't able to calculate the current brightness.

https://github.com/joBr99/nspanel-lovelace-ui/blob/e72014e60e5176c831bffa2afbee0c29922024ee/apps/nspanel-lovelace-ui/luibackend/controller.py#L128

**Comment by bkbartk** [comment]
changing to 23:59:59 works,

i noticed the brightness levels changed a bit, I think brightness 1 nos is a lot darker then before.

This actually means whenever I modify the config or restart the appdeamon the brightness which will be applied is the first time of the day?
That might not be ideal while trying to check which brightness suits the best.

**Comment by joBr99** [comment]
no it is looping through the list and compareing them with the current time, but there are cases where this doesn't work  (21:24>00:00 vs 21:24>23:59) in such a case it is using the last configured value, which was 0 in your case

The brightness levels itself didn't change.

**Comment by bkbartk** [comment]
I gave the source a better look and see what is happening over there.

I am not a python developer, and I don't have much XP with it, so prease tell me to mind my own bussiness if this doesn't help you. but would this peace of code change the behaviour?

```
    def calc_current_brightness(self, sleep_brightness_config):
        current_screensaver_brightness = 20
        #sleep_brightness_config = self._config.get("sleepBrightness")
        # set brightness of screensaver
        if type(sleep_brightness_config) == int:
            current_screensaver_brightness = sleep_brightness_config
        elif type(sleep_brightness_config) == str:
                current_screensaver_brightness = int(float(self._ha_api.get_state(sleep_brightness_config)))
        elif type(sleep_brightness_config) == list:
            sorted_timesets = sorted(sleep_brightness_config, key=lambda d: self._ha_api.parse_time(d['time']))
            # calc current screensaver brightness
            found_current_dim_value = False
            for index, timeset in enumerate(sorted_timesets):
                curtime = self._ha_api.get_now().time()
                self._ha_api.log("Current time %s", curtime)
                if not found_current_dim_value and self._ha_api.parse_time(timeset["time"]) <= curtime:
                    # first time after current time, set dim value
                    current_screensaver_brightness = sorted_timesets[index]["value"]
                    self._ha_api.log("Setting dim value to %s", sorted_timesets[index])
                    found_current_dim_value = True
            # still no dim value
            if not found_current_dim_value:
                current_screensaver_brightness = sorted_timesets[len(sorted_timesets) -1]["value"]
        return current_screensaver_brightness
```

**Comment by joBr99** [comment]
Acually it is taking the first value of the day in the current version not last last one.

I changed this in the commit
https://github.com/joBr99/nspanel-lovelace-ui/commit/d993e668833a8dedf48ede7e90666f5e5f5813cb
for this issue:
https://github.com/joBr99/nspanel-lovelace-ui/issues/333

I will have a look into your suggestion

**Comment by joBr99** [comment]
rewritten this part, give it a try
