### ISSUE TITLE
[Feature Request] - Real external temperature on screensaver page

### ISSUE THREAD

**Issue by sparkie79** [joBr99/nspanel-lovelace-ui#384]
### FEATURE DESCRIPTION
Could you override the current external temperature on the screensaver page to show the effective external temperature (from an ha sensor)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
Just create yourself an template weather entity in Home Assistant, this allows you to combine weather providers and sensors into a weather entity that you can use on nspanel and also on your Home Assistant Dashboard.

https://www.home-assistant.io/integrations/weather.template/
