### ISSUE TITLE
[BUG] Fan detail page shows light as icon

### ISSUE THREAD

**Issue by gerard33** [joBr99/nspanel-lovelace-ui#391]
### PROBLEM DESCRIPTION
When adding a fan in the entities card the icon is correct. When clicking on the fan name the fan detail page shows up with a light icon instead of the fan icon.

Another thing I noticed is that the page first show the word `Speed` but that is changed after a few seconds to `Snelheid` (Dutch translation of speed) and then the slides is also visible. Maybe it's possible to hide the `Speed` field until the slider is also possible?

_Not entered the info below as the "bug" is in the Nextion screen._

<details>
<summary>Requested information</summary>

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml:
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
</details>

**Comment by joBr99** [comment]
icon should be changed to fan and text is removed
