### ISSUE TITLE
[Feature Request] Vacuum Cleaner Card

### ISSUE THREAD

**Issue by oktay89** [joBr99/nspanel-lovelace-ui#393]
### FEATURE DESCRIPTION
Can you add support for vacuum_cleaner entity (Home Assistant)? I have a Xiaomi Roborock S5, i would like to control with nspanel. For the first step a simple start cleaning/last cleaning/battery will be enough.

### ADDITIONAL CONTEXT
It will be perfect if in the feature the card looks like this:
![image](https://user-images.githubusercontent.com/5344698/183431879-616b6fec-f8f3-4362-a0aa-5c6fc6339217.png)
Live map, choosing rooms to clean etc.

### PANEL / FIRMWARE VERION
Sonoff NSPanel, Tasmota 12.0.2, nspanel-lovelace-ui v3.2.3

**Comment by joBr99** [comment]
Hey,
displaying the map won't be possible on nextion.

I've implemented vacuums as a button, so it is possible to start the robot and return it back to the dock.

For displaying additional states there is #272 and for calling arbitrary services like starting zone cleanup, there is #253.

PS: Which Card are you using in the HA GUI?

**Comment by oktay89** [comment]
I am using the xiaomi vacuum map card:
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/releases/tag/v2.0.11
