### ISSUE TITLE
[Help] Device is so slow and can't flash screen firmware and says device doesn't match

### ISSUE THREAD

**Issue by 0x414c49** [joBr99/nspanel-lovelace-ui#395]
### PROBLEM DESCRIPTION

This morning; I saw that the device won't go to screen saver, and physical buttons won't function. I updated appdeamon and nspanel-lovelace via hacs.

The device was showing the screen savor but couldn't go to the pages. I didn't even get the update display popup. I tried to update it manually by going to the console and running the 

```
FlashNextion http://nspanel.pky.eu/lui-release.tft
```

But nothing happened, and this is the log from the console:

```
00:52:59.179 MQT: tele/tasmota_7DE400/LWT = Online (retained)
00:52:59.187 MQT: cmnd/tasmota_7DE400/POWER = 
00:52:59.309 CMD: FlashNextion http://nspanel.pky.eu/lui-release.tft
00:52:59.325 MQT: stat/tasmota_7DE400/RESULT = {"FlashNextion":"Done"}
00:52:59.380 FLH: host: nspanel.pky.eu, port: 80, get: /lui-release.tft
00:53:14.202 MQT: stat/tasmota_7DE400/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"https://github.com/tasmota/install/raw/main/firmware/unofficial/tasmota32-nspanel.bin","RestartReason":"Software reset CPU","Uptime":"0T00:07:17","StartupUTC":"","Sleep":0,"CfgHolder":4617,"BootCount":3,"BCResetTime":"1970-01-01T00:00:00","SaveCount":9}}
00:53:14.272 MQT: stat/tasmota_7DE400/STATUS11 = {"StatusSTS":{"Time":"1970-01-01T00:53:14","Uptime":"0T00:07:17","UptimeSec":437,"Heap":167,"SleepMode":"Dynamic","Sleep":0,"LoadAvg":9153,"MqttCount":45,"Berry":{"HeapUsed":14,"Objects":222},"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"Home - IOT","BSSId":"06:27:F5:9A:CD:68","Channel":6,"Mode":"11n","RSSI":88,"Signal":-56,"LinkCount":1,"Downtime":"0T00:00:04"}}}
00:53:14.355 MQT: stat/tasmota_7DE400/RESULT = {"Time":"1970-01-01T00:53:14","Uptime":"0T00:07:17","UptimeSec":437,"Heap":167,"SleepMode":"Dynamic","Sleep":0,"LoadAvg":9152,"MqttCount":45,"Berry":{"HeapUsed":14,"Objects":222},"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"Home - IOT","BSSId":"06:27:F5:9A:CD:68","Channel":6,"Mode":"11n","RSSI":86,"Signal":-57,"LinkCount":1,"Downtime":"0T00:00:04"}}
00:53:14.426 MQT: stat/tasmota_7DE400/STATUS10 = {"StatusSNS":{"Time":"1970-01-01T00:53:14","ANALOG":{"Temperature1":31.5},"ESP32":{"Temperature":91.7},"TempUnit":"C"}}
00:53:14.478 MQT: stat/tasmota_7DE400/RESULT = {"CustomSend":"Done"}
```

Error on device:

![photo_2022-08-09_10-44-57](https://user-images.githubusercontent.com/57097646/183608974-83393c53-456a-455c-bc55-d71165804ac3.jpg)

For what I can't understand the device is really slow, it takes sometimes a minute to navigate in Tasmota configuration pageas, lots of requests gets canceled in the browser network tab.

[*] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide a screenshot of your tasmota mqtt configuration:

- [ ] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:


```

- [ ] Provide your apps.yaml:
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:


```

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_

**Comment by 0x414c49** [comment]
I self-hosted the file but Tasmota won't make the HTTP request to download the file.

**Comment by 0x414c49** [comment]
Apparently, app daemon was causing the device to be slow. I can't understand why! Since I stopped appdeamon addon the Tasmota web nspanel is kinda smooth.

**Comment by joBr99** [comment]
Is you tasmota device allowed to access the internet?

Tasmota needs to reach an NTP Server to work properly.

https://tasmota.github.io/docs/FAQ/#device-is-often-unavailable-ussually-30-seconds-every-minute


To get debug logs for the flashing, enter `weblog 4` and then try the flashing again

**Comment by 0x414c49** [comment]
@joBr99:
It has access to the internet. I understood that I had to remove autoexec.**bec** to be able to flash. It's now flashing. Let's see how it goes.

**Comment by 0x414c49** [comment]
Nice lead on NTP. That is also a problem.

**Comment by 0x414c49** [comment]
I tried ping google.com or any other domains, and I understood my DNS server is not reachable for this device. I fixed the issue the time is synced, and it seems the speed problem is fixed.

**Comment by 0x414c49** [comment]
> > I understood that I had to remove autoexec.bec
> 
> .bec is the comiled version of the berry script, it's prefered over the bc file and autogenerated on load (or on reboot) if it doesn't exist
> 
> So removing helps in case you are trying to replace autoexec.be and the bec file is newer than the bc file.

Good to know, thanks.

The problem was DNS (a weird rule from my router that I had defined recently) caused NTP not to work.
