### ISSUE TITLE
[Feature Request] Select effects for RGB lights

### ISSUE THREAD

**Issue by ujvarigergo1** [joBr99/nspanel-lovelace-ui#397]
### FEATURE DESCRIPTION
Home Assistant light entities has "effects" fuction. It's useful for led strips and even cheaper led controllers support it so I think it would be great if there were a possibility to use that fuctionality with smart led strips and NSPanel

### ADDITIONAL CONTEXT
I use ESP8266 and esphome to control my led strips.

### PANEL / FIRMWARE VERION
v3.2.3, EU

**Comment by thundergreen** [comment]
+1 would really be nice adding effects indeed

**Comment by joBr99** [comment]
current dev version (only eu firmware) supports selecting effects, however the generated list of effects needs to be below 900 chars, so it doesn't work with the enormous list of effects WLED supports, there needs to be an option to create a "favorite list"

**Comment by joBr99** [comment]
to access the configuration of the entity; all of the communication has to be done with uuid's

**Comment by phoenixtechnam** [comment]
> 

WLED supports custom PRESETS (bookmarked effects). For me it would be enough to have the list of custom presets in the UI.

**Comment by joBr99** [comment]
implemented a fav list for effects:

```
          - entity: light.wled
            effectList: [Android, Aurora, Blends, Blink, Blink Rainbow]
```

https://docs.nspanel.pky.eu/faq/#how-to-upgrade-from-a-release-to-the-current-development-version
