### ISSUE TITLE
[Feature Request] [ioBroker] Einbindung eines "Home" Sprungs (ioB)

### ISSUE THREAD

**Issue by vocaris9** [joBr99/nspanel-lovelace-ui#403]
### FEATURE DESCRIPTION
Die aktuelle Navigationsstruktur ist derart, dass man in eine Page geht und dort mit den Nav Button vor - zurück rauf und runter geht.
zwischen den Pages gilt das gleiche.
Wenn man sich im Panel nun eine Struktur erstellen will. z.B. Page 1 hat 6 Nav Einträge zu Keller, EG, OG etc.
Ist man dann dort z.B. im OG und in einer 3 Subpage und möchte nun von dort ins EG, dann muss man x mal "zurück" klicken, bis man auf Page 1 ist und dann startet man seine Nanv in die nächste Ebene.
Es wäre somit von Vorteil, wenn man auf jeder Page und Subpage eine Item setzen kann, von dem man direkt zu einem hinterlegten Ziel springe kann. Das Ziel kann man im String dann hinterlegen. Damit ist es generisch und jeder kann eine direkten Sprung von jeder Page/Subpage zu eine direkten Ziel hinterlegen. Für den Sprung sollte man ein Icon selber auswählen können.
Ist die Frage ob man in den aktuellen Grids einen Platz ausmachen kann, wo man dieses Icon/Feature platzieren können.
Alternativ oder zusätzlich auch als Swipe. z.B. von oben nach unten oder von unten nach oben.

### ADDITIONAL CONTEXT
Es geht um Einstellungen für io-Broker

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU - TFT Panel=38
TFT FW: 3.2.3
TS: v3.1.0.1
Tasmota: 12.0.2

**Comment by thundergreen** [comment]
My idea would be having a config to set a timeout for the cards and maybe where to navigate after this timeout

**Comment by kuckuckmann** [comment]
Diesem Vorschlag stimme ich positiv zu. Wäre ein schöne nettes Feature.

**Comment by Armilar** [comment]
Wouldn't it be possible if you enabled the standard button to the higher level in the last subpage level and implemented the home button for the left button?
All you need is a house button over a new menu number, right?

**Comment by Armilar** [comment]
Thank you very much. I think that will help a lot. Will plan for the next release of TS-Script (3.5.0.6).

**Comment by Armilar** [comment]
Die neue Menüstruktur sieht 3 weitere Navigationsmöglichkeiten vor:

![image](https://user-images.githubusercontent.com/102996011/210389666-118177fd-774e-42a5-a662-cd485a2f52d1.png)

* next: innerhalb der gleichen Submenü-Ebene nach weitere Subpages aufschalten
![image](https://user-images.githubusercontent.com/102996011/210390048-d0d8e520-3f30-4bb0-8735-78efcc9d3d61.png)

* prev: auf gleicher Ebene zurückblättern
![image](https://user-images.githubusercontent.com/102996011/210390228-5c485a22-7ff4-4fc1-9c7f-6e1f586e0bde.png)

* home: definierte Seite

* targetPage: Zielseite des pageItem

* id: kann als Menü-Item zusätzlichen Alias aufnehmen und visualisieren. TT-Tom wird die künftige Navigationsstruktur beschreiben

Das neue Menü kommt mit dem nächsten Release.
