### ISSUE TITLE
[Feature Request] Control of Tuya Zigbee blinds 

### ISSUE THREAD

**Issue by pabutterworth** [joBr99/nspanel-lovelace-ui#406]
### FEATURE DESCRIPTION
I would like to be able to control motorized blinds on the panel.  I haven't got the blind motor yet, it's on order.
Its https://www.aliexpress.com/item/1005004556672678.html.
Is this somthing that could be added?

I guess it needs an up, stop and down button?

### PANEL / FIRMWARE VERION
EU Panel, your latest firmware!

**Comment by joBr99** [comment]
I don't see why this shound't already be supported.

https://docs.nspanel.pky.eu/card-entities/
