### ISSUE TITLE
[Feature Request] Vacuum Card

### ISSUE THREAD

**Issue by Gamerayers** [joBr99/nspanel-lovelace-ui#414]
### FEATURE DESCRIPTION
It would be WONDERFUL to support a vacuum, especially something like Valetudo. This would then become my 1 stop shop for everything. So far, I'm LOVING this system.
Another card which would be cool is camera card for veiwing security camers, but I'm guessing that is not as easy to implement.  I use Frigate so it is already MQTT.

### ADDITIONAL CONTEXT
Today this is how my vacuum works. It allows me to select a room, then from there, I click a button to start vacuuming. Not sure how to do this easily, other than a large number of entities today. And as you see, I have more than 6. If I could some how change the number of entities allowed on a page or allow for scrolling, that would work too. I have the US and have it mounted vertically, so I can easily fit more than 6, but due to the multiline setup, it doesn't allow for it.
![image](https://user-images.githubusercontent.com/59520501/186725525-afcd31d6-cf28-4e1a-9e5e-329d73cbebf9.png)

### PANEL / FIRMWARE VERION
US-P

**Comment by joBr99** [comment]
Hey, please see #393, with the latest dev version you can start and stop your robot from entities/grid card.

It is technically not possible to do transfer pictures or video on runtime to the nextion screen.
It is also not possible to do scrolling or moving UI events on runtime with nextion screens.

**Comment by joBr99** [comment]
For starting room cleanup you can configure helper buttons in the meantime and show them on the panel.

With #253 there will be a option to call services directly.
