### ISSUE TITLE
[Feature Request] Abwechselnde Wetteranzeige

### ISSUE THREAD

**Issue by kuckuckmann** [joBr99/nspanel-lovelace-ui#418]
### FEATURE DESCRIPTION
Der Screensaver bietet ja eine 5 tage Wettervorhersage und eine Tagesanzeige mit Wetterdetails.
Könnte man diese beiden Anzeigen nicht in einem Zeitlichen Abstand X Sekunden abwechselnd anzeigen lassen?
Es sind zwei nette Funktionen, so dass es schade ist, wenn man eine nicht zur Verfügung hat.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
EU Panel
DE-de
aktuelle Firmware
Tasmota 12.1.0

**Comment by joBr99** [comment]
ich meine das hab ich im iobroker forum schon mal gelesen

**Comment by Armilar** [comment]
Stimmt ist bereits in der aktuellen Version implementiert. 

Das Skript legt zwei Datenpunkte unter 0_userdata.0.NSPanel.X.ScreensaverInfo an (weaterForecast und weatherForecastTimer)

**Auszug aus dem Quellcode:**
_// Variablen zur Steuerung der Wettericons auf dem Screensaver (Steuerung in 0_userdata.0.XPANELX.ScreensaverInfo)
// Wenn weatherForecastTimer auf true, dann Wechsel zwischen Datenpunkten und Wettervorhersage (30 Sekunden nach Minute (Zeit))
// Wenn weatherForecastTimer auf false, dann Möglichkeit über weatherForecast, ob Datenpunkte oder Wettervorhersage (true = WeatherForecast/false = Datenpunkte)
var weatherForecast = getState(NSPanel_Path + "ScreensaverInfo.weatherForecast").val_

Habe ich schon etwas länger am laufen, jedoch gestern erst bereitgestellt.
