### ISSUE TITLE
Self configuration through be file

### ISSUE THREAD

**Issue by FreakErn** [joBr99/nspanel-lovelace-ui#419]
### FEATURE DESCRIPTION
I don't have iobroker so i am looking for a way the display to configure itself as an initial state. The old way of using this tasmota ns-panel we had a section in the nspanel.be (which was loaded by load("nspanel.be")) where the initial configuration was set, and from there we could send information to the panel and the panel could send its changing states. 

I would love to have a nspanel.be with my structure, all the pages, elements... all the good stuff, with default values.

For me it is a bit difficult to understand what iobroker does, without having it running. 
Can someone please post the whole batch of mqtt messages the iobroker is sending to the display after the display boots up? From there i would build my own nspanel.be file where the display builds itself.

### ADDITIONAL CONTEXT
I don't have or plan to have iobroker running

### PANEL / FIRMWARE VERION
None, i am in the planing state

**Comment by joBr99** [comment]
Hey,
the serial protocol is documented here:
https://github.com/joBr99/nspanel-lovelace-ui/tree/main/HMI

However there is no "how to get started guide" for implementing a new backend. So if you are planning implement a new backend for the display I would suggest to contact me on discord (https://discord.gg/98V7qp4).

This project is build for Home Assistant with an AppDaemon Backend.
There is a 3rd party backend for ioBroker (and something for ip-symcon is in the works).

I don't think that is suitable to build the backend for the display within the berry driver, at least not with the full feature set. This might work for simple switches or buttons, but this project is capable to do way more than the stock UI. Pulling current states from a home automation system also would be a problem.

However if you want to implement some sort of backend, I will answer you any questions to the serial protocol.

Which Home Automation System are you using?

**Comment by FreakErn** [comment]
Hey, thanks for your response.

Well, my idea is that the display will still have these features, but i do not want someone else (iobroker or whatever system) to create the pages. I am using Loxone with a mqtt bridge. In loxone i can read and send mqtt messages.

I don't want the display to be its own backend. Just the "configuration" part, what pages with what elements exists should be done by the displays esp. After that i can set the default values with their actual values.

I can send in Loxone whatever status of what ever element through mqtt to the display. I can resend all the status of the elements repetitive, and the weather, temperature... whatever else. But i cannot configure the pages through it. 

I will join the discord when i come home. Thanks for the offer of answering my questions. I really appreciate it!
