### ISSUE TITLE
[Feature Request] Custom action after arm or disarm alarm

### ISSUE THREAD

**Issue by blackscreener** [joBr99/nspanel-lovelace-ui#424]
### FEATURE DESCRIPTION
I want to connect NSPanel directly to alarm system (Ropam or RPI based alarm) without wifi connection. Can I make custom action (relay or serial command) after arm or disarm alarm on NSPanel? I prefer ESPHome integration.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
The display is sending a message on pressing buttons, for the alarm panel it is sending messages like this:

`event,buttonPress2,alarm_control_panel.alarmo,arm_away,1234`

You could use them as a trigger in local rules/code on tasmota/esphome.
