### ISSUE TITLE
[Feature Request] Labels for physical buttons

### ISSUE THREAD

**Issue by ljmellor** [joBr99/nspanel-lovelace-ui#428]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._
Above each of the physical buttons it would be nice to be able to add a custom label to make their function more apparent. If this could be tied into the screensaver too it would be really smart since the physical buttons are always available.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
Being able to toggle them based upon entity state would also be nice, something such as " - light on/off - lamp on/off - ".

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU running the latest of your firmwares.

**Comment by joBr99** [comment]
There is not enough space to add labels on the screensaver, 
however you can configure statusIcon1 and statusIcon2 with speaking icons for the buttons.
