### ISSUE TITLE
[Feature Request] Allow possibility to define custom colors to "cover" entities

### ISSUE THREAD

**Issue by viDU85** [joBr99/nspanel-lovelace-ui#429]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._

Allow the "cover." entities to have custom color. Currently definition like this does not change the icon color.

```
- entity: cover.0xa4c1385acbdb403d
  color: [103, 58, 183]
  icon: mdi:window-shutter
```

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
Latest 3.3.1 EU & US-P

**Comment by joBr99** [comment]
hey I did some refactoring on the function that is generating the entities, this should now also work for covers

You only need to update to main & restart AppDaemon, no need to update the firmware.

https://docs.nspanel.pky.eu/faq/#how-to-upgrade-from-a-release-to-the-current-development-version
