### ISSUE TITLE
[Feature Request] Weather Temperature override

### ISSUE THREAD

**Issue by randybb** [joBr99/nspanel-lovelace-ui#430]
### FEATURE DESCRIPTION
I would like to use current temperature (optionally humidity) value from my external temperature sensor instead of the value provided from weather.* entity.

### ADDITIONAL CONTEXT
We can already override forecast (weatherOverrideForecast1,...), this is missing.

### PANEL / FIRMWARE VERION
EU / 3.3.1

**Comment by joBr99** [comment]
Hey,
please configure a weather template in HomeAssistant, this also has the advantage that you can use it in HA's UI

https://www.home-assistant.io/integrations/weather.template/

**Comment by randybb** [comment]
Sure, this makes sense. Thanks!
