### ISSUE TITLE
[Feature Request] Timeout for Screensaver notify

### ISSUE THREAD

**Issue by randybb** [joBr99/nspanel-lovelace-ui#432]
### FEATURE DESCRIPTION
We can set timeout for [_popupNotify_](https://docs.nspanel.pky.eu/notifications/#seperate-page), this is not possible for [_notify_](https://docs.nspanel.pky.eu/notifications/#notification-on-screensaver). Or at least to have an option to remove notification from the screen, so I can handle that with an external automation.

### ADDITIONAL CONTEXT
I am using my NSpanels for various notifications, like doorbell is ringing, gate is opening - somebody is coming, low temp in fireplace - add fuel,... and it would be nice to show notification why it is beeping. In these cases confirmation is not needed and _popupNotify_ is too big :) 

### PANEL / FIRMWARE VERION
EU / 3.3.1

**Comment by joBr99** [comment]
Just send an empty notification and it will vanish :)
