### ISSUE TITLE
[Feature Request] Add support for Tasmota shutters & blinds 

### ISSUE THREAD

**Issue by stalakerob** [joBr99/nspanel-lovelace-ui#434]
### FEATURE DESCRIPTION
The Sonoff NSPanel is also a great replacement for a roller shutter control device. Unfortunately shutter support is not included in tasmota32-nspanel.bin Please add support for it.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
Just use the normal tasmota binary instead, should also work fine. 

Adding shutter support to that binary is something for the tasmota GitHub repo.
