### ISSUE TITLE
Uninstall Lovelace UI / Revert to Stock

### ISSUE THREAD

**Issue by ahorseman** [joBr99/nspanel-lovelace-ui#435]
Hello,

I've desparately tried to get Lovelace UI on my NSPanel work with OpenHAB but had no luck at all.

Hence, I want to switch back to the stock UI, which had at least some value on the default screen for me that I could control through Tasmota (i.e., temperature and clock) and especially, the display wasn't on all the time.

I unfortunately couldn't find documentation of how to revert to stock from Lovelace. Can you please either point me to that documentation or give some hint, how to get back to stock?

Thanks a lot in advance.

**Comment by joBr99** [comment]
Did you try to implement a backend for lovelace in OpenHab?

It is possible to revert back to stock, I can help you to do so, if you want to implement a backend for this firmware I can also help you with that.
