### ISSUE TITLE
[BUG] IoBroker Javascript-Adapter crashes after icon_mapping.ts

### ISSUE THREAD

**Issue by kptkip** [joBr99/nspanel-lovelace-ui#441]
### PROBLEM DESCRIPTION
Everytime I activate the typescript icon_mapping.ts in the global folder, the entire javascript-adapter in IoBroker crashes, tries to restart and crashes again a.s.o.

### REQUESTED INFORMATION
Where can I start searching ?

- [ ] Provide your apps.yaml:
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:

No entries in the protocol that could help in searching for the problem.

### TO REPRODUCE
Istalling icon_mapping.ts


### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._


### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._


### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
Version of Javscript-Adapter is 6.0.0
nodejs v16.17.0

**Comment by joBr99** [comment]
There is a bug in the latest JavaScript adapter in combination with global TypeScripts, create a global JavaScript and use the JavaScript file instead.

**Comment by kptkip** [comment]
🙏 thanks for this information.

WIth the Javscript instead the typescript, it works.

Thanks!
