### ISSUE TITLE
[Feature Request] Customize HMI

### ISSUE THREAD

**Issue by PhagoZ** [joBr99/nspanel-lovelace-ui#442]
### FEATURE DESCRIPTION
I would like to change language on statup and customize the UI a little bit.
I already did the changes in Nextion Editor.
That´s not a problem.
Tried to upload the .tft file to my own github (which I just opened for it), an called it via console with FlashNextion.

But I get the error:
"nextion unsupported operand type(s) for <: 'nil' and 'int'"

Did you had the same issue and how did you fix it?

### ADDITIONAL CONTEXT
did that in the past with HA and ESPHome on the NSPanel (now it is Tasmota, which I even like more)

### PANEL / FIRMWARE VERION
ioBroker as Backend
NSPanel EU
Tasmota 12.1.1.1

**Comment by joBr99** [comment]
The TFT needs to be on a http server, it doesn't work with https (and so also not with GitHub)

**Comment by PhagoZ** [comment]
Ah thanks.
Found a way to do it locally :)

Thanks a lot, great work.
Now I have to get through it, to build my customized customUI for NSPanel :D
