### ISSUE TITLE
[Feature Request] Conditions

### ISSUE THREAD

**Issue by robert-80** [joBr99/nspanel-lovelace-ui#445]
### FEATURE DESCRIPTION
Possibility to use conditions. For example i use a Logitech Hub, i want to check if the scene is audio and if yes display the 
entity of the sonos player on the media card. But when TV is active on the logitech, i want to display the nvidia shields media player as identity on the media card.

### ADDITIONAL CONTEXT
The special identities options are not enough, because the condition needs to be checked on a different identity then
the identity which will need to be displayed

### PANEL / FIRMWARE VERION
EU, 3.3.1

**Comment by joBr99** [comment]
You can send the panel to pages with external automations by sending `event,buttonPress2,navigate.cardMedia_test,button` to the  RESULT Topic.

**Comment by robert-80** [comment]
Clear, but i think that's not what i mean. In that case, if i switch media, the automation will send the panel to that page. But leaving the page, can't bring me back to it. What i mean is, i would like to have one mediacard, which displays the mediaplayer which is currently running, while preserving the possibility to swap between pages. Or do i mis understand you?

**Comment by joBr99** [comment]
navigate is just changing the active card, if you define multiple cardMedia on the top level you are still able to navigate between them

**Comment by robert-80** [comment]
Thank you, i understand that it's possible to have more then one cardMedia pages, but i don't want the sonos page visible when it's not the active scene on my Logitech hub. Currently i'm using a few OpenHASP solutions, which i would like to replace with nspanel. OpenHasp has more pages too, but only displays the media player which is active. Maybe i'm not explaining it the right way. Also, sonos is playing always, but the source on the receiver is not always sonos, and is changed by the logitech remote.

I will check the universal option. Thank you for pointing me to that.

**Comment by robert-80** [comment]
The universal option, is the way to go in this situation! Thank you!
