### ISSUE TITLE
[Feature Request] Support for more Nextion displayes

### ISSUE THREAD

**Issue by robert-80** [joBr99/nspanel-lovelace-ui#446]
### FEATURE DESCRIPTION
Because nspanel is based on the Nextion display, which has more displays (bigger, better), it would be nice to have
HMI / TFT files available for the other variants. Because a ESP32 with Tasmota connected to a different Nextion display
is the same setup, only "bigger" with more space for information.

### PANEL / FIRMWARE VERION
EU, 3.3.1

**Comment by joBr99** [comment]
The HMI File is open source do whatever you want with it, you can port it to different screens.

Nextion is a terrible platform. You can do a lot with it, but it is painful and time intensive, there are no automated build tools, lot of duplicated code and many more, it is already a huge pain to keep 3 different versions in sync. 

If you are building a display yourself, use a normal SPI Screen and just open a webbrowser of that screen.

**Comment by robert-80** [comment]
I understand, thank you.

**Comment by joBr99** [comment]
adding in #106 as context, somebody did port an early version of the project to different nextion screens
