### ISSUE TITLE
[Feature Request] - Pincode option for cards 

### ISSUE THREAD

**Issue by diginfo** [joBr99/nspanel-lovelace-ui#449]
### FEATURE DESCRIPTION
The ability to enable a passcode to be entered before displaying a card that was selected via navigation.

Something like:

```
  - type: cardGrid
    title: Admin Settings
    key: admin
    passcode: 1234

```

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
To prevent access to certain cards unless the user has the passcode.

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by diginfo** [comment]
Similar to this I guess:

https://github.com/joBr99/nspanel-lovelace-ui/issues/318

**Comment by joBr99** [comment]
https://docs.nspanel.pky.eu/card-unlock/
