### ISSUE TITLE
[Feature Request] [iobroker] Use parent pageitems as indicator and navigator to subpages

### ISSUE THREAD

**Issue by niiccooo1** [joBr99/nspanel-lovelace-ui#450]
### FEATURE DESCRIPTION
To use a parent pageitem as a status indicator and navigation to subpages at the same time.
E.g. show window state and with click on the icon showing subpages for shutters.

### PANEL / FIRMWARE VERION
EU

**Comment by Armilar** [comment]
Ist bereits im Release 3.7.3.2 enthalten

@tt-tom schreibt zu dem Punkt ein Wiki Example
