### ISSUE TITLE
[Feature Request]  Wildcard for icon types & colours

### ISSUE THREAD

**Issue by diginfo** [joBr99/nspanel-lovelace-ui#454]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._
Allow wildcards in the key for icons:

```
        icon:
          "On": mdi:water
          "Auto-Boost*": mdi:water-off
          "Auto": mdi:water
        color:
          "Auto - Boost*": [255,0,0]
          "Auto": [0,255,0]
          "off": [255,255,255]
```

The wiser heat system operation mode appends the remaining minutes to the state for example:

```
Auto - Boost 59m
Auto - Boost 20m
Auto - Boost 1m

```

Would it be possible to use wildcards in the state key ?

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by diginfo** [comment]
I guess a sensor template could be setup in HA to parse the data from the sensor states.

**Comment by joBr99** [comment]
similar to/should be part of #426
