### ISSUE TITLE
[Feature Request] Screensaver Icons Farbe zulassen

### ISSUE THREAD

**Issue by DerDoubleD** [joBr99/nspanel-lovelace-ui#459]
### FEATURE DESCRIPTION
bei `fourthScreensaverEntity: { ScreensaverEntity: "zigbee.0.00158d000239c7f8.opened", ScreensaverEntityIcon: "garage-open", ScreensaverEntityText: "Garage", ScreensaverEntityUnitText: "" },` onColor und offColor zulassen bzw. ergänzen

### ADDITIONAL CONTEXT
Schöner / Besser gestaltung möglich

### PANEL / FIRMWARE VERION
EU

**Comment by Armilar** [comment]
Kommt mit der nächsten oder übernächsten TS-Skript Version

**Comment by Armilar** [comment]
![image](https://user-images.githubusercontent.com/102996011/190639582-f0d8126d-5ecf-49dc-9fe0-147be7cb331b.png)

Anleitung siehe: https://github.com/joBr99/nspanel-lovelace-ui/wiki/ioBroker-Config-Screensaver
