### ISSUE TITLE
[BUG] Datenpunkt weatherForecast wird immer getoggelt

### ISSUE THREAD

**Issue by DerDoubleD** [joBr99/nspanel-lovelace-ui#460]
### PROBLEM DESCRIPTION
Der Datenpunkt `0_userdata.0.NSPanel.1.ScreensaverInfo.weatherForecast` wird immer umgeschaltet auch wenn der Datenpunkt `0_userdata.0.NSPanel.1.ScreensaverInfo.weatherForecastTimer` auf false steht.

### REQUESTED INFORMATION
Ich denke der Code müsste so aussehen.
```
schedule('* * * * *', () => {
    SendTime();
    if (getState(NSPanel_Path + "ScreensaverInfo.weatherForecastTimer").val == true) {
        //WeatherForcast true/false Umschaltung halbe Minute verzögert
        if (getState(NSPanel_Path + "ScreensaverInfo.popupNotifyHeading").val == '' && getState(NSPanel_Path + "ScreensaverInfo.popupNotifyText").val == '' && getState(NSPanel_Path + "ScreensaverInfo.weatherForecast").val == true && getState(NSPanel_Path + "ScreensaverInfo.weatherForecastTimer").val == true) {
            setStateDelayed(NSPanel_Path + "ScreensaverInfo.weatherForecast", false, 30000, false); 
        } else {
            setStateDelayed(NSPanel_Path + "ScreensaverInfo.weatherForecast", true, 30000, false);
        }
    };
});
```

- [ ] Provide your apps.yaml:
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
Start Script und stelle Datenpunkt `0_userdata.0.NSPanel.1.ScreensaverInfo.weatherForecastTimer auf` false

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by Armilar** [comment]
https://forum.iobroker.net/post/853573

Ist im Dev schon gefixt. Wer nicht abwarten kann, kann die Lösung im Link anwenden. Mit den cardMedia Adaptern (Alexa + Sonos + Google home + Spotify-Premium) kommt eine neue Version des TS-Skript.  Ich denke etwa am 14,09.2022
