### ISSUE TITLE
[Feature Request] - beep on touch

### ISSUE THREAD

**Issue by diginfo** [joBr99/nspanel-lovelace-ui#462]
### FEATURE DESCRIPTION
Not sure if this is possible, but can it emit a short beep on touch, to provide some feedback that the touch was detected ?

**Comment by joBr99** [comment]
you can probably do something like this in tasmota console, but it won't be perfect, implementing this in the backend wouldn't work because of the delay

`rule3 on CustomRecv do Buzzer 1 endon`
`rule3 1`


https://forum.iobroker.net/topic/50888/sonoff-nspanel/1400
