### ISSUE TITLE
Support for OpenHAB

### ISSUE THREAD

**Issue by TheOriginal92** [joBr99/nspanel-lovelace-ui#467]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._

Hi everyone, is there a chance to support OpenHAB?

The only solution I see at the moment is to implement a second IOBroker machine just to run this very nice interface.

Any help welcome.

Thanks in advance!

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

NSPanel EU

**Comment by joBr99** [comment]
Hey, see 436 and 362.

It is definitely possible, I'm the developer of the HMI Project for the Nextion Screen and the AppDaemon Backend for HomeAssistant.

@Armilar currently maintains/develops the ioBroker Backend and @Schnittcher is developing a backend for ip-symcon.

If you want to develop something for OpenHab, I'm more than happy to support you and explain you how to communicate to the NsPanel with this firmware.
