### ISSUE TITLE
[Feature Request] climate on cardEntities 

### ISSUE THREAD

**Issue by najjadasm** [joBr99/nspanel-lovelace-ui#469]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

![Screenshot_20220916_165217](https://user-images.githubusercontent.com/60378456/190656742-0fa64ce1-e2cb-4f18-8c8a-279d490bc1ca.jpg)

AC entity_id status not support on Entities Page card

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml:
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

EU

**Comment by joBr99** [comment]
Climate is not supported on cardEntities this is a separate card

https://docs.nspanel.pky.eu/card-climate/

**Comment by najjadasm** [comment]
> Climate is not supported on cardEntities this is a separate card
> 
> https://docs.nspanel.pky.eu/card-climate/

Could you please support only status

**Comment by joBr99** [comment]
has been implemented in current development version

https://docs.nspanel.pky.eu/faq/#how-to-upgrade-from-a-release-to-the-current-development-version
