### ISSUE TITLE
How to use popupNotify Page

### ISSUE THREAD

**Issue by jeanpaul1977** [joBr99/nspanel-lovelace-ui#47]
I've implemented my own Python backend application to control a NSPanel with Lovelace-UI, but I can't get the popupNotify Page working.

I tried the following commands, but nothing happens:
mosquitto_pub -t 'cmnd/tasmota_XXX/CustomSend' -h mqtt.home -p 1883 -m 'pageType,popupNotify'
mosquitto_pub -t 'cmnd/tasmota_XXX/CustomSend' -h mqtt.home -p 1883 -m 'entityUpdateDetail,|updateBerryNoYes|Driver Update available!|65535|Dismiss|65535|Yes|65535|some text to show|65535|0'

I've created the commands by looking at your Appdaemon application:
https://github.com/joBr99/nspanel-lovelace-ui/blob/main/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py#L57
https://github.com/joBr99/nspanel-lovelace-ui/blob/main/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py#L665

Can you help me out here? I expected the display to wake-up and show the message, but nothing happened so far.
(thanks for all your work btw. I really love the project!)

**Comment by joBr99** [comment]
Are you on the latest firmware for the display?

**Comment by jeanpaul1977** [comment]
I flashed the panel Wednesday 16th, so not today's version, but pretty recent.

**Comment by joBr99** [comment]
update the firmware and it will work :)

**Comment by jeanpaul1977** [comment]
Great; let me try to update the firmware in that case!

I found the documentation in the HMI folder and used that as well to develop the application.
I'm using Domoticz with all kinds of own-developed scripts (just like the one I'm now using to feed the NSPanel). I can send you some pictures if you like ;-)

**Comment by joBr99** [comment]
also in case you didn't know

`mosquitto_pub -t 'cmnd/tasmota_XXX/CustomSend' -h mqtt.home -p 1883 -m 'pageType,popupNotify'`

you don't have to do this over mqtt for testing, you can also do `CustomSend pageType,popupNotify` in the tasmota console

yeah, sure do that :)
never used Domoticz, but if you want to provide a PR with a backend for Domoticz like @britzelpuf is doing for ioBroker, I'm willing to merge it

**Comment by jeanpaul1977** [comment]
Thx for the invite! I'll let you know the results.

**Comment by salopette** [comment]
![sshot-1](https://user-images.githubusercontent.com/32480002/159203811-b8764a61-89e9-4fd3-acb3-2e9aab1182d4.jpg)
bei mir will das nicht flashen?

**Comment by joBr99** [comment]
Unknown kommt, wenn der Berry Treiber nicht geladen ist. Steht etwas in der Berry Konsole?

**Comment by jeanpaul1977** [comment]
I updated to V1.5.2 and can confirm that it's working as expected. Thanks!

**Comment by salopette** [comment]
So jetzt hat es glaub ich geklappt, habe erst den FlashNextion http://nspanel.pky.eu/lui.tft und dann FlashNextion http://nspanel.pky.eu/lovelace-ui/github/nspanel-e780bf3.tft durchlaufen lassen.

Wie komme ich jetzt an die Coolen bunten Lampen Symbole ran?

**Comment by joBr99** [comment]
du brauchst ne seite in der config mit cardGrid statt cardEntities

```
      - type: cardEntities
        heading: Example Page 3
        items:
          - scene.example_scene
          - delete
          - delete
          - delete
      - type: cardGrid
        heading: Example Page 4
        items:
          - light.light_example
```

**Comment by salopette** [comment]
Vielen Dank!

**Comment by joBr99** [comment]
beim nächsten Release sollte das mit dem flashing etwas einfacher gehen, weil er dich auf dem panel fragen kann ob du die display firmware flashen möchtest :)

**Comment by Twit123** [comment]
Just to add to this in case someone else has this issue.

The HMI readme shows popupExit which doesn't work but exitPopup does.

[https://github.com/joBr99/nspanel-lovelace-ui/tree/main/HMI#popupnotify-page](url)

I think it relates to this in the "popupNotify.txt"

`if(tInstruction.txt=="exitPopup")
                                    {
                                        click b0,1
                                    }`

Thanks for all the great work you have done on this, it's awesome.

Simon

**Comment by joBr99** [comment]
hey, you don't have to do any config in the apps.yaml for it

you only have to send a message to the CustomSend mqtt topic, try to send this message

`entityUpdateDetail~iname~heading~65535~textb1~65535~textb2~65535~msg~65535~10`

or on the tasmota console:

`CustomSend entityUpdateDetail~iname~heading~65535~textb1~65535~textb2~65535~msg~65535~10`

I might should add some more documentation for it, take a look at the nodered folder it contains an example for sending a notification.

Also take a look at this issue:

https://github.com/joBr99/nspanel-lovelace-ui/issues/152
