### ISSUE TITLE
aktivate Bluetooth Option 

### ISSUE THREAD

**Issue by strato345** [joBr99/nspanel-lovelace-ui#473]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by strato345** [comment]
Can you write the Bluetooth version over the existing one? I would like to use the display as Bluetooth BLE tracker..

**Comment by joBr99** [comment]
Try out tasmota32-bluetooth.bin

https://tasmota.github.io/docs/Bluetooth_ESP32/#esp32-s2

https://github.com/arendst/Tasmota/releases
