### ISSUE TITLE
[Feature Request] A Graph entity available

### ISSUE THREAD

**Issue by patatman** [joBr99/nspanel-lovelace-ui#477]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._
I'd love to be able to display graphs on my NSpanel, this can be the build-in graph from Lovelace, or the more advanced mini-graph-card (https://github.com/kalkih/mini-graph-card). 
This would allow to display energy usage, but also trend in temperature and other stuff I normally show in Lovelace in a glance.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
If there is something I can do to help, I'm happy to do so. 

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU, using the ESPhome firmware.

**Comment by joBr99** [comment]
This is not possible with Nextion, there is a terrible looking graph component in Nextion Editor, which looks like this:

![image](https://user-images.githubusercontent.com/29555657/191287479-5a4137f3-7a9a-44d8-afa1-bfa7388a69a9.png)

It is not customizable at all, so I'm not going to look further into it.
