### ISSUE TITLE
[BUG] Nextion Firmware type to configured correctly.

### ISSUE THREAD

**Issue by phoenixtechnam** [joBr99/nspanel-lovelace-ui#480]
Hi, 

I have the NSPanel US version, flashed with latest Tasmota and http://nspanel.pky.eu/lui-us-p-release.tft.
It works well together with Home Assistant, BUT
every time there is a content update for the display cards, I get the message:
"The configured display firmware model has changed, do you want to start the update now? Current Model: us-p. Configured Model: eu"

How do I change the configuration to "us-p" to avoid this message in the future ?

Thanks for the help

**Comment by joBr99** [comment]
Just add model: "us-p" to the config
