### ISSUE TITLE
[Feature Request] Support for M5Stack

### ISSUE THREAD

**Issue by ckuntze** [joBr99/nspanel-lovelace-ui#481]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._

Great project.
But I have a small problem with the design of the NSPanel.

Can the software also be ported to the M5Stack?

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
No, M5Stack is using a proper display directly attached to the esp32 and not a nextion screen, completly different hardware.

The screen in M5Stack can be used with lvgl for example with this project.
https://github.com/HASwitchPlate/openHASP
