### ISSUE TITLE
Password protection for switch or confirmation

### ISSUE THREAD

**Issue by mehmetu61** [joBr99/nspanel-lovelace-ui#49]
Hello, can you secure certain switches with a password or do you get a confirmation before you activate it?

**Comment by mehmetu61** [comment]
unfortunately no. Something very simple when you press a switch should it ask you if you really should continue. I have my main fuse with me. so you don't accidentally click on it. i use a translator

**Comment by joBr99** [comment]
there are various ways you could archive this goal in homeassistant for example

1. create two input booleans, turn the acual swich off after they are both false

or

1. create a button, which you can use to trigger an automation
2. listen for the buttonPress event in nodered/ha automation
3. send a notification
4. listen for button press events from the notification
5. exit notifcation screen, by sending pageOpen to the result topic

an example for creating notifications is in the nodered folder

a native build-in confirmation screen ist definitely out of the scope of this project, but it's possible to build this with automations/nodered
