### ISSUE TITLE
[Help] Mqtt messages for this page layout?

### ISSUE THREAD

**Issue by axi92** [joBr99/nspanel-lovelace-ui#497]
I had to use the template because the bot was otherwise closing the issue, sry if this is the wrong aproach.
Hi what are the mqtt messages for this page layout?
![grafik](https://user-images.githubusercontent.com/1394837/193425066-9ebbe5b6-216d-441b-8b94-aa80f0e5f8ee.png)

Is this still a `pageType~cardEntities`?
And how do I add the entities?
I use openhab so I have to code it myself.
If somebody else is on this road like me those links helped me:
https://github.com/joBr99/nspanel-lovelace-ui/issues/436#issuecomment-1236389380
https://github.com/joBr99/nspanel-lovelace-ui/issues/436#issuecomment-1236208688
https://github.com/joBr99/nspanel-lovelace-ui/blob/main/HMI/README.md
https://github.com/joBr99/nspanel-lovelace-ui/blob/main/ioBroker/icon_mapping.js

For now I got something like this:

```
(function() {
  console.log('SCRIPT STARTING!!!');
  console.log('Incomming Message:');
  let itemReceive = items.getItem('GenericMQTTThing_NSPanelCommunicationReceive');
  let itemSend = items.getItem('GenericMQTTThing_NSPanelCommunicationSend');
  let timeOffset = 2;
  let screenTimeout = 10;
  iconMap = new Map([
        ["lightbulb-on", ""],
        ["lightbulb", ""],
    ]);
  lightArray = new Array(
    "LichtBuro",
    "LichtVorzimmer_State",
    "LichtWohnzimmer_State"
  );
  console.log(itemReceive.state);
  let inputMessage = itemReceive.state;
  let inputJSON = JSON.parse(inputMessage);
  // {"CustomRecv":"event,buttonPress2,screensaver,bExit,1"}
  // {"CustomRecv":"event,sleepReached,cardEntities"}
  console.log(inputJSON.CustomRecv.includes('event,buttonPress2,screensaver,bExit,'));
  if(inputMessage.includes('{"CustomRecv":"event,startup,42,eu"}') || inputMessage.includes('{"CustomRecv":"event,sleepReached,cardEntities1"}') || inputMessage.includes('{"CustomRecv":"event,buttonPress2,cardEntities,bPrev"}')
    ){
    itemSend.sendCommand('dimmode~1~100'); //1% in standby and 100% in active
    let now = new Date();
    let current = now.getHours()+timeOffset + ':' + now.getMinutes();
    // Set time
    itemSend.sendCommand(`time~${current}`);
    let options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
    let dateString = now.toLocaleDateString('de-DE', options);
    // Set day of week, day and month
    itemSend.sendCommand(`date~${dateString}`);
    // Set screen timeout
    itemSend.sendCommand(`timeout~${screenTimeout}`);
    // Set Weather
    // weatherUpdate~tMainIcon~tMainText~tForecast1~tF1Icon~tForecast1Val~tForecast2~tF2Icon~tForecast2Val~tForecast3~tF3Icon~tForecast3Val~tForecast4~tF4Icon~tForecast4Val~optionalLayoutIcon~optionalLayoutText
    //Set Page to Screensaver
    itemSend.sendCommand('pageType~screensaver');
  } else if(inputJSON.CustomRecv.includes('event,buttonPress2,screensaver,bExit,')){
    console.log('Exit screensaver now!');
    itemSend.sendCommand('pageType~cardEntities');
    itemSend.sendCommand(`entityUpd~test~1|1~light~light.LichtBuro~${iconMap.get('lightbulb')}~17299~Schreibtischlampe~0~text~sensor.server_energy_power~Y~17299~Server ENERGY Power~155 W~shutter~cover.rolladenfenster_cover_1~Z~17299~Fenster Eingang~A|B|C|disable|enable|enable~switch~switch.bad~D~63142~Bad~1`);

  } else {
    console.log('default!');
  }
 

  //itemSend.sendCommand('pageType~screensaver'); //working
  console.log('SCRIPT ENDING!!!');
})();
```

**Comment by joBr99** [comment]
Hey, 
I will answer you questions any questions to the serial protocol if you are developing something for openhab. Do you have discord? This is way easier in a chat.

**Comment by joBr99** [comment]
> I had to use the template because the bot was otherwise closing the issue, sry if this is the wrong aproach.

I'm looking at the auto-closed issues, sadly this is the only way to force people not deleting the content of the templates, to not ask the same every time.



So back home, to answer your question:

Theese messages are used to get cardEntites

`pageType~cardEntities`
`entityUpd~test~1|1~light~light.schreibtischlampe~X~17299~Schreibtischlampe~0~text~sensor.server_energy_power~Y~17299~Server ENERGY Power~155 W~shutter~cover.rolladenfenster_cover_1~Z~17299~Fenster Eingang~A|B|C|disable|enable|enable~switch~switch.bad~D~63142~Bad~1`

`test` is the heading
`1|1` are the navigation buttons, if you don't want to show them, use `0|0`
`light~light.schreibtischlampe~X~17299~Schreibtischlampe~0` the entites always have 6 fields, examples for the different types are in the Readme within the HMI Folder

The page in your screenshot is cardGird, which takes the same commant format which cardEntities does (even through it doesn't use all of the supplied information). This allows you to reuse a function used to generate the entity items.

`pageType~cardGrid`
`entityUpd~test~1|1~light~light.schreibtischlampe~X~17299~Schreibtischlampe~0~text~sensor.server_energy_power~Y~17299~Server ENERGY Power~155 W~shutter~cover.rolladenfenster_cover_1~Z~17299~Fenster Eingang~A|B|C|disable|enable|enable~switch~switch.bad~D~63142~Bad~1`


But really, contact me on discord way easier to explain there.

**Comment by axi92** [comment]
Ty that will help, how can I contact you on discord? Do you have a server or send me your tag?

**Comment by joBr99** [comment]
https://discord.gg/98V7qp4

Use this one is the unofficial nextion Discord server
