### ISSUE TITLE
[BUG] ioBroker Snippet Double Tap Screensaver Issue

### ISSUE THREAD

**Issue by benny000004** [joBr99/nspanel-lovelace-ui#499]
### PROBLEM DESCRIPTION
Double Tap Screensaver leads to not being able to close the PopUp Window; a small fix helps here:

```
        case 'bExit':
            if (config.screenSaverDoubleClick **&& words[2] == 'screensaver'**) {
                if (words[4] == 2) {
                    GeneratePage(activePage);
                }
```

Adding the part "&& words[2] == 'screensaver'" leads to the expected behavior.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
sounds reasonable

**Comment by Armilar** [comment]
Thank you - yes that was still an open point. With the next version it will be fixed in the code
