### ISSUE TITLE
[Feature Request] Equalizer popup for cardMedia

### ISSUE THREAD

**Issue by Armilar** [joBr99/nspanel-lovelace-ui#502]
### FEATURE DESCRIPTION
Would it be possible to open a sound control (Bass, MidRange, Treble) as an optional pop-up window from the cardMedia?

Something like that?
![image](https://user-images.githubusercontent.com/102996011/193623530-1f350b1a-a00d-4cbe-a97c-425e5432303a.png)

The slider would have to have the zero point in the middle and allow the range in the way of -6 to +6 or -10 to +10.

### PANEL / FIRMWARE VERION
(EU, US-L or US-P)

**Comment by joBr99** [comment]
Hmm, are you planning to adjust this from the panel? I guess having presets and choosing from thoose would be more convinient than having sliders and adjusting all of them each time.

**Comment by Armilar** [comment]
That's probably true and also somehow faster
