### ISSUE TITLE
[Feature Request] Control a group of thermostats

### ISSUE THREAD

**Issue by pbvdven** [joBr99/nspanel-lovelace-ui#504]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._
Control a group of thermostats

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
i have created a group in HA for 3 AC group.thermostats it works fine in HA but the cardThermo won't let me control it
### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU

**Comment by joBr99** [comment]
It should work fine, what did you do to fix it?

**Comment by pbvdven** [comment]
I didn’t get it working with normal group function it worked in HA. but the cardthermo showed up but only had MO and O as buttons 
and temp at 0. I used the entity group.all-ac. Then i used custom integration called climate group and it gave me a combined climate.all-ac and now it works fine.
