### ISSUE TITLE
[BUG] id in payload for 'ct' is missing

### ISSUE THREAD

**Issue by Hobbyflyer** [joBr99/nspanel-lovelace-ui#509]
### PROBLEM DESCRIPTION
Farbtemperatur ('ct') doesn't show slider 

iobroker/NSPanelts.ts
```
out_msgs.push({
                        payload: 'entityUpdateDetail' + '~'                   //entityUpdateDetail
                            + icon + '~'                   //iconId
                            + iconColor + '~'                   //iconColor
```
should be
```
out_msgs.push({
                        payload: 'entityUpdateDetail' + '~'                   //entityUpdateDetail
                             + id + '~'
                            + icon + '~'                   //iconId
                            + iconColor + '~'                   //iconColor
```

**Comment by Hobbyflyer** [comment]
Sorry versuche mich gerade am ersten issue...

**Comment by joBr99** [comment]
alles gut, hab zwar kein plan worum es geht, aber @Armilar wird es schon wissen

**Comment by Armilar** [comment]
Und das hast du sehr gut gemacht mit dem ersten Issue und es stimmt sogar. Hab die id wieder eingesetzt. Mache gleich ein Hotfix. Der ist schon seit vielen, vielen Versionen nicht mehr da. Merkwürdig das es keinem aufgefallen ist.
