### ISSUE TITLE
[Feature Request] Popup window with bigger font and different background.

### ISSUE THREAD

**Issue by JaroslawPrzybyl** [joBr99/nspanel-lovelace-ui#510]
### FEATURE DESCRIPTION
I tested popup window implemented in this project and I think, current form it is not so useful. Too small font and the same background color.
Natural purpose of such window is a kind of alarm or warning, so I think, it should be more visible. Something like this, but possibility to change background color for such popup would be also welcome: big font, readable from the distance (photo shows popup from esphome integration for NSPanel):

![image](https://user-images.githubusercontent.com/33628620/194828214-9e228b80-d7a6-4561-8d5b-9d2fa4d75a45.png)

### ADDITIONAL CONTEXT
NA

### PANEL / FIRMWARE VERION
Tasmota 12.1.1

**Comment by joBr99** [comment]
Added another parameter that allows to change the font of the text

`entityUpdateDetail~id~title~65535~~~~~message~65535~10~3`
![image](https://user-images.githubusercontent.com/29555657/195986349-ef679d90-1b92-4255-9e0d-1adab63b58ad.png)

Font 0 - Default - Size 24 (No Icons, Support for various special chars from different langs)
Font 1 - Size 32 (Icons and limited chars)
Font 2 - Size 32 (No Icons, Support for various special chars from different langs)
Font 3 - Size 48 (Icons and limited chars)
Font 4 - Size 80 (Icons and limited chars)
Font 5 - Size 128 (ascii only)

And I added two parameters for an alternative layout with an icon.

`entityUpdateDetail~id~title~65535~~~~~message~65535~10~2~~2000`

![image](https://user-images.githubusercontent.com/29555657/195987306-37754c69-22b3-40cc-a9ec-fc7a6e310dfd.png)

**Comment by JaroslawPrzybyl** [comment]
Great, thx! Could you tell me, what should I update to see this change? I tried "firmaware update" on device, but after I still see tasmota version 12.1.1 and nothing changed.

**Comment by joBr99** [comment]
You need to update the display firmware.

https://docs.nspanel.pky.eu/faq/#how-to-upgrade-from-a-release-to-the-current-development-version


Run `FlashNextion http://nspanel.pky.eu/lui.tft` in the Tasmota Console.

**Comment by JaroslawPrzybyl** [comment]
Last question: why I can modify a color only for title, not for message, neither icon? I run following command:
`service: mqtt.publish
data:
  topic: cmnd/NSPanel_warsztat/Backlog
  payload: >-
    CustomSend pageType~popupNotify; CustomSend
    entityUpdateDetail~id~title~2000~~~~~message~2000~10~3~~2000;`

and I see green title, but message and icon is white.

**Comment by joBr99** [comment]
hmm, it's showing like this for me

![image](https://user-images.githubusercontent.com/29555657/195989612-f69b16e9-9950-408e-b951-5f48c8c6c0a8.png)

**Comment by JaroslawPrzybyl** [comment]
In my case, same code:
![image](https://user-images.githubusercontent.com/33628620/195989719-e9a0de8c-d6b4-4284-ba17-0981b7ad6d11.png)
Do we have for sure the same software version on Nextion display?I only run FlashNextion in the tasmota console, nothing else, should I do also steps with updating AppDaemon to dev version?

**Comment by joBr99** [comment]
Run `FlashNextion http://nspanel.pky.eu/lui.tft` again in the Tasmota Console, the version on github wasn't the newest.

**Comment by JaroslawPrzybyl** [comment]
Now is perfect, thx for help!

**Comment by JaroslawPrzybyl** [comment]
Ech, not, one remark more, sorry for being grumpy :)
In this popup window I have no characters specific for my language. I have added babel package into Appdaemon and can use my language in cards, also screensaver displays it correctly, but not popup window. 
Code example:
`entityUpdateDetail~id~title~2000~~~~~aąeęoólłnńzżźend~2000~30~3~~2000;`

Result on screen:
![image](https://user-images.githubusercontent.com/33628620/195990853-f090581d-038c-4643-b2db-7c944e438452.png)

**Comment by joBr99** [comment]
>Font 0 - Default - Size 24 (No Icons, Support for various special chars from different langs)
>Font 1 - Size 32 (Icons and limited chars)
>Font 2 - Size 32 (No Icons, Support for various special chars from different langs)
>Font 3 - Size 48 (Icons and limited chars)
>Font 4 - Size 80 (Icons and limited chars)
>Font 5 - Size 128 (ascii only)

it depends on the font, only font 0 and 2 are supporting thoose chars

**Comment by LucaBors** [comment]
Hi, i'm not able to understand how to change color and where to find a color matrix. Thank you! :)

**Comment by joBr99** [comment]
Hey,
the colors are RGB565 in decimal. Unfortunally there is no good color picker for this.

You can use this one
http://www.barth-dev.de/online/rgb565-color-picker/

and then convert the hex value to decimal

https://bin-dez-hex-umrechner.de/

**Comment by LucaBors** [comment]
Oh, this work perfect, thank you! :)
Another info, is it possibile to change the image (the triangle !) with something else? If yes, how? :)

**Comment by joBr99** [comment]
Yes, just pick a different icon from here.
https://docs.nspanel.pky.eu/icon-cheatsheet.html
It's the char at the end before the color, you can copy the char from the Cheatsheet with the U button.

**Comment by LucaBors** [comment]
Cool, now it's almost perfect :)
