### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by kroon040** [joBr99/nspanel-lovelace-ui#511]
### FEATURE DESCRIPTION
Sleepbrightness seperate days of the week

### ADDITIONAL CONTEXT
I have one display in my bedroom, and I dim it to 0  from 23:00 to 6:15. Only in weekends I will have is form 23:00 to 08:00  , so it should ben nice  to have it configurable for seperate days of the week

### PANEL / FIRMWARE VERION
3.4.0

**Comment by joBr99** [comment]
Hey, it is possible to use a input_number entity for the sleep brightness instead of a number or schedule. With this you should be able to use an external scheduler.

**Comment by joBr99** [comment]
This might be a solution to easily configure this schedule in homeassistant.

https://github.com/nielsfaber/scheduler-card

It looks like you can trigger the set_number service on the input_number entity with it.
https://github.com/nielsfaber/scheduler-component#action


Alternatively you can create a NodeRed flow or something like that for it.
