### ISSUE TITLE
[Feature Request] Darstellung eines Einzelwertes Groß auf einer Card/Page

### ISSUE THREAD

**Issue by JohGrei** [joBr99/nspanel-lovelace-ui#514]
### FEATURE DESCRIPTION
um Einzelwerte, Groß auf einer Page darzustellen wäre eine Implementierung einer neuen Page-Art notwendig. 
Mein Use-Case ist der Nachbau einer Infrarotkabine - Steuerung (originale ist defekt) bei der nach dem Einschalten Einzelwerte rotierend, durch das direkte Anspringen einer Page, dargestellt werden.
Die Rotate-Funktion ist ja jetzt mittels JS in ioBroker realisierbar
<img width="341" alt="Mockup_singlePage" src="https://user-images.githubusercontent.com/41279608/195787733-0fc4eb14-78d7-4c1e-b796-746301fc1cd4.png">

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
EU DEV Version

**Comment by Armilar** [comment]
Mir ist aktuell nicht klar, wie du softwareseitig aus der Nummer wieder rauskommen möchtest. Um unterschiedliche Werte nacheinander zu senden musst du unter dem Screensaver-Timeout bleiben. Daher kann das Panel nur als Dauer-Visu genutzt werden. Oder soll ein weiterer Button das Sende-Blockly oder Skript abschalten, so dass eine Bedienung möglich ist, ohne das eine Seite zyklisch aufgeschaltet wird und den Bedienprozess unterbricht.

**Comment by JohGrei** [comment]
Mein Plan wäre, nach dem Starten der Kabine dauert es ca. 15 min bis die Betriebstemperatur erreicht ist. Bis dahin kann ich das Panel ganz normal bedienen. Sobald ich dann aber den Saunagang starte bin ich ja in der Kabine und da soll ich dann rotierend die unterschiedlichen Messwerte/Zeiten zu sehen bekommen. Wenn dann die Gesamtzeit abgelaufen ist, schaltet der Rotationsmodus wieder aus. und Das Panel ist dann wieder ganz normal zu bedienen.
Was ich jetzt nicht weiß, ob ich den Screensaver überhaupt per MQTT-Stoppen oder die Zeitdauer entsprechend verlängern kann, weil sonst muss ich en ScreensaverTimout auf 1800 s stellen

**Comment by joBr99** [comment]
Ich denke das einfachste wäre in dem Fall die Werte als Notification auf dem Screensaver anzuzeigen.

https://docs.nspanel.pky.eu/notifications/#notification-on-screensaver

Da ist leider kein Bild dabei, wird aber über dem Wetter angezeigt.

**Comment by Armilar** [comment]
> https://github.com/joBr99/nspanel-lovelace-ui/issues/514#issuecomment-1278800126
> _Was ich jetzt nicht weiß, ob ich den Screensaver überhaupt per MQTT-Stoppen oder die Zeitdauer entsprechend verlängern kann, weil sonst muss ich en ScreensaverTimout auf 1800 s stellen_

Muss gar nicht, solange du unter 20s rotierst, macht das Script den Rest. 1800s dürfte wohl nicht funktionieren

@joBr99 meint folgende Darstellung:
![image](https://user-images.githubusercontent.com/102996011/195835607-4c88f3c0-14fe-43ae-89ba-6fb89357b9b5.png)
