### ISSUE TITLE
[Feature Request]   change color text

### ISSUE THREAD

**Issue by ozozno** [joBr99/nspanel-lovelace-ui#520]
### FEATURE DESCRIPTION
Change the color of a text according to numerical state

### ADDITIONAL CONTEXT
I have an entity card with the values of my flower plant.
Fertility: 2500
Humidity: 38
Temperature: 21
I would like to be able to put the values in colors according to their numerical value, for example:
when humidity<30 -> color blue
when humidity >30 and <60 -> green color
when humidity >60 -> color red.

It's possible?

### PANEL / FIRMWARE VERION
Panel/Firmware Version you are using: EU, version 3.4.0

**Comment by joBr99** [comment]
there is an existing feature request for this #426
