### ISSUE TITLE
Date and Day don’t always update

### ISSUE THREAD

**Issue by MartinTheBruce** [joBr99/nspanel-lovelace-ui#524]
My display regularly has the previous day displayed. It appears that the MQTT message to update the day/date string is only scheduled once… I suspect this is being dispatched at the turn of midnight, but maybe before the system has updated relevant entities which supply date/time to NodeRed… it would be better and more robust to send this update periodically, even alongside the time update message, given the display is updating for that anyway.

**Comment by joBr99** [comment]
going to look into this on friday or saturday

**Comment by joBr99** [comment]
no clue why this happens and I cannot reproduce it

I've changed the date callback from daily to hourly, so in case it doesn't get updated at midnight it is going to be updated an hour later.
