### ISSUE TITLE
[Help] Notification - Formatting CR/LF (Homeassistant)

### ISSUE THREAD

**Issue by irqnet** [joBr99/nspanel-lovelace-ui#527]
### PROBLEM DESCRIPTION

Using the notification by publishing a MQTT message, seems not to support CR or LF formatting in the message itself.
Depending in the message length I'm sending to the panel, the formatting seems a bit broken sometimes. 

Notification service:

![image](https://user-images.githubusercontent.com/32534199/197151437-83905317-88fe-49c9-8c7b-a7abefc19adf.png)

Script Template:

![image](https://user-images.githubusercontent.com/32534199/197151503-8ad9da1c-856b-48af-9903-05640c3bd9ab.png)

### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/32534199/197151300-e3760571-6594-4071-b763-e82da33a9e77.png)

**Comment by joBr99** [comment]
Hey,
please try to add `\r\n` to your message.

**Comment by irqnet** [comment]
Tried that, but it's not working.

The message is still formatted like one the screenshot in my first post, even the \r\n are not part of the message.
Seems that they are kind of interpreted as formatting chars, but without any effect.

**Comment by irqnet** [comment]
Sorry, seems that there are some caching effects in Homeassistant when running a script multiple times.

The \r\n characters are displayed on the panel as well, without beeing interpreted. The new line is now just caused do to the higher value of my PV system.

![image](https://user-images.githubusercontent.com/32534199/197187590-f5fd5155-8139-4a17-8760-79bb7d78e1bc.png)

**Comment by joBr99** [comment]
Can you try to escape them in Homeassistent by using `\\r\\n`

**Comment by irqnet** [comment]
To rule out any issues in the templating feature of Homeassistant I just shrinked it down to pure text:

message: Testline1 \r\n Testline2
message: Testline1 \\r\\n Testline2

both options are printed as full text without line breaks.

**Comment by joBr99** [comment]
looks like you have to do it like this:

```
service: mqtt.publish
data:
  topic: "cmnd/tasmota_nspwohn/Backlog"
  payload: CustomSend pageType~popupNotify;CustomSend entityUpdateDetail~id~title~2000~~~~~m1{{'\r\n'}}m2~2000~100~4~~2000

```
