### ISSUE TITLE
[Feature Request] Auxillary entites in thermoCard

### ISSUE THREAD

**Issue by magnusoverli** [joBr99/nspanel-lovelace-ui#538]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._
Ability to display auxillary entities inside the cardThermo, such as current power, energy consumption. Also current temperature (for devies that does not supply this itself, for example template heat pumps).
Basically any numeric state and a friendly name. 

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
![image](https://user-images.githubusercontent.com/29555657/197746778-a777691c-c9d6-41a3-b3e9-be76ef17d48e.png)

I don't see there any free space for putting addional information.

For climate entities that are not providing the current temperature you can use a template to combine it into one entity.

https://github.com/jcwillox/hass-template-climate

**Comment by joBr99** [comment]
Well it depends on your climate entity, climate entities can have tons of different modi, fan_modes, swing_modes and fan_modes. Climate devices with two setpoints are usally HVAC Systems that can heat and cool.

![image](https://user-images.githubusercontent.com/29555657/197853819-e3043db7-594f-4b7f-bfd9-0318f4c962e8.png)

**Comment by joBr99** [comment]
slightly changed the layout of cardThermo

![image](https://user-images.githubusercontent.com/29555657/202024193-75034dc4-c37a-45e1-959f-61e63821415b.png)

resulting in bigger icons for changing the temperature
