### ISSUE TITLE
[HELP] use an input_text to set rgb color for entities

### ISSUE THREAD

**Issue by federicosantolini** [joBr99/nspanel-lovelace-ui#539]
### FEATURE DESCRIPTION
Use an input_text to send the rgb combination to the yaml for icons color

### ADDITIONAL CONTEXT
instead of using [255,0,0], it could be useful to use something like input_text.colore_consumo_nspanel and set the color dynamically, like the one used for the brightness percentage

standard:
![image](https://user-images.githubusercontent.com/94896891/197770853-dba895cd-4fe5-461c-9705-0b22ff072bb6.png)

with input_text
![image](https://user-images.githubusercontent.com/94896891/197770937-e4d0c0fc-5332-4be9-9445-1c32ba87aa38.png)

### PANEL / FIRMWARE VERION
NSPanel 12.2.0.1

**Comment by Giewarro** [comment]
Struggling with the same for temp sensors. Just tried "ha:{{ ..." but without success.

**Comment by joBr99** [comment]
with 3.7.3 you can now use homeassistant templates for the color

for your power sensor you can define the color based on the value like this, using a value from a input_text should also be possible
```
        color: >
          {% if int(states("sensor.carbon_monoxide")) < 40  %}
          [255,0,0]
          {% elif int(states("sensor.carbon_monoxide")) < 50 %}
          [0,255,0]
          {% elif int(states("sensor.carbon_monoxide")) < 60 %}
          [0,0,255]
          {% endif %}

```
