### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by polskifacet** [joBr99/nspanel-lovelace-ui#543]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._
Please add the ability to use a 12 hour clock on the screen saver. 
### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
US-P Latest Firmware

**Comment by randybb** [comment]
It is already supported. Check `timeFormat` https://docs.nspanel.pky.eu/config-overview/

**Comment by polskifacet** [comment]
Could you provide an example? This is what I have.

nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/Control/NSPanel/RESULT"
    panelSendTopic: "cmnd/Control/NSPanel/CustomSend"
    model: "us-p"
    timeformat: "%I:%M   ?%p"
    screensaver:
      entity: weather.home
      weatherUnit: fahrenheit
      alternativeLayout: True
      theme:
      autoWeather: True

**Comment by joBr99** [comment]
yes, adding `timeFormat: %I:%M   ?%p` to your config should get you the 12-hour Format
