### ISSUE TITLE
[Feature Request] Please create an option to change time from 24hr to AMPM

### ISSUE THREAD

**Issue by treborjm87** [joBr99/nspanel-lovelace-ui#549]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._. Would like to have the ability to change the time to an AMPM format.  This would significantly increase the WAF factor.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._. No problems... just a "would like to have".

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_ US-L (Tasmota)

**Comment by joBr99** [comment]
Hey, just configure the time format to the example in the docs.

https://docs.nspanel.pky.eu/config-overview/

**Comment by treborjm87** [comment]
Johannes,

I did see that option...

So, to get 1300 to show as 1:00 PM, do I use:

timeFormat: "%H%M   ?%p"

OR

timeFormat: "%I%M   ?%p"

Thank you for replying!

This is an amazing project!  I wish that I was at least some kind of programmer that could be as useful to the community.

Treb

**Comment by joBr99** [comment]
%I is the correct one for 12 hour time format

timeFormat: "%I:%M   ?%p"

Directive | Meaning
-- | --
%H | Hour (24-hour clock) as a decimal number [00,23]. 
%I | Hour (12-hour clock) as a decimal number [01,12].
%p | Locale’s equivalent of either AM or PM.

https://docs.python.org/3/library/time.html

**Comment by treborjm87** [comment]
Wow!

Thanks for getting back to me so soon!  You are AMAZING!

timeFormat: "%H%M   ?%p"  this does work, but would like to the ":" in between hour and minutes

timeFormat: "%I%M   ?%p". I don't see a change from the other option.

I am searching thru the Python web page you pasted, looking for the format to get that ":" into the time.  But am not seeing it.  I am obviously missing it.

Thanks again!

Treb

**Comment by treborjm87** [comment]
Helps if I look at your example.  I see the ":" in your example!

Thank you SO MUCH!

This works great!

Treb

**Comment by treborjm87** [comment]
One last question on this...  Can the leading zero "0" be trimmed?

Currently, here in the US, it is 9:00 AM.  The display shows 09:00.

Thanks Johannes!

Treb

**Comment by joBr99** [comment]
Try to do this:
```
timeFormat: "%-I:%M   ?%p"
```

**Comment by treborjm87** [comment]
That is perfect!  Exactly what I was looking for!

Thanks again, Johannes!!!
