### ISSUE TITLE
[Feature Request] icon from ha_template to remain icon, not text

### ISSUE THREAD

**Issue by danielszilagyi** [joBr99/nspanel-lovelace-ui#553]
### FEATURE DESCRIPTION
I'm trying to call a service with the documented way, however when I add the ha_template to my configuration, the icon is always displayed as text. I tried to define this in many ways but the outcome is always the same, the icon showing up as a text showing mdi: which is the output of the ha template but it is not escaped. Also checked in home assistant template editor the output is not escaped in any way.

### ADDITIONAL CONTEXT
- entity: service.script.reflektor_elso_2
            name: Első reflektor be
            icon: 'ha:{% if is_state("switch.reflektor_elso", "on") %}mdi:lightbulb-on{% else %}mdi:lightbulb-off{% endif %}'

### PANEL / FIRMWARE VERION
Tasmota Driver Version: 4 Panel Version: 43 EU

**Comment by joBr99** [comment]
you might want to do simply this, it should show the status of the switch.

```
entity: service.script.reflektor_elso_2
name: Első reflektor be
status: switch.reflektor_elso
```

Using HA Templates is mainly for replacing the icon with a temperature or something like this; if you want it to output the icons, you have to use the acually char that you can get from the cheatsheet by clicking on the U. But you don't have to use it in this case.

You might be also able to use this in combination with status to change the icons if you need to, currently not 100% sure.
```
            icon:
                "on": mdi:lightbulb
                "off": mdi:lightbulb
```
