### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by ClaireRovic** [joBr99/nspanel-lovelace-ui#559]
### FEATURE DESCRIPTION
Add the ability to use an include statement which will import the configuration for a card type/config.

### ADDITIONAL CONTEXT
As I have four panels and will plan on getting some more, my apps yaml is getting large. In my use case 90% of the configuration is identical for each panel. I only change the default page depending on the room the panel is in.

### PANEL / FIRMWARE VERION
US-L

**Comment by joBr99** [comment]
You can move parts of the configuration to a separate file and include that file in your configuration.

https://appdaemon.readthedocs.io/en/latest/APPGUIDE.html?highlight=include#include-yaml-files

Also see this as an example, it has the screensaver theme separated into a file.
https://github.com/joBr99/nspanel-lovelace-ui/tree/main/appdaemon/screensaver-theme-include

**Comment by ClaireRovic** [comment]
Thanks, heaps, for your patience
