### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by ChrisVonFrosta** [joBr99/nspanel-lovelace-ui#560]
### FEATURE DESCRIPTION
show pictures on the NSPanel

### ADDITIONAL CONTEXT
i would like to see images on this screen. For example to show photos while screensaver runs or picture from suveilance camera if someone rings the doorbell

### PANEL / FIRMWARE VERION
12.2.0.2(nspanel)  EU

**Comment by exxtreme5** [comment]
2nd this

**Comment by joBr99** [comment]
See #448 #323 #288 #177 #127 and probably some more. 

This is not possible with the nextion screen, it doesn't allow you to transfer pictures to it. You can only do this with NsPanel Pro.
