### ISSUE TITLE
DefaultCard for ioBroker

### ISSUE THREAD

**Issue by PhagoZ** [joBr99/nspanel-lovelace-ui#561]
Hallo zusammen,

ich hab gesucht und bin nur auf die HA Lösung gestoßen, um die DefaultCard bei verlassen des Screensavers zu definieren.
Wie geht das denn im iobroker?

**Comment by joBr99** [comment]
Hey,
am Besten du fragst mal im ioBroker Forum:
https://forum.iobroker.net/topic/58170/sonoff-nspanel-mit-lovelace-ui

Falls das noch nicht funktioniert bitte das Template für nen Feature Request ausfüllen und nicht löschen.
