### ISSUE TITLE
Timezone incorrect

### ISSUE THREAD

**Issue by kub3let** [joBr99/nspanel-lovelace-ui#562]
Both Homeassistant and Appdaemon timezones are set to Europe/Berlin via config:
```
/homeassistant/config/configuration.yaml:
homeassistant:
  time_zone: Europe/Berlin

/homeassistant/config/appdaemon/appdaemon.yaml
---
appdaemon:
  time_zone: Europe/Berlin
```

Server time is set to UTC.

The time displayed on the nspanel is UTC but should be Europe/Berlin

It should send 14:03 to the nspanel but sends 13:03 instead
```
2022-11-09 13:03:46.968461 INFO nspanel1: Startup Event
2022-11-09 13:03:46.972589 INFO nspanel1: Sending MQTT Message: time~13:03~
2022-11-09 13:03:46.978041 INFO nspanel1: Sending MQTT Message: date~Wednesday, 09.11.2022
```

Note that Homeassistant correctly uses Europe/Berlin in automations etc.

Changing the timezone in appdaemon.yaml to for example UTC makes no difference.

Appdaemon seems to ignore what is set in appdaemon.yaml and uses the server time ?

**Comment by joBr99** [comment]
Hey, 
are you using your own docker containers?

It is using the timezone from the docker container, so you might have to set the timezone of the docker container itself.

One way to do this should be passing though localtime.

    volumes:
      - ./docker-data/homeassistant/:/config
      - /etc/localtime:/etc/localtime:ro

**Comment by kub3let** [comment]
@joBr99 thanks for your reply, yes I use my own containers.

I did have the /etc/localtime:/etc/localtime:ro volume mount, but that just passes UTC from the Host

By overriding the TZ environment variable in the appdaemon container, it now works.

docker run:
```
-e TZ="Europe/Berlin" 
```

docker compose:
```
environment:
    TZ:"America/Los_Angeles"
```
