### ISSUE TITLE
[Feature Request] timeAdditionalTemplate themable

### ISSUE THREAD

**Issue by mikosoft83** [joBr99/nspanel-lovelace-ui#565]
### FEATURE DESCRIPTION
Add option to choose color for timeAdditionalTemplate in theme.

### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
hey it should be `tTimeAdd` in the theme

**Comment by mikosoft83** [comment]
Thanks, that works. It's not reflected in the docs though so just heads up
