### ISSUE TITLE
[Feature Request] Templatable fields in entities

### ISSUE THREAD

**Issue by mikosoft83** [joBr99/nspanel-lovelace-ui#566]
### FEATURE DESCRIPTION
Please add option to use template in any entity field (name, icon) to generate dynamic labels and icons.

### ADDITIONAL CONTEXT
For icons I'd like to change icon based on numeric state, so the "ha:" template doesn't work in this case.

### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
you can overwrite the icon based on a entity state
```
            icon:
                "on": mdi:lightbulb
                "off": mdi:lightbulb
```

https://docs.nspanel.pky.eu/entities/#override-icons-or-names

**Comment by mikosoft83** [comment]
Yes, but I'd like to do something like
temperature below x, icon is snowflake
temperature between x and y, icon is drop
temperature above y, icon is heat

**Comment by joBr99** [comment]
so this? #426

**Comment by joBr99** [comment]
by the way, the `ha:` icon type should work for this; as long as you are using the acual icons chars instead of the name

you can copy the char by clicking the U
https://docs.nspanel.pky.eu/icon-cheatsheet.html

**Comment by mikosoft83** [comment]
Ah, okay, that worked.
It's not the most readable way to do it but it's something
