### ISSUE TITLE
[Feature Request] clock font resize 

### ISSUE THREAD

**Issue by najjadasm** [joBr99/nspanel-lovelace-ui#57]
Cloud you please resize font to be fit with the screen 
please below 
![16480870552144283900749088319419](https://user-images.githubusercontent.com/60378456/159826689-99e85dda-0d61-44a5-80f9-0c31d3c137ec.jpg)

**Comment by joBr99** [comment]
hey, 
sadly it's not possible to automaticly resize the font based on the string length with nextion screens

**Comment by najjadasm** [comment]
can to resizes the font from the nextion firmware to be smaller of the existing

**Comment by hatran0884** [comment]
or it would be easier if you can set the time to be 24h basis. so AM will be no longer there.

**Comment by joBr99** [comment]
For now, remove the am/pm or change it to 24h, I will let this open and look what I can do.

**Comment by najjadasm** [comment]
Noted and thanks very much for your work

**Comment by joBr99** [comment]
![image](https://user-images.githubusercontent.com/29555657/160151991-12eeb230-cae8-4d3c-a320-b37b833c4329.png)

Added a second text box, over the time box, for AM/PM, appears if there is an _?_ in the time string and get's filled with the content after the _?_

`timeFormat: "%I:%M   ?%p"`

**Comment by joBr99** [comment]
implemented with release v1.8.3
