### ISSUE TITLE
Erweiterungen a la QRCode...

### ISSUE THREAD

**Issue by fumanchi** [joBr99/nspanel-lovelace-ui#571]
Hi..

Ich bin bereits sehr glücklich mit dem Funktionsumfang und komme gut mit der Steuerung des ns Panel über iobroker zurecht. Ich würde aber sehr gerne genauer verstehen wie das tft (Nextion Template?) gebaut wird und es gerne um Funktionen wie die Darstellung einfacher Plots erweitern. 
Wenn ich das richtig gesehen habe, wird zum Beispiel auch ein QRCode Befehl wie "qrcode m0.x,m0.y,200,6371,65535,-1,vaQR.txt" auf dem Display interpretiert um einen QRCode zu generieren und darzustellen. Ich hätte Lust und Zeit mich dahinter zu klemmen und vielleicht wird oben geschrieben, einfache Zeitreihen in Form von Plots oder Balkendiagrammen darzustellen. 
Da ich aber leider nirgends den Code finden kann, mit dem das nspanel.tft erzeugt wird, würde ich mich freuen wenn mir Johannes oder sonstwer zum Einstieg Mal am Beispiel des QRCodes erklären könnte, was mir aktuell noch (zum Verständnis) fehlt :)

Danke!

Zu meiner Qualifikation: Ich bin zwar nicht der Held in Sachen Java oder Type Script aber habe jahrelange Erfahrung in der Software Entwicklung (die letzten ~15 Jahre C/C++ Entwicklung im Automobilbereich) und lasse darüber hinaus im Privaten etliche ESPs im Haus für unterschiedlichste Aufgaben (u.a. Steuerung meines Sonos Systems mittels RFID Karten a la Tonuino nur mit OLED-Display, POE Funk Wetterstation via MQTT, Hausgemachter NUKI Door opener über die AC-Türöffner Relais der Videogegensprechanlage via MQTT, u.s.w. ) mittels hausgemachter Software (und Hardware) nach meiner Pfeife tanzen.

**Comment by joBr99** [comment]
Hey,
ich bin auf dem Unoffical Nextion Discord errichbar, das ist hierfür besser geeignet.

https://discord.gg/98V7qp4

**Comment by joBr99** [comment]
Das NSPanel besteht auch einem ESP32 und einem Nextion Display, welches aus einem STM32 und einem Display besteht. Der STM32 ist für das Display verantwortlich, die zwei Microcontroller reden über seriell.

Soweit zur Hardware, auch wenn das fragwürdige Design Entscheidungen sind, damit müssen wir halt leben ...

Nextion Projekte werden mit dem Nextion Editor erstellt. "Source" daür ist das HMI File.
https://nextion.tech/nextion-editor/

Den Rant über dieses tolle Tool spar ich mir an der Stelle mal.

Skripte in Nextion werden mit commands des Nextion Instruction Set geschrieben.

https://nextion.tech/instruction-set/
