### ISSUE TITLE
[Help] Trying to find developer documentation (Trying to implement FHEM backend)

### ISSUE THREAD

**Issue by chefpro** [joBr99/nspanel-lovelace-ui#575]
I am thinking about to implement a module for FHEM for lovelace-ui.
I can not find any documentation how to generate the ui myself.

What I have done:
* Flashed tasmota
* Updated the nextion firmware with lovelace-ui
Now I am on the point where the display shows "Waiting for content"

So far, so good...

Next step:
How can I place a card and widget with simple mqtt messages?
Is that possible at all? I hope it is...

Second next step:
How to communicate with this widgets? (I found at least some documentation for that in the md files)
(Maybe this can be implemented with a configuration for the statemaschine I forked for fhem.)

I hope I can just support the lovelace-ui in fhem with a simple configuration. At least for testing and learning. Later on I also could provide a fhem module for it. If placing cards and widgets with mqtt is possible then I see no problem for this.

Thanks a lot, Peter

**Comment by joBr99** [comment]
Hey,
please contact me on discord.

https://discord.gg/98V7qp4

**Comment by joBr99** [comment]
This is a starting point, but as I said contact me on discord, way eaiser. 

https://github.com/joBr99/nspanel-lovelace-ui/issues/436#issuecomment-1236208688

Once you got the principle even the documentaion on the HMI Readme helps, even though it could be way better.
