### ISSUE TITLE
[Feature Request] Extend the Width of the Second Line of the Time Field on the Screensaver Pane

### ISSUE THREAD

**Issue by mooangus** [joBr99/nspanel-lovelace-ui#577]
### FEATURE DESCRIPTION
It looks like the second line of the time field on the screensaver pane is limited in size and does not extent to the edges of the screen of the display panel.  Currently, I am able to display two characters but any more get cut off.  I would propose extending the field to the edges of the screen to allow for display of additional text. My reason for the request is to allow the panel to display the day of the week on the second line of the time field. Thank you for your hard work on this project and I really appreciate the project.

### PANEL / FIRMWARE VERION
US-P

**Comment by joBr99** [comment]
Hey, 
run `FlashNextion http://nspanel.pky.eu/lui-us-p.tft` in your tasmota console,
I've resized the text box. (However I did not test it)

**Comment by mooangus** [comment]
Thanks so much!  I've sent you a small token of my appreciation. That worked perfectly. Just in case anyone is searching for something like this.  This is my entry for the time format to display the short form day of the week on the second line:

timeFormat: "%-I:%M?%a"
