### ISSUE TITLE
Exit screensaver with MQTT command

### ISSUE THREAD

**Issue by bluemaster27** [joBr99/nspanel-lovelace-ui#579]
I would like the screensaver to exit when a motion sensor is triggered.
In MQTT explorer is see this command when touching the screen:
{"CustomRecv":"event,buttonPress2,screensaver,bExit,1"}

Not really an MQTT hero, so any help on what and how to send would be great. 
I preferably want to do it in Node Red, but any way of exiting the screensaver on motion is welcome.

**Comment by joBr99** [comment]
Hey, you almost got it.

Just send `{"CustomRecv":"event,buttonPress2,screensaver,bExit,1"}` to the RESULT MQTT Topic.
