### ISSUE TITLE
[Feature Request] Override names

### ISSUE THREAD

**Issue by fschwarz86** [joBr99/nspanel-lovelace-ui#58]
Hi there,

another feature request from my end: Can we get name overrides similar to icon overrides? There are multiple use cases for this:
- Name of entity is too long to render correctly on display
- Some entities (e.g. manually configured MQTT entities) can't have a UI friendly name and will always show the entity ID
- Name of entity has redundant information (e.g. contains the name of the room while it might be implicit from the context)

As usual: Thank you for considering!

Cheers,
Florian

**Comment by gerard33** [comment]
See PR #59.
