### ISSUE TITLE
[Feature Request] Entity or gridcard option to set time or decimal

### ISSUE THREAD

**Issue by hanfelt** [joBr99/nspanel-lovelace-ui#580]
It would be nice to be able to have an option to be able to set how a sensor is displayed.
In my example I have added a sensor that shows when the next bus is leaving and now it shows: 15:4 it would be nice if it returned 15:45 instead. I think this option could be useful for other things as well.

**Comment by hanfelt** [comment]
Thanks a lot gonna try it out ;)

**Comment by hanfelt** [comment]
This is not a question for you but if I don’t want to show the attribute but the one in the screenshot what do I type then?
￼

**Comment by joBr99** [comment]
Hey, your screenshot isn't attached.

Current State is accessable like this: `{{ states('device_tracker.paulus') }}`
https://www.home-assistant.io/docs/configuration/templating/

**Comment by hanfelt** [comment]
The entity "state"

**Comment by hanfelt** [comment]
Sorry I didn’t read all your message ill try It out have a great weekend and thanks for your help ;) I have a question about sending text as a popup as well to the nspanel with status from an entity but ill send you that later ;) Cheers and thank you so much for bringing nspanel to us...

**Comment by hanfelt** [comment]
icon: 'ha: {{ states("sensor.mot_ljungskile") }}’

This is the right syntax ;) the fourth number is a little cut of in the grid view but its ok ;)
