### ISSUE TITLE
[Help] Waiting for Content (I'm not using HomeAssistant)

### ISSUE THREAD

**Issue by nutkracker** [joBr99/nspanel-lovelace-ui#583]
### PROBLEM DESCRIPTION

Hi,

I'm after some assistance please. I'm wanting to use NodeRed to send messages to the NSPanel via MQTT (I'm not using HomeAssistant). When NSPanel starts up, its sitting "Waiting for content...".

What messages via the cmnd topic do I need to send to the NSPanel so that it comes out of the loop its currently it, waiting for the right messages to configure itself to start?

I'm wanting to go NodeRed -> MQTT -> NSPanel

Thank you,

Nutz

[] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide a screenshot of your tasmota mqtt configuration:

- [ ] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:


```

- [ ] Provide your apps.yaml:
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:


```

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_

**Comment by joBr99** [comment]
You can use this as a starting point.

https://github.com/joBr99/nspanel-lovelace-ui/issues/436#issuecomment-1236208688

Please contact me on discord, there is also somebody that started to write a backend for openhab in nodded. 

https://discord.gg/98V7qp4

**Comment by nutkracker** [comment]
Thanks… will take a look!

**Comment by nutkracker** [comment]
@joBr99 discord link doesn’t work/expired?

**Comment by joBr99** [comment]
https://unofficialnextion.com/t/welcome-to-the-unofficial-nextion-tjc-user-forum/8

Try the link in this forum post.

**Comment by nutkracker** [comment]
I’m on now. Cheers!
