### ISSUE TITLE
[BUG] icon color for service ignored

### ISSUE THREAD

**Issue by mikosoft83** [joBr99/nspanel-lovelace-ui#586]
### PROBLEM DESCRIPTION
When I configure an entity in cardGrid like this:
- entity: service.light.turn_on
data:
entity_id: light.schreibtischlampe
color: [255, 0, 0]

The color is ignored. When I use any entity, color is correct

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide your apps.yaml (or your config):
```
  apps.yaml here:
see above example

```
- [x] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
none

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
See above

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
Color of the icon should reflect configured value.

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU

**Comment by joBr99** [comment]
Hey, install main in HACS and restart AppDaemon.

https://docs.nspanel.pky.eu/faq/#how-to-upgrade-from-a-release-to-the-current-development-version

**Comment by mikosoft83** [comment]
Perfect!
