### ISSUE TITLE
[BUG]  Something has gone wrong flashing display firmware 

### ISSUE THREAD

**Issue by mattzeer** [joBr99/nspanel-lovelace-ui#587]
### PROBLEM DESCRIPTION
Hello,
When i try to flash Nspanel EU with the command "FlashNextion" i have an error 

 FLH: Something has gone wrong flashing display firmware [bytes('8080808080008080808000800000008080800000000000808080008080000080...')]

### SCREENSHOTS
![image](https://user-images.githubusercontent.com/16178152/203086793-74a8a923-9c86-451f-9025-191cd1ae91c4.png)

### PANEL / FIRMWARE VERION
NSPANEL EU
LASTEST VERSION

**Comment by joBr99** [comment]
hey, just reboot tasmota and try again
