### ISSUE TITLE
[Feature Request] - Fill CardPower manually with CustomSend when Card is Active

### ISSUE THREAD

**Issue by Hobbyflyer** [joBr99/nspanel-lovelace-ui#589]
### FEATURE DESCRIPTION
Need a Datapoint in iobroker (e.g.   setState(NSPanel_Path +'ActivePage',activePage);) that contais the actual Page.
This DP should switch between Pages and Screensaver.
or
used PageNavi updated when user change screen manually (get / set)
      

### ADDITIONAL CONTEXT
Backgroud: Fill CardPower manually with CustomSend when Card is Active.
[Sample](https://github.com/Hobbyflyer/nspanel-lovelace-ui/blob/main/FoxHome/CardPower.js)

### PANEL / FIRMWARE VERION
V3.5.0.5, BD 4, TFT 43, Tasmota 12.2.2.0

**Comment by Armilar** [comment]
> from v3.6.0.4

![image](https://user-images.githubusercontent.com/102996011/204805479-3a4512cb-8c35-45bb-bf12-964f78e6e2f6.png)

I added a RegisterEntityWatcher to update the values

`RegisterEntityWatcher(page.items[0].id + '.ACTUAL');
`

**Comment by Hobbyflyer** [comment]
Updated to 3.6.0.3 & BD 6 TFT 45
After this Basic update everything is working as espected.

Added "RegisterEn..." Line to 3.6.0.3 than my CardPower is displayed, but it flickers with an other (Sample?)  CardPower.
This Card displays an empty card with the central rectangle an upper left car icon.

**Comment by Armilar** [comment]
In the HMI, not the part of a card is written, but all pages are re-rendered. That will not change either. Either new data and flickering when loading the page or no data update when the page is open.
This also happens when changing sides. You just don't see it in regular operation.

I have adapted the solution from cardMedia. In my opinion, this works. However, you cannot eliminate the flickering.

```
function unsubscribePowerSubscriptions(): void {
    for (let i = 0; i < config.pages.length; i++) {
        if (config.pages[i].type == 'cardPower') {
            let powerID = config.pages[i].items[0].id;
            unsubscribe(powerID + '.ACTUAL')
        }
    }
    for (let i = 0; i < config.subPages.length; i++) {
        if (config.subPages[i].type == 'cardPower') {
            let powerID = config.subPages[i].items[0].id;
            unsubscribe(powerID + '.ACTUAL')
        }
    }
} 

function subscribePowerSubscriptions(id: string): void {
    on({id: id + '.ACTUAL', change: "ne"}, async function () {
            GeneratePage(activePage);
    });
} 

function GeneratePowerPage(page: PagePower): Payload[] {
    try {
        activePage = page;
        
        let id = page.items[0].id;

        if (Debug) {
            console.log(page.items[0].id);
        }
        
        unsubscribePowerSubscriptions();
        subscribePowerSubscriptions(id);
        
        let demoMode = false;

        try {
            id = page.items[0].id
        } catch (err) {
            console.log("Kein PageItem definiert - cardPower Demo-Modus aktiv");
            demoMode = true;
        }

        let heading = 'cardPower Example';
        if (demoMode != true) {
            let o = getObject(id)
             heading = page.heading !== undefined ? page.heading : o.common.name.de
        }

        const obj = JSON.parse((getState(page.items[0].id + '.ACTUAL').val));

        let out_msgs: Array<Payload> = [];
        out_msgs.push({ payload: 'pageType~cardPower' });

        //Demo Data if no pageItem present
        let array_icon_color = [White, MSGreen, MSYellow, MSGreen, MSYellow, MSGreen, MSRed];
        let array_icon = ['home', 'battery-charging-60', 'solar-power-variant', 'wind-turbine', 'shape', 'transmission-tower', 'car'];
        let array_powerspeed = ['', '-1', '2', '4', '1', '1', '5'];
        let array_powerstate = ['', '0,5 kW', '0,9 kW', '2,8 kW', '0,2 kW', '0,1 kW', '4,6 kW'];

        let arrayColorScale = [colorScale0, colorScale1, colorScale2, colorScale3, colorScale4, colorScale5, colorScale6, colorScale7, colorScale8, colorScale9, colorScale10]

        let homeIconColor = 0;
        if (!demoMode) {
            for (let obji = 0; obji < 7; obji++) {
                array_icon_color[obji + 1] = arrayColorScale[obj[obji].iconColor];
                array_icon[obji + 1] = obj[obji].icon;
                array_powerspeed[obji + 1] = obj[obji].speed;
                array_powerstate[obji + 1] = obj[obji].value + ' ' + obj[obji].unit ;
            }
            array_icon[0] = obj[0].icon;
            array_powerstate[0] = obj[0].value + ' ' + obj[0].unit;
            homeIconColor = obj[0].iconColor;
        }

        let power_string : any = '';

        for (let i = 1; i < 7; i++ ) {
            power_string = power_string + rgb_dec565(array_icon_color[i+1]) + '~';    // icon_color~
            power_string = power_string + Icons.GetIcon(array_icon[i+1]) + '~';       // icon~
            power_string = power_string + array_powerspeed[i+1] + '~';                // speed~
            power_string = power_string + array_powerstate[i+1] + '~';                // entity.state~
        }

        power_string = power_string.substring(0, power_string.length - 1);

        out_msgs.push({
            payload: 'entityUpd~' +                         //entityUpd~*
                heading                         + '~' +     //internalNameEntity*~*
                GetNavigationString(pageId)     + '~' +     //navigation*~*
                rgb_dec565(array_icon_color[homeIconColor]) + '~' +     // icon_color~      Mitte
                Icons.GetIcon(array_icon[0])    + '~' +     // icon~            Mitte
                array_powerstate[0]             + '~' +     // entity.state~    Mitte
                power_string
        });

        return out_msgs

    } catch (err) {
        console.warn('function GeneratePowerPage: ' + err.message);
    }
}
```

**Comment by Hobbyflyer** [comment]
OK than please do not change anything. Cause my solution  with reading CustomSend to determine that the CardPower is selected works. If so i create a custom send, an write new data to the display to update values. I only have problems when time or weather was send, cause the string changes ans value updates stops. But thats ok

**Comment by Armilar** [comment]
I can't find the page number either. At most the content of the current variable or e.g. a headline. If that should be enough, I could provide that.

**Comment by Hobbyflyer** [comment]
![IMG_20221130_195200](https://user-images.githubusercontent.com/47834021/204897661-6c4e5f7b-db87-4bad-bcb5-ef143e898c7b.jpg)
![IMG_20221130_195131](https://user-images.githubusercontent.com/47834021/204897674-b3eac93e-16c6-47b7-bcde-7f82b0d7c29c.jpg)
First image what expect
second image that i get. But both images changes fast. -> flickering

**Comment by Armilar** [comment]
![image](https://user-images.githubusercontent.com/102996011/204899571-17f14519-382d-44e7-b9a0-e106f7970d18.png)

I can provide you with that. Then you can implement it yourself however you want

**Comment by Hobbyflyer** [comment]
Solved it with
function GeneratePage(page: Page): void {
    try {
        activePage = page;
        **setState(NSPanel_Path + 'ActivePage',page.heading);**

Thanks
