### ISSUE TITLE
[Help] ONLY INFO

### ISSUE THREAD

**Issue by wifi75** [joBr99/nspanel-lovelace-ui#590]
hello sir,
sorry I'm disturbing you, I just wanted to know if I can directly update the tasmota32.nspanel.bin file directly from this interface of mine, I don't remember which firmware I wrote some time ago via USB serial.
Do you think I can blashare directly via ota or do I have to disassemble everything and do everything with the usb-serial?

![image](https://user-images.githubusercontent.com/31816231/203261000-2fb02c6e-2153-4bc7-b48a-2db488f95695.png)

**Comment by joBr99** [comment]
yes, this should work

https://community.home-assistant.io/t/revert-to-tasmota-using-ota/106847
