### ISSUE TITLE
[Feature Request] IOBroker: Make central power card icon exchangeable

### ISSUE THREAD

**Issue by beandi** [joBr99/nspanel-lovelace-ui#597]
### FEATURE DESCRIPTION
(IOBroker Typescript) The central "home"-icon on the power card should be choosen by the user, the home-icon is not always perfect to mimic the energy flow.

### ADDITIONAL CONTEXT
The first icon in the passed array is the central one and "hard coded" in the typescript ("home"), maybe make it a variable in the user-defined block?

### PANEL / FIRMWARE VERION
EU

With an alternative icon:
![NSPanel_EnergyFlow](https://user-images.githubusercontent.com/25351649/204219701-9576a216-4c91-4630-be81-746dc63ab007.jpg)

**Comment by randybb** [comment]
Make sense, it can be a RV, a boat or a castle :)

**Comment by beandi** [comment]
> Make sense, it can be a RV, a boat or a castle :) This is already possible `entityUpd~heading~navigation~colorHome~iconHome~textHome[~iconColor~icon~speed~valueDown]x6` So you mean the central fusion icon. Probably all icons should be templetable as you could use the same card for gas, water, beer,.. whatever.
It's not possible yet in the nspanel.ts for IOBroker, sorry this was not clear enough.
The central icon by default is a "Home"-Icon, as in my picture on the right. When i want to visualize the summed-up flow to the "home", the icon in the middle should be something different (like the fusion icon i.e.)

**Comment by Armilar** [comment]
> from v3.6.0.4

![image](https://user-images.githubusercontent.com/102996011/204798975-fea10294-c5b6-46fc-8c6f-ab5bd734b412.png)    
  
use id: 0
![image](https://user-images.githubusercontent.com/102996011/204799555-d2be3cfb-39ee-4e19-88b9-e6e72250b3cf.png)  

![image](https://user-images.githubusercontent.com/102996011/204800304-a0d984dd-b4b2-441d-92d7-8a3c8d9c12c5.png)  

![image](https://user-images.githubusercontent.com/102996011/204800847-5823b35a-1508-4496-8efe-3d5c6d6f5568.png)  
Wert, Einheit und Farbe können ebenso genutzt werden
