### ISSUE TITLE
touching is not accurate

### ISSUE THREAD

**Issue by hatran0884** [joBr99/nspanel-lovelace-ui#60]
Hi, your work is simply amazing, took a bit more time to install intially but after all were setup, i can easily configure and put what i want

however, i dont know if you have similar issue, but touching on my device is not accurate, i meant that if i press a button, i will have to press a bit far away to the right side from the button position, it happens to all other buttons, all go abit to the right side. i am not sure if i need to do some touch calibration but i didnt have issue with ESPHome. 
let me know if it can be resolved ?

**Comment by joBr99** [comment]
Do you have an US or EU version?

**Comment by hatran0884** [comment]
i have a US version

**Comment by hatran0884** [comment]
you are correct again, removing the line lcd_dev solved my problem. i see the UI element still are centered, all look in proper positions. but i have a popup saying there is an update available, so it means i cannot update to new version for now ?

**Comment by hatran0884** [comment]
you are right, i have just noticed a bit offset on the right side, but its not really annoying because you set the background to be fully black so the offset is hardly noticeable.
