### ISSUE TITLE
[BUG] Flashing Issues on Tasmota Dev Version after 12.2.0.3

### ISSUE THREAD

**Issue by joBr99** [joBr99/nspanel-lovelace-ui#601]
Please downgrade to the current release binary of tasmota if your version is greater then 12.2.0.3.

http://ota.tasmota.com/tasmota32/release-12.2.0/tasmota32-nspanel.bin

**Comment by joBr99** [comment]
Currently testing different Versions, to figure out which commit broke the flashing.

Tasmota 12.2.0.1 - 100e95f2c - works
Tasmota 12.2.0.3 - 18ec24b86 - 7th of November - works

Tasmota 12.2.0.5 - 783631903 - broken

**Comment by dodavies** [comment]
I flashed my panel out of the box today using the Tasmota webpage to flash it and then tried to flash the screen and received this 80808080 error.
reverted to the version listed above and it is currently flashing with no issue

**Comment by Xenon69** [comment]
I flashed my panel today using the Tasmota current version to flash it and then tried to flash the screen and received this 80808080 error.
reverted to the version listed above and it is currently flashing with no issue
panel showing "waiting for content", I think I need to continue the configuration

**Comment by LucaBors** [comment]
Hi, with 12.3.1 update is broken.

**Comment by joBr99** [comment]
hey, can you delete autoexec.bec and replace the content of autoexec.be with the content from here:

https://raw.githubusercontent.com/joBr99/nspanel-lovelace-ui/main/tasmota/autoexec.be

and retry?

**Comment by federicosantolini** [comment]
Unfortunately same issue. deleted the autoexec.bec, replaced the autoexec.be, rebooted and flashed again. no more "something went wrong error but it freezes at 23%
![image](https://user-images.githubusercontent.com/9
![20221227_084929](https://user-images.githubusercontent.com/94896891/209631436-7273e1d1-fc8c-4619-baf2-c1aa1ddc4385.jpg)
4896891/209631240-fd416700-675c-4bdb-b83a-214c95195051.png)

**Comment by joBr99** [comment]
Hey @federicosantolini,
which tasmota version are you using?
Is this the first time flashing the firmware?
What was installed before? Stock firmware?
Did you try to power cycle and retry the flashing?

**Comment by federicosantolini** [comment]
Ciao @joBr99, the verision is **12.3.1**
it worked fine for a couple of months with tasmota and all the custom dashboard from HA. After a long power cut in my house it came back like this. I tried everything I saw in your github but i'm still like this. maybe the power cut damaged it... all the sensors and buttons are working perfectly fine. if you need any kind of log please let me know

**Comment by federicosantolini** [comment]
i Hey there! Sorry for the late reply... I did answer yesterday but it looks like I never actually posted it, so here it is again! :)
I tried the link you sent me too but it's still getting stuck in the same way. From what I can see, it always stops after about 50-55 seconds of transfer, so like you said, it could be a connection issue. I'm not sure what to do though, my NSPanel is in a spot where it gets perfect WiFi and it never disconnects... it just seems to stop after about 55 seconds. I'm attaching a couple of images to show you.

This picture is from the 115200 baud flash
![image](https://user-images.githubusercontent.com/94896891/211215651-94ec7ed7-2d3a-4df1-a866-d687aa95f404.png)

This one is with the standard link
![image](https://user-images.githubusercontent.com/94896891/211215800-41f68a8e-8eef-4b1f-a1eb-c0a61aae1709.png)

As you can see it stops approximately after the same amount of seconds, every time.
Do you have any documentation I can read to flash the firmware directly? Thanks a lot!

**Comment by joBr99** [comment]
there are two test points (Screen TX/RX) on the screen that you can use to flash it with the nextion editor (use version 1.63.3)

https://nextion.tech/download/nextion-setup-v1-63-3.exe
https://nextion.tech/download/nextion-setup-v1-63-3.zip

Open the HMI file from the repo and flash it though the editor.

![image](https://user-images.githubusercontent.com/29555657/211215899-8bd41a53-e34c-4fe6-ba32-48f002ac8973.png)

Note that you need to connect TX-TX and RX-RX, because the labels are from the POV of the ESP32.

**Comment by federicosantolini** [comment]
Thanks so much for your help! I finally managed to flash the firmware from a local server on the fifth try. It took a while but it worked! Now I'm trying to reconfigure everything. The only problem I see right now is a red bar on one side of the screen that I need to figure out how to remove, but everything else seems to be going well! Thanks again!
![20230108_212902](https://user-images.githubusercontent.com/94896891/211217652-fccca3f0-bafa-464f-8982-5e190d69ca18.jpg)

**Comment by joBr99** [comment]
you got the wrong firmware; this red bar only appears if you have the EU firmware on an US model

**Comment by federicosantolini** [comment]
i flashed the eu on my eu model (i think it's an EU model, the rectangular one)

**Comment by joBr99** [comment]
Dimension
NSPanel-EU: 86x86x41.7mm
NSPanel-US: 120x74x41.7mm

square one is the EU version

![image](https://user-images.githubusercontent.com/29555657/211217909-492b980e-8dbd-4c4a-a3ec-21f63212550d.png)

**Comment by federicosantolini** [comment]
Finally everything is working properly! Unfortunately on amazon.it it wasn't specified if it was EU or US, and I didn't have the NSPanel box anymore to check. I'm really grateful for the help you provided! Thank you so much and sorry for really bothering you and for the often banal questions I asked!
