### ISSUE TITLE
[Feature Request] (IOBroker) Multiple sub-pages under one target

### ISSUE THREAD

**Issue by beandi** [joBr99/nspanel-lovelace-ui#602]
### FEATURE DESCRIPTION
Not sure if i understand the actual navigation scheme correctly, but to my knowledge it's only possible to have one subpage per "navigation button". 
So i.e. i  have 8 lights, which i want to reach on a "lights"-subpage. Currently i need a "lights_1" and a "lights_2" subpage navigation item because of a maximum of 4 (or 6) items per page.
It would be nice to have those two subpages automatically "side-by-side", the back-button could stay on the left top (facing upwards) while a next button on the right cycles through the subpages on this level.
Also the back button in the subpages should be a "up"-arrow by default.

### ADDITIONAL CONTEXT
The differentiation of subpages on the same level could be made by some characters in the id? "__1", "__2" etc.?

### PANEL / FIRMWARE VERION
EU

**Comment by Armilar** [comment]
You mean that when you go to a subpage, you reach another subpage on the right side (i.e. scroll subpages)?

Unfortunately, this is not possible with the navigation scheme. I don't think it's going to happen any time soon either. Possibly for a much later version, since the navigation would have to be adjusted a lot.

For the back buttons, two are already planned for future versions. Up arrow and home button

**Comment by mikosoft83** [comment]
The way I'm doing it I just sacrifice one entity (I use only grid card) for a navigation item to a "next" card
E.g. on main card I'd have a navigation item that goes to "lights_1"
and in "lights_1" I have another navigation item that goes to "lights_2"
Both lights cards are hidden so a back button handles the navigation back.
It's not the best solution but it's doable and it works

**Comment by Armilar** [comment]
with ioBroker TypeScript-Release  v3.7.3.3

![image](https://user-images.githubusercontent.com/102996011/210279230-ced8d902-f307-4f63-9333-1fbaa41247f8.png)

![image](https://user-images.githubusercontent.com/102996011/210279260-5c01eb07-8b20-4440-86d1-507fb3ccdfa1.png)
