### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by HadiHassaoui** [joBr99/nspanel-lovelace-ui#605]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._

Having a Background image (jpg, gif, png), and if it can change based on entity state (a sun for the day and a moon for night exemple), if no space, can it call a url

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
Theres no problem, only a feature request.
### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
US-P

**Comment by joBr99** [comment]
this is not possible Nextion Display doesn't support transfering a picture at runtime; pictures need to be embedded in the firmware
