### ISSUE TITLE
[Feature Request] Add thermostat temperature to screensaver / Alternative Screensaver Layout?

### ISSUE THREAD

**Issue by GravitySandwichh** [joBr99/nspanel-lovelace-ui#607]
### FEATURE DESCRIPTION
Have the option to also show current temperature of a temp sensor on the screensaver

### ADDITIONAL CONTEXT
I use my NSPanel as a thermostat, it would be great if i could see it's current temperature of any assigned sensor instead of just the outside weather. 

### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
I'm personally showing the temperature in the upper right corner with an icon in case it's currently heating.

```
    screensaver:
      entity: weather.k3ll3r
      statusIcon1:
        entity: sensor.temp_wohn_humidity
        icon: 'ha:{{int(states("sensor.temp_wohn_humidity"))}}%'
      statusIcon2:
        entity: climate.wohnzimmer_boden
        icon: 'ha:{{iif(state_attr("climate.wohnzimmer_boden", "hvac_action")=="heat", "梅 ", "", "")}}{{int(state_attr("climate.wohnzimmer_boden","current_temperature"))}}°'
```

Alternatively you can replace one of the forecast icons like this:

```
    screensaver:
      entity: weather.k3ll3r
      weatherOverrideForecast4:
        entity: sensor.example_item
        name: name
        icon: lightbulb
```

**Comment by GravitySandwichh** [comment]
Issue is that both of these currently are only able to show it smaller than the current weather right now. If possible, i would rather have a big temperature and a small weather.

**Comment by ArcadeMachinist** [comment]
I guess it fits into this feature request.

Is there a way to override "main" weather temperature?
I see all 4 forecasts are overridable, but main one is not.
I would really prefer current temperature being read from a local sensor.

**Comment by joBr99** [comment]
@ArcadeMachinist 
Create a Weather Template in HomeAssistant, this has also the benefit that you can use the weather widget with the local temp in the HA UI.

https://www.home-assistant.io/integrations/weather.template/

**Comment by LucaBors** [comment]
Hi Jo i'm adding a request if possibile. 
I'd like to have my personal temperature sensor in the screensaver replacing the "internet" weather temperature. Is this something possibile? I'm asking because the provider i'm using is not really reliable regarding temperature.

**Comment by joBr99** [comment]
Yeah, an alternative screensaver layout is definitly possible, I also thought about this.

Could somebody draw an "mock-up" to get some ideas?

I was thinking about a vertically divided screensaver with the time on the left side.

12 | other elements
34 | other elements

**Comment by joBr99** [comment]
@LucaBors this is possible with a weather template

https://www.home-assistant.io/integrations/weather.template/

**Comment by joBr99** [comment]
@andrei-micu-ro did your experiments with an alternative layout come to an result?

**Comment by andyxpert** [comment]
yeah, worked beautifully
I'm on mobile now, in a few hours I'll share some screenshots of my HMI
In a few words:
- background with transparent items
- temp/humid on screensaver
- bigger fonts for some elements
- some extra custom status icons at the top
- plan on adding some state icons predefined for thermostats/climate and others (washer, dishwasher status, etc)
- plan on adding a second screensaver for extra statuses

It's a pitty we can't have collaborative iterative work on HMI :(

**Comment by LucaBors** [comment]
> 

this is super cool! work perfect! :)

**Comment by joBr99** [comment]
And you can also use this template in the homeassistent dashboard :)

**Comment by nicolas-lang** [comment]
Hi, 
I am not sure if this might be a separate Feature request, but I would consider it an "Alternative Screensaver Layout".
I think more flexibility for the screensavers would be nice I would love to see the option to replace the forecast with a "graph"

### Graphs as a Screensaver
I am very conscious of the air pressure as it affects me quite a bit and I would love to have the possibility do display a simple bar or line graph like:
![image](https://user-images.githubusercontent.com/635895/211006470-7adcf517-a823-4e49-9aa7-12ef074b5594.png)

**Comment by joBr99** [comment]
there are no graphs in nextion

we are working on a custom made card with a graph, that is drawn manually, but this will be limited to that card

**Comment by nicolas-lang** [comment]
Oh, I wasn't aware of that limitation.

What about displaying an externally pre-rendered image? (as a separate card and as a replacement of parts/all of the screensaver)

That should even give some additional flexibility for various other use-cases

**Comment by joBr99** [comment]
nextion doesn't allow to transfer pictures to it on runtime

**Comment by andrei-micu-ro** [comment]
Graphs, niiiiiice :D

I had a tryout a while ago with some graph-like design where I had around 10 small sliders side-by-side, each linked to a custom template sensor in HA (which held the previous 10 values), but it doesn't look that nice, also you have to have automations in HA to update those "custom" sensors' values periodically (every 15-30 mins or so).
Scaling however is horrible as if you want better resolution you'll need to create more such sensors paired with the sliders.

Another idea was based on images and I had 10-20 "bold bullet" images that I moved around programmatically to trace somewhat of a graph - again it looked horror

@nicolas-lang - I suggest you install the Nextion Editor and play with it so you better understand what limitations exist and what you can do with it.
As stated, all images need to be pre-bundled in the image and you can't transfer anything new, you can only "play" with the objects bundled. The same goes for fonts (which need to be defined character-by-character and added to the image.

**Comment by joBr99** [comment]
@andrei-micu-ro 
https://github.com/joBr99/nspanel-lovelace-ui/wiki/ioBroker-Card-Definitionen-(Seiten)#cardchart-ab-ts-script-v370

It's acually already implemented on the HMI Side and on ioBroker; only missing implementation for AppDaemon/HomeAssistant

**Comment by koffienl** [comment]
> ### FEATURE DESCRIPTION
> Have the option to also show current temperature of a temp sensor on the screensaver
> 
> ### ADDITIONAL CONTEXT
> I use my NSPanel as a thermostat, it would be great if i could see it's current temperature of any assigned sensor instead of just the outside weather.
> 
> ### PANEL / FIRMWARE VERION
> EU

Although I would like some bigger font, for now I just send the temperature as a notification to the nspanel with a automation.
I don't need the forecast at all, I just want to see the temperature (date and time is nice, but could be smaller).

```
  - service: mqtt.publish
    data:
      payload_template: >-
        notify~{{ states.sensor.woonkamer_temperatuur.state }} °C~Buiten: {{
        states.sensor.weather_temperature.state }} °C
      topic: cmnd/nspanel_woonkamer/CustomSend```

**Comment by koffienl** [comment]
> PLease any idea how to get single sensor number (temperature sensor) instead of the whole weather forecast? Is there right now some easy way how to show bigger temperature number under the time and date? (on screensaver). Sorry but can´t realize hot to change weather template to show the defined sensor temperature. Thanks.

Like I said; just send a notification to the nspanel. It will fully overwrite the forecast on the screensaver.

```alias: Push woonkamer temperatuur naar NSPanel
description: ""
trigger:
  - platform: time_pattern
    minutes: /1
condition: []
action:
  - service: mqtt.publish
    data:
      payload_template: >-
        notify~{{ states.sensor.woonkamer_temperatuur.state }} °C~Buiten: {{
        states.sensor.weather_temperature.state }} °C
      topic: cmnd/nspanel_woonkamer/CustomSend
  - service: mqtt.publish
    data:
      payload_template: >-
        notify~{{ states.sensor.woonkamer_temperatuur.state }} °C~Buiten: {{
        states.sensor.weather_temperature.state }} °C
      topic: cmnd/nspanel_hal/CustomSend
    enabled: false
mode: single
```

Perhaps you can play with the alternative notification?
https://github.com/joBr99/nspanel-lovelace-ui/issues/510

**Comment by joBr99** [comment]
Use the actual name of your weather entity; replace `weather.` and `weather.my_region` with your weather entity. (You've already used that in apps yaml)

**Comment by numerobis08** [comment]
Rh si you Igor quick feedback. 
I the template I cannot find weather. I can only find weather.my_region so means it should be like this below ?

weather:

platform: template
name: "My Weather Station"
condition_template: "{{ states('weather.') }}"
temperature_template: "{{ states('sensor.capteur_fenetre_device_temperature') | float }}"
humidity_template: "{{ states('sensor.humidity') | float }}"
forecast_template: "{{ state_attr('sensor.capteur_fenetre_device_temperature', 'forecast') }}"

**Comment by numerobis08** [comment]
It worked thanks :-)

**Comment by jiripaskov** [comment]
> 

Thanks but sorry. I didn´t mean just to show only temperature. I would like to show standard screensaver with time and date but this sensor temperature in the size of weather icons (instead of weather). Notification will show only the notification text...

**Comment by joBr99** [comment]
![image](https://user-images.githubusercontent.com/29555657/213819364-d4266571-f169-48b2-857e-87f9a4518b59.png)

Slightly changed alternative screensaver layout to get space for two big temperatures.

**Comment by joBr99** [comment]
Config Example:
```
    screensaver:
      doubleTapToUnlock: True
      entities:
        - entity: weather.k3ll3r
        - entity: weather.k3ll3r
          type: 0
        - entity: weather.k3ll3r
          type: 1
        - entity: weather.k3ll3r
          type: 2
        - entity: weather.k3ll3r
          type: 3
        - entity: sensor.temp_wohn_temperature
          icon: mdi:home-thermometer-outline
```

**Comment by zunaidhoorjook** [comment]
Has the above been tested with the US-Potrait model of the NSPanel?
