### ISSUE TITLE
temp up and down does not work in the themorstat page

### ISSUE THREAD

**Issue by hatran0884** [joBr99/nspanel-lovelace-ui#61]
Hi, one more issue related to the temp control in the themorstat page. i actually can turn on or turn off or set modes but unable to increase the temp or descrease temp.

**Comment by joBr99** [comment]
Will check later, might be broken with the latest update.

**Comment by detlefh68** [comment]
Hi, I also installed my NSPanel with lovelace-ui and I'm totally hooked! Thank you for the great work!
Unfortunately, setting the temperature in the ThermoCard doesn't work for me either. The value on the display changes, but the value is not changed in the HomeAssistant.

**Comment by joBr99** [comment]
should be fixed with v1.7.3

**Comment by hatran0884** [comment]
yes, i confirm that it has been fixed in 1.7.3, however i found that there are 02 temp sensors named: Analog Temp which shows 28.7 degree and ESP32 Temp which shows 41 degree. both 02 sensors show higher temp then the actual my room temp so they  do not seem to be the ambient temp sensor. 
can i get the correct temp sensor to put into the themorstat page ?

**Comment by joBr99** [comment]
you need to calibrate the ntc in tasmota, search for adcparam

https://community.home-assistant.io/t/sonoff-nspanel-smart-scene-wall-switch-by-itead-coming-soon-on-kickstarter/332962/102
