### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by alexandrugai** [joBr99/nspanel-lovelace-ui#610]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide a screenshot of your tasmota mqtt configuration:

![mqttconfig](https://user-images.githubusercontent.com/47159620/206279763-34ceb941-a4fb-4b74-9c0c-f8be433b9591.png)

- [x] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:

![appdaemonyaml](https://user-images.githubusercontent.com/47159620/206279809-f172d973-a711-4a79-8929-6d44d9c9f77e.png)

```

- [x] Provide your apps.yaml:
```
  apps.yaml here:

![appsyaml](https://user-images.githubusercontent.com/47159620/206279844-0643836a-7569-4765-9630-f88b666784ee.png)

```
- [x] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:


```
![appdaemon1](https://user-images.githubusercontent.com/47159620/206279866-05c0e83d-c3ee-439c-8e1e-87c9718f392c.png)
![appdaemon2](https://user-images.githubusercontent.com/47159620/206279869-9973788a-7ec1-45af-aae9-7cc9d17f5fd3.png)

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_

**Comment by BaetensJan** [comment]
In your apps.yaml file, change the 'tasmota_%06X' references to tasmota_7BE638 which is the id that your tasmota will use

**Comment by alexandrugai** [comment]
it worked... thank you for your time
i didn't think it was that simple
