### ISSUE TITLE
[Feature Request]  Activate buzzer while touching the screen

### ISSUE THREAD

**Issue by wunderbaum** [joBr99/nspanel-lovelace-ui#612]
### FEATURE DESCRIPTION
It would be nice to have a audio feedback when touching the screen to walk through the pages.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU

**Comment by joBr99** [comment]
you can do this in your tasmota console; however it's not going to be perfect

```
rule3 on CustomRecv do Buzzer 1 endon
rule3 1
```

**Comment by wunderbaum** [comment]
Thanks alot!
At least it works, but it buzzes 2,3,4 times and not just a simple _click_.

**Comment by joBr99** [comment]
I guess this is related to the PWM mode do you have a click or a beep?

The correct mode for the buzzer on nspanel is PWM, you can enable it with `BuzzerPWM 1`. (even though it will be a beep than)

you can customize your beep by playing around with the paramters of the buzzer command

https://tasmota.github.io/docs/Buzzer/#buzzer-command
