### ISSUE TITLE
[BUG] Custom icon in scene entities is not shown in cardGrid

### ISSUE THREAD

**Issue by soyxan** [joBr99/nspanel-lovelace-ui#615]
### PROBLEM DESCRIPTION
The custom icon configured in a `scene` entity is not shown in the `cardGrid` screen. Instead, it shows the default one (paint palette)

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide your apps.yaml (or your config):
```
  apps.yaml here:
    cards:
      - type: cardGrid
        title: General
        entities:
          - entity: light.shellyrgbw2_808277_channel_4
          - entity: light.tz3000_jl7qyupf_ts0012_50beb7a8_on_off
          - entity: scene.cama
          - entity: scene.dormir

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
For instance, in the scene configuration in HA I choose `mdi:movie` icon, but in the NSPanel the `mdi:palette` is shown instead.

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
I know that I can override the icon in the `apps.yaml` file but in order to avoid duplicates I expect that the custom icon defined in HA scene should be displayed

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU 3.6.0

**Comment by joBr99** [comment]
The icons are not exposed over the HA API, you have to configure them in apps.yaml aswell.

```
- entity: scene.cama
  icon: mdi:lightbulb

```

https://docs.nspanel.pky.eu/entities/?h=icon#override-icons-or-names
