### ISSUE TITLE
time in the screensaver is not accurate

### ISSUE THREAD

**Issue by hatran0884** [joBr99/nspanel-lovelace-ui#62]
Hi, third issue but i am not sure if it actually is an issue but the time in the screensaver is not accurate, i live in Vietnam so i set locale to be vi_VN but the screen still shows 7-8 hours behind our actual time. 
for your info, i installed appdaemon as a docker container and have no idea of how to install a babel package which might be the cause of this issue
appreciate if you could help.

**Comment by joBr99** [comment]
Babel doesn't do anything with the time, you need to fix the Timezone within your docker container.

**Comment by hatran0884** [comment]
you are correct, i have set the container time and the screen now shows the correct  time. thanks. you can close this issue.
