### ISSUE TITLE
Send data to Nextion

### ISSUE THREAD

**Issue by piotrkapustka** [joBr99/nspanel-lovelace-ui#623]
### FEATURE DESCRIPTION
_I would like to send Nextion additional data. 
I am using the command

Nextion t0.txt="hello"

but i can't send

Nextion sensortemp.val=globaltemp

where globaltemp is a variable from Tasmota.
How can I do this?._

### ADDITIONAL CONTEXT
_I would like to not send some data after mqtt._

### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
This is not going to work. What exactly are you trying to archive? If you want to display values from tasmota, just configure the entity of the value in apps.yaml

**Comment by piotrkapustka** [comment]
Thank you for the quick reply.
I would like to run the panel without HA and I am looking for an idea how to send data via UART as Nextion commands [time, temperature, setpoint etc]

**Comment by joBr99** [comment]
Are you using a home automation system? 

There are already alternative backends for ioBroker, ip symcon and also something for openhab written in node-red.
