### ISSUE TITLE
[Feature Request] Make Pages transparent and add nice Background

### ISSUE THREAD

**Issue by thundergreen** [joBr99/nspanel-lovelace-ui#625]
### FEATURE DESCRIPTION
The functionality is really awesome. Unfortunately my wife "complaint" about the design a bit. It would be awesome having either the possibility to define the page background color or transparency or taking a background image.

### ADDITIONAL CONTEXT
I don't know if this is technically possible with Nextion but it would be a nice option

### PANEL / FIRMWARE VERION
EU - Latest Firmware

**Comment by joBr99** [comment]
Nextion doesn't support transparency or the transfer of pictures on runtime. However you can open the HMI project add add a background, which works to some extend, still no transparency.

You can configure the background color with `defaultBackgroundColor`. Even though it is not documented you can also use RGB values there, however you will see the lack of transparency support on sliders and switches.

https://docs.nspanel.pky.eu/config-overview/
