### ISSUE TITLE
cardThermo - Icons wrapped

### ISSUE THREAD

**Issue by ClaireRovic** [joBr99/nspanel-lovelace-ui#631]
![1671953268055](https://user-images.githubusercontent.com/52806118/209460568-632f7115-a229-4ca8-8865-b04dc8997dd5.jpg)

As can be seen by the above image the icons for the Thermo card take up two lines. This does make it look a bit strange.

**Comment by joBr99** [comment]
hey, 
checkout the development version (no need to run the flashnextion command)

I've disabled the spaceing for us-p

**Comment by joBr99** [comment]
added to 3.7.3
