### ISSUE TITLE
[Feature Request] Berry driver TAPP file instead of autoexec.be

### ISSUE THREAD

**Issue by soyxan** [joBr99/nspanel-lovelace-ui#632]
### FEATURE DESCRIPTION
Distribute the berry driver as a TAPP (Tasmota application) file instead of autoexec.be, this way if anyone is using a custom made autoexec.be file (like me) it will not be overwritten when updating from the screen.

### ADDITIONAL CONTEXT
As per the Tasmota documentation: Any file with .tapp (Tasmota Application) extension will be considered as an uncompressed ZIP, and if it contains a sub-file autoexec.be it will be executed.
https://tasmota.github.io/docs/Tasmota-Application/

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
I do not really see a benefit in this, what do you have in your autoexec.be? 

Updates to the berry driver are really rare, for example there was no new version from April to end of November. It only needs to be altered if something in tasmota changes that breaks the berry driver.

**Comment by soyxan** [comment]
I implemented some custom scripts in my NSPanel to fully integrate the Tasmota thermostat in HA. but anyone could have any other requirement that needs a custom autoexec.be file. What I need to do now is to rename your autoexec.be file and import it from my autoexec.be.
Also, I think that the purpose of the TAPP files is specifically designed for this case, as your driver will be properly identified in the Tasmota file system, avoiding any unintended modification/deletion, in fact, Tasmota has many applications that are already distributed this way, for instance, the OpenHASP implementation in Tasmota ( https://tasmota.github.io/docs/HASPmota/ )

**Comment by joBr99** [comment]
Will have a look; yes you can rename it without any issues and just load it from your autoexec. (That's actually how it's done in the project with the stock firmware)

**Comment by joBr99** [comment]
There is now a .tapp file in the repo you can install the driver with

```
Backlog UrlFetch https://raw.githubusercontent.com/joBr99/nspanel-lovelace-ui/main/tasmota/nsp-lovelace-driver.tapp; Restart 1
```

There is a mecanism implemented for the migration from autoexec.be to tapp, but since this requires the new berry driver this will be done in some future release. Until the switchover the backend won't do automatic updates of the tapp driver.

**Comment by joBr99** [comment]
Initial Installation of tapp driver:
```
Backlog UrlFetch https://raw.githubusercontent.com/joBr99/nspanel-lovelace-ui/main/tasmota/nsp-lovelace-driver.tapp; Restart 1
```
Initial Installation of autoexec driver:
```
Backlog UrlFetch https://raw.githubusercontent.com/joBr99/nspanel-lovelace-ui/main/tasmota/autoexec.be; Restart 1
```

Update and migration to tapp driver, requires version 8 of the berry driver
````
UpdateDriverVersion https://raw.githubusercontent.com/joBr99/nspanel-lovelace-ui/main/tasmota/nsp-lovelace-driver.tapp
```
Update of autoexec driver
```
UpdateDriverVersion https://raw.githubusercontent.com/joBr99/nspanel-lovelace-ui/main/tasmota/autoexec.be
```

**Comment by soyxan** [comment]
Thanks for the quick work!

I have seen that the `UpdateDriverVersion` command in the berry driver implements both ways of updating (.tapp or .be), but in the AppDaemon script `nspanel-lovelace-ui.py` the `desired_tasmota_driver_url` used in the `Updater` constructor (which underneaths calls the `UpdateDriverVersion` command), points only to the .be file (https://github.com/joBr99/nspanel-lovelace-ui/blob/main/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py#L38). I assume that in a future new version of this script, it will reference the .tapp file somehow, right?

**Comment by joBr99** [comment]
>There is a mecanism implemented for the migration from autoexec.be to tapp, but since this requires the new berry driver this will be done in some future release. Until the switchover the backend won't do automatic updates of the tapp driver.

Yes, at some point it will be changed to tapp.
