### ISSUE TITLE
[BUG] HMI - pageScreensaver - tNotifyText - Text wird abgeschnitten

### ISSUE THREAD

**Issue by stoepf** [joBr99/nspanel-lovelace-ui#653]
### PROBLEM DESCRIPTION
Die maximale Länge des Feldes ist auf 80 begrenzt.
Da durch wird der Text in der Mitte der zweiten Zeile abgeschnitten

### TO REPRODUCE
Per MQTT `notify~Lorem ipsum dolor sit amet~Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt` an NSPanel senden

### EXPECTED BEHAVIOUR
Begrenzung auf größer 120 Zeichen

### PANEL / FIRMWARE VERION
3.7.0 EU

**Comment by joBr99** [comment]
sind jetzt 120 zeichen

https://docs.nspanel.pky.eu/faq/#how-to-upgrade-from-a-release-to-the-current-development-version
