### ISSUE TITLE
[Feature Request] Screensaver Split statusIcons from weather command

### ISSUE THREAD

**Issue by Pol3cat** [joBr99/nspanel-lovelace-ui#654]
### FEATURE DESCRIPTION
Nextion Befehl/Payload um die Icons (oben rechts/links) und die Farbe der Textfelder auf den Screensaver direkt zu steuern.
Aktuell muss NotifyHead/Text leer sein damit diese angepasst werden können.
So ist man Flexibler.

### ADDITIONAL CONTEXT
z.B. 
```
if (tInstruction.txt=="IconUpdate")
{
    //statusIcon1
    spstr strCommand.txt,tIcon1.txt,"~",1
    spstr strCommand.txt,tTmp.txt,"~",2
    covx tTmp.txt,tIcon1.pco,0,0
    //statusIcon2
    spstr strCommand.txt,tIcon2.txt,"~",3
    spstr strCommand.txt,tTmp.txt,"~",4
    covx tTmp.txt,tIcon2.pco,0,0
    spstr strCommand.txt,tTmp.txt,"~",5
         if(tTmp.txt!="")
         {
             tIcon1.font=3
         }
    spstr strCommand.txt,tTmp.txt,"~",6
        if(tTmp.txt!="")
        {
             tIcon2.font=3
        }
}
```
```
if (tInstruction.txt=="ColorUpdate")
```
gleiche wie 'color' nur ohne Notify Bedingung.

### PANEL / FIRMWARE VERION
EU NSPanel

**Comment by joBr99** [comment]
hey, 
vermutlich wäre es am besten, wenn man die status icons bei dem weather update rausnimmt und die in einen eigenen command packt

hat den nachteil, dass es länger dauert den screensaver aufzubauen (weil mehere verschiedene commands) sollte aber beim screensaver nicht so schlimm sein

**Comment by joBr99** [comment]
added a new command `statusUpdate~icon1~icon1Color~icon2~icon2~icon2color~icon1font~icon2font`

the paramters are still part of the weatherupdate; so sending the data with the weather update is probably the best option for now, planning to remove that with 3.9.X

there are enough changes to the serial protocol for 3.8.X

**Comment by Pol3cat** [comment]
müsste das nicht
`statusUpdate~{icon1}~{icon1Color}~{icon2}~{icon2Color}~{icon1Font}~{icon2Font}`
sein?

Haste den Befehl mal getestet? Bei mir reagiert der nicht. Habe neuste Version geflashed

**Comment by joBr99** [comment]
ne hab ich nicht, kann ich machen, sollte aber gehen

wenn du in python nen format string benutzt, dann natürlich `statusUpdate~{icon1}~{icon1Color}~{icon2}~{icon2Color}~{icon1Font}~{icon2Font}`

**Comment by Pol3cat** [comment]
Habe die 
`FlashNextion http://nspanel.pky.eu/lovelace-ui/github/nspanel-v3.7.3.tft`
geflashed

irgendwie frisst er da nix

**Comment by joBr99** [comment]
nein, das funktioniert nicht, das ist ja das aktuelle release nicht die dev version

du musst die hier nehmen (aufpassen, hat auch die neuen parameter für die navigation)
EU VERSION: FlashNextion http://nspanel.pky.eu/lui.tft

**Comment by Pol3cat** [comment]
Ah ok. der Teufel steckt im Detail.

Die Navi haben wir schon angepasst

**Comment by joBr99** [comment]
paramters related to the status icons are removed from the weatherUpdate Command, however the weather update command has also changed to follow the enitiy scheme

![image](https://user-images.githubusercontent.com/29555657/213887544-8dbe96a1-6fbf-4cac-b7d4-cb8c9cfcf990.png)

this has also implications on the color command, because all colors related to icons have been removed from the color command

Examples are on the HMI Readme page

https://github.com/joBr99/nspanel-lovelace-ui/tree/main/HMI#screensaver-page
