### ISSUE TITLE
[BUG] NSpanel "waiting for content.." 

### ISSUE THREAD

**Issue by MaxLaMenace10280** [joBr99/nspanel-lovelace-ui#656]
Hello
after having prepared the settings of the Nspanel, I am stuck at the "MQTT on AppDaemon" part.
Indeed the NSPanel remains stuck on "waiting for content"
The settings look correct to me.
![image](https://user-images.githubusercontent.com/121713411/210140002-0d9659fe-2b50-41f9-b9c6-38aac4db6f8a.png)
![image](https://user-images.githubusercontent.com/121713411/210140995-a61d699c-15ff-4fee-9f32-36eaa9754c07.png)
![image](https://user-images.githubusercontent.com/121713411/210140103-0d0a8866-8eff-4d97-a1d3-720b3cf0869f.png)
![image](https://user-images.githubusercontent.com/121713411/210140825-51ebb44f-374d-4ddb-bb9f-5ed2f4a41bdd.png)

**Comment by joBr99** [comment]
You need to download the lovelace backend app in the homeassistant community store.

https://hacs.xyz/docs/setup/download/

![image](https://user-images.githubusercontent.com/29555657/210141063-fceab0ae-1347-42c3-834b-2743e039f117.png)

![image](https://user-images.githubusercontent.com/29555657/210141070-74ae83e0-cf7c-46f4-8956-ae2b319cb6b3.png)

**Comment by MaxLaMenace10280** [comment]
this is already uploaded

![image](https://user-images.githubusercontent.com/121713411/210149088-f98821b4-abf2-448d-8328-37cc459f4c35.png)

**Comment by joBr99** [comment]
Try to redownload or reinstall it, there has to be an Nspanel Lovelace UI folder in the Appdaemon folder.

**Comment by MaxLaMenace10280** [comment]
I've already done it, I even deleted and restarted my "home assistant" server

**Comment by joBr99** [comment]
deleted? so you are using homeassistant core with a docker container?

**Comment by MaxLaMenace10280** [comment]
no the home assistant supervisor on windows 10 with virtual box

**Comment by joBr99** [comment]
HACS is downloading to `/appdaemon/apps/nspanel-lovelace-ui`, without this folder and it's files it's not going to work.

try to use the redownload button in hacs

![image](https://user-images.githubusercontent.com/29555657/210149480-5ced7d17-a98e-42ec-adfe-3a1b89d40533.png)

**Comment by MaxLaMenace10280** [comment]
I already tried .
Since my restart I have this kind of message in the log (appdaemon) 
![image](https://user-images.githubusercontent.com/121713411/210149581-9280f68b-9b71-4b55-a4aa-af8dbae43242.png)

**Comment by joBr99** [comment]
Please paste your appdamen log after restarting the addon and your Appdaemon log here. there is something wrong with your mqtt config

**Comment by MaxLaMenace10280** [comment]
![image](https://user-images.githubusercontent.com/121713411/210149677-c6f72e01-c67a-4c0f-847f-f810ca6e8d3f.png)

**Comment by joBr99** [comment]
You are using '192.168.1.92' as your mqtt host in tasmota and '192.168.75.30'. The IP in Appdaemon conf is wrong.

**Comment by MaxLaMenace10280** [comment]
yes indeed it was me who made a mistake when restarting the server, but it's still the same
![image](https://user-images.githubusercontent.com/121713411/210150143-4a2ce965-97ed-4207-bf89-1316bacf0b72.png)

**Comment by joBr99** [comment]
might be related to your setup with virtualbox is 192.168.1.92 the ip address of your windows host?

you can try to use `core-mosquitto.local.hass.io` instead of the ip address

**Comment by MaxLaMenace10280** [comment]
where can i find this address ?

**Comment by joBr99** [comment]
put
```
       client_host: core-mosquitto.local.hass.io
```
into your config and try if that works

**Comment by MaxLaMenace10280** [comment]
![image](https://user-images.githubusercontent.com/121713411/210150653-dc48135e-038e-4ca3-b22e-fca485587742.png)

**Comment by joBr99** [comment]
this means that your username/password isn't correct

you can get addional information on this from the log of your mosquitto addon

**Comment by MaxLaMenace10280** [comment]
![image](https://user-images.githubusercontent.com/121713411/210150849-e1663240-6dff-42bb-9fd6-f3baa9ca411b.png)
it seems to be better, but my ns panel screen still shows the message "waiting..."

**Comment by joBr99** [comment]
yes your mqtt topics don't match

the logs says you have `tele/mqtt_user/RESULT` and in tasmota you are using `nspanel_entree` and not `mqtt_user`

adjust the panelRecv and Send in your apps.yaml

**Comment by MaxLaMenace10280** [comment]
sorry, i'm going to look stupid. lol
but it's always the same
![image](https://user-images.githubusercontent.com/121713411/210151125-631b4359-13d3-4973-8db0-e49a63d1fedf.png)

**Comment by joBr99** [comment]
There was a typo in my snippet, you are acually using `nspanel-entree` and not ``nspanel_entree` on your screenshot above.

```
    panelRecvTopic: "tele/nspanel-entree/RESULT"
    panelSendTopic: "cmnd/nspanel-entree/CustomSend"
```

**Comment by joBr99** [comment]
sorry `nspanel_entree` was correct please send the log in tasmota console

**Comment by MaxLaMenace10280** [comment]
MQTT =
![image](https://user-images.githubusercontent.com/121713411/210151343-a9ce4dc4-6021-4380-a8c8-a191be542867.png)
TASMOTA =
![image](https://user-images.githubusercontent.com/121713411/210151364-4bc09112-15d8-48b5-9916-f70f548574ff.png)
AppDaemon =
![image](https://user-images.githubusercontent.com/121713411/210151384-8edf3cdb-002c-4627-a99d-e7a3c2bbdc85.png)

**Comment by joBr99** [comment]
go to the tasmota console and check the log there

**Comment by MaxLaMenace10280** [comment]
![image](https://user-images.githubusercontent.com/121713411/210151534-e75d437e-a857-4597-b752-fdfcdcd36794.png)

**Comment by joBr99** [comment]
yeah as expected tasmota isn't able to connect

you are using the wrong ip address, what's the ip address you are using to reach homeassistant and is this ip also working from a different computer/your phone

**Comment by MaxLaMenace10280** [comment]
sorry, another error on my part, when restarting virtualbox the ip address had changed
I now have my nspanel working.
thank you very much for the help and sorry for the inconvenience
