### ISSUE TITLE
[Feature Request] Dynamic SleepTimeout

### ISSUE THREAD

**Issue by svdstra** [joBr99/nspanel-lovelace-ui#672]
### FEATURE DESCRIPTION
_Make it also possible to use a static value or an input_number/sensor as value for sleepTimeout._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_EU, latest version_

**Comment by joBr99** [comment]
hey, what's your use case for that?


In the meantime:
It's acually simple to build that yourself with an automation, just send `timeout~123` to the `cmnd/tasmota_your_mqtt_topic/CustomSend` Topic.

**Comment by koffienl** [comment]
Or use the ```sleepTracking``` option.
