### ISSUE TITLE
[BUG] Waiting for content since v3.8.2

### ISSUE THREAD

**Issue by chekdo** [joBr99/nspanel-lovelace-ui#673]
Hi,
Since I've upgraded the v3.8.2, my screen always says "Waiting for content". And I see nothing on MQTTExplorer in the cmnd.
I flash again the nspanel with the instruction : "FlashNextion http://nspanel.pky.eu/lovelace-ui/github/nspanel-v3.8.2.tft"
But it's always the same things.
Can you help me please? Have you got the same problem ?
Thanks

**Comment by joBr99** [comment]
Please fill out the requested information in the issue template.

![image](https://user-images.githubusercontent.com/29555657/211054247-e794ae0e-28be-4df1-95ad-938498eae496.png)

Especially without the appdaemon log, nobody is able to help you.
