### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by KrystianIOS** [joBr99/nspanel-lovelace-ui#679]
Hi, i have issue while im trying to download the lui-release.tft. When i execute "FlashNextion http://nspanel.pky.eu/lui-release.tft" only i got is:
17:47:12.287 RSL: RESULT = {"FlashNextion":"Done"}
17:47:12.323 FLH: host: nspanel.pky.eu, port: 80, get: /lui-release.tft
And wont download for no reason.
Any suggestions?
![ScreenShot 2023-01-07 174829](https://user-images.githubusercontent.com/80451824/211161516-45a0bbce-ce9e-4de5-8d92-10ac778c59cf.jpg)

**Comment by joBr99** [comment]
What's displayed on the panel? Stock Firmware? an Error message?

Did you try to reseat the serial cable?

**Comment by KrystianIOS** [comment]
> What's displayed on the panel? Stock Firmware? an Error message?
> 
> Did you try to reseat the serial cable?

Black screen is displayed. 
Yeah i tryied reseat the serial cable.

**Comment by joBr99** [comment]
A black screen without an error Message? So the screen isn't turned on? Did you apply the tasmota template?

https://docs.nspanel.pky.eu/prepare_nspanel/

**Comment by KrystianIOS** [comment]
> A black screen without an error Message? So the screen isn't turned on? Did you apply the tasmota template?
> 
> https://docs.nspanel.pky.eu/prepare_nspanel/

yeah, black screen without an error message. I did apply tasmota template a few times, will try to see if the screen is connected correctly.

**Comment by KrystianIOS** [comment]
If it dosent help i can also try repeat the installation.

**Comment by KrystianIOS** [comment]
so... the screen was connected wrong. After this all works fine. sorry for wasting your time. bye

**Comment by minestrone70** [comment]
In my case I forgot to flag the Activate option in the configure>Other page. After activating the template the display lit up
