### ISSUE TITLE
[Feature Request] Implement new popups for lights from HA 2023.03

### ISSUE THREAD

**Issue by sarahmva** [joBr99/nspanel-lovelace-ui#683]
### FEATURE DESCRIPTION
Addition of an alternative dimmer (iight) popup or card. The main feature on this card is a slider that is better to operate than the currently existing sliders. The slider should also be larger to allow for more precision.
![image](https://user-images.githubusercontent.com/68161487/211180310-c853ab11-6799-4ec7-a2a8-d1a5e562ce41.png)

### ADDITIONAL CONTEXT
When using the current light popup, I have discovered that the slider is hard to operate. In parts, this is related to the way the touch panel works, but size is also making dimming lights very hard. 

### PANEL / FIRMWARE VERION
NSPanel US - nspanel-us-p-v3.8.2.tft

**Comment by joBr99** [comment]
With HA 2023.3 there will be new popups for swiches / lights.

![image](https://user-images.githubusercontent.com/29555657/221420569-3f6c0e8d-ff24-455f-b7a9-1e31898d5d8b.png)

**Comment by joBr99** [comment]
unfortunately the new slider's from homeassistant are not possible with nextion, thoose rounded edged won't be possible and without them it looks quite crappy.

**Comment by Coding-Lion** [comment]
I think I have found a solution to achieve rounded corners, while still having all colors available:

https://github.com/Coding-Lion/nextion_experiments

**Comment by joBr99** [comment]
what did you use to generate this font?

**Comment by Coding-Lion** [comment]
I used Inkscape to create SVG files and then Icomoon to create the font.

**Comment by joBr99** [comment]
to match homeassistant's new silders it needs to be vertical instead of horizontal, did you try this aswell?

**Comment by Coding-Lion** [comment]
I haven't tried this yet, but I don't think it should be an Issue

**Comment by Coding-Lion** [comment]
I managed to get a vertical version working. I think it looks even better than the horizontal version:

https://github.com/Coding-Lion/nextion_experiments#vertical

**Comment by joBr99** [comment]
![image](https://user-images.githubusercontent.com/29555657/232340053-77d97def-587a-4340-8fc6-ecd01dcdf694.png)
![image](https://user-images.githubusercontent.com/29555657/232340083-040d07c6-4002-401f-90e2-f4669de15bd1.png)

@Coding-Lion try it on a real panel, it works ok-ish even though there are strange some color glitsches

Can you add the svg's you've used to your repo?

**Comment by joBr99** [comment]
Ended up with this:

```
//draw black background
fill hBrightness.x,hBrightness.y,100,hBrightness.val*-25/10+250,8484
//draw draw colored bar at the position of the current brightness value
fill hBrightness.x,hBrightness.val*-25/10+314,100,hBrightness.val*25/10,col.val
if(hBrightness.val>7)
{
  //draw cursor
  fill hBrightness.x+25,hBrightness.val*-25/10+322,50,4,WHITE
  //paint corner
  xstr hBrightness.x,hBrightness.val*-25/10+314,100,hBrightness.h,7,8484,0,0,0,3,"a"
}
//paint corners
xstr hBrightness.x,hBrightness.y,100,hBrightness.h,7,defaultBcoColor,0,0,0,3,"a"
xstr hBrightness.x,hBrightness.y+hBrightness.h-15,100,hBrightness.h,7,defaultBcoColor,0,0,0,3,"b"
```

Font only contains the corners:
![image](https://user-images.githubusercontent.com/29555657/233129934-9ef60dec-c659-4696-944c-4b47f162ea37.png)

**Comment by Coding-Lion** [comment]
Nice work! I think it look great!
