### ISSUE TITLE
[BUG] alarmcontrol broken

### ISSUE THREAD

**Issue by LucaBors** [joBr99/nspanel-lovelace-ui#691]
Ciao Jo,
there's something broken since 3.8.x with my alarm configuration. At the moment my "alarmcontrol" is no more able to identify if a windows is open.

my configuration is:
```
type: cardAlarm
entity: alarm_control_panel.casa
key: alarm
alarmControl:
entity: navigate.cardGrid_opensensors
status: binary_sensor.sensori_allarme_
```
Please note that i've a status icon in screensaver that work perfect with the same entity:
```
statusIcon2:
entity: binary_sensor.sensori_allarme
icon:
"on": mdi:window-closed-variant
"off": "text:"
altFont: True
```
Other than that also my config for this cardgrid (that show open door/windows) is broken and changing state to on/off does not affect the card:
```
- type: cardGrid
navItem1:
entity: navigate.home
icon: mdi:home
entities:
- entity: binary_sensor.porta_giardino_contact
name: Giardino Ingresso
state: "off"
```
Thank you for support!

**Comment by joBr99** [comment]
Hey @LucaBors,
this didn't see this issue for whatever reason.

I don't see any code changes on this feature, I think you need to specifiy the icon overwrites aswell on the alarmControl config.

Your yaml exaples are missing identation so I cannot tell if there is something wrong with them.

Please post them in code tags.

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by sarahmva** [comment]
I am not sure if this is the same issue I am seeing with the current release version downloaded from here:
http://nspanel.pky.eu/lui-us-p-release.tft (this also seems to be the version downloaded by the automatic firmware upgrade)

The result is this:
![image](https://user-images.githubusercontent.com/68161487/219271556-525e8db0-c4f3-4e5d-9161-d580a60e6c85.png)

When I use the 3.8.3 version (I found some change notice affecting the alarm panel) it works as expected.  
http://nspanel.pky.eu/lovelace-ui/github/nspanel-us-l-v3.8.3.tft

**Comment by sarahmva** [comment]
@joBr99 Strange, I had updated AppDaemon and restarted it a few days ago. Just did it again and now it works fine.

Sorry for the false alarm.
