### ISSUE TITLE
[Help] Original Nextion firmware request

### ISSUE THREAD

**Issue by soyxan** [joBr99/nspanel-lovelace-ui#692]
Hi, I have an issue with my NSPanels bought from iTead (not related at all to this awesome project). The manufacturer request me to send some videos of the problem and I prefer to not show that I flashed the NSPanel (in order to avoid warranty voiding), so I would like to get the original Nextion firmware in order to load it to the NSPanel ( just need the TFT file, I will prepare myself the http server to do the flashing with `FlashNextion `command).

Anyone could share it with me? Thanks!

**Comment by joBr99** [comment]
Have look here:
https://github.com/masto/NSPanel-Demo-Files/issues/4

**Comment by ChrisVonFrosta** [comment]
this "original" file not working for my NSPanel

**Comment by joBr99** [comment]
you need to download it and put it on an http server (for example the one build into homeassistant) - https is not working

**Comment by ChrisVonFrosta** [comment]
i did. it is on my raspi apache server.
i see two optiones. first: it says like "device not match". 
second (right now): it stucks on UART Update Screen
![IMG_5223](https://github.com/joBr99/nspanel-lovelace-ui/assets/16272493/cadb908b-923c-4ce9-9518-f155f7b7e442)

**Comment by joBr99** [comment]
The URL in your FlashNextion command is invalid.

It has to be something like `FlashNextion http://192.168.170.10/ns-panel.tft`

**Comment by ChrisVonFrosta** [comment]
Your are right... i put it in the public www folder and thought it is downloadable, but isn't.

**Comment by joBr99** [comment]
Use this one: `FlashNextion http://nspanel.pky.eu/stock-tmp2510.tft`

**Comment by ChrisVonFrosta** [comment]
thx! something is runnig :)

**Comment by ChrisVonFrosta** [comment]
Since here is no discussion, i do not want to crate a issue and you seems to be active ... ;)
i want to play with NSPanel without iobroker (or something else).
I would use berry script to create the interface or buttons.
That should be possible, shouldn't it?
Could you give me a short entrie point?
Sure it would presuppose NSPanel flahed with your file

**Comment by joBr99** [comment]
there is somebody that played with that aswell

https://github.com/schnurly/nspanel-lovelace-ui

Documentation of the serial protocol is here:

https://github.com/joBr99/nspanel-lovelace-ui/tree/main/HMI

**Comment by ChrisVonFrosta** [comment]
thx

**Comment by maxromanovsky** [comment]
> Use this one: `FlashNextion http://nspanel.pky.eu/stock-tmp2510.tft`

@joBr99 is it possible to get this firmware? URL mentioned by you returns 404

**Comment by joBr99** [comment]
you can download them from here, need to be copied to an http server:

https://github.com/masto/NSPanel-Demo-Files/issues/4

**Comment by maxromanovsky** [comment]
@joBr99 this link also gives 404: https://github.com/masto/NSPanel-Demo-Files/issues/4#issuecomment-1034608391

**Comment by joBr99** [comment]
lol either files hosted on discord expire after some time or they indeed take stuff offline

**Comment by maxromanovsky** [comment]
I guess it's a combination of both...
