### ISSUE TITLE
[BUG] Localized characters from homeassistant entities are not displayed correctly

### ISSUE THREAD

**Issue by mikosoft83** [joBr99/nspanel-lovelace-ui#695]
### PROBLEM DESCRIPTION
Loclaized characters from home assistant entities (e.g. calendar) are displayed incorrectly as two characters. Issue is with several accented characters e.g. í,č,ť.
I tried several encodings and decodings from python but nothing helped, the characters were always incorrect (in different ways but still incorrect).

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide your apps.yaml (or your config):
```
    timeAdditionalTemplate: >-
      {% if today_at('00:00')|as_timestamp() < strptime(state_attr('calendar.minko_majka', 'start_time'), '%Y-%m-%d %H:%M:%S')|as_timestamp() < today_at('23:59')|as_timestamp() and
         now()|as_timestamp() < strptime(state_attr('calendar.minko_majka', 'end_time'), '%Y-%m-%d %H:%M:%S')|as_timestamp() %}
        {% if not state_attr('calendar.minko_majka','all_day') %}
          {{ strptime(state_attr('calendar.minko_majka','start_time'),'%Y-%m-%d %H:%M:%S')|as_timestamp()|timestamp_custom('%H:%M') }}
        {% endif %}
        {{ state_attr('calendar.minko_majka','message') }}
      {% endif %}


```
- [x] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
2023-01-12 08:39:00.287263 INFO nspanel-hallway: Sending MQTT Message: time~08:39~12:30
  
  MAJKA: vybavi����� Narniu


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Have an entity with the given characters in HA, display it on the NSpanel

### EXPECTED BEHAVIOUR
The word in the additional time info on the screenshot should be "vybaviť".

### SCREENSHOTS
![IMG_20230112_083948](https://user-images.githubusercontent.com/63317931/212009306-04bd2770-2d65-4895-8e55-292caee318b4.jpg)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
EU, backend 3.8.3

**Comment by joBr99** [comment]
Might be related to Combining Diacritical Marks not included in the font.

https://github.com/joBr99/nspanel-lovelace-ui/blob/main/HMI/fonts/gen-chars.py#L7

**Comment by mikosoft83** [comment]
Unfortunately unicode normalization is not available in templates. Is there a possibility to add it to the appdaemon code itself?

**Comment by joBr99** [comment]
Run `FlashNextion http://nspanel.pky.eu/lui.tft` and check if the chars are now rendered correctly.

**Comment by mikosoft83** [comment]
Yes, the added accents in the firmware helped, now it all looks correct

**Comment by mikosoft83** [comment]
Hi, here I am again, this issue manifests itself again but this time in the date template. I thought the font is the same for both fields?

**Comment by joBr99** [comment]
dateAdditionalTemplate is displayed in the same text box as the date itself is, so it is also the same font

**Comment by mikosoft83** [comment]
I did some more testing and I think I got to the bottom of this.
The issue is not linked to text from sensors only nor to a particular field.
When there is only one combining character in the whole text, the character will be displayed incorrectly. As long as there are two or more everything is displayed just fine. This is true for both time template and date template and they are independent, so time template may be displayed incorrectly and date template correctly. The only condition is the number of combining characters in each text.
Is this a bug in the Nextion firmware itself or is it something that can be fixed in Nextion editor?

**Comment by mikosoft83** [comment]
I also found [this issue](https://github.com/yozik04/nextion/issues/4) that may be related.

**Comment by joBr99** [comment]
If it's something on nextion side it definitely nothing that can be fixed in the editor, the nextion project encoding is utf-8.

The project isn't using the standard nextion instruction set, instead it is using reparse mode; I don't know how the ASCII limitation applies to that.

The icons used in various text fields are also 2 Byte Characters, which is working perfectly fine.
https://docs.nspanel.pky.eu/icon-cheatsheet.html

If you want to play with the encoding add something like this to the beginning of the send_mqtt_msg function in mqtt.py, however I don't think that is going to help. (https://github.com/joBr99/nspanel-lovelace-ui/blob/main/apps/nspanel-lovelace-ui/luibackend/mqtt.py#L67)
```
msg = msg.encode('utf-8')
```
