### ISSUE TITLE
[Feature Request] live stream

### ISSUE THREAD

**Issue by ofirshtrull** [joBr99/nspanel-lovelace-ui#696]
### FEATURE DESCRIPTION
maybe have the option to display video from a doorbell? 

### ADDITIONAL CONTEXT
let's say someone rings the smart doorbell,
in ha, there is an option to show the live stream on the tv
maybe have the option to show also on the nspanel

### PANEL / FIRMWARE VERION
US-L

**Comment by joBr99** [comment]
As descried in #448 #323 #288 #177 #127 and probably some more this is technically not possible with nextion.
