### ISSUE TITLE
[BUG] After update Entities card show 1729 apps.yaml

### ISSUE THREAD

**Issue by westado** [joBr99/nspanel-lovelace-ui#697]
After updating to 3.8.3 I have this image when I press the screensaver.

EU Firmwa
![WhatsApp Image 2023-01-12 at 12 44 22](https://user-images.githubusercontent.com/69120129/212059505-c1fe38b6-e6da-43f7-8fe5-96cc2c539d13.jpeg)
re 3.8.3

**Comment by joBr99** [comment]
Did you restart the Appdaemon addon after updating?

**Comment by westado** [comment]
yes i did ist

**Comment by westado** [comment]
Thias is the config in apps.yaml
#Wohnenzimmer
---
nspanel-wohnen:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel/RESULT"
    panelSendTopic: "cmnd/nspanel/CustomSend"
    model: eu
    sleepTimeout: 10
    sleepBrightness:
      - time: "8:00:00"
        value: 100
      - time: "22:00:00"
        value: 1
    locale: "de_DE"
    
    screensaver:
      entity: weather.openweathermap
      alternativeLayout: true      
      theme:
        autoWeather: true
      
    cards:
      - type: cardEntities
        title: Test Entities Card
        entities:
          - entity: light.w1_l11_bad
          - entity: light.w1_l1_schlafen_bett
          - entity: light.w1_l5_wohnen_eingang

**Comment by westado** [comment]
In another project I also have the same error with this configuration

![image](https://user-images.githubusercontent.com/69120129/212063508-73176761-e113-4bd4-8777-e666e4a48337.png)

**Comment by westado** [comment]
---
nspanel-gang-og:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel/RESULT"
    panelSendTopic: "cmnd/nspanel/CustomSend"
    model: eu
    sleepTimeout: 10
    sleepBrightness:
      - time: "8:00:00"
        value: 100
      - time: "18:00:00"
        value: 1
    locale: "de_DE"
    
    screensaver:
      entity: weather.openweathermap
      alternativeLayout: true      
      theme:
        autoWeather: true
      
    cards:

### Startseite
      - type: cardGrid
        title: Home
        entities:
          - entity: navigate.cardEntities_buro_lights
            name: Aktionen
          - entity: navigate.cardThermo_Bad
            name: Heizung Bad
          - entity: navigate.cardThermo_Wohnzimmer
            name: Heizung Wohnzimmer
          - entity: navigate.cardThermo_Kueche
            name: Heizung Küche
          - entity: navigate.cardThermo_Mia
            name: Heizung Mia
          - entity: navigate.cardQR_wifi
            name: Gast WLAN




#############################
###  Unter-Seiten
#############################
    hiddenCards:

### Büro Lampen
      - type: cardEntities
        title: Aktionen
        key: buro_lights  
        entities:
          - entity: input_boolean.sonos_ansagen
            name: Sonos Ansagen
          - entity: input_text.kristian_zustand
            name: Zustand Kristian
          - entity: input_text.martina_zustand
            name: Zustand Martina


### Mia Heizung
      - type: cardThermo
        title: Heizung Mia
        key: Mia
        entity: climate.mia
        
### Isabel Heizung
      - type: cardThermo
        title: Heizung Isabel
        key: Isabel
        entity: climate.isabel
        
        
### Küche Heizung
      - type: cardThermo
        title: Heizung Kueche
        key: Kueche
        entity: climate.kueche

### Bad Heizung
      - type: cardThermo
        title: Heizung Bad
        key: Bad
        entity: climate.bad


### Wohnzimmer Heizung
      - type: cardThermo
        title: Heizung Wohnzimmer
        key: Wohnzimmer
        entity: climate.wohnzimmer


### Personen
#      - type: cardEntities
#        title: Personen
#        key: person
#        entities:
#          - entity: person.person
#            name: Frederik
#          - entity: person.person2
#            name: Max

### Alarmanlage
#      - type: cardAlarm
#        key: alarm
#        title: Alarmanlage
#        entity: alarm_control_panel.master
#        supportedModes: ['arm_away', 'arm_night']


      - type: cardQR
        title: Gast WLAN
        qrCode: "WIFI:S:Dermanovic;T:WPA;P:0101110001;;"
        entities:
          - entity: iText.test_ssid
            name: Name
            icon: mdi:wifi
          - entity: iText.test_pw
            name: Password
            icon: mdi:key

**Comment by westado** [comment]
Have now tested to go back to the 3.7.3 version and exactly then I have no more error. The error is only with the 3.8.3

**Comment by irqnet** [comment]
> Have now tested to go back to the 3.7.3 version and exactly then I have no more error. The error is only with the 3.8.3

same here, can confirm the exact behavior in my environment

**Comment by joBr99** [comment]
This error message from appdaemon is definitely not related to the issue discuses here.

The new version also comes with a new firmware for the panel as every version, you should get an update message on the panel.


You can do it manually:

EU Version: `FlashNextion http://nspanel.pky.eu/lovelace-ui/github/nspanel-v3.8.3.tft`

US Landscape Version: `FlashNextion http://nspanel.pky.eu/lovelace-ui/github/nspanel-us-l-v3.8.3.tft`

US Portrait Version: `FlashNextion http://nspanel.pky.eu/lovelace-ui/github/nspanel-us-p-v3.8.3.tft`

However there should be an update dialog on the Display, without the appdameon log after startup I cannot say why it's not displaied.

**Comment by irqnet** [comment]
After updating the display it's working again.

**Comment by westado** [comment]
> After updating the display it's working again.

How did you update the device?

**Comment by joBr99** [comment]
read my message ...

**Comment by westado** [comment]
Ich habe die Nachricht gelesen. Jedoch wenn ich die url in der tft Upload lade ändert sich nichts !

**Comment by joBr99** [comment]
Tasmota neusteren; `FlashNextion http://nspanel.pky.eu/lovelace-ui/github/nspanel-v3.8.3.tft` auf der Konsole ausführen, dann muss der Ladebalken auf dem Display kommen, ohne die aktuelle Firmware auf dem DIsplay, wird's nicht gehen.

**Comment by westado** [comment]
> Tasmota neusteren; `FlashNextion http://nspanel.pky.eu/lovelace-ui/github/nspanel-v3.8.3.tft` auf der Konsole ausführen, dann muss der Ladebalken auf dem Display kommen, ohne die aktuelle Firmware auf dem DIsplay, wird's nicht gehen.

Danke nach dem Neustart ging es !

**Comment by westado** [comment]
Könntest du mir doch noch einmal helfen? Habe ein anderes Projekt noch da habe ich alles mit esphome gemacht. Wenn ich die tft datei über dienste flashe startet das Display nur neu und ladet aber nicht die datei.

**Comment by joBr99** [comment]
Kann der ESP ins Internet?

**Comment by westado** [comment]
> Kann der ESP ins Internet?

Ja das kann er . Ich hatte ja als das Gerät noch neu war beim ersten mal auch kein Problem die TFT Dateien zu laden.

**Comment by westado** [comment]
Hast du mir die tft datei die es noch vor dem 24.12. gab? Zu diesem Zeitpunkt habe ich die ganzen Geräte geflasht

**Comment by joBr99** [comment]
es gibt keinen unterschied bei den tft files wenn's ums flashen geht, links zu alten versionen sind in den release notes

> [14:16:59][W][nspanel_lovelace_upload:166]: HTTP Request failed; URL: http://nspanel.pky.eu/lui-release.tft; Error: connection refused, retrying (1/5)

Connection refused ist eigentlich recht eindeutig und hört sich so an als ob der ESP nicht ins Internet kommt.

**Comment by westado** [comment]
> es gibt keinen unterschied bei den tft files wenn's ums flashen geht, links zu alten versionen sind in den release notes
> 
> > [14:16:59][W][nspanel_lovelace_upload:166]: HTTP Request failed; URL: http://nspanel.pky.eu/lui-release.tft; Error: connection refused, retrying (1/5)
> 
> Connection refused ist eigentlich recht eindeutig und hört sich so an als ob der ESP nicht ins Internet kommt.

Also habe alles gefunden es muss im esphome unter die IP Einstellungen auch der dns1 angegeben werden sonst kann er keine Dateien laden. Vilen Dank. Und ich hoffe es wird noch mehr Funktionen in Zukunft geben. Dieses Projekt macht mir bei meinen Umbau im Haus so vieles einfacher.

**Comment by westado** [comment]
Hallo,
jetzt muss ich dich noch einmal stören. Habe gestern 15 NS Panel geflasht mit esp home und die tft dateien dazu. Dies egehen alle bis auf einer. An diesem kann ich alles schaltern aber der tft hat beim upload einen fehler gehabt und ist nicht mehr weiter gelaufen. Seid dem zeigt der display immer System Data Error! ich kann auch den tft nicht mehr laden

**Comment by joBr99** [comment]
System Data Error ist normalerweise kein Problem. Es kann u.u. vorkommen, dass das Display auf 9600 baud hängt wenn das flashen abbricht und die Stock FW drauf ist. 

Ändere die baud in esphome mal auf 9600 und flash dieses tft https://nspanel.pky.eu/test.tft

**Comment by westado** [comment]
Viel Dank diese Datei ladet er jetzt und danach kann ich wieder auf die alte baud gehen und die original laden?

**Comment by joBr99** [comment]
Es gibt dann auf dem display nen knopf um die baud zu setzen, den musst du drücken, dann sollte es wieder gehen.

**Comment by westado** [comment]
Mega geht alles wieder. Vielen Dank
