### ISSUE TITLE
[Feature Request] Labels for physical buttons

### ISSUE THREAD

**Issue by Rainerlan** [joBr99/nspanel-lovelace-ui#700]
### FEATURE DESCRIPTION
Labels to be displayed on the screen above the physical buttons in screensaver

### ADDITIONAL CONTEXT
As I use the buttons in detached mode (I control the relay from a generic thermostat entity using the Thermo Card), I would like to use them for other purposes - as eg to switch between scenes - Currently one must know the function of the button.
Would be great if the whole screensaver content could be moved up (as there seems plenty of space on the top), so that the labels could be added at the bottom of the screen.
The cards layout could be kept - as most of the time, the screen is in screensaver mode, the button labels would be displayed most of the time also.

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU

**Comment by joBr99** [comment]
Use the status Icons on the screensaver.
![image](https://user-images.githubusercontent.com/29555657/212495946-85ea00e0-8e04-4036-9145-d86092d07ea0.png)


> could be moved up (as there seems plenty of space on the top), 
![image](https://user-images.githubusercontent.com/29555657/212496016-7d7242d3-eeb7-4718-91d9-774aa71f3b8b.png)

There is acually exactly no space left to move anything up.

**Comment by Rainerlan** [comment]
I agree, those Icons could be used - but this solution is not intuitive. 
Maybe thats only my opinion: If Buttons and their labels are placed too far from each other, then its hard for people to understand the connection (eg. my wife and children).
My wish would be, to have the option to configure button labels close to the physical buttons.
E.g. I could do w/o tTimeAdd - And have everything below moved up.
Also the tIcon1/2 could be moved to the bottom (and have everything shifted up) and there being configured to be/swapped against button labels.

**Comment by joBr99** [comment]
With Nextion it's not possible to move elements on runtime and moving existing stuff like this will result in users that want to have it back where it was.

Thinking out of the box; there is a lot of space between the screen and the buttons and the function of the buttons is most likely more static than dynamic. How about using white clear labels to stick between the screen and the buttons?

![image](https://user-images.githubusercontent.com/29555657/212550525-dd553522-7d34-4c5d-a2d2-e1691cb95bce.png)

**Comment by joBr99** [comment]
@Rainerlan see #739

**Comment by Rainerlan** [comment]
@joBr99: Awesome! I love this - many thanks for the hint!
