### ISSUE TITLE
[Feature Request] Support floats in `speed` in PowerCard

### ISSUE THREAD

**Issue by magnusoverli** [joBr99/nspanel-lovelace-ui#704]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._
Add finer granularity to the speed setting in PowerCard and support floats
### ADDITIONAL CONTEXT
_Add any other context about the problem here._
I have been playing with how to represent the actual power draw on different important appliances and such in my house, in a manner that makes sense in the PowerCard. The speed setting is good, but could do with some tweaking.
I have come up with this template to calculate the power consumption for a particular device as a fraction of the total, and represent it on a scale between -3 and 0.
This is what I am using:

```
              {% set entity_power = states('sensor.hvac_sensor_active_power') |float | round(3)%}
              {% set total_power = states('sensor.ams_power_active') | float | round(3) %}
              {% set entity_usage = (entity_power / total_power * 3) | float %}
              {{ (entity_usage | round()) * -1 }}
```
Currently I am rounding the result so that the number is an integer, but this gives a very low granularity. A better approach would be this template:

```
              {% set entity_power = states('sensor.hvac_sensor_active_power') |float | round(3)%}
              {% set total_power = states('sensor.ams_power_active') | float | round(3) %}
              {% set entity_usage = (entity_power / total_power * 3) | float %}
              {{ (entity_usage | round(1)) * -1 }}
```
This template would return a float with no more than a single digit after the decimal point and would add the ability to visualise everything that draws between 3 and 33 percent of the total power.
Currently, anything that draws less than 33% of the total power will not get a speed at all, as the template will render a 0.

In addition, maybe it would be a good idea to change the scale from +/- 3 to +/-1? Or maybe even +/- 100, and use concepts people already know (percent). This way it would be easier for people to calculate their speed without the need to convert it to a scale of three?
Mathematically it is not hard, but in people's minds it a lot harder to see how that could be done. Supporting a scale of +/-1 (a fraction) is alot easier to contemplate for most users.

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU version
Master version (Backend)
Latest pre-release tft.

**Comment by joBr99** [comment]
Hey, 
Nextion uses integer math and does not have real or floating support, so we are limited to integers here.

Some Background on how the power flow part of the card works:

- There is a slider on the card with a value range from 0-100.
- There is a loop on the card adding the speed value every 100ms to the current value of the silder.

So it might be an option to increase the value range of the slider, to have more precise steps on the slider.

There is acually no limit on the speed value you can also do 4 or 5, it will just do bigger steps after 100ms.

**Comment by joBr99** [comment]
Run `FlashNextion http://nspanel.pky.eu/lui.tft`

I've changed the value range of the sliders from 0-1000, this should allow to do more precise steps.

**Comment by magnusoverli** [comment]
Yeah, cool! This works a lot better already! For me at least, there is no need to do anything else! :-D
Anything you can think of that would imply this is not going to be the standard moving forward?

**Comment by joBr99** [comment]
No, sounds good, will be included in the next release.

Can you check what the current maximum usable value for the speed is? (At some point it's probably way to fast)

I would guess with 100 as speed it's way to fast, so maybe it's a good idea to increase the value range even further.

**Comment by magnusoverli** [comment]
Hmmm... I feel like `100` is not unusable, but maybe just a little over the top. Some margins are probably wise.
You suggest having a scale of for example `120` in the nextion software, but limiting to `100` in the config?

**Comment by joBr99** [comment]
increase the value range to 1500, give it another try

**Comment by magnusoverli** [comment]
Using that slider size is OK. Provides this result when using a speed value of `100`:

**Comment by magnusoverli** [comment]
Looks like this at 100:

**Comment by joBr99** [comment]
changed the value range to 1200 and also added a cap at 120

**Comment by magnusoverli** [comment]
Lokks very good! 👍🏻
