### ISSUE TITLE
[Feature Request] - Control NSPanel as RGB(W) lamp

### ISSUE THREAD

**Issue by rony-x2** [joBr99/nspanel-lovelace-ui#707]
Hello,

I have a perhaps somewhat unusual feature request / idea 😊
Namely, that the display of the NSPanel can be controlled as an RGB(W) lamp via Home Assistant....

I would like to explain...
I have had the NSPanel installed in my bathroom for a few months. If someone has to go to the toilet at night, the light from the display would be perfectly sufficient to illuminate our (quite small) bathroom without blinding it.
It would be switched on via a motion detector.

(It could probably be used as a night light in the hallway ... etc).

I also have the NSPanel in view when showering, without glasses. If it could be controlled as an RGB(W) lamp, the flashing of colours alone could display notifications that could be configured in Home Assistant.

Example:
two seconds red - the doorbell rings
three flashes of yellow - washing machine in the basement is finished
and so on ....

I don't know if it's possible, but it would be a pretty cool extension for the NSPanel 😊

And one more thing - big thanks for your work 😊

Greetings

**Comment by joBr99** [comment]
Hey, 
there isn't a build-in way in appdaemon to create entities within homeassistant.

You can do this though the color command, try the following commands in the Tasmota Console to get an idea what it does.

The following commands are for the development version, update to it first (however only do this if you are using the EU Version of the Panel)

https://docs.nspanel.pky.eu/faq/#how-to-upgrade-from-a-release-to-the-current-development-version

In case you are using the US Panel, you can still try the following commands, just restart tasmota after doing so and it will be back to normal.

```
CustomSend dimmode~100~100
CustomSend color~63488~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535
CustomSend color~2016~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535
CustomSend color~31~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535
CustomSend color~0~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535
```

You can use thoose commands in automations by sending the command to the `cmnd/tasmota_your_mqtt_topic/CustomSend` topic.
