### ISSUE TITLE
[Feature Request] use the internal thermostat without smarthome

### ISSUE THREAD

**Issue by MacSchlack** [joBr99/nspanel-lovelace-ui#708]
### FEATURE DESCRIPTION
Controle the intern relais over a script to use it as a thermostat without smarthome 

### ADDITIONAL CONTEXT
I use the panel as thermostat. 
I know it is not perfekt but it works (maybe). 
At the moment i use ioproker to read the temperature and control  the relay for the heater over mqtt.

Do you think it will be possible to use a rule or script in the esp to controle the Relay direkt and ther is a special page to controle the intern valuse for the regulation?

thank you

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU)_

**Comment by janprive** [comment]
I read somewhere that it’s possible to “calibrate” the sensor with some console command…. Does someone know this?

**Comment by joBr99** [comment]
@janprive see #144 

@MacSchlack 

You have a couple of options:

- write a tasmota rule and control the relay through your rule
https://tasmota.github.io/docs/Rules/

- write a berry script which is controlling your relay
https://tasmota.github.io/docs/Berry/

- build your own tasmota binary with thermostat support
https://tasmota.github.io/docs/Thermostat/

All of the ways will control the heating locally without any smarthome system running, however you won't be able to use the Touchscreen while your home automation system is offline. This will only work with a connection to the backend.
