### ISSUE TITLE
Cannot change language of NSPanel

### ISSUE THREAD

**Issue by TrustedFloppa** [joBr99/nspanel-lovelace-ui#719]
I cannot change my language even i did select the right locale config
Here is my config
`nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/Sonoff_NSPanel/RESULT"
    panelSendTopic: "cmnd/Sonoff_NSPanel/CustomSend"
    model: eu
    locale: "pl_PL"
    sleepTimeout: 20`
what could go wrong?

**Comment by joBr99** [comment]
Babel installed?

https://docs.nspanel.pky.eu/prepare_ha/#add-babel-package-to-appdaemon-container-optional

**Comment by TrustedFloppa** [comment]
Thank you for your help, I didn't install Babel
Because I was doing the whole guide the way I remembered ,my bad
