### ISSUE TITLE
[BUG?] Icon not show in notifications (text instead)

### ISSUE THREAD

**Issue by EddyK69** [joBr99/nspanel-lovelace-ui#723]
### PROBLEM DESCRIPTION
When I try to send a notification via MQTT with an icon like:
`CustomSend pageType~popupNotify; CustomSend entityUpdateDetail~id~TITLE~65535~YES~1952~NO~63776~MESSAGE~65472~5~2~mdi:account~63776
`

no icon is shown in the notification, but instead it shows the text 'mdi:account'.

Is this a bug of am I doing it wrong? How should I use this icon feature?

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
You need to use the acual char for the icon in the notifications.

You can get the char by clicking the `U` in the cheatsheet.

https://docs.nspanel.pky.eu/icon-cheatsheet.html

Will add some documentation about this later.
