### ISSUE TITLE
[BUG] Minor nitpick flaw in screensaver formatting

### ISSUE THREAD

**Issue by EddyK69** [joBr99/nspanel-lovelace-ui#725]
### PROBLEM DESCRIPTION
In the latest 3.9.3, I found a little nitpick flaw in the formatting of the screensaver...

![215338225-017618c0-7402-4de2-ba7d-e8591aa8104d](https://user-images.githubusercontent.com/13943630/215504222-e0ffed3e-4a25-4702-a181-1a608e80891e.png)

No big deal, but for the people that are keen on nice formatting... ;)

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
This is actually not really related to the screensaver, more to the way sensors are rendered, I'm going to remove the space from the sensors.

However you can also get around this by using a config like this:

```
        - entity: sensor.temp_wohn_temperature
          value: '{{states("sensor.temp_wohn_temperature")}}°C'
          icon: mdi:home-thermometer-outline
```

**Comment by joBr99** [comment]
Removed the space in current dev version.

https://github.com/joBr99/nspanel-lovelace-ui/commit/9a3cc08db8ab02bfb85af26ed25bda625d3baf13
