### ISSUE TITLE
[BUG] Screensaver doesn't show the bottom Climate area anymore

### ISSUE THREAD

**Issue by andrei-micu-ro** [joBr99/nspanel-lovelace-ui#726]
### PROBLEM DESCRIPTION
Ok, this is not nice, what happened to backwards compatibility and keeping an old version as-is ?
I don't see the Climate area in the bottom of the screensaver with my NSPanel.
I created my custom TFT (altering the HMI) and I was very happy with the result. Now after a recent update (not sure whether it's appdaemon or the NSPanel Backend which caused it) the bottom part is blacked out and I can't see the weather details.
I can debug the problem and see what broke it, but this is not nice...
Which version kept the climate in the screensaver intact ? (without the added extra temperature sensor for indoor) I'm on 3.7.3 now with AppDaemon at 4.2.1 - just reverted from latest - and it's still not displaying.

![image](https://user-images.githubusercontent.com/73104962/215520286-ae3fbd35-a09b-4437-b277-3783c9c6b390.png)
I want it to work as the above image shows. Which version was the latest before you playing with the climate area ?
Also, if you changed the layout, why do the images in the readme.md still show the old design ? It's misleading. A PR that changes the design or Look&Feel should be merged AFTER the documentation is updated to reflect the change.

![image](https://user-images.githubusercontent.com/73104962/215521449-7fb9f69d-b135-45ef-ba33-d0e5a33242df.png)
As long as you stay on the same major version it is expected to have backwards compatibility.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
Please read the release notes, there are some changes to config related to the forecast overwrites, that's it. 
And please make sure that you **restart the AppDaemon Addon** after changing versions, otherwise they are no going to apply.


> Ok, this is not nice, what happened to backwards compatibility and keeping an old version as-is ?

No clue what you mean, the internal API between the backend and the HMI Project can change at any time if there is a good reason for it. The version of the backend always needs to mach the version of the panel.

The mapping between backend version and the firmware is defined within the project. The versions between backend and HMI need to match. If there is an update available for the panel it's going to display a promt for starting the update.

https://github.com/joBr99/nspanel-lovelace-ui/blob/main/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py#L30

> I don't see the Climate area in the bottom of the screensaver with my NSPanel.
Update the Backend and your TFT to the lastest version and restart the AppDaemon Addon.

>I created my custom TFT (altering the HMI) and I was very happy with the result. Now after a recent update (not sure whether it's appdaemon or the NSPanel Backend which caused it) the bottom part is blacked out and I can't see the weather details.

There is no backwards compatibility for HMI versions and there never will be. If you have your own HMI you need to merge the changes.

> I can debug the problem and see what broke it, but this is not nice...
Which version kept the climate in the screensaver intact ? (without the added extra temperature sensor for indoor) I'm on 3.7.3 now with AppDaemon at 4.2.1 - just reverted from latest - and it's still not displaying.

I don't know what your display project is based on, you can see the version number within the HMI Project and also on the startup event in mqtt.

>I want it to work as the above image shows. Which version was the latest before you playing with the climate area ?

The documentation is up to date and this image is still the default. You just need to update your HMI and Backend as documented and stated in all Release Notes.

**Comment by andrei-micu-ro** [comment]
It's sad how you approach a simple breaking of backwards compatibility rule.
Let me be clear, as maybe you didn't get my point above.
There are a few components to make this work:
- Screen Design (Nextion Editor - producing a binary tft file from an unversionable hmi file)
- AppDaemon - backend serving the data to the front end (the one above)
- MQTT - the bus for communication
- NSPanel HA Backend - the actual backend pushing the data to the front end via AppDaemon

Now, considering that I don't change the front end, AppDaemon or MQTT, I consider that any change in the HA Backend resulting in a MINOR version bump SHOULD MAINTAIN BACKWARDS COMPATIBILITY
If you disagree with the above then please enlighten me.

Continuing my chain of thoughts -  you said "there are some changes to config related to the forecast overwrites, that's it." - fully agree, that's what makes this open community shine - the possibility for anyone to request a change or a feature and for someone else to make it happen. I'm forever grateful to the Open Source community hence my support, my thoughts and help wherever I can. However, this doesn't mean that any small change that someone requests or you deem necessary should break the existing integrations/implementations someone may have. Here specifically you could've easily added a flag (Feature Toggling it's called) to allow the new and enhanced functionality. Or you could've bumped to a higher Major version - which would've made me think twice before upgrading, I would've read the release notes, or skipped the upgrade altogether. But adding a breaking change and only increasing the minor version is bad, bad habit, because now I HAVE TO read the release notes (and not postpone this for a later stage when I WANT TO do it) and adapt my customization accordingly.

Maybe my initial description wasn't clear enough and you thought that I did upgrades on more layers - no, I keep the HMI fixed (with the tft file on the server with my changes, as I want the front-end to please me, not be aligned with the entire community).
I don't care about MQTT versioning as nothing can break there.
I have watchtower upgrading my docker images nightly (AppDaemon indeed was upgraded, but with no impact)
The only thing that caused the problem is the upgrade I did on the NSPanel backend from HA as I saw you added some changes to the screensaver and thought it's ok to get the latest and when I have some time I'll look into that alternate design and play with it. I mainly did the upgrade because you fixed some things - didn't read in detail as I planned to do that at a later stage.

Now you get my problem ? If all goes well and I only see a minor version bump I expect no break of backwards compatibility.
I didn't open this issue to ask for help about doing upgrades, just to ask you _**Which version I can use that will still show the climate area as it was**_
But it seems I have to debug it as 3.7.3 doesn't work as expected... 

You can safely close the issue, but please, **please** try to code a little more cautiously so that these things don't happen.

**Comment by andrei-micu-ro** [comment]
> And? How many devices do you have? I have 6. I am always reading release notes for everything and since I was totally confident that I will need to change my config I have just updated it, flashed all nspanels (needs full upload, so it takes time) and modified my config accordingly. Now it is more consistent and it makes more sense, so I don't have any issue with that breaking change.

:) that was me half-a-year ago (or even more). But once I got the panel to look and work as I wanted it I left it like that, no constant changing the yaml config or the screens and only did basic upgrades.
I have 1 because I have google home screens everywhere - I have this NSPanel because of an old switch I can't cover with anything and I thought it would be great to use that hole in the wall for something better like a screen I can control :D 
And I was soooooooooo happy with what this guy did, as before I had a custom design done entirely by me with the entire config done in the yaml (ESPHome based HA communication via direct API). Once I found this solution with AppDaemon I thought God smiled to me and I immediately took it, adapted and configured it and then I was happy.
Until today when it stopped working as expected - and to be honest I wasn't expecting breaking changes done so bluntly. 

Anyway, I'll update to the latest revision, rework my yaml config, rework the screensaver and then I'll probably ignore future updates unless I have time to thoroughly read the release notes :D 

No hard feelings, @joBr99 , I still owe you a lot for making this work with AppDaemon and simplifying the entire screen configuration :)

**Comment by joBr99** [comment]
lol, who says that I'm using sematic versioning? Is that documented somewhere?

also changes to the internal api are nothing to be considered here

backend and HMI are always bundled and the "public" API is the configuration in apps.yaml


> Which version I can use that will still show the climate area as it was

As I said the HMI Version is bunded to the Backend Version, to tell you the compatible Backend Version I need to know the version of your HMI Project. This can be looked up in the Nextion Editor or on the startup message that is send during the waiting for content screen.

**Comment by joBr99** [comment]
> Anyway, I'll update to the latest revision, rework my yaml config, rework the screensaver and then I'll probably ignore future updates unless I have time to thoroughly read the release notes :D

Maybe you should just share the changes you made to your screensaver. If they are usefull to you they also could be to others.
