### ISSUE TITLE
[Feature Request] Access sub-page from screensaver

### ISSUE THREAD

**Issue by masterfish1** [joBr99/nspanel-lovelace-ui#733]
### FEATURE DESCRIPTION
My idea is for one (or more) of the entities on the screensaver to act as buttons to access sub-pages. Clicking anywhere else on the screen takes you to the default page but the 'mask' that does that has 'cut-outs' so that buttons can be accessed.

### ADDITIONAL CONTEXT
For example:
    screensaver:
      entities:
        - entity: weather.weather
        - entity: navigate.guest_wifi
          type: 0

In this instance, offering a button directly to the guest WiFi page from the screensaver, which seems a logical place to access this page from.

### PANEL / FIRMWARE VERION
I have the EU panel. I don't know where to find the firmware version, sorry. I've only just set it up so I imagine it would be the latest.

**Comment by joBr99** [comment]
Afaik Nextion doesn't allow such a cutout. I would recommend you to create cardGird as "homepage" after exiting the screensaver.

From that cardGrid you can navigate to your hidden card, including one for the qrcode.

**Comment by masterfish1** [comment]
Apologies for checking this, especially given my very limited knowledge of Nextion but I was wondering if something like this is possible.

I have assumed you are using a single button covering the screen to move from the screensaver, if so, could it be possible to do this with a Hotspot (or an overlaid button) in the place where the graphic would be?

I realise this isn't a plausible solution to use it for any position, but is it possible that if a navigate entity is included on the screensaver in the final position only, then this alternative means of exiting the screensaver be used?

Whether it is or not, thanks for all your effort with this. I've had good fun setting my screen up.

![screen](https://user-images.githubusercontent.com/7001305/216052161-ef13f3f9-b116-4046-8970-682e8c503fee.jpg)

**Comment by joBr99** [comment]
It's a touchcap which listens to all touches on the screen, it also implements swipe gestures (even through they are currently not used in the homeassistent backend) Any buttons would interfear with the touchcap.

**Comment by masterfish1** [comment]
I knew I knew nothing about Nextion. Thanks for taking the time to reply.
