### ISSUE TITLE
[Feature Request] input_number with decimal numbers

### ISSUE THREAD

**Issue by vencakratky** [joBr99/nspanel-lovelace-ui#734]
### FEATURE DESCRIPTION
Home Assistant uses input_number including decimal numbers, nspanel shows only integer values

### ADDITIONAL CONTEXT
If someone uses input_number for temperature/boiler control, it is unusable in the current state

### PANEL / FIRMWARE VERION
EU, Last firmware (3.9.4)
![homeassistant](https://user-images.githubusercontent.com/54419577/215799797-fbc94a9a-7224-4922-bd82-daec71a4b5e0.jpeg)
![nspanel](https://user-images.githubusercontent.com/54419577/215799821-c69e8eab-d486-4d35-a537-de00c85587c1.jpeg)
Thank you

**Comment by joBr99** [comment]
Besides Nextion not supporting double/floating number, theese sliders are not really good to use for adjusting numbers.

>Nextion uses integer math and does not have real or floating support.

https://nextion.tech/instruction-set/



I would create a climate entity from your input numbers or depeding on your use case use a generic thermostat.

https://github.com/jcwillox/hass-template-climate

**Comment by vencakratky** [comment]
Thank you for the sufficient answer 👍
