### ISSUE TITLE
[Feature Request] calendar card

### ISSUE THREAD

**Issue by jrspowers** [joBr99/nspanel-lovelace-ui#737]
### FEATURE DESCRIPTION
hello would it be possible to add agenda card like on ha i attach photo how i would see and hopefully can put this in it would be very useful

### ADDITIONAL CONTEXT
![calendar card](https://user-images.githubusercontent.com/60328474/215894486-71e3ee6e-4808-47e4-8f43-f7407cfa5b0b.png)

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
there is already a request for calendars #624

**Comment by jrspowers** [comment]
yes okay but not all this on the screensaver card with a whole week overview that would be nice or can't this be added?
