### ISSUE TITLE
[Feature Request] Tempating entity values on Power Card

### ISSUE THREAD

**Issue by muffintsi** [joBr99/nspanel-lovelace-ui#740]
Please add support for tempating entity values on Power Card.
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
3.9.4 EU.

**Comment by joBr99** [comment]
You can use templates on all entities to overwrite the value like this:
```
          value: '{{states("sensor.temp_wohn_temperature")}}°C'

```
