### ISSUE TITLE
[Help] PowerCard Exemple in HMI README.md not working

### ISSUE THREAD

**Issue by PreinfalkG** [joBr99/nspanel-lovelace-ui#741]
### PROBLEM DESCRIPTION

I have been trying to display the 'PowerCard' directly from the Tasmota 'Berry Scripting console' for many hours now.

For this I use the documentation under https://github.com/joBr99/nspanel-lovelace-ui/tree/main/HMI and also the example given there 

`"entityUpd~PowerTest~x~navUp~A~65535~~~delete~~~~~~text~sensor.power_consumption~B~17299~Power consumption~100W~1~text~sensor.power_consumption~C~17299~Power consumption~100W~1~text~sensor.today_energy~D~17299~Total energy 1~5836.0kWh~0~delete~~~~~~0~text~sensor.today_energy~E~17299~Total energy 1~5836.0kWh~-30~delete~~~~~~0~text~sensor.today_energy~F~65504~Total energy 1~5836.0kWh~90~text~sensor.today_energy~G~17299~Total energy 1~5836.0kWh~10"`

It is possible that the documentation part of the 'PowerCard' is not up to date. I can display most of the other cards from the Berry Scripting console without any problems using nextion.send("....").

My Nextion Screen Firmware is: event,startup,**49**,eu

The example from the Read.me file creates this display on my NSPanel. Even with hours of experimentation I have not yet found out what is wrong.
![2023-02-01_193026](https://user-images.githubusercontent.com/16906959/216131194-13ab3c5d-4a5b-425a-a886-2341d4f67e20.jpg)

### REQUESTED INFORMATION

```

### ADDITIONAL INFORMATION

direcly via Tasmota Berry console

**Comment by joBr99** [comment]
The documention in the repo refers to the current development version, looks like you have the release version on your panel.

**Comment by joBr99** [comment]
You can flash the dev version with `FlashNextion http://nspanel.pky.eu/lui.tft`

**Comment by PreinfalkG** [comment]
Hi joBr99

thank you very much, that was the correct hint >> Many, many Thanks for your work !

_Note: I don't use HA and ioBroker and so i use the NSPanel with Tasmota and Lovelace UI directly with 'native MQTT'.
Currently it looks like this for me_

Video PowerCard: https://photos.app.goo.gl/PPhvwurN85nbMumq8
Video MainScreen: https://photos.app.goo.gl/isq3BT6c3Pn7oR8J6
Video OtherCards: https://photos.app.goo.gl/HLppD3GvByJYqGfV7 


![Photo_powerCard](https://user-images.githubusercontent.com/16906959/216889141-97e2a548-3b0e-45d1-b515-297d6ba8cc13.jpg)
