### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Harrie62** [joBr99/nspanel-lovelace-ui#742]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide your apps.yaml (or your config):
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by Harrie62** [comment]
I've flashed the NS Panel to latest FW. I do not understand the layout for the screensaver. 
I tried all the samples and mostly the device won't update. 
-entity:

  
entities:  
      -entity:
 
The only one working is:  
  
 screensaver:
      entity: weather.openweathermap     ( or other weather entities)
then i see one day in big letters and one day (skipt) in small letters

**Comment by joBr99** [comment]
Hey, please at least try to answer some of the questions asked in the issue template above without this information I cannot help you.

**Comment by Harrie62** [comment]
Sorry, my first issue. But all worked great until the update.
The old provided weather layouts are currently not working on the screensaver display.
And I do not understand how the yaml code works for the screensaver. 
Maybe a better example of yaml code

**Comment by joBr99** [comment]
did you restart the appdaemon addon after the update?

**Comment by Harrie62** [comment]
Yes several times.

And just now I updated with weather.home the icons are there as before. 

Solved, :)

**Comment by joBr99** [comment]
There isn't anything within the config that's is going to break with the update, there are some advanced config options that no longer have an effect, however the panel will still works fine.

The only important thing is to reboot the appdaemon addon after the update otherwise it will still send the old serial messages to the panel.

**Comment by Harrie62** [comment]
Thank you, I think it was the appdeamon addon restart after all.
I did the restart and the update to the NS panel in short time, and that worked.
