### ISSUE TITLE
[Feature Request] Improvement : add const NSPanel_MQTT_Path

### ISSUE THREAD

**Issue by SurfGargano** [joBr99/nspanel-lovelace-ui#743]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._

Add a const NSPanel_MQTT_Path, e,g.
 NSPanel_MQTT_Path = 'mqtt.3.SmartHome.Wohn.';
under the const section (const AliasPath: string =....)

Modify all mqtt const with the NSPanel_MQTT_Path, e.g :
panelRecvTopic: NSPanel_MQTT_Path + 'tele.RESULT',       // Bitte anpassen
panelSendTopic: NSPanel_MQTT_Path + 'cmnd.CustomSend',   // Bitte anpassen
mrIcon1ScreensaverEntity: { ScreensaverEntity: NSPanel_MQTT_Path +'stat.POWER1', 
mrIcon2ScreensaverEntity: { ScreensaverEntity: NSPanel_MQTT_Path +'stat.POWER2', 

So if a new version was released only 1 line has to be changed.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
TFT 49 / v3.9.0 / BerryDriver 8 / Tasmota 12.3.1

**Comment by Armilar** [comment]
It's not that easy, since the users then have to refer to your nomenclature for the full topics.

It would also be possible for a prefix to appear elsewhere. Then the script would not allow valid processing.

**Comment by Armilar** [comment]
![image](https://user-images.githubusercontent.com/102996011/218504034-51f12ff2-c8ff-4494-9573-b9a8060a699d.png)

I now use the data points within the examples
