### ISSUE TITLE
[Feature Request] Activate screensaver like an entity

### ISSUE THREAD

**Issue by EddyK69** [joBr99/nspanel-lovelace-ui#747]
### FEATURE DESCRIPTION
I would like to have an option to start the screensaver by clicking an entity.
Just like you can specify entity: navagite.card1, i would like to have an option like entity: screensaver 

### ADDITIONAL CONTEXT
n/a

### PANEL / FIRMWARE VERION
EU

**Comment by EddyK69** [comment]
Comment in #746 shows that this is already possible
https://github.com/joBr99/nspanel-lovelace-ui/issues/746#issuecomment-1415412290

**Comment by joBr99** [comment]
yeah, answered to the wrong issue

---------------------------

the screensaver is a normal card, you can add a key to it and use it with navigate
