### ISSUE TITLE
[BUG] Add bPrev and bNext back for HW Button Navigation

### ISSUE THREAD

**Issue by henne49** [joBr99/nspanel-lovelace-ui#749]
### PROBLEM DESCRIPTION
I have followed the manual at https://docs.nspanel.pky.eu/phys-btn/#change-behaviour-of-hardware-buttons

I have entered the tasmota rule and I want to use the HW Buttons to navigate between configured cards instead of the arrows on the screen. 

### REQUESTED INFORMATION
What else do I need to check to make this work, If I decouple the Buttons, then I see the buttons and can automate in home-assistant on them. But I simply want to use basic navigation.

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU 3.9.4

**Comment by joBr99** [comment]
The way the panel is navigating changed a few versions back and this is no longer possible.

I've added new commands for next/prev Navigation and updated the documentation. You will need to update to the dev version.

https://docs.nspanel.pky.eu/faq/
