### ISSUE TITLE
[Feature Request] Raw use from other HA system

### ISSUE THREAD

**Issue by hallard** [joBr99/nspanel-lovelace-ui#751]
### FEATURE DESCRIPTION

I got some NSPanel flashed with tasmota and I'm looking for something customizable and this one looks awesome (because I need energy). Unfortunately I'm not using HA nor ioBroker but as all is driven thru MQTT I think it should be okay.

Can I run AppDaemon to manage widget and configuration screen (but without this one connected to HA) and just use MQTT to update values on the NSpanel? Should be do able not?

May be I could also send data to AppDeamon thru MQTT? not sure of this one.

Thanks.

**Comment by joBr99** [comment]
no the appdaemon addon only works with homeassistant

however there are plenty of alternative backends already available and the Serial Protocol is documented here:
https://github.com/joBr99/nspanel-lovelace-ui/blob/main/HMI/README.md



ioBroker: https://forum.iobroker.net/topic/58170/sonoff-nspanel-mit-lovelace-ui/

IP Symcon: https://community.symcon.de/t/beta-modul-nspanel-lovelace-ui/130109

SmartHomeNG: https://github.com/sisamiwe/shng-nspanel-plugin

OpenHAB: https://github.com/donoo/o2n2l

https://github.com/m-schaeffler/node-red-nspanel

**Comment by hallard** [comment]
thank you for your answer, and yeah, node-red is definitively the one I need (was not in the list on main read.me), I using this one day my day.

Any demo/sample code available, just to be sure on data format to be sent by the nodered node?

**Comment by joBr99** [comment]
there are samples in the HMI documenation for each card and each parameter is explained (even though it's not 100% complete)

the node-red repo is something I've seen recently

**Comment by hallard** [comment]
Hi @joBr99, today I flashed my nspanel with your awesome firmware, then I tried your node red example adapting them to my config.

![image](https://user-images.githubusercontent.com/2471931/218275720-8bc68d2d-650e-4ef4-b40a-e170599c7431.png)

All is working fine, thanks. 

So trying to go further, if I understand correctly there is no node-red default back end mode available (yet) and it's up to me to do all stuff about switching between widgets and different screen correct?

So as an example, if I want to do same example as done in appdaemon [here](https://github.com/joBr99/nspanel-lovelace-ui/blob/main/appdaemon/apps-simple.yaml) I need to create a kind of `init` node on node red with all card correct?

Thanks

**Comment by joBr99** [comment]
There is no node red backend, you have to craft the commands yourself if you want to use node red. 

This might be helpful, however I've never used it.

https://github.com/m-schaeffler/node-red-nspanel

Documentation of the serial code is in the HMI folder.

**Comment by hallard** [comment]
Ok that's what I understood, will learn and give a try, may be I will fork and then add some kind of examples for node red.

Let me know on to get on discord, may be better.

Thanks for you help

**Comment by joBr99** [comment]
This project acually started with an nodered backend, however I personally think that node-red isn't suited for a task link this.

There's a lot of data combinded for an page and it was quite hard to implement a backend with state callbacks etc. however if you are building a custom integration with your own nodes it might be a different story.

Discord: https://unofficialnextion.com/t/welcome-to-the-unofficial-nextion-tjc-user-forum/8

**Comment by elgerg** [comment]
@hallard I was wondering if you got anywhere with this?

I too would like to control my NSPanel with Node-red as I dont use any other HA system.

Any pointers would be appreciated, just something simple like create a page/card and an item or two then how to turn them on/off or set them.

Thanks!

**Comment by elgerg** [comment]
Actually, I found this:

https://github.com/donoo/o2n2l/blob/main/node-red/flows.json

Might be a good starting point.

**Comment by joBr99** [comment]
Yeah: https://github.com/joBr99/nspanel-lovelace-ui#other-resources

and there is another one:

https://github.com/m-schaeffler/node-red-nspanel
