### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by ClaireRovic** [joBr99/nspanel-lovelace-ui#752]
### FEATURE DESCRIPTION
When a selection from the panel is made, a beep can be heard (maybe using the Tasmota code). This could be set globally or per selection.

### ADDITIONAL CONTEXT
When I use the climate card and go to turn the device off. It is very hard to tell if the panel has auctioned the touch.

### PANEL / FIRMWARE VERSION
US-P

**Comment by joBr99** [comment]
you can run theese two commands in tasmota console; however this isn't perfect

```
rule3 on CustomRecv do Buzzer 1 endon
rule3 1
```

**Comment by ClaireRovic** [comment]
That has worked very well thank you.
