### ISSUE TITLE
[Feature Request] Rounding and calculating entities with templates (i.e. on the PowerCard)

### ISSUE THREAD

**Issue by Kilowatt-W** [joBr99/nspanel-lovelace-ui#757]
### FEATURE DESCRIPTION
When using the new Powercard some values are to big to fit in the bars, so it would be nice to be able to use templates like in the state or icon settings to change the look and feel of the entity or result.

### ADDITIONAL CONTEXT
for example :
          - entity: 'ha:{{ (sensor.relative_autonomy_fronius_power_flow_0 | round ()) }}'
            icon: mdi:percent-circle-outline

### PANEL / FIRMWARE VERION
Actual Firmware and Build

**Comment by EddyK69** [comment]
This is already possible with:

```
          - entity: sensor.relative_autonomy_fronius_power_flow_0
            value: "{{states('sensor.relative_autonomy_fronius_power_flow_0') | float | round(1) }}"
```

**Comment by Kilowatt-W** [comment]
Wonderful, so sorry I missed that in the description, maybe you could insert it there ?

Greetings from Austria.
kilowatt

**Comment by joBr99** [comment]
offically this is a feature that will be added in the next version (even though it might be in the release already due to a patch)

documentation will be updated with the release of the next version

#721
