### ISSUE TITLE
[Feature Request] New cardCalendar

### ISSUE THREAD

**Issue by ravenst0ne** [joBr99/nspanel-lovelace-ui#758]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._
Would be nice to have a card for displaying the calendar, like the current month and the option to navigate to other months through buttons.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
"Days" could be marked with a dot, if something is on the days agenda. After clicking on that day, a popup should be opened to show the appointment.
Also a list (best case scrollable) with next appointments would improve the features.

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU

**Comment by joBr99** [comment]
there is already a FR for this #624
