### ISSUE TITLE
[Error]  in proxmox it does not work

### ISSUE THREAD

**Issue by diexpc** [joBr99/nspanel-lovelace-ui#761]
### PROBLEM DESCRIPTION
I have a problem and it is that in proxmox it does not work, it keeps trying to connect but without results

**Comment by joBr99** [comment]
lol, it it possible to provide less information?
I don't have a glass sphere ...


please see this:
https://docs.nspanel.pky.eu/faq/


if you are using docker directly, pay attention to this:
`Instructions for users of HomeAssistant Core installed through docker containers.` 
on this page: https://docs.nspanel.pky.eu/prepare_ha/


and if it still doesn't work please fill out everything asked in the "Help - Waiting for Content" Issue Template.
https://github.com/joBr99/nspanel-lovelace-ui/issues/new/choose

**Comment by jameshiscott** [comment]
Fyi: works fine in my proxmox install. Top tip is to check you mqtt can connect you can see this in the logs in tasmota and or use a desktop client to check it

**Comment by joBr99** [comment]
yeah, working fine on my proxmox too, however proxmox doesn't have anything to do with homeassistant, because it is just a hypervisor and also there are multiple ways to install homeassistant on proxmox ...
