### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by mikosoft83** [joBr99/nspanel-lovelace-ui#762]
### PROBLEM DESCRIPTION
Panel is not displaying time additional template. The data gets sent to the panel.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide your apps.yaml (or your config):
```
  apps.yaml here:


```
- [x] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
2023-02-10 09:55:00.244623 INFO nspanel-hallway: Sending MQTT Message: time~09:55~SMETI: Bioodpad
2023-02-10 09:56:00.235447 INFO nspanel-hallway: Sending MQTT Message: time~09:56~SMETI: Bioodpad
2023-02-10 09:57:00.224869 INFO nspanel-hallway: Sending MQTT Message: time~09:57~SMETI: Bioodpad


```

### TO REPRODUCE
Configure time additional template

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
![image](https://user-images.githubusercontent.com/63317931/218049071-d7cab99a-65fb-4cd0-8ce5-8a0aec565395.png)

### ADDITIONAL CONTEXT
I think it started after I updated to 3.9.x

### PANEL / FIRMWARE VERION
appdaemon 3.9.4, panel LUI EU 3.9.0

**Comment by randybb** [comment]
Just tested it with both layouts and no issues.
Btw, it is not documented https://docs.nspanel.pky.eu/hmi-serial-protocol/?h=time#general-commands-implemented-on-all-pages :)

**Comment by mikosoft83** [comment]
It may be related to my particular config combination but that's what I don't know.
I'm using it with ESPHome and noticed I don't have logging enabled for panel, so I'll recompile with the logger and will try to see what's in the ESPHome logs

**Comment by mikosoft83** [comment]
Recompiled, tested, it apparently sends it to the panel but for some weird reason it's not shown:
[14:31:01][D][nspanel_lovelace:106]: Sending custom command: time~14:31~SMETI: Bioodpad
Everything else is showing and updating as expected

**Comment by randybb** [comment]
![PXL_20230210_144023206.jpg](https://user-images.githubusercontent.com/206765/218106343-f6670bfe-c285-44c7-812b-b737005599e7.jpg)

It works, but it is not visible within the first minute when it comes back to the screensaver. But the command is visible in log

**Comment by mikosoft83** [comment]
Yes, I'm aware the update takes a while but again, it worked pre update, it doesn't after

**Comment by mikosoft83** [comment]
I tried stripping the config to minimum but it still doesn't display the template, anything else I can try?

**Comment by joBr99** [comment]
as long as you see `time~09:57~SMETI: Bioodpad` it cannot be a configuration issue; the command looks correct

Can you try it with the latest development firmware? (`http://nspanel.pky.eu/lui.tft`)

Just tested with this one; however I don't remember that this was/is broken in the release.

**Comment by mikosoft83** [comment]
The dev firmware resolved that issue. I also wonder what it was as I'm not 100% sure it was immediately after 3.9.x update
