### ISSUE TITLE
Add Sunrise & Sunset time to screensaver

### ISSUE THREAD

**Issue by Panoru84** [joBr99/nspanel-lovelace-ui#764]
### FEATURE DESCRIPTION
We have many cool features from the weather Alias to display on the screensaver, but what about sun rise and sun set?

### ADDITIONAL CONTEXT
Not sure what your day is like and where you are living but for me sunrise and sunset are much more important then wind :D
Would be great to have these values available, too.

### PANEL / FIRMWARE VERION
EU- NsPanel script v3.9.0.2

Thanks for your great job!!! I highly appreciate!

**Comment by joBr99** [comment]
For homeassistent this is really simple, but I guess you're asking for Iobroker. @Armilar

**Comment by Armilar** [comment]
It is already included in ioBroker for version 4.0.0.

In ioBroker is also very simple

**Comment by Armilar** [comment]
https://forum.iobroker.net/post/946384

**Comment by Panoru84** [comment]
> It is already included in ioBroker for version 4.0.0.
> 
> In ioBroker is also very simple

Thanks for your reply and also the comment in iobroker forum.

Last short question - because 4.0.0 has now been mentioned some times.
That version is not released yet, isn't it?

**Comment by joBr99** [comment]
Nope will be in ~2 weeks.
