### ISSUE TITLE
[Feature Request] - Display Static Text

### ISSUE THREAD

**Issue by byraff613** [joBr99/nspanel-lovelace-ui#766]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._

I’d really like to be able to display some static text on a card.
Best case scenario, to add the ability to replace the weather feature on the screensaver with static text.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

If this text could be pulled from a txt file or a Google sheet, it would be next level.
I’m thinking to display a weekly Joke, inspirational quote, something like that 😂

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

I’m using homeassistent and the US Portrait

**Comment by joBr99** [comment]
just send a notification to the screensaver

https://docs.nspanel.pky.eu/notifications/#notification-on-screensaver

**Comment by byraff613** [comment]
Thanks, will give this a go!
Thanks for this, having lots of fun 😀
