### ISSUE TITLE
wled effects control

### ISSUE THREAD

**Issue by kallejoken** [joBr99/nspanel-lovelace-ui#767]
the possible wled effects are selectable, but they are not passed on to the device.

is the problem already known?

**Comment by Armilar** [comment]
Which problem? And in which system HA? ioBroker? From what example? With which version of the TFT and if ioBroker, with which script version or pageItem?

**Comment by joBr99** [comment]
I would really appreciate if people wouldn't delete the content of the issue templates, so thoose questions would already be answered ...

However yeah, wled effect selection was broken in the latest development version, due to a rolled back change for broken cardUnlock I've just fixed it.

**Comment by kallejoken** [comment]
sorry.

 esphome, HomeAssistant, current TFT version.

as soon as you select an effect, it is not passed on to the end device.

sorry i am still quite new here in the github , so i have to find my way around first

**Comment by joBr99** [comment]
selecting effects is a feature of the upcoming version; if you want to use it you need to update to the development version

https://docs.nspanel.pky.eu/faq/#how-to-upgrade-from-a-release-to-the-current-development-version

**Comment by kallejoken** [comment]
yes great thank you
