### ISSUE TITLE
[BUG] Dots on cardPower moving reversed on US-P compared to EU Panel

### ISSUE THREAD

**Issue by bembelstemmer** [joBr99/nspanel-lovelace-ui#768]
### PROBLEM DESCRIPTION
Hi, i'm currently using a mixed Set of EU and US Panels. I'm trying to visualize energy distribution with cardPower and the ioBroker Typescript as Backend. The Card itself workes without problems but when using the same data for EU and US-Portrait Panels, the Dots are just moving reversed on the US-P Panel. I hope it's just a small signing issue. Please tell me if i can provide more information than provided below.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide your apps.yaml (or your config):
```
Not sure which to paste here from the TypeScript Backend as it's working fine in general.
var Energiefluss_Uebersicht = <PagePower>
{
    "type": "cardPower",
    "heading": "Energiefluss",
    "useColor": true,
    "subPage": false,
    "parent": undefined,
    "items": [
        <PageItem>{ id: "alias.0.Energiefluss_Uebersicht" },
    ]
};
```
- [x] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
Log Output from customSend
entityUpd~Energiefluss~button~bPrev~~65535~~~button~bNext~~65535~~~65535~~~ ~~~~~34511~全~0~0 kW~34511~全~0~0 kW~64333~~25~0.03 kW~64333~~25~1.74 kW~34511~~-25~1.45 kW~26095~~0~0 kW

```

### TO REPRODUCE
Configure a card power with positive and negative speeds and compare the visualization on the EU and US-P Panel which are using the same Data.

### EXPECTED BEHAVIOUR
I would expect that the Speed definition should positive animate the dot from the central box to the outer one and with minus from the outer to the central also on the US Panel like it is one the EU Panel.

### SCREENSHOTS
If needed i can create videos but not sure if that helps.

### ADDITIONAL CONTEXT
Here's the Data from the ioBroker Datapoint i use with the Script.
`[
  {
    "id": 0,
    "value": "",
    "unit": "",
    "icon": "home",
    "iconColor": 0
  },
  {
    "id": 1,
    "value": 0,
    "unit": "kW",
    "icon": "solar-power-variant",
    "iconColor": 3,
    "speed": 0
  },
  {
    "id": 2,
    "value": 0,
    "unit": "kW",
    "icon": "solar-power-variant",
    "iconColor": 3,
    "speed": 0
  },
  {
    "id": 3,
    "value": 0.06,
    "unit": "kW",
    "icon": "transmission-tower",
    "iconColor": 10,
    "speed": 25
  },
  {
    "id": 4,
    "value": 1.48,
    "unit": "kW",
    "icon": "lightbulb",
    "iconColor": 10,
    "speed": 25
  },
  {
    "id": 5,
    "value": 1.17,
    "unit": "kW",
    "icon": "battery-70",
    "iconColor": 3,
    "speed": -25
  },
  {
    "id": 6,
    "value": 0,
    "unit": "kW",
    "icon": "car",
    "iconColor": 0,
    "speed": 0
  }
]`

### PANEL / FIRMWARE VERION
Both Panels (EU and US-P) are flashed to v3.9.0 downloaded from
http://nspanel.pky.eu/lovelace-ui/github/nspanel-v3.9.0.tft
http://nspanel.pky.eu/lovelace-ui/github/nspanel-us-p-v3.9.0.tft
and are running the latest TypeScript Release. Also tested with a Fresh copy and only that one page.

Thanks a lot already 👍

**Comment by joBr99** [comment]
This is acually documented behaviour; even though it should be changed in a future version of the HMI.

https://docs.nspanel.pky.eu/card-power/

**Comment by bembelstemmer** [comment]
Whoops. As ioBroker User i'm a little struggling between the two kind of documentations. So i probably missed it down there.
I'm currently creating two Datapoints with inversed values due to that. Would just be nice to reduce it to one in the future for easier maintenance.

Thanks for having a look 🎉

**Comment by joBr99** [comment]
no worries; you don't have to look at the homeassistant docs ;)
