### ISSUE TITLE
[Help] Wahts the syntax for icon in CustomSend via notificationscript from homeassistant

### ISSUE THREAD

**Issue by wunderbaum** [joBr99/nspanel-lovelace-ui#771]
### PROBLEM DESCRIPTION

I try to send a notification with an icon, but I always get only the text of the icondescription, not the icon:

Thats my sending in the home-assistant script:
`CustomSend pageType~popupNotify; CustomSend entityUpdateDetail~id~{{ "Wasserschaden!" }}~65535~LINKS~65535~RECHTS~65535~{{ "Waschmaschine\r\n\r\nWassereinbruch" }}~65535~{{ 5 }}~3~mdi:water-alert-outline~59392; Buzzer 20000,4,2`

I'm kinda lost. The text is red, the rest of the notification is good, too. But how can I get the icon among it.

**Comment by joBr99** [comment]
you need to send the char of the icon instead of the name

https://docs.nspanel.pky.eu/icon-cheatsheet.html

you can get the char by clicking on the 'U'

**Comment by wunderbaum** [comment]
Thanks alot! That was easy when its known!
