### ISSUE TITLE
[BUG] timeAdditionalTemplate not working

### ISSUE THREAD

**Issue by hatran0884** [joBr99/nspanel-lovelace-ui#772]
### PROBLEM DESCRIPTION
TimeAdditionalTemplate and DateAdditionalTemplate are both showing up after 3.9 update
also, swipe left and right to switch among pages not working either

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:

  config:
    panelRecvTopic: "tele/nspanel_white/RESULT"
    panelSendTopic: "cmnd/nspanel_white/CustomSend"
    model: us-l
    timeAdditionalTemplate: ' Âm Lịch {{ states("sensor.lich_am") }} Quý Mão '
    updateMode: auto-notify
```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_US-L

**Comment by joBr99** [comment]
please try updating to the dev version and check if the issue is still there

https://docs.nspanel.pky.eu/faq/#how-to-upgrade-from-a-release-to-the-current-development-version

**Comment by hatran0884** [comment]
i have updated to main version but unfortunately, its not showing up. 
the gesture of swiping right and left are not working as well
pressing the right and left buttons are also difficult to be done.

**Comment by joBr99** [comment]
Did you update the firmware aswell?

(`FlashNextion http://nspanel.pky.eu/lui-us-l.tft` in tasmota console)

**Comment by hatran0884** [comment]
yes, you are right, i have just updated the firmware and all the above issues have gone. thanks

**Comment by joBr99** [comment]
bzw: `FlashNextion http://nspanel.pky.eu/lovelace-ui/github/nspanel-us-l-i-latest.tft`

for the inverted version should also work
