### ISSUE TITLE
[Feature Request] with screensaver2 it is possible to add events on f1Icon..f5Icon ?

### ISSUE THREAD

**Issue by SurfGargano** [joBr99/nspanel-lovelace-ui#774]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._

With screensaver2 it is possible to add events on f1Icon..f5Icon, so if I click on the icon an event message will be send ?
I want to change the page immediately when I pressed the icon.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
NSPanel EU , new version with screensaver2

**Comment by joBr99** [comment]
adding actions to the 5 icons requires adding 5 variables; no way to fit this into the page as it is already packed with way to much elements, there is just not enough memory on the panel

![image](https://user-images.githubusercontent.com/29555657/234403667-d5fe11e7-6bed-4695-b70c-75df154064d6.png)
