### ISSUE TITLE
Notification can not be closed via exitPopup

### ISSUE THREAD

**Issue by Gerrit-KMeier** [joBr99/nspanel-lovelace-ui#784]
### PROBLEM DESCRIPTION
I manually issued a Notification via MQTT with this command:
`
CustomSend pageType~popupNotify
CustomSend entityUpdateDetail~restartNoYes~Notification~65535~No~63488~Yes~2016~Hello World~65535~0
`

According the manual this notification can be closed with 
`CustomSend exitPopup`

The only thing that happens is, the cross in the upperright corner get's highlighted but the screen persists

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide your apps.yaml (or your config):
```
  apps.yaml here:
No apps.yaml, since I have not ioBroker or Home Assistent. I just use Node Red
and try to implement it into fhem.

```
- [x] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
n/a

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

```
mosquitto_pub -t cmnd/nspanel01/CustomSend -m 'entityUpdateDetail~restartNoYes~Notification~65535~No~63488~Yes~2016~Hello World~65535~0'
```

Closing Notification:
`mosquitto_pub -t cmnd/nspanel01/CustomSend -m 'exitPopup'`

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
After closing the Notification the Screen should become blank. 

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

EU 39

I wish there were more examples how to define the different screens manually via mqtt and customSend. Right now it's just try and error.

**Comment by joBr99** [comment]
popup's are closed server side

Sending `exitPopup` is way to trigger the button on the panel via mqtt, which should result into a message from the screen.

`event,buttonPress2,popupNotify,bExit`

this bExit message is sent by all popups

you need to answer with `pageType` to navigate away from the popup and render the current card/screensaver

**Comment by joBr99** [comment]
There are a lot of examples on the HMI Readme, even though there still could be more, there are now tables explaining the parameters for almost every card. However between version 39 and the current version 50 there are a lot of changes.

**Comment by Gerrit-KMeier** [comment]
okay. I issued these commands in the consolewindows of tasmota once again
```
Backlog UrlFetch https://raw.githubusercontent.com/joBr99/nspanel-lovelace-ui/main/tasmota/autoexec.be; Restart 1
FlashNextion http://nspanel.pky.eu/lui-release.tft
```

now the MQTT response in Tasmota is
`MQT: tele/nspanel01/RESULT = {"CustomRecv":"event,startup,50,eu"}`

> you need to answer with pageType to navigate away from the popup and render the current card/screensaver

and now everything behaves as described. In fact I wasn't aware of the fact `exitPopup` is just like tapping the Icon without changing the screen itself.


Now I have to dig myself into the powerCard and find out how to setup a proper screen by hand. An example CustomSend string is missing over there.

**Comment by joBr99** [comment]
It's here:
https://github.com/joBr99/nspanel-lovelace-ui/tree/main/HMI#cardpower

The documentation on docs.nspanel.pky.eu are mainly user facing stuff for homeassistant, documentation of the HMI and Serial Protocol itself are in the Readme of the HMI Folder.

`CustomSend pageType~cardPower`

`CustomSend entityUpd~PowerTest~x~navUp~A~65535~~~delete~~~~~~text~sensor.power_consumption~B~17299~Power consumption~100W~1~text~sensor.power_consumption~C~17299~Power consumption~100W~1~text~sensor.today_energy~D~17299~Total energy 1~5836.0kWh~0~delete~~~~~~0~text~sensor.today_energy~E~17299~Total energy 1~5836.0kWh~-30~delete~~~~~~0~text~sensor.today_energy~F~65504~Total energy 1~5836.0kWh~90~text~sensor.today_energy~G~17299~Total energy 1~5836.0kWh~10`

**Comment by joBr99** [comment]
> MQT: tele/nspanel01/RESULT = {"CustomRecv":"event,startup,50,eu"}

This is send by the startupScreen periodically, not related to the popup.

**Comment by Gerrit-KMeier** [comment]
> This is send by the startupScreen periodically, not related to the popup.

yeah I know. I currently don't know another function to determine the installed version

**Comment by joBr99** [comment]
no worries; didn't read the your entire comment

**Comment by Gerrit-KMeier** [comment]
`Custom send pageType~cardPower` switches my panel to a blue blox in portrait mode with a house in it. The rest ist empty

the second command which is supposed to update all the fields does'nt do anything at all.

**Comment by joBr99** [comment]
need to check

so, this might be acually an issue

https://github.com/joBr99/nspanel-lovelace-ui/issues/781

Try with the landscape version for now.

**Comment by Gerrit-KMeier** [comment]
No if have the EU version with a square display. I just wanted to describe the appearance of the blue box. By the way: can I somehow rotate the screen by 90° left or right?

**Comment by joBr99** [comment]
No, that's not possible.

**Comment by joBr99** [comment]
try this example for cardPower

`entityUpd~PowerTest~x~navUp~���~65535~~~delete~~~~~~text~sensor.power_consumption~���~17299~Power consumption~100 W~1~delete~~~~~~0~text~sensor.today_energy~���~17299~~9719.0 kWh~-20~delete~~~~~~0~text~sensor.today_energy~���~17299~~9719.0 kWh~20~delete~~~~~~0~text~sensor.today_energy~���~65504~~9719.0 kWh~30~text~sensor.today_energy~���~17299~~9719.0 kWh~-40`
