### ISSUE TITLE
[BUG] cannot execute FlashNextion

### ISSUE THREAD

**Issue by cotthemh** [joBr99/nspanel-lovelace-ui#787]
### PROBLEM DESCRIPTION
the first time i tried to flash the display it did not work, it just hung at 0%,  After the reboot i a blue screen with 'system Data ERROR!'. 
 tried flashing again but that did not really give anything else, also i tried copying the file to a local web server, unfortunately, that also gives the same result.

apparently the flash does not really start, as the log also shows it does not start writing.  I also reinstalled from scratch using the procedure again, but that did not help, the display just keeps doing the same thing.
21:42:30.478 CMD: FlashNextion http://nspanel.pky.eu/lui-release.tft
21:42:30.490 MQT: stat/livingPanel/RESULT = {"FlashNextion":"Done"}
21:42:30.524 FLH: host: nspanel.pky.eu, port: 80, get: /lui-release.tft
21:43:00.981 MQT: stat/livingPanel/RESULT = {"CustomSend":"Done"}
21:44:00.985 MQT: stat/livingPanel/RESULT = {"CustomSend":"Done"}

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
please try this commad ´FlashNextionAdv6 http://nspanel.pky.eu/lui-release.tft´

**Comment by cotthemh** [comment]
this gives me this it start the flash but it stays at 0%
![20230226_215649](https://user-images.githubusercontent.com/19887406/221437064-132c7f79-817b-4d62-be57-cfc84da26c68.jpg)

**Comment by joBr99** [comment]
please power cycle and retry with `weblog 3` before you start flashing and post the more verbose log

**Comment by cotthemh** [comment]
i changed back to my local server with the same command, i think tasmota does not resolve the dns normally which is why it fails with the regular url.

anyhow nice work!!! it did flash properly, now i get this, i guess its HA config from here on  THANKS YOU!!!!
![20230226_221356](https://user-images.githubusercontent.com/19887406/221437723-7bc7aae9-8257-458e-8c38-c5fa9d397dc5.jpg)

22:06:22.973 CMD: weblog 3
22:06:22.980 MQT: stat/livingPanel/RESULT = {"WebLog":3}
22:06:23.634 CFG: Saved, Count 39, Bytes 4096
22:07:00.300 SRC: MQTT
22:07:00.302 CMD: Grp 0, Cmd 'CUSTOMSEND', Idx 1, Len 11, Pld -99, Data 'time~22:07~'
22:07:00.317 NXP: payload sent = bytes('55BB0B0074696D657E32323A30377E1743')
22:07:00.323 MQT: stat/livingPanel/RESULT = {"CustomSend":"Done"}
22:07:14.863 CMD:  FlashNextionAdv6 http://192.168.30.190:8080/lui-release.tft
22:07:14.865 SRC: WebConsole from 192.168.30.190
22:07:14.866 CMD: Grp 0, Cmd 'FLASHNEXTIONADV', Idx 6, Len 42, Pld -99, Data 'http://192.168.30.190:8080/lui-release.tft'
22:07:14.877 MQT: stat/livingPanel/RESULT = {"FlashNextionAdv":"Done"}
22:07:14.928 FLH: host: 192.168.30.190, port: 8080, get: /lui-release.tft
22:07:14.931 WIF: DNS resolved '192.168.30.190' (192.168.30.190) in 1 ms
22:07:14.942 FLH: Connected:true
22:07:15.048 FLH: Retry 2
22:07:15.347 FLH: HTTP Respose is 200 OK or 206 Partial Content
22:07:15.354 FLH: Flash file size: 8202684
22:07:15.358 NXP: Nextion command sent = bytes('4452414B4A485355594447424E434A48474A4B534842444EFFFFFF')
22:07:15.361 NXP: Nextion command sent = bytes('7265636D6F643D30FFFFFF')
22:07:15.364 NXP: Nextion command sent = bytes('7265636D6F643D30FFFFFF')
22:07:15.367 NXP: Nextion command sent = bytes('636F6E6E656374FFFFFF')
22:07:15.476 NXP: Received Raw = bytes('1AFFFFFF636F6D6F6B20322C33303631342D302C4E5834383332463033355F30...')
22:07:15.529 FLH: Send (High Speed) flash start
22:07:15.533 NXP: Nextion command sent = bytes('77686D692D77726920383230323638342C3932313630302C72657330FFFFFF')
22:07:15.976 NXP: Received Raw = bytes('05')
22:07:15.980 FLH: Read block
22:07:15.982 FLH: Buff size 5463
22:07:15.986 FLH: Writing 4096
22:07:15.993 MQT: tele/livingPanel/RESULT = {"Flashing":{"complete": 0, "time_elapsed": 0}}
22:07:16.052 FLH: Total 4096
22:07:16.376 NXP: Received Raw = bytes('05')
22:07:16.379 FLH: Read block
22:07:16.394 FLH: Buff size 7111
22:07:16.399 FLH: Writing 4096
22:07:16.454 FLH: Total 8192
22:07:16.476 NXP: Received Raw = bytes('05')
22:07:16.478 FLH: Read block
22:07:16.494 FLH: Buff size 8759
22:07:16.500 FLH: Writing 4096
22:07:16.555 FLH: Total 12288
22:07:16.575 NXP: Received Raw = bytes('05')
22:07:16.578 FLH: Read block
22:07:16.580 FLH: Buff size 4663
22:07:16.586 FLH: Writing 4096
22:07:16.640 FLH: Total 16384
22:07:16.676 NXP: Received Raw = bytes('05')
22:07:16.679 FLH: Read block
22:07:16.700 FLH: Buff size 6311
22:07:16.705 FLH: Writing 4096
22:07:16.760 FLH: Total 20480
22:07:16.775 NXP: Received Raw = bytes('05')
22:07:16.778 FLH: Read block
22:07:16.789 FLH: Buff size 7959
22:07:16.796 FLH: Writing 4096
22:07:16.850 FLH: Total 24576
22:07:16.876 NXP: Received Raw = bytes('05')
22:07:16.879 FLH: Read block
22:07:16.891 FLH: Buff size 9607
22:07:16.899 FLH: Writing 4096
22:07:16.954 FLH: Total 28672
22:07:16.977 NXP: Received Raw = bytes('05')
22:07:16.981 FLH: Read block
22:07:16.983 FLH: Buff size 5511
22:07:16.989 FLH: Writing 4096

**Comment by joBr99** [comment]
you can get back to the normal log output with `weblog 2` :)

**Comment by cotthemh** [comment]
i got an update on homeassistant, then it stopped working again it got stuck on 87%

i tried the command again which worked yesterday, but that did not work here is the log:
00:00:00.002 HDW: ESP32-D0WD-V3 
00:00:00.044 UFS: FlashFS mounted with 276 kB free
00:00:00.066 CFG: Loaded from File, Count 51
00:00:00.076 QPC: Count 1
00:00:00.077 CFG: CR 426/699, Busy 0
00:00:00.086 CFG: CR 426/699, Busy 0
00:00:00.094 ROT: Mode 1
00:00:00.204 CFG: No '*.autoconf' file found
00:00:00.209 BRY: Berry initialized, RAM used=4041 bytes
00:00:00.219 BRY: No 'preinit.be'
00:00:00.223 TFS: File '.drvset003' not found
00:00:00.224 CFG: Energy use defaults as file system not ready or file not found
00:00:00.227 SRC: Restart
00:00:00.233 Project tasmota - livingPanel Version 12.4.0(nspanel)-2_0_6(2023-02-24T15:35:36)
00:00:00.234 ETH: No ETH MDC and/or ETH MDIO GPIO defined
00:00:00.508 NXP: Initializing Driver
00:00:00.515 BRY: Successfully loaded 'autoexec.be'
00:00:00.774 WIF: Attempting connection...
00:00:01.153 WIF: Connecting to AP1 GVE_iot Channel 7 BSSId 50:EB:F6:5F:43:28 in mode 11n as livingPanel-4120...
00:00:01.946 WIF: Attempting connection...
00:00:02.222 WIF: IPv4 192.168.30.105, mask 255.255.255.0, gateway 192.168.30.1
00:00:02.691 WIF: Connected
00:00:03.206 HTP: Web server active on livingPanel-4120 with IP address 192.168.30.105
00:00:03.986 WIF: DNS resolved 'pool.ntp.org' (45.87.76.3) in 85 ms
00:00:03.997 WIF: IPv6 Local fe80::7a21:84ff:febb:b018
00:00:04.073 RTC: UTC 2023-02-27T17:42:35, DST 2023-03-26T02:00:00, STD 2023-10-29T03:00:00
18:42:35.000 RTC: Synced by NTP
18:42:35.124 MQT: Attempting connection...
18:42:35.127 WIF: DNS resolved '192.168.30.202' (192.168.30.202) in 1 ms
18:42:35.182 MQT: Connected
18:42:35.186 MQT: tele/livingPanel/LWT = Online (retained)
18:42:35.188 MQT: cmnd/livingPanel/POWER = 
18:42:35.189 MQT: Subscribe to cmnd/livingPanel/#
18:42:35.191 MQT: Subscribe to cmnd/tasmotas/#
18:42:35.192 MQT: Subscribe to cmnd/DVES_BBB018_fb/#
18:42:35.196 MQT: tele/livingPanel/INFO1 = {"Info1":{"Module":"NSPanel","Version":"12.4.0(nspanel)","FallbackTopic":"cmnd/DVES_BBB018_fb/","GroupTopic":"cmnd/tasmotas/"}}
18:42:35.211 MQT: tele/livingPanel/INFO2 = {"Info2":{"WebServerMode":"Admin","Hostname":"livingPanel-4120","IPAddress":"192.168.30.105","IP6Global":"","IP6Local":"fe80::7a21:84ff:febb:b018"}}
18:42:35.225 MQT: tele/livingPanel/INFO3 = {"Info3":{"RestartReason":"Software reset CPU","BootCount":24}}
18:42:35.240 MQT: stat/livingPanel/RESULT = {"POWER1":"OFF"}
18:42:35.242 MQT: stat/livingPanel/POWER1 = OFF
18:42:35.247 MQT: stat/livingPanel/RESULT = {"POWER2":"OFF"}
18:42:35.250 MQT: stat/livingPanel/POWER2 = OFF
18:42:35.255 TFS: File 'autoexec.bat' not found
18:42:35.592 HTP: Main Menu
18:42:35.346 SRC: MQTT
18:42:35.348 CMD: Grp 0, Cmd 'STATUS', Idx 1, Len 1, Pld 1, Data '1'
18:42:35.354 MQT: stat/livingPanel/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota32/release/tasmota32-nspanel.bin","RestartReason":"Software reset CPU","Uptime":"0T00:00:05","StartupUTC":"2023-02-27T17:42:30","Sleep":0,"CfgHolder":4617,"BootCount":23,"BCResetTime":"2023-02-25T23:34:39","SaveCount":51}}
18:42:35.402 SRC: MQTT
18:42:35.404 CMD: Grp 0, Cmd 'STATUS', Idx 1, Len 2, Pld 11, Data '11'
18:42:35.411 MQT: stat/livingPanel/STATUS11 = {"StatusSTS":{"Time":"2023-02-27T18:42:35","Uptime":"0T00:00:05","UptimeSec":5,"Heap":140,"SleepMode":"Dynamic","Sleep":0,"LoadAvg":139,"MqttCount":1,"Berry":{"HeapUsed":16,"Objects":243},"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"GVE_iot","BSSId":"50:EB:F6:5F:43:28","Channel":7,"Mode":"11n","RSSI":58,"Signal":-71,"LinkCount":1,"Downtime":"0T00:00:04"}}}
18:42:35.462 SRC: MQTT
18:42:35.464 CMD: Grp 0, Cmd 'STATE', Idx 1, Len 0, Pld -99, Data ''
18:42:35.472 MQT: stat/livingPanel/RESULT = {"Time":"2023-02-27T18:42:35","Uptime":"0T00:00:05","UptimeSec":5,"Heap":143,"SleepMode":"Dynamic","Sleep":0,"LoadAvg":145,"MqttCount":1,"Berry":{"HeapUsed":16,"Objects":243},"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"GVE_iot","BSSId":"50:EB:F6:5F:43:28","Channel":7,"Mode":"11n","RSSI":58,"Signal":-71,"LinkCount":1,"Downtime":"0T00:00:04"}}
18:42:35.521 SRC: MQTT
18:42:35.522 CMD: Grp 0, Cmd 'STATUS', Idx 1, Len 2, Pld 10, Data '10'
18:42:35.533 MQT: stat/livingPanel/STATUS10 = {"StatusSNS":{"Time":"2023-02-27T18:42:35","ANALOG":{"Temperature1":22.1},"TempUnit":"C"}}
18:42:36.908 QPC: Reset
18:42:37.935 HTP: Consoles
18:42:38.901 APP: Boot Count 24
18:42:38.910 MQT: tele/livingPanel/STATE = {"Time":"2023-02-27T18:42:38","Uptime":"0T00:00:08","UptimeSec":8,"Heap":142,"SleepMode":"Dynamic","Sleep":0,"LoadAvg":168,"MqttCount":1,"Berry":{"HeapUsed":16,"Objects":243},"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"GVE_iot","BSSId":"50:EB:F6:5F:43:28","Channel":7,"Mode":"11n","RSSI":56,"Signal":-72,"LinkCount":1,"Downtime":"0T00:00:04"}}
18:42:38.952 MQT: tele/livingPanel/SENSOR = {"Time":"2023-02-27T18:42:38","ANALOG":{"Temperature1":22.1},"TempUnit":"C"}
18:42:39.928 CFG: Saved, Count 52, Bytes 4096
18:42:40.654 HTP: Console
18:43:00.066 SRC: MQTT
18:43:00.068 CMD: Grp 0, Cmd 'CUSTOMSEND', Idx 1, Len 11, Pld -99, Data 'time~18:43~'
18:43:00.084 NXP: payload sent = bytes('55BB0B0074696D657E31383A34337ECC70')
18:43:00.090 MQT: stat/livingPanel/RESULT = {"CustomSend":"Done"}
18:43:38.684 CMD: FlashNextionAdv6 http://192.168.30.190:8080/lui-release.tft
18:43:38.686 SRC: WebConsole from 192.168.30.190
18:43:38.688 CMD: Grp 0, Cmd 'FLASHNEXTIONADV', Idx 6, Len 42, Pld -99, Data 'http://192.168.30.190:8080/lui-release.tft'
18:43:38.700 MQT: stat/livingPanel/RESULT = {"FlashNextionAdv":"Done"}
18:43:38.750 FLH: host: 192.168.30.190, port: 8080, get: /lui-release.tft
18:43:38.754 WIF: DNS resolved '192.168.30.190' (192.168.30.190) in 0 ms
18:43:38.770 FLH: Connected:true
18:43:38.876 FLH: Retry 2
18:43:39.173 FLH: HTTP Respose is 200 OK or 206 Partial Content
18:43:39.180 FLH: Flash file size: 8202408
18:43:39.185 NXP: Nextion command sent = bytes('4452414B4A485355594447424E434A48474A4B534842444EFFFFFF')
18:43:39.189 NXP: Nextion command sent = bytes('7265636D6F643D30FFFFFF')
18:43:39.192 NXP: Nextion command sent = bytes('7265636D6F643D30FFFFFF')
18:43:39.197 NXP: Nextion command sent = bytes('636F6E6E656374FFFFFF')
18:44:00.077 SRC: MQTT
18:44:00.079 CMD: Grp 0, Cmd 'CUSTOMSEND', Idx 1, Len 11, Pld -99, Data 'time~18:44~'
18:44:00.095 NXP: skipped command becuase still flashing
18:44:00.103 MQT: stat/livingPanel/RESULT = {"CustomSend":"Done"}

**Comment by joBr99** [comment]
No, retry the normal command, adv6 isn't going to work.

**Comment by cotthemh** [comment]
nice that worked, any idea why it did not work from home assistant?  many thanks!!

**Comment by joBr99** [comment]
No, sometimes flashing can fail, this also depends on the device 🤷‍♂️ Homeassistent/Appdaemon is issuing the same command, did you flash from the internet or locally this time?

**Comment by cotthemh** [comment]
i flashed locally, i first downloaded the latest version which was on the site and put it on my local folder, but actually it was the same which i already had (at least it was the same size)

**Comment by joBr99** [comment]
Maybe it's also only failing for you if you are doing it over the Internet. You can override the URL for the TFT file in the configuration. (However you still need to download it somehow to somewhere)

**Comment by cotthemh** [comment]
my homeassist is running locally, and it did start because it got to 87%, the esphome interface seems to download it from the homeassist itself
