### ISSUE TITLE
Auto Update geht nicht

### ISSUE THREAD

**Issue by salopette** [joBr99/nspanel-lovelace-ui#79]
Update im Display angeschoben, aber es passiert nichts weiter.

16:42:01.311 MQT: stat/nspanel/RESULT = {"CustomSend":"Done"}
16:42:11.186 MQT: tele/nspanel/RESULT = {"CustomRecv":"event,buttonPress2,updateDisplayNoYes,notifyAction,yes"}
16:42:11.952 MQT: stat/nspanel/RESULT = {"FlashNextion":"Done"}
16:42:11.966 FLH: host: nspanel.pky.eu, port: 80, get: /lovelace-ui/github/nspanel-v1.8.0.tft
16:42:12.946 HTTP/1.1 404 Not Found
16:42:12.950 
16:42:12.952 Date: Sat, 26 Mar 2022 15:42:11 GMT
16:42:12.956 
16:42:12.958 Content-Type: text/html; charset=iso-8859-1
16:42:12.962 
16:42:12.964 Connection: close
16:42:12.966 
16:42:12.970 CF-Cache-Status: DYNAMIC
16:42:12.972 
16:42:12.976 Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=KgI51nj9pYw0UAbM8xwFLqmglAbr5gnkTgnkX8JWtyJXMZ0Vtjyzcepgcl4ykROUst30QRfgwosnebJE9dNa0H3U%2FnMJcEiwsc%2FkVQZQeA6tuItpSpUSKwCMWlKg5oXiWgg60A%3D%3D"}],"group":"cf-nel","max_age":604800}
16:42:12.984 
16:42:12.986 NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
16:42:12.990 
16:42:12.993 Server: cloudflare
16:42:12.996 
16:42:12.998 CF-RAY: 6f20feac0cf17270-HAM
16:42:13.002 
16:42:13.004 alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
16:42:13.008 
16:42:13.011 
16:42:13.014 
16:42:13.016 
16:42:13.140 FLH: Send (High Speed) flash start
16:42:13.542 BRY: Exception> 'divzero_error' - division by zero

**Comment by joBr99** [comment]
Update in HACS nochmal auf die neuste Version und starte AppDaemon neu
v1.8.0 ist nen release, das es eigentlich gar nicht gibt :)

**Comment by salopette** [comment]
Manuell geht auch nicht.

16:45:37.835 MQT: stat/nspanel/RESULT = {"CustomSend":"Done"}
16:45:42.134 CMD: FlashNextion http://nspanel.pky.eu/lovelace-ui/github/nspanel-v1.8.1.tft
16:45:42.152 MQT: stat/nspanel/RESULT = {"FlashNextion":"Done"}
16:45:42.229 FLH: host: nspanel.pky.eu, port: 80, get: /lovelace-ui/github/nspanel-v1.8.1.tft
16:45:43.142 HTTP/1.1 404 Not Found
16:45:43.145 
16:45:43.147 Date: Sat, 26 Mar 2022 15:45:42 GMT
16:45:43.149 
16:45:43.151 Content-Type: text/html; charset=iso-8859-1
16:45:43.154 
16:45:43.156 Connection: close
16:45:43.158 
16:45:43.160 CF-Cache-Status: DYNAMIC
16:45:43.163 
16:45:43.165 Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=rpAwPJm9nIVPX7Ur4itK6a6PTuDzO1bj5QOa%2FRD0UUn46OBIoIWhyRKQLbyVZSKnef%2Bw9yXv1KlrYczWxQakNXG3uD2DhTv1i7OYcXxumMFegmWz2rK9zz5GqAL6rE%2BiPbn78w%3D%3D"}],"group":"cf-nel","max_age":604800}
16:45:43.188 
16:45:43.191 NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
16:45:43.193 
16:45:43.195 Server: cloudflare
16:45:43.198 
16:45:43.200 CF-RAY: 6f2103cfff9a4180-HAM
16:45:43.203 
16:45:43.205 alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
16:45:43.208 
16:45:43.210 
16:45:43.214 
16:45:43.216 
16:45:43.241 FLH: Send (High Speed) flash start
16:45:43.645 BRY: Exception> 'divzero_error' - division by zero

**Comment by salopette** [comment]
War ich wohl zu schnell :-)
![sshot-1](https://user-images.githubusercontent.com/32480002/160247277-5434ca6c-393b-48bb-9ff6-577ac0269a12.jpg)

**Comment by joBr99** [comment]
jap, warst du, da hatte was mit den versionsnummern im release nicht gestimmt, was dazugeführt hätte das du die update meldung immer bekommst
