### ISSUE TITLE
[BUG] PowerCard: Item ausblenden: Leerstring für iconColor liefert js-warning

### ISSUE THREAD

**Issue by l4rs** [joBr99/nspanel-lovelace-ui#801]
### PROBLEM DESCRIPTION
Laut [Wiki](https://github.com/joBr99/nspanel-lovelace-ui/wiki/ioBroker-Card-Definitionen-(Seiten)#cardpower-ab-ts-script-v341) ist es möglich, einzelne Items der PowerCard auszublenden, wenn für alle Felder ein Leerstring übergeben wird. 
Für die iconColor muss aktuell aber eine 0 übergeben werden, sonst liefert das Typescript zum NSPanel (v4.0.3) eine Warnung:
`
javascript.0 (31919) script.js.System.NSPanel.NSPanelTs_v403: function GeneratePowerPage: Cannot read properties of undefined (reading 'red')
javascript.0 (31919) script.js.System.NSPanel.NSPanelTs_v403: function SendToPanel: Cannot read properties of undefined (reading 'payload')
`
und die PowerCard kann nicht angezeigt werden. Entweder ist die Beschreibung im Wiki nicht passend oder das TS prüft nicht auf den Leerstring.

### SCREENSHOTS
![image](https://user-images.githubusercontent.com/1215848/223081797-b8e51da7-56f3-4540-adea-35e9986beec3.png)

### ADDITIONAL CONTEXT
Die Anzeige-Daten (JSON) werden mittels Script im ioBroker generiert.

Das generierte JSON:
`[{"id":0,"value":427,"unit":"W","icon":"home-lightning-bolt-outline","iconColor":0},{"id":1,"value":21,"unit":"W","icon":"solar-power-variant-outline","iconColor":3,"speed":-2},{"id":2,"value":"","unit":"","icon":"","iconColor":0,"speed":""},{"id":3,"value":"","unit":"","icon":"","iconColor":0,"speed":""},{"id":4,"value":448,"unit":"W","icon":"transmission-tower","iconColor":10,"speed":10},{"id":5,"value":"","unit":"","icon":"","iconColor":0,"speed":""},{"id":6,"value":0,"unit":"kW","icon":"car-electric-outline","iconColor":5,"speed":0}]`

### PANEL / FIRMWARE VERION
NSPanel EU, TFT v50 / TypeScript v4.0.3 / BerryDriver v8 / Tasmota v12.4.0

**Comment by Armilar** [comment]
fixed https://github.com/joBr99/nspanel-lovelace-ui/pull/817
