### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by BlueManRising** [joBr99/nspanel-lovelace-ui#809]
### FEATURE DESCRIPTION
Turn Screen Off after set time, remove "screen saver" and enable as a card for future use

### ADDITIONAL CONTEXT
I am going to edit the Nextion Display ...  if the QRcard will stop erroring out, see other issue request

Overall love this project! keep up the good work!

### PANEL / FIRMWARE VERION
US-P

**Comment by christianloesel** [comment]
Other option: add setting to toggle between screensaver or turning off the display.

Would regret to loose the screensaver function completely.

**Comment by joBr99** [comment]
you can set `sleepBrightness` to `0` this will disable the screensaver

it's also possible to configure a key on the screensaver and navigate from a cardEntities or cardGird to it though navigate
