### ISSUE TITLE
[Feature Request] alarm panel

### ISSUE THREAD

**Issue by Zahnweh** [joBr99/nspanel-lovelace-ui#81]
Once again thanks for your awsome work! In a future release I'd love to see support for the HA alarm panel. Will this be possible from a technical point of view?

**Comment by joBr99** [comment]
I already started to work on it, if you want to see it, press this hidden button on the entities page like 10 times.

![image](https://user-images.githubusercontent.com/29555657/160252329-af3e9feb-82b9-476d-bbc0-c08c65193e45.png)

and then click on alarm :)

you might need to power cycle the panel or restart appdaemon to exit this page again

**Comment by Zahnweh** [comment]
Sounds great! Let me know if some testing is needed ;)

**Comment by joBr99** [comment]
@Zahnweh 

add this to your apps.yaml

```
      - type: cardAlarm
        item: alarm_control_panel.alarmo
 ```
 
 and update to the current development version
 
https://github.com/joBr99/nspanel-lovelace-ui#how-to-upgrade-from-a-release-to-the-current-development-version

**Comment by joBr99** [comment]
did you update the firmware?

> 3. Flash current Development Firmware in Tasmota Console.
> 
> FlashNextion http://nspanel.pky.eu/lui.tft

**Comment by Zahnweh** [comment]
Yes sir! Updated to 1.8.4 in HACS, then flashed the display and restarted HA and the Panel.

**Comment by joBr99** [comment]
no, it's not in the current release you have to udpate to main

https://github.com/joBr99/nspanel-lovelace-ui#how-to-upgrade-from-a-release-to-the-current-development-version

**Comment by Zahnweh** [comment]
May bad! I just accepted the update HACS was offering me. Now I updated to main and the panel card seems to show everything. But the layout looks a little shuffled.

![IMG_1633](https://user-images.githubusercontent.com/81824819/160459205-a08d9ed2-c866-4068-a812-17e312764228.jpg)

**Comment by joBr99** [comment]
looks like your display firmware isn't on the current development version

**Comment by Zahnweh** [comment]
Flashed it once again and now everything looks fine. It's fantastic! Activating / deactivating the alarm is working properly and also whether "armed home" is enabled or not is successfully mapped to the panel. Good job!
