### ISSUE TITLE
[BUG] Cannot long-press light on hidden cardGrid

### ISSUE THREAD

**Issue by Censored3** [joBr99/nspanel-lovelace-ui#815]
### PROBLEM DESCRIPTION
Long pressing a light keeps toggling it instead of going to the light detail page, when the cardGrid containing the light is a hiddenCard.
Works fine on a regular cardGrid card.
Didn't try it with other entities.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
v4.0.5

**Comment by joBr99** [comment]
Please provide logs, there is technically not really a difference between normal and hidden cards and I'm unable to reproduce this.

**Comment by Censored3** [comment]
It suddenly works, now - no clue why. Maybe a fluke... Sorry for the inconvenience :-)
