### ISSUE TITLE
Nextion Editor for US-P HMI File [BUG] 

### ISSUE THREAD

**Issue by BlueManRising** [joBr99/nspanel-lovelace-ui#816]
### PROBLEM DESCRIPTION
HMI US-P is corrupt, during debug
Error:Invalid number of arguments:qrcode m1.x,m1.y,200,defaultBcoColor,65535,-1,vaQR.txt( Double click to jump to code)
Error:Invalid number of arguments:qrcode m0.x,m0.y,200,defaultBcoColor,65535,-1,vaQR.txt( Double click to jump to code)

in QR card, tmSerial(timer)
error on the following 2 lines:
                if(type1.txt=="delete"||type1.txt=="")
                {
                  qrcode m1.x,m1.y,200,defaultBcoColor,65535,-1,vaQR.txt
                }
              }else
              {
                qrcode m0.x,m0.y,200,defaultBcoColor,65535,-1,vaQR.txt
              }

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
modify the qrcode command like the following:

`qrcode 8,m1.x,m1.y,200,6371,65535,-1,vaQR.txt` 

Note the extra 8 as first parameter or downgrade to this editor version:

https://nextion.tech/download/nextion-setup-v1-63-3.exe
https://nextion.tech/download/nextion-setup-v1-63-3.zip
