### ISSUE TITLE
[Feature Request] Select Speaker on Media Page

### ISSUE THREAD

**Issue by hatran0884** [joBr99/nspanel-lovelace-ui#82]
Hi, just updated to newest version of 1.8.3 and have small issue with the player page, i can control the spotify to volume up or down and change to next song but the song name is not updated respectively, i will have to change to next page and then go back to the spotify page to see the song name updated. 
similarly, the mode state in Thermostat page also is not updated until you move out and move back to this page. 
i guess, these info only updated after refreshing the page to pull updated info.  

by the way, is there anyway to play spotify on specific speaker or spotify connect device ? or you can code to show a source selector on the spotify page ?

**Comment by joBr99** [comment]
it's impossible to create a dropdown menu with nextion screens, but I will see what I can do

**Comment by joBr99** [comment]
callback bug should be fixed in v1.8.4

**Comment by joBr99** [comment]
@hatran0884 
on current main/dev version
![2022-03-27_15h41_18](https://user-images.githubusercontent.com/29555657/160284764-4935febb-5983-45f3-8667-32bdd373c685.png)

**Comment by hatran0884** [comment]
looks great, i guess we can change the device by that arrow ?

**Comment by joBr99** [comment]
Just update in HACS to main (redownload, select main, wait a sec until HACS finished loading, press download) and try yourself. Arrow let's select you a speaker, click on the name of the speaker to confirm the change.

**Comment by hatran0884** [comment]
Just updated but my unit doesnt show the speaker, i have updated both hacs and nspanel.tft. What might be wrong?
![66DD3495-382F-4CCC-8FE1-BE1F7C4FA3FD](https://user-images.githubusercontent.com/58875735/160288858-4af1605c-6d98-4d80-8b10-576fa1a6d912.jpeg)

**Comment by joBr99** [comment]
Strange, did you restart AppDeamon?

**Comment by hatran0884** [comment]
yes, i forgot to restart Appdaemon, now its working. the problem is now the media card is unable to play spotify songs by itself, i will have to start playing by smartphone first. it happens both on HASS and this media page. so i guess it is the problem of spotify component itself. 
i have a BOSE soundtouch and it has an entity named media_player.soundtouch, so i am thinking is it okay to have another media page for this device and then i can play spotify indirectly through this device ?

**Comment by joBr99** [comment]
yes, I'm just using the HomeAssistant API, so this is a limitation of the spotify integration in HA

it doesn't have to be spotify, that's just the only thing I can test with, you can use any media_player in HA

**Comment by hatran0884** [comment]
i have just tried and it worked, however it brings up another small issue, this soundtouch media player has a power button, on HASS dasboard, i will have to turn it on first to play spotify, so could you pls add a power button on the media page ? the spotify media page should be distingushed from other media page, so only spotify page should have a speaker selection and should not have a power button. 
sorry if i have requested too much, it is up to you to code it further.

**Comment by joBr99** [comment]
I don't have such a speaker can you send pictures of the development section in Homeassistent in different states of that speaker (off, on, playing)

**Comment by hatran0884** [comment]
Here u go, it seems it does not have an ON state, whenever i turn it on, its state changes to playing. 
![Uploading 40A99F1E-707C-4403-9EFE-AF804CBF14D8.jpeg…]()

**Comment by hatran0884** [comment]
![5BE9DEF5-4049-49F9-A4AE-5EB717770861](https://user-images.githubusercontent.com/58875735/160293345-d065a5f0-5ccc-45db-9172-bc4990cd4d5b.jpeg)
![9F4EED94-393C-4657-86BF-B4B349FA1DE0](https://user-images.githubusercontent.com/58875735/160293348-004b49e5-392d-4bb0-93f3-96c0c4fdadee.jpeg)

**Comment by joBr99** [comment]
No idea how to detect if the device has the capability to turn it on or off.

Would this be a Solution? Could simply turn it on in case it's off

```python
        if button_type == "media-pause":
            player = self._ha_api.get_entity(entity_id)
            if player.state == "off":
                player.call_service("turn_on")
            player.call_service("media_play_pause")
```

**Comment by hatran0884** [comment]
it should be okay, any chance I can test it now ?

**Comment by joBr99** [comment]
This change is pushed, just update to main

**Comment by hatran0884** [comment]
it worked like a charm, i just need to press play button to turn on the media player and start playing songs, but there is a litte issue with the speaker selector, this media player has 03 selections: AUX, Bluetooth and Spotify, but if i change to AUX or Bluetooth, the Spotify will disappear and i wont be able to change it back to Spotify. So could you code to remove the speaker selector or has an option in the config to disable this selector ? 
![JPEG image 2](https://user-images.githubusercontent.com/58875735/160395218-20c51e74-3742-4bac-ad05-4d2c2273c107.jpeg)

**Comment by joBr99** [comment]
the selector will be displayed if there is more than one source in this list

![image](https://user-images.githubusercontent.com/29555657/160396638-51e91f39-ad47-46ab-9814-2aa984f31a2e.png)

as you can see spotify isn't in that list, so it's also not selectable

**Comment by hatran0884** [comment]
Yes, thats why i was asking if you could make an option in the config to disable or hide this selector?

**Comment by joBr99** [comment]
page should now show a power button if the device supports it, but I cannot test that, because I don't have such a device

**Comment by hatran0884** [comment]
i have just tested , the power button does not show on the media page. and the play button also does not turn it on to play.

**Comment by joBr99** [comment]
can you send me the

**Comment by hatran0884** [comment]
here is what i got from Appdaemon log: 

<html>
<body>


2022-03-29 20:57:00.014358 INFO nspanel: Sending MQTT Message: time,20:57
--
2022-03-29 20:56:11.617634 INFO nspanel: Sending MQTT Message: entityUpd,\|media_player.soundtouch_living_room\|Soundtouch Living Room\|0\|\|\|0\|9\|\|AUX?BLUETOOTH\|disable
2022-03-29 20:56:11.607027 INFO nspanel: Started rendering of page 2 with type cardMedia
2022-03-29 20:56:07.805965 INFO nspanel: Sending MQTT Message: weatherUpdate,?12?21.4��C?Wed?12?27.8 ��C?Thu?20?29.2 ��C?Fri?20?22.6 ��C?Energy?32?10.23 kWh
2022-03-29 20:56:07.799205 INFO nspanel: Forecast 1 is overrriden with {'sensor.nang_luong_hom_nay': {'name': 'Energy', 'icon': 'solar-power'}}
2022-03-29 20:56:07.788105 INFO nspanel: Received Message from Screen: event,screensaverOpen
2022-03-29 20:56:04.068900 INFO nspanel: Sending MQTT Message: entityUpd,\|media_player.soundtouch_living_room\|Soundtouch Living Room\|0\|AMEE - thay m���i c�� g��i y��u anh\|AMEE\|25\|8\|SPOTIFY\|AUX?BLUETOOTH\|disable
2022-03-29 20:56:04.058851 INFO nspanel: Started rendering of page 2 with type cardMedia
2022-03-29 20:56:00.014374 INFO nspanel: Sending MQTT Message: time,20:56
2022-03-29 20:55:51.781165 INFO nspanel: Sending MQTT Message: entityUpd,\|media_player.soundtouch_living_room\|Soundtouch Living Room\|0\|\|\|25\|9\|INVALID_SOURCE\|AUX?BLUETOOTH\|disable
2022-03-29 20:55:51.760638 INFO nspanel: Sending MQTT Message: pageType,cardMedia
2022-03-29 20:55:51.756971 INFO nspanel: Started rendering of page 2 with type cardMedia
2022-03-29 20:55:51.753951 INFO nspanel: Button Press Event; entity_id: screensaver; button_type: bExit; value: 1


</body>
</html>

**Comment by joBr99** [comment]
can you do this change in the pages.py, restart appdaemon and try again?

![image](https://user-images.githubusercontent.com/29555657/160630275-184e84b0-da58-455f-a91c-9d6b62fd88c2.png)

**Comment by hatran0884** [comment]
i think you dont need to waste your time to create a power button, just go back to the way of pressing the play button to turn it on and play. i am okay with that.

**Comment by hatran0884** [comment]
sorry, i only updated the display firmware, forgot to update the appdaemon backend. it working now, the power button now shows up but nothing happens when i press this power button.

**Comment by joBr99** [comment]
hmm, media-OnOff looks good

it's calling the same api I did with the play button before

```
        if button_type == "media-OnOff":
            if player.state == "off":
                self._ha_api.get_entity(entity_id).call_service("turn_on")
            else:
                self._ha_api.get_entity(entity_id).call_service("turn_off")
```

sorry for the dumb question, but did you restart appdaemon?

**Comment by joBr99** [comment]
nevermind found the issue

**Comment by hatran0884** [comment]
yes, now the button works but only with turn off event, whenever i press turn on, the source says: invalid_source, then i tried to turn it on by HASS dashboard, the media player turns to unavailable. i checked the HASS log and found this: 
[Soundtouch Living Room](..........) became unavailable by Tran Manh Ha
i tried to restart HASS without help, i am not sure if this NSpanel version is doing smt that causes the media player to become unavailble ? i remember yesterday i can easily turn on or turn off this media player using HASS dashboard without issue. 
pls correct me if i am wrong

**Comment by joBr99** [comment]
it's calling the exact same api from HA

this is the power button:
```
        if button_type == "media-OnOff":
            if player.state == "off":
                self._ha_api.get_entity(entity_id).call_service("turn_on")
            else:
                self._ha_api.get_entity(entity_id).call_service("turn_off")
```

and the play button did somthing like this

```
if player.state == "off":
     self._ha_api.get_entity(entity_id).call_service("turn_on")
```

does it also become unavalibe when you are calling the turn_off service from HA developer tools?

**Comment by hatran0884** [comment]
strange, i tried to call turn off and turn on services from HA developer tools for a few times, now i can turn on and turn off the media player using both HA and NSpanel without issue. so i will keep testing it further. thank you
