### ISSUE TITLE
[Feature Request]  Add support for input_datetime entities

### ISSUE THREAD

**Issue by boroloko** [joBr99/nspanel-lovelace-ui#820]
### FEATURE DESCRIPTION
Add (If posible) support for "input_datetime." entities on cardEntities and/or cardGrid cards

### ADDITIONAL CONTEXT
I use some of this entities for fast changing time triggers from automations about covers and lights and I would like to add a card that includes these entities

### PANEL / FIRMWARE VERION
I'm using the EU version panel and firmware Tasmota 12.4.0.2

**Comment by joBr99** [comment]
see #688
