### ISSUE TITLE
[Feature Request] Suggestion to include 5,000 common Trad. and Simp. Chinese characters in HMI

### ISSUE THREAD

**Issue by knifehandz** [joBr99/nspanel-lovelace-ui#823]
### FEATURE DESCRIPTION
I've searched and read other issues related to CJK or Chinese character problems before opening this feature request, thank you for making this possible and the great work!

I've downloaded the HMI file to try to include 5,000 commonly used characters from both Tradition Chinese and Simplified Chinese (total 10,000, roughly counting, as there are overlaps) using Arial Unicode MS, just to see how much space this would take. So far for 24pt font this added about 370KB, and 32pt font added about 500KB; the resulting tft file is about 8.38MB.

Given the size increase isn't that bad, please consider including these into the official tft file to allow more freedom using Chinese characters.

In regards to Japanese Kanji (Japanese Chinese characters), I am not too confident this would cover all common ones though.

Included text file contains the suggested characters, first line Traditional Chinese, second line Simplified Chinese.
[Suggested Chinese Characters.txt](https://github.com/joBr99/nspanel-lovelace-ui/files/11009177/Suggested.Chinese.Characters.txt)

### ADDITIONAL CONTEXT
The reason for Arial Unicode MS is because it has all the characters needed, a big problem when using Chinese is Traditional / Simplified fonts don't align (different base line, different weight, etc.)

Testing of the generated tft (Traditional Chinese):
**Screensaver**
![20230318_235620](https://user-images.githubusercontent.com/9383052/226122607-e81b7376-a6d2-4360-b439-ec5e75f47674.jpg)
**Cards**
![20230318_235631](https://user-images.githubusercontent.com/9383052/226122616-ec0e4501-9986-47e5-9b50-6526239596bb.jpg)

![20230318_235638](https://user-images.githubusercontent.com/9383052/226122622-ec1ec647-8999-494c-ad41-43e2bb502122.jpg)

Source of character selection: https://blog.csdn.net/pandaClose/article/details/112259939

### PANEL / FIRMWARE VERION
Program Version: 12.4.0(nspanel)
Build Date & Time: 2023-02-24T15:35:36
Core/SDK Version: 2_0_6/4.4.3.20230129
Panel: US-L (self-built with the suggested characters included)

**Comment by knifehandz** [comment]
Good day @joBr99, any love for this? If this doesn't make sense, please feel free to let me know, I'll close the issue. Thanks.

**Comment by joBr99** [comment]
I'm planning to do this :)

**Comment by joBr99** [comment]
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/2e4869c4-148b-46a0-8e44-b9dd06f6ea77)

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/4c416301-6bef-4440-9e1c-dd503472be1e)

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/1cc02c1b-5257-4af9-bdc3-64f0b42cf5fe)

Size increase is ~20% +1664 KiB :/

The font used by the project is Noto Sans (https://fonts.google.com/noto/specimen/Noto+Sans). 

No clue about the quality of chinese chars in this font. Please give it a try:

`FlashNextion https://nspanel.pky.eu/nspanel_US_L-NewFontTest.tft`

**Comment by knifehandz** [comment]
Thank you! Need to go out of country for a week, will give it a try next week as soon as possible and report back.

**Comment by knifehandz** [comment]
Just realized the size increase from your side is larger than what I tested, but probably reasonable. Please see below for side-by-side test results of Arial Unicode MS (the one I generated on my side) and Noto Sans (the NewFontTest from you) - in order:

**Test 1 - living room**
![20230619_005926](https://github.com/joBr99/nspanel-lovelace-ui/assets/9383052/93cd79fe-fa81-4ca9-9c5a-7f1c777af301)
![20230619_011218](https://github.com/joBr99/nspanel-lovelace-ui/assets/9383052/86c10943-6831-4b96-970e-a89c5f073c94)

**Test 2 - dining room and kitchen**
![20230619_005935](https://github.com/joBr99/nspanel-lovelace-ui/assets/9383052/9bd3bb16-5372-4a40-a71d-fef64b175fc6)
![20230619_011226](https://github.com/joBr99/nspanel-lovelace-ui/assets/9383052/48596947-6752-475c-ad6b-de2e8d2c5a40)

**Test 3 - garden**
![20230619_005940](https://github.com/joBr99/nspanel-lovelace-ui/assets/9383052/fdfb5da6-a5e4-47ba-9965-43e24d8ad591)
![20230619_011233](https://github.com/joBr99/nspanel-lovelace-ui/assets/9383052/780da488-a94c-4f14-9947-d6e835843876)

**Test 4 - Traditional Chinese test**
![20230619_005946](https://github.com/joBr99/nspanel-lovelace-ui/assets/9383052/de6896cb-f10c-4eb6-84c7-6c06452cdb53)
![20230619_011241](https://github.com/joBr99/nspanel-lovelace-ui/assets/9383052/d16f86d2-09a2-4259-b3a4-981eedea370b)

**Test 5 - Simplified Chinese test**
![20230619_005953](https://github.com/joBr99/nspanel-lovelace-ui/assets/9383052/46e8a7b6-0a9c-4ebd-9260-3d64e2659768)
![20230619_011254](https://github.com/joBr99/nspanel-lovelace-ui/assets/9383052/ef0743fe-441a-41eb-b750-645acd1b1dd0)

_Please note test 4 and 5 are for testing only, and both contain identical words only in different languages. Mostly just squeezing possible smart home words that make sense into an entity name._

**To summarize my observation:**
1. Noto Sans contains only West European/Latin characters, and due to limitation of Nextion editor's font processing capabilities, when a character does not exist in the chosen font, it'll fallback to the font the OS chooses.
2. Noto Sans has very nice English characters, and I am guessing the Chinese characters are taken from one of your Traditional Chinese fonts in the OS, which looks nice too. It then falls back to Simplified (actually looks like Japanese) font for those missing.
3. The only problem is with Simplified Chinese, there are different font weights between characters. This is usually due to different fonts being used. If you compare test 4 and test 5, it's quite obvious test 4 has an uniform thickness between every character, while test 5 has inconsistencies.
4. Size increase is observable too, compared to my TFT, yours has more details and sharper Chinese characters... not too sure what I've done wrong, but they also look different in size :/

Personally though I do not mind the minor differences because as a small screen it is not too distracting, so please consider to give this a pass (the inclusion itself is awesome already!)

I'll try to work on finding a nice font like Noto Sans with more Unicode characters built-in and inform back.

Again, thank you for your great efforts in making this happen! :) :)

**Comment by joBr99** [comment]
Looks like there is also Noto Sans for Chinese, maybe there is also a version that contains everything.

https://fonts.google.com/noto/specimen/Noto+Sans+SC

**Comment by knifehandz** [comment]
Thank you, will have a look and test myself too from the GitHub one. Looking into the CJK version in particular.

I've downloaded the one from Google Fonts when I first tried to generate my own TFT. and that's why I assumed Noto Sans is only for western languages. Glad to know it's not :D

**Comment by joBr99** [comment]
checked the font I've installed on my system and it's this one

https://github.com/notofonts/noto-fonts

looks project has been moved to this one:

https://notofonts.github.io/
https://github.com/notofonts/notofonts.github.io


Not sure what the noto-cjk project contains and how it plays along the normal font; maybe it's needed to merge two font files before generating the nextion editor.
