### ISSUE TITLE
[BUG] CardQR sleepReached event message has wrong source

### ISSUE THREAD

**Issue by laluz742** [joBr99/nspanel-lovelace-ui#826]
The send message has wrong source on cardQR:
       tSend.txt="event,sleepReached,cardAlarm"

**Comment by joBr99** [comment]
this source isn't used by the backend in any way

**Comment by laluz742** [comment]
Jep, but this is what is received on topic tele/RESULT:
{"CustomRecv":"event,sleepReached,cardAlarm"}
