### ISSUE TITLE
[Feature Request]  - Image display

### ISSUE THREAD

**Issue by zanaca** [joBr99/nspanel-lovelace-ui#828]
### FEATURE DESCRIPTION
Showing images on a media like card, from a remote URL.

### ADDITIONAL CONTEXT
It would be great to be able to remote show images on nspanel.  A doorbell button is pressed and a camera would take a picture of the frontdoor and the image would be shown on nspanel "X". You can think of a Ring doorbell camera showing it's image on the  nsPanel

### PANEL / FIRMWARE VERION
EU and US-P

**Comment by joBr99** [comment]
See #560 #448 #323 #288 #177 #127 and probably some more.
