### ISSUE TITLE
[BUG] tmSleep with wrong source (cardAlarm) on cardPower, cardChart, cardLChart

### ISSUE THREAD

**Issue by laluz742** [joBr99/nspanel-lovelace-ui#833]
With regards to  Issue #826  same is for other cards
in tmSleep with new  [Commit 4483d5e1c7db4fa2d3f74ad0d55d5f17c171db46](https://github.com/joBr99/nspanel-lovelace-ui/commit/4483d5e1c7db4fa2d3f74ad0d55d5f17c171db46), thus wrong source for `sleepReached` event

Following cards have `tSend.txt="event,sleepReached,cardAlarm"`
+ cardPower
+ cardChart
+ cardLChart

in `tmSleep` object

**Comment by joBr99** [comment]
yeah ... I already didn't get this in #826, what is the bug here? this value isn't used anywhere

**Comment by laluz742** [comment]
I‘m currently developing a new backend for node-red, this is why these issues come up.

**Comment by joBr99** [comment]
ah ok, do you need thoose values for something?

**Comment by laluz742** [comment]
Not yet… just stumbled over these return values. Anyways, it seems to be inconsistent though

**Comment by joBr99** [comment]
well, best option would be to remove this value, as it's not needed, however since nextion requires a lot of duplicated code, this would need to be changed in 45 locations ...
