### ISSUE TITLE
[Feature Request] Trying to use this system for Loxone, so without Home Assistant or without ioBroker

### ISSUE THREAD

**Issue by gertst** [joBr99/nspanel-lovelace-ui#834]
### FEATURE DESCRIPTION
I'm a Loxone user and have LoxBerry running. This makes it possible to communicate to Loxone over MQTT.
I'm trying to understand how this works. Is it possible to set all up using MQTT only?

Or may be only have HA/ioBroker for setup and only use MQTT afterwards?
 
What's possible and what looks like the most preferred way to set this up?
I'm a programmer myself and might be able to change some stuff if needed.
I'm also happy to document the workflow if this would work.

Thanks a lot!
Gert

### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
you can write a backend with any language

serial/mqtt protocol is documented here:

https://github.com/joBr99/nspanel-lovelace-ui/tree/main/HMI

There are backends for iobroker (typescript) and home assistant (python) in this repo.

And there are many more:

IP Symcon: https://community.symcon.de/t/beta-modul-nspanel-lovelace-ui/130109 (php)

SmartHomeNG: https://github.com/sisamiwe/shng-nspanel-plugin (python)

OpenHAB: https://github.com/donoo/o2n2l (nodered/javascript)

**Comment by gertst** [comment]
Thanks a lot for the fast replay - it answers exactly what I was looking for!

Gert
