### ISSUE TITLE
[Feature Request] Entities Card seems to only allow 4 entities in us-p model

### ISSUE THREAD

**Issue by blindguynar** [joBr99/nspanel-lovelace-ui#838]
### FEATURE DESCRIPTION
The screen itself looks like it can support 5 or maybe 6 entities so i'm unclear as to why the entire screen isn't available. 

### ADDITIONAL CONTEXT
using US model in portrait mode.  I looked through the code and couldn't fine a limitation aside from the grid card, but this is the entitiescard.  It must be in the tff file?  Happy to make a pull request if i've over looked it in the code.

### PANEL / FIRMWARE VERION
4.0.5 - US-P

**Comment by joBr99** [comment]
it should, have to check, in case it only show's 4 entities this is a bug

**Comment by joBr99** [comment]
just checked, this is working perfectly fine, if you still have this issue you will need to provide some more details

![image](https://user-images.githubusercontent.com/29555657/231833461-6c40b582-96ae-4253-8925-0a7c62d17e02.png)
