### ISSUE TITLE
weather entity not found

### ISSUE THREAD

**Issue by detlefh68** [joBr99/nspanel-lovelace-ui#84]
Guten Morgen,

Vielen Dank für die super Projekt, ich nutze es seit ein paar Tagen und bin begeistert. Ich sende dir einen kleinen Beitrag für die Pizza 👍 

Ich habe seit zwei Tagen keine Wetterinformationen mehr auf dem Panel. Heute habe ich von „main“ auf die Version 1.8.3 upgedatet. BEim AppDaemon erscheint im LOG die Meldung:

    ERROR nspanel-1: Skipping Weather Update, entitiy not found

In der Config habe ich „weather.home“ eingetragen:

    timeFormat: "%H:%M"
    dateFormat: "%A, %d. %B %Y" # ignored if babel python package is installed
    weatherEntity: weather.home
![IMG_0836](https://user-images.githubusercontent.com/60793377/160272795-0430a9ad-f1c5-4820-89a6-e8382cfc9a1d.jpeg)

Kann ich etwas ändern oder einstellen, damit die Wetterinformationen wieder angezeigt werden?

Vielen Dank!

**Comment by joBr99** [comment]
vielen dank, ja einfach weatherEntity zu weather ändern

**weatherEntity in config has been renamed to weather**

**Comment by detlefh68** [comment]
super, es funktioniert => das habe ich übersehen…

Vielen Dank!
