### ISSUE TITLE
[Help] popupShutter

### ISSUE THREAD

**Issue by elgerg** [joBr99/nspanel-lovelace-ui#851]
Hi,

I am trying to use the popupShutter page but based on the following:

var page = "pageType~popupShutter";

//"~~~~~~~~";

var cmnd_list = [];
cmnd_list[0] = "entityUpdateDetail";
cmnd_list[1] = "Curtains"; //entityName
cmnd_list[2] = "50"; //*sliderPos*
cmnd_list[3] = "10"; //2ndrow
cmnd_list[4] = "5"; //textPosition
cmnd_list[5] = ""; //icon1 - arrow-expand-horizontal
cmnd_list[6] = ""; //iconUp - arrow-expand-horizontal
cmnd_list[7] = ""; //iconStop
cmnd_list[8] = ""; //iconDown - arrow-collapse-horizontal
cmnd_list[9] = "1"; //iconUpStatus
cmnd_list[10] = "2"; //iconStopStatus
cmnd_list[11] = "3"; //iconDownStatus
cmnd_list[12] = "N/A"; //textTilt
cmnd_list[13] = ""; //iconTiltLeft
cmnd_list[14] = ""; //iconTiltStop
cmnd_list[15] = ""; //iconTiltRight
cmnd_list[16] = ""; //iconTiltLeftStatus
cmnd_list[17] = ""; //iconTiltStopStatus
cmnd_list[18] = ""; //iconTiltLeftStatus
cmnd_list[19] = ""; //tiltPos

I dont get any fields/icons. I just get the top right X, up, stop and down arrows.

Can you let me know what I am missing or add a table like you did with the others here?

https://github.com/joBr99/nspanel-lovelace-ui/tree/main/HMI#popupshutter-page

Thanks!

**Comment by joBr99** [comment]
the `entityName` needs to match the name you've used on cardGrid/cardEntities

**Comment by elgerg** [comment]
Wow, quick answer.

I missed the following:

var page = "pageType~popupShutter~Curtains~Curtains";

I just had
var page = "pageType~popupShutter";

Should I be able to override the up and down icons?

Also is it possible to remove the tilt slider? I'm hoping to adapt this for curtains.

Thanks!

**Comment by joBr99** [comment]
some example commands from one of my panels:

cardEntities Page: 

`entityUpd~Rolladen~x~navUp~���~65535~~~delete~~~~~~shutter~cover.rolladenfenster_cover_1~���~17299~Fenster Eingang~���|���|���|disable|enable|enable~shutter~cover.nspterrasse_cover_1~���~17299~Terrasse Fenster~���|���|���|disable|enable|enable~shutter~cover.rolladenterasse_cover_1~���~17299~Terrasse~���|���|���|disable|enable|enable~shutter~cover.rolladen~���~17299~Alle Roll��den~���|���|���|disable|enable|enable`

Message from screen: `event,pageOpenDetail,popupShutter,cover.nspterrasse_cover_1`

Detail Page: `entityUpdateDetail~cover.nspterrasse_cover_1~100~Position: 100~Position~���~���~���~���~disable~enable~enable~~~~~disable~disable~disable~disable`

Tilt Silder won't appear in my example, however I need to check the code to see what exactly is triggering it to hide.

**Comment by elgerg** [comment]
Cool, thanks for the updatedetail part!

I can get the icons looking right with that and I am using the update detail but using the same as you referenced above:

```
cmnd_list[6] = ""; //iconUp - arrow-expand-horizontal
cmnd_list[7] = ""; //iconStop
cmnd_list[8] = ""; //iconDown - arrow-collapse-horizontal
```

I still just get the defaults.

If you can let me know about removing the tilt slider I would be ever so grateful.

Thanks

**Comment by joBr99** [comment]
cmnd_list[19] = ""; //tiltPos

needs to be `disable` for the slider to hide
https://github.com/joBr99/nspanel-lovelace-ui/blob/main/HMI/n2t-out/popupShutter.txt#L570

**Comment by elgerg** [comment]
Ignore that last comment, I must be doing something stupid.

I have it working exactly has hoped for now. 

I think I was missing something in the:
enable~enable~~~~~disable~disable~disable~disable

This is my finished working version:

```
var cmnd_list = [];
cmnd_list[0] = "entityUpdateDetail";
cmnd_list[1] = "LoungeCurtains"; //entityName
cmnd_list[2] = "70"; //*sliderPos*
cmnd_list[3] = "Lounge Curtains"; //2ndrow
cmnd_list[4] = "Open/Close 70%"; //textPosition
cmnd_list[5] = ""; //icon1 - arrow-expand-horizontal
cmnd_list[6] = ""; //iconUp - arrow-expand-horizontal
cmnd_list[7] = ""; //iconStop
cmnd_list[8] = ""; //iconDown - arrow-collapse-horizontal
cmnd_list[9] = "enable"; //iconUpStatus
cmnd_list[10] = "enable"; //iconStopStatus
cmnd_list[11] = "enable"; //iconDownStatus
cmnd_list[12] = ""; //textTilt
cmnd_list[13] = ""; //iconTiltLeft
cmnd_list[14] = ""; //iconTiltStop
cmnd_list[15] = ""; //iconTiltRight
cmnd_list[16] = "disable"; //iconTiltLeftStatus
cmnd_list[17] = "disable"; //iconTiltStopStatus
cmnd_list[18] = "disable"; //iconTiltLeftStatus
cmnd_list[19] = "disable"; //tiltPos
```

and thanks for the link to the txt file, it will give me a hint to go next time ;)

Thanks!

**Comment by elgerg** [comment]
I will see what I can do on that front, never been any good at PR's.

Can you recommend any decent free git GUIs?

My next question would be around:

```
var page = "pageType~popupShutter~Lounge Curtains~LoungeCurtains";
```

Is it possible to make "Lounge Curtains" a bigger font and maybe centered? It seems to be a page title but doesnt really look like it is.

Thanks again!

**Comment by joBr99** [comment]
> I will see what I can do on that front, never been any good at PR's.

Just fork on GitHub, edit the page there should be straight forward all within GitHub.

No, color/font/etc is hard codes on the page.
