### ISSUE TITLE
[Help] pageType~cardEntities

### ISSUE THREAD

**Issue by elgerg** [joBr99/nspanel-lovelace-ui#852]
Hi,

For card entities how do you set the up/down icons for the shutter?

I have 

```
cmnd_list[26] = "shutter" //type
cmnd_list[27] = "cover.curtains" //intNameEntity
cmnd_list[28] = "" //icon
cmnd_list[29] = "52231" //iconColor
cmnd_list[30] = "Curtains" //displayName
cmnd_list[31] = "||" //xxxx|stop|arrow-right-thin
```

But just get the up stop and down icons instead of the collapse, stop and expend ones I was hoping for..

Thanks!

**Comment by joBr99** [comment]
icon_up   = ""
            icon_stop = ""
            icon_down = ""
            icon_up_status = "disable"
            icon_stop_status = "disable"
            icon_down_status = "disable"

value = f"{icon_up}|{icon_stop}|{icon_down}|{icon_up_status}|{icon_stop_status}|{icon_down_status}"

Maybe this helps, there are 6 values now instead of 3.

Status is enable or disable

**Comment by elgerg** [comment]
That was it!
The missing 3 disable/enable (s)!

Thanks!
