### ISSUE TITLE
[BUG] All commands return stat/nspanel/RESULT = {"Command":"Unknown"}

### ISSUE THREAD

**Issue by gertst** [joBr99/nspanel-lovelace-ui#855]
### PROBLEM DESCRIPTION
I try to run the  nspanel-lovelace-ui using MQTT commands only. No HA.
I'm able to receive the topics tele/xxx/ and stat/xxx/
But when trying to send a topic like cmnd/nspanel/CustomSend time~18:17, I receive the topic stat/nspanel/RESULT = {"Command":"Unknown"}
What am I missing?
I tried to send the commands in the Tasmota console also, but same issue.
In my MQTT client how should I send the topic? Using Plain Text, I guess?

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here: 
Not using HA.


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
Not using HA.

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU, version from 10 days ago.

**Comment by joBr99** [comment]
sounds like you do not have the correct berry driver installed

**Comment by joBr99** [comment]
let me know if you have further questions

**Comment by gertst** [comment]
Aha, I redid installing the berry driver and that fixed it - thanks for the fast and to the point help!

For some reason I had to send this command a few times before it really installed the driver... but nevermind, now I'm ready to find out more about the mqtt topics and try to develop a simple backend for some Loxone communication :-)

Do you have any idea of other people are working on Loxone integration? I will probably go with a NodeJS implementation.

 I just want to setup some simple screens that I need. Unfortunately I don't have the time to write a full fletched backend.

Thanks again for the huge dedication on making this project so awesome!

Gert

**Comment by joBr99** [comment]
didn't seen a loxone or nodejs implementation, however take a look at the iobroker backend in this repo, there's probably some stuff you can reuse since it's typescript
