### ISSUE TITLE
[Help] colorWheel,x|y|wh

### ISSUE THREAD

**Issue by elgerg** [joBr99/nspanel-lovelace-ui#857]
Hi there,

I am trying to convert colors from the color wheel to either RGB or CIE 1931 color space (x/y)

A little more context, to drive:
https://www.zigbee2mqtt.io/devices/TS0505B.html#tuya-ts0505b

I must admit that at the moment I have no idea what x|y|wh is. Any chance you can shed light on this?

Thanks!

**Comment by joBr99** [comment]
x and y are the relative coordinates of the touch event on the color wheel picture
wh is the width and height of the color wheel

Here are some implementations for converting thoose values to rgb.

Python: https://github.com/joBr99/nspanel-lovelace-ui/blob/main/apps/nspanel-lovelace-ui/luibackend/helper.py#L15

TypeScript: https://github.com/joBr99/nspanel-lovelace-ui/blob/main/ioBroker/NsPanelTs.ts#L7981
