### ISSUE TITLE
"None" showing in Screen saver display

### ISSUE THREAD

**Issue by madnat** [joBr99/nspanel-lovelace-ui#859]
I am guessing this is a config issue on my setup... but have "None" displayed twice on the screen saver display of the NSPanel (EU)

I have 3 displays and all show the same problem.  How do I remove "None"?

Weather is provided by UK Met API service...  Screenshot for specific details:
 
![IMG_1067](https://user-images.githubusercontent.com/2383947/232020213-1f288bd8-f204-4727-98c2-1c53b6981102.jpg)

**Comment by joBr99** [comment]
No it's an issue with the new AppDeamon version, if you have an backup downgrade the HA addon to 0.11, if not you've to wait for the next release.

See #847

**Comment by madnat** [comment]
Thank you for the quick response.  Appreciated
