### ISSUE TITLE
[Feature Request]  calendar page 📅

### ISSUE THREAD

**Issue by pbvdven** [joBr99/nspanel-lovelace-ui#860]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._

Home assistant Calendar page not for new input but day overview 

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

I would like to see my ha calendar  for that day on the nspanel would also be nice I've you could go to next day 

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU

**Comment by joBr99** [comment]
duplicate #624
