### ISSUE TITLE
Unistall Nextion

### ISSUE THREAD

**Issue by madebywitteveen** [joBr99/nspanel-lovelace-ui#864]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._
Please give an option to remove the nextion firmware ! 
I would like to go back to the original tasmota32-nspanel
### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by madebywitteveen** [comment]
Could anyone help out please?
I'm trying to undo the nextion firmware with lovelaceui on my nspanel with tasmota.
I flashed the tasmota32-nspanel again but after boot the "waiting for content" is still circling. how to remove this 

thank you

**Comment by joBr99** [comment]
https://github.com/masto/NSPanel-Demo-Files/issues/4

There is dumped stock firmware for the nextion display out there, you need to flash it with flashnextion as you did with lovelace.
You need to put the tft file on an http server. (not https)

**Comment by madebywitteveen** [comment]
Thank you, do you know this file at a HTTP server somewhere? I don't have a server 

I'm getting these errors:

1:00:22.599 NXP: Received Raw = bytes('55BB13006576656E742C737461727475702C35302C657557CC')
21:00:22.602 FLH: Something has gone wrong flashing display firmware [bytes('55BB13006576656E742C737461727475702C35302C657557CC')]
21:00:27.166 WIF: Checking connection...
21:00:28.498 NXP: Received Raw = bytes('55BB13006576656E742C737461727475702C35302C657557CC')
21:00:28.502 FLH: Something has gone wrong flashing display firmware [bytes('55BB13006576656E742C737461727475702C35302C657557CC')]
21:00:34.401 NXP: Received Raw = bytes('55BB13006576656E742C737461727475702C35302C657557CC')
21:00:34.405 FLH: Something has gone wrong flashing display firmware [bytes('55BB13006576656E742C737461727475702C35302C657557CC')]
21:00:40.398 NXP: Received Raw = bytes('55BB13006576656E742C737461727475702C35302C657557CC')
21:00:40.401 FLH: Something has gone wrong flashing display firmware [bytes('55BB13006576656E742C737461727475702C35302C657557CC')]
21:00:46.299 NXP: Received Raw = bytes('55BB13006576656E742C737461727475702C35302C657557CC')
21:00:46.306 BRY: GC from 27260 to 17230 bytes, objects freed 111/243 (in 4 ms) - slots from 178/289 to 163/289
21:00:46.308 FLH: Something has gone wrong flashing display firmware [bytes('55BB13006576656E742C737461727475702C35302C657557CC')]
21:00:47.166 WIF:

**Comment by madebywitteveen** [comment]
ok I will try

**Comment by madebywitteveen** [comment]
I am sorry to bother you again my friend; 

did setup the local http but getting these errors:

:40.835 SRC: Button
21:30:40.846 MQT: stat/wallpanellivingroom/RESULT = {"POWER1":"OFF"}
21:30:40.849 MQT: stat/wallpanellivingroom/POWER1 = OFF
21:30:41.694 BTN: Button1 multi-press 1
21:30:42.021 CFG: Saved, Count 16, Bytes 4096
21:30:42.508 SRC: Button
21:30:42.518 MQT: stat/wallpanellivingroom/RESULT = {"POWER1":"ON"}
21:30:42.520 MQT: stat/wallpanellivingroom/POWER1 = ON
21:30:42.832 CFG: Saved, Count 17, Bytes 4096
21:30:46.123 NXP: Received Raw = bytes('55BB13006576656E742C737461727475702C35302C657557CC')
21:30:46.135 MQT: tele/wallpanellivingroom/RESULT = {"CustomRecv":"event,startup,50,eu"}
21:30:52.123 NXP: Received Raw = bytes('55BB13006576656E742C737461727475702C35302C657557CC')
21:30:52.135 MQT: tele/wallpanellivingroom/RESULT = {"CustomRecv":"event,startup,50,eu"}
21:30:57.988 WIF: Checking connection...
21:30:58.022 NXP: Received Raw = bytes('55BB13006576656E742C737461727475702C35302C657557CC')
21:30:58.034 MQT: tele/wallpanellivingroom/RESULT = {"CustomRecv":"event,startup,50,eu"}
21:31:04.022 NXP: Received Raw = bytes('55BB13006576656E742C737461727475702C35302C657557CC')
21:31:04.033 MQT: tele/wallpanellivingroom/RESULT = {"CustomRecv":"event,startup,50,eu"}
21:31:09.923 NXP: Received Raw = bytes('55BB13006576656E742C737461727475702C35302C657557CC')
21:31:09.934 MQT: tele/wallpanellivingroom/RESULT = {"CustomRecv":"event,startup,50,eu"}
21:31:15.822 NXP: Received Raw = bytes('55BB13006576656E742C737461727475702C35302C657557CC')
21:31:15.834 MQT: tele/wallpanellivingroom/RESULT = {"CustomRecv":"event,startup,50,eu"}
21:31:17.989 WIF: Checking connection...
21:31:21.823 NXP: Received Raw = bytes('55BB13006576656E742C737461727475702C35302C657557CC')
21:31:21.834 MQT: tele/wallpanellivingroom/RESULT = {"CustomRecv":"event,startup,50,eu"}
21:31:27.723 NXP: Received Raw = bytes('55BB13006576656E742C737461727475702C35302C657557CC')
21:31:27.734 MQT: tele/wallpanellivingroom/RESULT = {"CustomRecv":"event,startup,50,eu"}
21:31:33.722 NXP: Received Raw = bytes('55BB13006576656E742C737461727475702C35302C657557CC')
21:31:33.734 MQT: tele/wallpanellivingroom/RESULT = {"CustomRecv":"event,startup,50,eu"}
21:31:37.989 WIF: Checking connection...
21:31:39.623 NXP: Received Raw = bytes('55BB13006576656E742C737461727475702C35302C657557CC')
21:31:39.634 MQT: tele/wallpanellivingroom/RESULT = {"CustomRecv":"event,startup,50,eu"}
21:31:45.622 NXP: Received Raw = bytes('55BB13006576656E742C737461727475702C35302C657557CC')
21:31:45.634 MQT: tele/wallpanellivingroom/RESULT = {"CustomRecv":"event,startup,50,eu"}
21:31:49.126 BRY: GC from 27127 to 16916 bytes, objects freed 145/240 (in 5 ms) - slots from 263/304 to 164/259
21:31:51.523 NXP: Received Raw = bytes('55BB13006576656E742C737461727475702C35302C657557CC')
21:31:51.535 MQT: tele/wallpanellivingroom/RESULT = {"CustomRecv":"event,startup,50,eu"}
21:31:56.346 CMD: flashnextion http://localhost:8181/ns-panel.tft
21:31:56.348 SRC: WebConsole from 192.168.1.139
21:31:56.350 CMD: Grp 0, Cmd 'FLASHNEXTION', Idx 1, Len 34, Pld -99, Data 'http://localhost:8181/ns-panel.tft'
21:31:56.372 MQT: stat/wallpanellivingroom/RESULT = {"FlashNextion":"Done"}
21:31:56.406 FLH: host: localhost, port: 8181, get: /ns-panel.tft
21:31:56.410 WIF: DNS resolved 'localhost' (127.0.0.1) in 0 ms
21:31:56.416 FLH: Connected:false
21:31:56.520 FLH: Retry 2
21:31:56.722 FLH: Retry 3
21:31:57.024 FLH: Retry 4
21:31:57.427 FLH: Retry 5
21:31:57.429 FLH: Nothing available to read!
21:31:57.433 NXP: Nextion command sent = bytes('4452414B4A485355594447424E434A48474A4B534842444EFFFFFF')
21:31:57.438 NXP: Nextion command sent = bytes('7265636D6F643D30FFFFFF')
21:31:57.442 NXP: Nextion command sent = bytes('7265636D6F643D30FFFFFF')
21:31:57.456 NXP: Nextion command sent = bytes('636F6E6E656374FFFFFF')
21:31:57.465 NXP: Received Raw = bytes('55BB13006576656E742C737461727475702C35302C657557CC')
21:31:57.469 FLH: Something has gone wrong flashing display firmware [bytes('55BB13006576656E742C737461727475702C35302C657557CC')]
21:31:58.983 WIF: Checking connection...
21:32:03.465 NXP: Received Raw = bytes('55BB13006576656E742C737461727475702C35302C657557CC')
21:32:03.468 FLH: Something has gone wrong flashing display firmware [bytes('55BB13006576656E742C737461727475702C35302C657557CC')]
21:32:09.365 NXP: Received Raw = bytes('55BB13006576656E742C737461727475702C35302C657557CC')
21:32:09.368 FLH: Something has gone wrong flashing display firmware [bytes('55BB13006576656E742C737461727475702C35302C657557CC')]
21:32:15.365 NXP: Received Raw = bytes('55BB13006576656E742C737461727475702C35302C657557CC')
21:32:15.369 FLH: Something has gone wrong flashing display firmware [bytes('55BB13006576656E742C737461727475702C35302C657557CC')]
21:32:18.982 WIF: Checking connection...
21:32:21.265 NXP: Received Raw = bytes('55BB13006576656E742C737461727475702C35302C657557CC')
21:32:21.268 FLH: Something has gone wrong flashing display firmware [bytes('55BB13006576656E742C737461727475702C35302C657557CC')]
21:32:27.266 NXP: Received Raw = bytes('55BB13006576656E742C737461727475702C35302C657557CC')
21:32:27.270 FLH: Something has gone wrong flashing display firmware [bytes('55BB13006576656E742C737461727475702C35302C657557CC')]

**Comment by joBr99** [comment]
http://localhost:8181/ns-panel.tft

You need to use the IP address of your PC and not localhost, localhost it the local device, so the nspabel itself.

**Comment by madebywitteveen** [comment]
Thanks, it starts something what looks like USART update, says 'writing data......' just like installing but nothing else further screen stays like this without progress.

any ideas ? thanks

**Comment by joBr99** [comment]
Restart tasmota and try again, without the logs from the console there's not much I can tell u

**Comment by madebywitteveen** [comment]
I understand, the panel does not boot after this thus no console log. The only option is to flash the tasmota32-nspanel into it to gain access but then the lovelace is still in there?!
Tried this 3 times already, I'm getting stuck.

This is the flasher-log:
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:184
load:0x40078000,len:12680
load:0x40080400,len:2908
entry 0x400805c4

00:00:00.002 HDW: ESP32-D0WD-V3 
00:00:00.078 UFS: FlashFS mounted with 276 kB free
00:00:00.103 CFG: Loaded from File, Count 5
00:00:00.114 QPC: Count 1
00:00:00.297 BRY: Berry initialized, RAM used=4041 bytes
00:00:00.314 TFS: File '.drvset003' not found
00:00:00.315 CFG: Energy use defaults as file system not ready or file not found
00:00:00.323 Project tasmota - Tasmota Version 12.4.0.5(nspanel)-2_0_7(2023-04-16T21:20:08)
00:00:00.724 NXP: Initializing Driver
00:00:00.730 BRY: Successfully loaded 'autoexec.be'
00:00:00.015 WIF: WifiManager active for 3 minutes
00:00:01.660 HTP: Web server active on tasmota-C38908-2312 with IP address 192.168.4.1
00:00:06.916 QPC: Reset

**Comment by joBr99** [comment]
There are two microcontroller in this thing the STM in the display and the esp32 on the board. This is a replacement for the firmware on the display. It doesn't have anything to do with tasmota. You can actually replace tasmota with esphone aswell.

You need to flash the stock display firmware TFT file, you can do that with flashnextion which is updating the firmware on the display. Cannot tell you why your tasmota installation gets inaccessible, but those two microcontrollers are completely independent. 

If your display is showing errors like system data error, you can safely ignore them.

**Comment by madebywitteveen** [comment]
I understand that my friend but it doens't flash, it hangs and does nothing.

before using the flashnextion I have to use this right?:
Backlog UrlFetch https://raw.githubusercontent.com/joBr99/nspanel-lovelace-ui/main/tasmota/autoexec.be; Restart 1

otherwise I can not use the flasnextion command?
and to be clear: by stock firmware you mean this one?:
https://cdn.discordapp.com/attachments/538814618106331139/925351768852951050/ns-panel.tft

**Comment by joBr99** [comment]
Yes and it has to be on a local http Server doesn't work directly from the discord url

**Comment by madebywitteveen** [comment]
think I found something ! tried to flash two times in a row:

the display turns white and states: "model does not match, device model: NX4832F035_011C

can you do anything with this information ?

**Comment by joBr99** [comment]
This happens if your TFT file isn't a TFT file.

Redownload the TFT file and check if there's not a bunch of garbage in the file.

**Comment by madebywitteveen** [comment]
The one I am using looks like a binary with all unreadable characters, there is also a nspanel_blank.tft on the web with contains html code (which I did not use !)

there are more people having issues, many are suggesting to change the baudrate?
How and where can I do that? 
in the autoexec.be ?

thanks again

**Comment by madebywitteveen** [comment]
I'm giving up. Can I send the nspanel to you please ? Maybe you can fix this? 
Or do you know someone in Netherlands who can ?

thanks

**Comment by joBr99** [comment]
try to flash with this url: `FlashNextion http://nspanel.pky.eu/stock-nsp-1704.tft`

**Comment by madebywitteveen** [comment]
nu luck unfortuneately:

23:12:52.243 CMD: Grp 0, Cmd 'FLASHNEXTION', Idx 1, Len 44, Pld -99, Data 'http://192.168.1.139:8181/stock-nsp-1704.tft'
23:12:52.267 MQT: stat/wallpanellivingroom/RESULT = {"FlashNextion":"Done"}
23:12:52.303 FLH: host: 192.168.1.139, port: 8181, get: /stock-nsp-1704.tft
23:12:52.306 WIF: DNS resolved '192.168.1.139' (192.168.1.139) in 1 ms
23:12:54.313 FLH: Connected:false
23:12:54.416 FLH: Retry 2
23:12:54.619 FLH: Retry 3
23:12:54.921 FLH: Retry 4
23:12:55.323 FLH: Retry 5
23:12:55.325 FLH: Nothing available to read!
23:12:55.329 NXP: Nextion command sent = bytes('4452414B4A485355594447424E434A48474A4B534842444EFFFFFF')
23:12:55.334 NXP: Nextion command sent = bytes('7265636D6F643D30FFFFFF')
23:12:55.338 NXP: Nextion command sent = bytes('7265636D6F643D30FFFFFF')
23:12:55.353 NXP: Nextion command sent = bytes('636F6E6E656374FFFFFF')
23:12:55.362 NXP: Received Raw = bytes('55BB13006576656E742C737461727475702C35302C657557CC')
23:12:55.365 FLH: Something has gone wrong flashing display firmware [bytes('55BB13006576656E742C737461727475702C35302C657557CC')]
23:12:55.538 NXP: Received Raw = bytes('636F6D6F6B20322C33303631342D302C4E5834383332463033355F303131432C...')
23:12:55.591 FLH: Send (High Speed) flash start
23:12:55.597 NXP: Nextion command sent = bytes('77686D692D7772697320302C3932313630302C72657330FFFFFF')
23:12:55.965 NXP: Received Raw = bytes('05')
23:12:55.969 FLH: Read block
23:12:55.972 BRY: Exception> 'type_error' - unsupported operand type(s) for <: 'nil' and 'int'
23:13:00.130 WIF: Checking connection...

**Comment by joBr99** [comment]
`http://192.168.1.139:8181/stock-nsp-1704.tft` != `http://nspanel.pky.eu/stock-nsp-1704.tft`

Restart tasmota and run `FlashNextion http://nspanel.pky.eu/stock-nsp-1704.tft` nothing else

**Comment by madebywitteveen** [comment]
my hero ! it's going...........7%......................9%........................
was it my http server?

**Comment by madebywitteveen** [comment]
................40%............still going...........

**Comment by madebywitteveen** [comment]
did work, thanks man 

made a donation

off to bed

**Comment by madebywitteveen** [comment]
morning; and do you know why the lovelaveui didn't show icons? that's what the whole firmware issue started

thanks

**Comment by joBr99** [comment]
Please be more precise, what do you mean with that

**Comment by madebywitteveen** [comment]
Ok sure,The ui did not show icons, there was an error at each icon that the picture was not found.Same as this person explains:https://community.home-assistant.io/t/nspanel-not-showing-icon-images/554773
-------- Original message --------From: Johannes ***@***.***> Date: 18/04/2023  07:46  (GMT+01:00) To: joBr99/nspanel-lovelace-ui ***@***.***> Cc: madebywitteveen ***@***.***>, Author ***@***.***> Subject: Re: [joBr99/nspanel-lovelace-ui] Unistall Nextion (Issue #864) 
Please be more precise, what do you mean with that

**Comment by madebywitteveen** [comment]
Ok thanks!
-------- Original message --------From: Johannes ***@***.***> Date: 18/04/2023  15:02  (GMT+01:00) To: joBr99/nspanel-lovelace-ui ***@***.***> Cc: madebywitteveen ***@***.***>, Author ***@***.***> Subject: Re: [joBr99/nspanel-lovelace-ui] Unistall Nextion (Issue #864) 
Not found means that the entity wasn't found within your homeassistent installation, so the entity names you've configured aren't correct.

**Comment by madebywitteveen** [comment]
Good morning,

is it possible that you keep the http://nspanel.pky.eu/stock-nsp-1704.tft file on your site for a month or so?
Lovelace looks great but it would be nice to be able to revert.
Do you think that the issue we had monday was with my local HTTP server ?

thanks

**Comment by joBr99** [comment]
No, I don't want to host due to legal reasons.

But you can just use HomeAssistant as a webserver for it. (If there is no www folder you can create one.)

![image](https://user-images.githubusercontent.com/29555657/233128926-01590336-49e1-4a84-989e-c46bd89b5fda.png)

`FlashNextion http://192.168.75.30:8123/local/nspanel.tft`

**Comment by madebywitteveen** [comment]
Thanks, I have it working now,Works great that UI !H
-------- Original message --------From: Johannes ***@***.***> Date: 19/04/2023  17:44  (GMT+01:00) To: joBr99/nspanel-lovelace-ui ***@***.***> Cc: madebywitteveen ***@***.***>, Author ***@***.***> Subject: Re: [joBr99/nspanel-lovelace-ui] Unistall Nextion (Issue #864) 
No, I don't want to host due to legal reasons.
But you can just use HomeAssistant as a webserver for it. (If there is no www folder you can create one.)

FlashNextion http://192.168.75.30:8123/local/nspanel.tft
