### ISSUE TITLE
[BUG] Using buttons on a cardThermo causes timer to stop functioning

### ISSUE THREAD

**Issue by elgerg** [joBr99/nspanel-lovelace-ui#868]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
I have created a card thermo page as thus:

```
pageType~cardThermo
entityUpd~Heating~button~navigate.prev~~65535~~~button~navigate.next~>~65535~~~Heating~21.0°C~70~OFF(1)~70~300~5~   +~52231~0~plus15~15~52231~0~plus15~   +~52231~0~plus30~30~52231~0~plus30~~~~~~~~~~~~~~~~~Current~Status~true~°C~~1
```

When I press one of the "   +", 15 or 30 the screen never send the sleep timeout event. It doesnt matter what popup you go to the only thing that seems to trigger a timeout that I have tried is the popupLight page (from a popup card), anything thats navigated by pressing on the screensaver never seems to go back.

I hope I am making myself clear?

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:

I'm using Node-Red to produce the above.

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
I am not using app daemon

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Run the above commands

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
I expected that after the timeout (30 seconds) the screensaver would re-appear due to "event,sleepReached,cardThermo" but that never gets triggered.

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
I am not sure how to get the version but it was one downloaded from Github on the 6th, as for the type it's the EU one.

**Comment by joBr99** [comment]
![image](https://user-images.githubusercontent.com/29555657/233155851-fad7df28-3c3f-443c-a278-f64c2e6dd0bf.png)

Not sure if I understood the problem.

There is no automatic navigation back to the screensaver from cards, there is only the `event,sleepReached` message and you need to answer with pageType and the data for the page to navigate away from it.

**Comment by elgerg** [comment]
I just had a lightbulb moment.

I am sending a second 

```
entityUpd~Heating~button~navigate.prev~~65535~~~button~navigate.next~>~65535~~~Heating~21.0°C~70~OFF(1)~70~300~5~   +~52231~0~plus15~15~52231~0~plus15~   +~52231~0~plus30~30~52231~0~plus30~~~~~~~~~~~~~~~~~Current~Status~true~°C~~1
```

Event 10 seconds after the button press. Without this update the sleep does reach..

Strange?

**Comment by joBr99** [comment]
are you also sending pageType again? pageType will reset the sleep timer

**Comment by elgerg** [comment]
To expand on:

"There is no automatic navigation back to the screensaver from cards or popups, there is only the event,sleepReached message and you need to answer with pageType and the data for the page to navigate away from it."

That sleep reached event doesnt seem to fire after the second update.

When I removed the link back after the button trigger it did call the "event,sleepReached,cardThermo".



> are you also sending pageType again? pageType will reset the sleep timer

Yes, that must be the issue.

**Comment by joBr99** [comment]
https://github.com/joBr99/nspanel-lovelace-ui/blob/main/HMI/n2t-out/cardThermo.txt#L1058

pageType is reseting the sleepTimer, should be the case of all pages

**Comment by elgerg** [comment]
You're right. I knew I must have been doing something really dumb.

I've tested this and it works perfectly! 

Thank you for your help once again :)
