### ISSUE TITLE
Black screen after running "FlashNextion" command

### ISSUE THREAD

**Issue by taert79** [joBr99/nspanel-lovelace-ui#87]
Hi,

I followed instructions to flash my NSPanel step by step and everything seems to work, except that the screen on my device remains black after running the "FlashNextion" command. Nothing seems to happen... I have tried various times. Here's what I see in the console log: 
11:16:39.943 CMD: FlashNextion http://nspanel.pky.eu/lui.tft
11:16:39.961 MQT: stat/tasmota_poolhouse/RESULT = {"FlashNextion":"Done"}
11:16:40.033 FLH: host: nspanel.pky.eu, port: 80, get: /lui.tft

**Comment by joBr99** [comment]
are you sure that this cable is connected?

![image](https://user-images.githubusercontent.com/29555657/160380688-7bf337b2-2c7b-462c-92f9-f06640c6685b.png)

**Comment by joBr99** [comment]
the display shouldn't be black

another option is to check if the tasmota template is applied correctly
