### ISSUE TITLE
[Feature Request] Popup "Lights" with effects and speed

### ISSUE THREAD

**Issue by christianloesel** [joBr99/nspanel-lovelace-ui#875]
### FEATURE DESCRIPTION
A configured Device with Hue or RGB brings the ability to get Popup for Brightness and Color / Colortemperatur adjustments. In Advance some Lights (mostly LED-Bands) have different modes / effects and speed-settings. It would be great to have those setting on the NSpanel too.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
EU
Tasmota 12.5.0
Display 50
TFT 4.0.5

**Comment by christianloesel** [comment]
Didn‘t find out how to activate it. Can you show me what kind of device I have to set-up for it?
In the end it will go to Tasmota on a Shelly RGBW. Thank you

**Comment by joBr99** [comment]
![image](https://user-images.githubusercontent.com/29555657/234343641-1ceb634a-62dd-4f99-8fbd-ab1a56441db4.png)

It's shown automatically if you entity supports effects / has the effect_list attribute.

**Comment by joBr99** [comment]
well, this information was missing; cannot tell you how it works on iobroker, but it is implemented there aswell

best location to ask for iobroker questions is
https://forum.iobroker.net/topic/58170/sonoff-nspanel-mit-lovelace-ui

**Comment by christianloesel** [comment]
Can you please tell me where it's implemented? I searched in /ioBroker/NsPanelTs.ts from line 6090 on.

**Comment by Armilar** [comment]
The functions related to the new popupLight are not yet implemented in ioBroker. Will come from version 4.6.0.

However, it is possible to use standard controls in e.g. a cardEntities or in a cardGrid as in the following example:

https://github.com/joBr99/nspanel-lovelace-ui/wiki/ioBroker---FAQ-&-Anleitungen#21-wled

**Comment by joBr99** [comment]
I thought the effect popup was implemented in the ioBroker before it was implemented in the HA backend o.O

**Comment by Armilar** [comment]
Yes, you can display the popupInSel from the cardEntities or the cardGrid. Therefore, I have listed the example with the WLED, in which it is used as an example.

It only doesn't work from the new popupLight, since that is currently not implemented in ioBroker.

**Comment by joBr99** [comment]
the commands for the popup didn't change

**Comment by christianloesel** [comment]
Ok thank you.
I will wait for the 4.0.5 update. Love keeping the panel pages simple :-)
