### ISSUE TITLE
[BUG] Problems with weather-instances-number !="0"

### ISSUE THREAD

**Issue by kptkip** [joBr99/nspanel-lovelace-ui#876]
### PROBLEM DESCRIPTION
IoBroker-files:
When using an instance of a weather-adapter - doesn't matter which one - that has not the number "0" the weather-data in the screensaver doesn't show data.
 As an example: `accuweather.1.`

### REQUESTED INFORMATION
The reason is, that on the one hand the weather entity is checked and set as a variable:
`weatherEntity: "alias.0.[MYWEATHERALIAS]",    // Dieser Alias wird automatisch für den gewählten Wetter erstellt und kann entsprechend angepasst werden`

But on the other hand the explicit string "accuweather.0" for the instance is hard-coded  >40 times in the following code of the application.

After manually search/replace of all appearances of "accuweather.0" with "accuweather.1" now it works.

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:

```

### TO REPRODUCE
_Steps to reproduce the behavior:_


### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._


### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._


### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by Armilar** [comment]
Will implement the instance number of the adapter

v4.0.6

**Comment by Armilar** [comment]
Fix Online

v4.0.5.13
