### ISSUE TITLE
[Feature Request] Icon template for cardPower (and possibly other cards)

### ISSUE THREAD

**Issue by phoenixtechnam** [joBr99/nspanel-lovelace-ui#877]
Currently it does not seem possible to use icon templates in CardPower entities the same way as with color and speed attributes:
The example below is to have different battery charge icons for different battery voltages

![image](https://user-images.githubusercontent.com/29205326/234612535-18743a63-0ab1-4622-8fc9-6cc8a8a4cfd2.png)

It would be great to have icon templates in CardPower and possibly other cards (didn't test).

**Comment by joBr99** [comment]
for icons you can use this

`
        icon: 'ha:{{ iif(is_state('light.kitchen', 'on'), '<I>mdi:flashlight</I>', '<I>mdi:flashlight-off</I>') }}'
`
https://docs.nspanel.pky.eu/entities/

(with upcoming version / dev version)

#867
