### ISSUE TITLE
US version

### ISSUE THREAD

**Issue by drbios** [joBr99/nspanel-lovelace-ui#88]
hi, i have the us version of the NSpannel, this tft file load but it's not working properly. it's posibe make a US version?

**Comment by joBr99** [comment]
yes, download the HMI Project remove the lcd_dev line in Program.s and generate you an tft file this will fix the touch offset issue

**Comment by joBr99** [comment]
also see issue #60

**Comment by drbios** [comment]
when you say generate a new tft ... you mean use the nextion editor?

**Comment by joBr99** [comment]
yes download the hmi project remove that line and generate a tft in the nextion editor

**Comment by drbios** [comment]
Thank you for your response
Best regards

**Comment by joBr99** [comment]
as already noted in #60 at the moment I'm not planning to provide precomiled tfts for the US version, if you guys want to help with that, we can do that :)
