### ISSUE TITLE
[Feature Request] RTSP Feeds /  picture-entity

### ISSUE THREAD

**Issue by LordDamocles** [joBr99/nspanel-lovelace-ui#880]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._
It would be cool to have the option to see RTSP feeds or have the option to use the picture-entity.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU
US-P

**Comment by joBr99** [comment]
See #828 #560 #448 #323 #288 #177 #127 and probably some more. It's technically not possible to do that

**Comment by LordDamocles** [comment]
Bugger.
I see now this has been asked a bit, in several ways, is it possible to update the but you mention this is may be possible with the NSPanel Pro?

**Comment by joBr99** [comment]
Yes, with nspabel pro it's easy. But nspabel can only display pics that are build into the firmware.
