### ISSUE TITLE
[Feature Request] Alarm Clock / Timer Page

### ISSUE THREAD

**Issue by dannyv1101** [joBr99/nspanel-lovelace-ui#884]
Hi, it would be very nice to add an alarm clock page. Where I can see existing alarm clocks, or timers and also can set up alarm clocks and timers. Maybe it is possible that this page works together with the android app mqtt alarm clock. But interface with this app can also be done in an additional blockly.

### FEATURE DESCRIPTION
- see timers and alarm clocks
- set up timers and alarm clocks
- toggle different datapoints (for example: alarm is acitve, alarm is snoozed, alarm is deaktivated, timer is running or timer is expiered)

**Comment by joBr99** [comment]
There is already a timer popup

![image](https://user-images.githubusercontent.com/29555657/235895534-d2b2e29c-ebfa-4d48-ab81-70c48540e4b4.png)

https://github.com/joBr99/nspanel-lovelace-ui/wiki/ioBroker-ALIAS-Definitionen#timer---popuptimer---leveltimer

**Comment by Armilar** [comment]
Was implemented for ioBroker with release v3.7.0

https://github.com/joBr99/nspanel-lovelace-ui/wiki/ioBroker-ALIAS-Definitionen#timer---popuptimer---leveltimer
