### ISSUE TITLE
panel freezes at 17:40

### ISSUE THREAD

**Issue by Claus-Schumacher** [joBr99/nspanel-lovelace-ui#894]
My NSPANEL EU is running on 4.0.5 since many week. The esp is running on esphome. Since maybe four or five days the panel kind of freezes every day at exactly 17:40. It responses to touch such that it changes the screen brightness. Screen content doesn't change, though.
The only way I found so far to get the display working again is to unmount it to cut power and then mount it again. It boots nicely and then runs flawlessly until the next day at 17:40.
I'm happy to post whatever additional information is needed.

**Comment by joBr99** [comment]
well logs from appdaemon and esphome would be helpful, also is the panel still online after it's freezing

**Comment by dannyv1101** [comment]
I just saw the issue, I also had a freeze at 1 of 4 panels 2 days before, I am sure it also was 17:40.
I removed the power of the panel waited for some seconds and then I connected it again, nothing happend, the panel stayed black. So I removed the panel and conneced it to 5V and then it worked again (after about ten seconds staying also black). So I put the panel back to the baseunit and now it is running for 2 days without any trouble.

**Comment by Claus-Schumacher** [comment]
I'll provide appdaemon logs shortly. 
Meanwhile I found an automatable work around: at least when running on esphome there is a toggle button to turn on and off the display. Turn it off and on again with that and it is fine for another 24h.

**Comment by Claus-Schumacher** [comment]
Sorry for bothering you all! It was entirely my fault. I accidentally activated a "testing" automation which tried (besides the intended actions) to upload a TFT file to the panel which no longer existed. This upload approach apparently froze the display.
So embarrassing ... Sorry again!

**Comment by joBr99** [comment]
exiting reprase mode (which you have to do for flahsing) will stop the panel from processing messages ;) so sounds reasonable
