### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by geeks-r-us** [joBr99/nspanel-lovelace-ui#897]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

When hardware buttons are used for toggle function only on click is sent. After that there is no reaction until tele/RESULT change to something else then 
    {"CustomRecv":"event,button1"}

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:

Using IOBroker

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:

Using IOBroker
```

### TO REPRODUCE
_Steps to reproduce the behavior:_

- disconnect hardware buttons from relays
- add button handler code and configure it as toggle
- push button without issuing an event of the touchscreen afterwards

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

hardware button should react all the time

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

Using latest IOBroker and TS script

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

EU Panel with Tasmota 12.5

**Comment by joBr99** [comment]
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/0300443f-41f2-4b03-8602-6d7eeb76b5cc)

Is this checkbox checked on your installation? This would explain the behaviour, mqtt events needs to be published all the time not only on changes.
