### ISSUE TITLE
[Feature Request] Switch Page

### ISSUE THREAD

**Issue by grericht** [joBr99/nspanel-lovelace-ui#898]
### FEATURE DESCRIPTION
i would like to have a page with minimum 8 switches. maybe 4x2 or 2x4. I think if there is only an icon+switch per endity, it would be possible to get 4x4. If there is the possibility to hit the ican, changing color, maybe 6x4 would be possible.

### ADDITIONAL CONTEXT
with blueprint there is the possiblility to get 4x2 icons (color changing) with switch on one page. this would be nice for lovelace ui too.

### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
so cardGird with more icons?

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/1500c0b1-8bbd-4118-9c56-824ace996dad)

**Comment by grericht** [comment]
yes. like the gridCard but i think it would be nice to have much more icons on one window. with blueprint it is possible to give a value if u want a seperate window with the question if u realy want to change the switch. so u can be save, not to switch unwilling

**Comment by joBr99** [comment]
Current development version will automatically switch to an layout with 8 items if there are more than 6 entities configured.

 ![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/66b7c90d-b5d1-4d70-9ada-2296de84b0ce)

**Comment by joBr99** [comment]
@Armilar pageType ist "cardGrid2", sind vermutlich nicht mehr als 3 zeilen code, im backend :)

**Comment by grericht** [comment]
for an update i have to install the latest tft file?

**Comment by joBr99** [comment]
just follow the instructions in the release notes
https://github.com/joBr99/nspanel-lovelace-ui/releases/tag/v4.1.4
