### ISSUE TITLE
Flashing not possible[BUG] 

### ISSUE THREAD

**Issue by Henry221164** [joBr99/nspanel-lovelace-ui#904]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

Flashing the nspanel-v4.1.0.tft is not possible
### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel1/RESULT"
    panelSendTopic: "cmnd/nspanel1/CustomSend"
    model: eu
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "0:30:00"
        value: 0
    locale: "de_DE"
    screensaver:
      entity: weather.openweathermap

    cards:
      - type: cardEntities
        entities:
          - entity: sensor.wohnzimmer_temp_feuchte_temperature
          - entity: sensor.wohnzimmer_temp_feuchte_humidity
          - entity: sensor.aussentemp_hutte
          - entity: sensor.openweathermap_humidity
        title: Allgemein
      - type: cardGrid
        entities:
          - entity: light.licht_an_aus
          - entity: light.flur_licht
          - entity: light.wohnzimmer_couch_licht
          - entity: light.wohnzimmer_licht_hinter_tv
          - entity: light.wohnzimmer_licht_anrichte
        title: Licht 
      - type: cardEntities
        title: Jalusien
        entities:
          - entity: cover.jalusie_fenster_2
          - entity: cover.jalusie_kleine_tur
          - entity: cover.jalusie_grosse_tur
      - type: cardThermo
        title: Heizung
        supportedModes: ['heat', 'off','auto']
        entity: climate.wohnzimmer
           
```
  Log output here:

 2023-05-22 12:16:12.999968 INFO nspanel-1: MQTT callback for: {'topic': 'tele/nspanel1/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,startup,50,eu"}'}
2023-05-22 12:16:13.002619 INFO nspanel-1: Received Message from Screen: event,startup,50,eu
2023-05-22 12:16:13.005572 INFO nspanel-1: Sending MQTT Message: X
2023-05-22 12:16:13.010811 INFO nspanel-1: Update Pre-Check failed Tasmota Driver Version: None Panel Version: 50
2023-05-22 12:16:13.011660 INFO nspanel-1: Startup Event
2023-05-22 12:16:13.019887 INFO nspanel-1: Sending MQTT Message: time~12:16~
2023-05-22 12:16:13.028296 INFO nspanel-1: Sending MQTT Message: date~Montag, 22. Mai 2023
2023-05-22 12:16:13.029965 INFO nspanel-1: Sending MQTT Message: dimmode~10~100~6371
2023-05-22 12:16:13.031638 INFO nspanel-1: Sending MQTT Message: pageType~screensaver
2023-05-22 12:16:13.033290 INFO nspanel-1: Sending MQTT Message: timeout~20
2023-05-22 12:16:13.045785 INFO nspanel-1: Sending MQTT Message: weatherUpdate~~~���~31728~OpenWeatherMap~18.8��C~~~���~31728~Mo.~20.5��C~~~���~25375~Mo.~22.2��C~~~���~25375~Mo.~19.8��C~~~���~38060~Mo.~14.8��C
2023-05-22 12:16:13.047670 INFO nspanel-1: Sending MQTT Message: statusUpdate~~~~~~
2023-05-22 12:16:13.513626 INFO nspanel-1: MQTT callback for: {'topic': 'tele/nspanel1/RESULT', 'wildcard': None, 'payload': '{"nlui_driver_version":"8"}'}
2023-05-22 12:16:13.516619 INFO nspanel-1: Update Pre-Check sucessful Tasmota Driver Version: 8 Panel Version: 50
2023-05-22 12:16:13.517683 INFO nspanel-1: Update of Display Firmware needed
2023-05-22 12:16:13.519204 INFO nspanel-1: Sending MQTT Message: pageType~popupNotify
2023-05-22 12:16:13.521561 INFO nspanel-1: Sending MQTT Message: entityUpdateDetail~updateDisplayNoYes~Display Update available!~65535~Dismiss~65535~Yes~65535~There's a firmware update available for the      Nextion screen of the NSPanel. Do you want tostart the update now?                                         If the update fails check the installation         manual and flash again over the Tasmota        console.                                                                 Be patient, the update will take a while.~65535~0
2023-05-22 12:16:55.036316 INFO nspanel-1: MQTT callback for: {'topic': 'tele/nspanel1/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,updateDisplayNoYes,notifyAction,yes"}'}
2023-05-22 12:16:55.039115 INFO nspanel-1: Received Message from Screen: event,buttonPress2,updateDisplayNoYes,notifyAction,yes
2023-05-22 12:16:55.040780 INFO nspanel-1: Sending MQTT Message: http://nspanel.pky.eu/lovelace-ui/github/nspanel-v4.1.1.tft
2023-05-22 12:16:55.043591 INFO nspanel-1: Button Press Event; entity_id: updateDisplayNoYes; button_type: notifyAction; value: yes 
2023-05-22 12:17:00.927052 INFO nspanel-1: Sending MQTT Message: time~12:17~
2023-05-22 12:18:00.931215 INFO nspanel-1: Sending MQTT Message: time~12:18

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```

### TO REPRODUCE
_Steps to reproduce the behavior:_
First install the NSPanel Lovelace UI Backend update v4.1.4
Second Restart AppDaemon Container
Third On the NS-Panel push the Button Yes to install(Flash) the Panel with the new NS-Panel.tft

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

Nothings gone happend expect:
11:16:54.330 FLH: host: nspanel.pky.eu, port: 80, get: /lovelace-ui/github/nspanel-v4.1.1.tft
11:16:55.514 FLH: Send (High Speed) flash start
11:16:55.865 BRY: Exception> 'type_error' - unsupported operand type(s) for <: 'nil' and 'int'

### SCREENSHOTS
NS-Panel Console Screenshot
_If applicable, add screenshots/pictures to help explain your problem._
11:16:12.398 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:16:12.447 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:16:12.500 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:16:12.540 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:16:12.656 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:16:12.796 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:16:12.846 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:16:13.122 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:16:54.148 MQT: tele/nspanel1/RESULT = {"CustomRecv":"event,buttonPress2,updateDisplayNoYes,notifyAction,yes"}
11:16:54.323 MQT: stat/nspanel1/RESULT = {"FlashNextion":"Done"}
11:16:54.330 FLH: host: nspanel.pky.eu, port: 80, get: /lovelace-ui/github/nspanel-v4.1.1.tft
11:16:55.514 FLH: Send (High Speed) flash start
11:16:55.865 BRY: Exception> 'type_error' - unsupported operand type(s) for <: 'nil' and 'int'
11:17:00.229 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:18:00.228 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:19:00.226 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:19:27.032 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:19:27.135 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:19:27.182 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:20:00.231 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}

Another Screenshot from the Startingprozess of the NS-Panel with trying to update the tft.(Flashing)

00:00:00.002 HDW: ESP32-D0WD-V3 
00:00:00.046 UFS: FlashFS mounted with 276 kB free
00:00:00.068 CFG: Loaded from File, Count 682
00:00:00.078 QPC: Count 1
00:00:00.216 BRY: Berry initialized, RAM used=4041 bytes
00:00:00.231 TFS: File '.drvset003' not found
00:00:00.232 CFG: Energy use defaults as file system not ready or file not found
00:00:00.242 Project tasmota - nspanel1 Version 12.5.0(nspanel)-2_0_7(2023-04-17T08:07:02)
00:00:00.489 NXP: Initializing Driver
00:00:00.496 BRY: Successfully loaded 'autoexec.be'
00:00:01.041 WIF: Connecting to AP1 andre 2,4GHZ Channel 1 BSSId 44:4E:6D:3B:C8:ED in mode 11n as nspanel1-6316...
00:00:05.927 WIF: Connected
00:00:06.112 RSL: RESULT = {"CustomRecv":"event,startup,50,eu"}
00:00:06.187 HTP: Web server active on nspanel1-6316 with IP address 192.168.178.104
00:00:06.916 QPC: Reset
00:00:07.178 MQT: Attempting connection...
00:00:07.215 MQT: Connected
00:00:07.220 MQT: tele/nspanel1/LWT = Online (retained)
00:00:07.222 MQT: cmnd/nspanel1/POWER = 
00:00:07.228 MQT: tele/nspanel1/INFO1 = {"Info1":{"Module":"NSPanel","Version":"12.5.0(nspanel)","FallbackTopic":"cmnd/DVES_0CD8AC_fb/","GroupTopic":"cmnd/tasmotas/"}}
00:00:07.244 MQT: tele/nspanel1/INFO2 = {"Info2":{"WebServerMode":"Admin","Hostname":"nspanel1-6316","IPAddress":"192.168.178.104","IP6Global":"2001:9e8:4193:e000:e2e2:e6ff:fe0c:d8ac","IP6Local":"fe80::e2e2:e6ff:fe0c:d8ac"}}
00:00:07.258 MQT: tele/nspanel1/INFO3 = {"Info3":{"RestartReason":"Software reset CPU","BootCount":97}}
00:00:07.276 MQT: stat/nspanel1/RESULT = {"POWER1":"OFF"}
00:00:07.282 MQT: stat/nspanel1/POWER1 = OFF
00:00:07.285 MQT: stat/nspanel1/RESULT = {"POWER2":"OFF"}
00:00:07.286 MQT: stat/nspanel1/POWER2 = OFF
00:00:08.341 MQT: stat/nspanel1/STATUS = {"Status":{"Module":0,"DeviceName":"nspanel1","FriendlyName":["nspanel1",""],"Topic":"nspanel1","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0,"StatusRetain":0}}
00:00:08.398 MQT: stat/nspanel1/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota32/release/tasmota32-nspanel.bin","RestartReason":"Software reset CPU","Uptime":"0T00:00:09","StartupUTC":"","Sleep":0,"CfgHolder":4617,"BootCount":96,"BCResetTime":"2022-01-30T10:18:38","SaveCount":682}}
00:00:08.454 MQT: stat/nspanel1/STATUS11 = {"StatusSTS":{"Time":"1970-01-01T00:00:08","Uptime":"0T00:00:09","UptimeSec":9,"Heap":140,"SleepMode":"Dynamic","Sleep":0,"LoadAvg":178,"MqttCount":1,"Berry":{"HeapUsed":16,"Objects":240},"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"andre 2,4GHZ","BSSId":"44:4E:6D:3B:C8:ED","Channel":1,"Mode":"11n","RSSI":48,"Signal":-76,"LinkCount":1,"Downtime":"0T00:00:07"}}}
00:00:08.511 MQT: stat/nspanel1/STATUS2 = {"StatusFWR":{"Version":"12.5.0(nspanel)","BuildDateTime":"2023-04-17T08:07:02","Core":"2_0_7","SDK":"4.4.4.20230218","CpuFrequency":160,"Hardware":"ESP32-D0WD-V3 rev.3","CR":"419/699"}}
00:00:08.551 MQT: stat/nspanel1/RESULT = {"Time":"1970-01-01T00:00:08","Uptime":"0T00:00:09","UptimeSec":9,"Heap":142,"SleepMode":"Dynamic","Sleep":0,"LoadAvg":188,"MqttCount":1,"Berry":{"HeapUsed":16,"Objects":240},"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"andre 2,4GHZ","BSSId":"44:4E:6D:3B:C8:ED","Channel":1,"Mode":"11n","RSSI":48,"Signal":-76,"LinkCount":1,"Downtime":"0T00:00:07"}}
00:00:08.614 MQT: stat/nspanel1/STATUS10 = {"StatusSNS":{"Time":"1970-01-01T00:00:08","ANALOG":{"Temperature1":29.4},"TempUnit":"C"}}
11:16:11.907 MQT: tele/nspanel1/STATE = {"Time":"2023-05-22T11:16:11","Uptime":"0T00:00:12","UptimeSec":12,"Heap":142,"SleepMode":"Dynamic","Sleep":0,"LoadAvg":277,"MqttCount":1,"Berry":{"HeapUsed":16,"Objects":240},"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"andre 2,4GHZ","BSSId":"44:4E:6D:3B:C8:ED","Channel":1,"Mode":"11n","RSSI":46,"Signal":-77,"LinkCount":1,"Downtime":"0T00:00:07"}}
11:16:11.951 MQT: tele/nspanel1/SENSOR = {"Time":"2023-05-22T11:16:11","ANALOG":{"Temperature1":29.4},"TempUnit":"C"}
11:16:12.138 MQT: tele/nspanel1/RESULT = {"CustomRecv":"event,startup,50,eu"}
11:16:12.282 MQT: tele/nspanel1/RESULT = {"nlui_driver_version":"8"}
11:16:12.338 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:16:12.398 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:16:12.447 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:16:12.500 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:16:12.540 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:16:12.656 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:16:12.796 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:16:12.846 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:16:13.122 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:16:54.148 MQT: tele/nspanel1/RESULT = {"CustomRecv":"event,buttonPress2,updateDisplayNoYes,notifyAction,yes"}
11:16:54.323 MQT: stat/nspanel1/RESULT = {"FlashNextion":"Done"}
11:16:54.330 FLH: host: nspanel.pky.eu, port: 80, get: /lovelace-ui/github/nspanel-v4.1.1.tft
11:16:55.514 FLH: Send (High Speed) flash start
11:16:55.865 BRY: Exception> 'type_error' - unsupported operand type(s) for <: 'nil' and 'int'
11:17:00.229 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:18:00.228 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:19:00.226 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:19:27.032 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:19:27.135 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:19:27.182 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:20:00.231 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:21:00.177 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:21:11.908 MQT: tele/nspanel1/STATE = {"Time":"2023-05-22T11:21:11","Uptime":"0T00:05:12","UptimeSec":312,"Heap":135,"SleepMode":"Dynamic","Sleep":0,"LoadAvg":999,"MqttCount":1,"Berry":{"HeapUsed":16,"Objects":243},"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"andre 2,4GHZ","BSSId":"44:4E:6D:3B:C8:ED","Channel":1,"Mode":"11n","RSSI":54,"Signal":-73,"LinkCount":1,"Downtime":"0T00:00:07"}}
11:21:11.953 MQT: tele/nspanel1/SENSOR = {"Time":"2023-05-22T11:21:11","ANALOG":{"Temperature1":30.0},"TempUnit":"C"}
11:22:00.231 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:23:00.227 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:24:00.177 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:25:00.378 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:25:58.897 APP: Serial logging disabled
11:26:00.182 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:26:11.907 MQT: tele/nspanel1/STATE = {"Time":"2023-05-22T11:26:11","Uptime":"0T00:10:12","UptimeSec":612,"Heap":137,"SleepMode":"Dynamic","Sleep":0,"LoadAvg":999,"MqttCount":1,"Berry":{"HeapUsed":16,"Objects":243},"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"andre 2,4GHZ","BSSId":"44:4E:6D:3B:C8:ED","Channel":1,"Mode":"11n","RSSI":48,"Signal":-76,"LinkCount":1,"Downtime":"0T00:00:07"}}
11:26:11.921 MQT: tele/nspanel1/SENSOR = {"Time":"2023-05-22T11:26:11","ANALOG":{"Temperature1":30.3},"TempUnit":"C"}
11:27:00.232 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:28:00.227 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:29:00.227 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:29:26.977 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:29:27.087 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:29:27.133 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
11:30:00.227 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU ,Tasmota 12.5.0 >>>Project tasmota - nspanel1 Version 12.5.0(nspanel)-2_0_7(2023-04-17T08:07:02)

**Comment by joBr99** [comment]
Is your panel able to reach the Internet/DNS or is there something blocking the connection?

**Comment by Henry221164** [comment]
yes the Panel has a Connect to the Internet and ist reachable--Diese Nachricht wurde von meinem Android Mobiltelefon mit 1&1 Mail gesendet.Am 22.05.23, 16:00 schrieb Johannes ***@***.***>:

   
  Is your panel able to reach the Internet/DNS or is there something blocking the connection?

**Comment by Henry221164** [comment]
Here the tasmota log27:56.521 MQT: stat/nspanel1/RESULT = {"FlashNextion":"Done"}15:27:56.530 FLH: host: nspanel.pky.eu, port: 80, get: /lovelace-ui/github/nspanel-v4.1.1.tft15:27:57.707 FLH: Send (High Speed) flash start15:27:58.063 BRY: Exception> 'type_error' - unsupported operand type(s) for <: 'nil' and 'int'15:27:59.400 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}--Diese Nachricht wurde von meinem Android Mobiltelefon mit 1&1 Mail gesendet.Am 22.05.23, 16:00 schrieb Johannes ***@***.***>:

   
  Is your panel able to reach the Internet/DNS or is there something blocking the connection?

**Comment by joBr99** [comment]
Bitte einmal 
- Tasmota neustarten, 
- `weblog 3` in der Konsole ausführen 
- dann `FlashNextion http://nspanel.pky.eu/lui-release.tft`

und davon bitte den Log posten.

**Comment by Henry221164** [comment]
ne"}
17:49:49.389 CMD: weblog 3
17:49:49.397 MQT: stat/nspanel1/RESULT = {"WebLog":3}
17:49:49.877 CFG: Saved, Count 696, Bytes 4096
17:50:00.246 SRC: MQTT
17:50:00.249 CMD: Grp 0, Cmd 'CUSTOMSEND', Idx 1, Len 11, Pld -99, Data 'time~18:50~'
17:50:00.264 NXP: payload sent = bytes('55BB0B0074696D657E31383A35307E9D40')
17:50:00.271 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
17:50:24.727 CMD: FlashNextion http://nspanel.pky.eu/lui-release.tft
17:50:24.730 SRC: WebConsole from 192.168.178.234
17:50:24.733 CMD: Grp 0, Cmd 'FLASHNEXTION', Idx 1, Len 37, Pld -99, Data 'http://nspanel.pky.eu/lui-release.tft'
17:50:24.744 MQT: stat/nspanel1/RESULT = {"FlashNextion":"Done"}
17:50:24.786 FLH: host: nspanel.pky.eu, port: 80, get: /lui-release.tft
17:50:24.791 WIF: DNS failed for nspanel.pky.eu after 2 ms
17:50:24.794 FLH: Connected:false
17:50:24.898 FLH: Retry 2
17:50:25.101 FLH: Retry 3
17:50:25.403 FLH: Retry 4
17:50:25.805 FLH: Retry 5
17:50:25.807 FLH: Nothing available to read!
17:50:25.812 NXP: Nextion command sent = bytes('4452414B4A485355594447424E434A48474A4B534842444EFFFFFF')
17:50:25.816 NXP: Nextion command sent = bytes('7265636D6F643D30FFFFFF')
17:50:25.820 NXP: Nextion command sent = bytes('7265636D6F643D30FFFFFF')
17:50:25.824 NXP: Nextion command sent = bytes('636F6E6E656374FFFFFF')
17:50:25.834 NXP: Received Raw = bytes('636F6D6F6B20322C33303631342D302C4E5834383332463033355F303131432C...')
17:50:25.888 FLH: Send (High Speed) flash start
17:50:25.893 NXP: Nextion command sent = bytes('77686D692D7772697320302C3932313630302C72657330FFFFFF')
17:50:26.238 NXP: Received Raw = bytes('05')
17:50:26.241 FLH: Read block
17:50:26.245 BRY: Exception> 'type_error' - unsupported operand type(s) for <: 'nil' and 'int'
17:51:00.285 SRC: MQTT
17:51:00.287 CMD: Grp 0, Cmd 'CUSTOMSEND', Idx 1, Len 11, Pld -99, Data 'time~18:51~'
17:51:00.301 NXP: skipped command becuase still flashing
17:51:00.308 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}
17:52:00.285 SRC: MQTT
17:52:00.287 CMD: Grp 0, Cmd 'CUSTOMSEND', Idx 1, Len 11, Pld -99, Data 'time~18:52~'
17:52:00.301 NXP: skipped command becuase still flashing
17:52:00.308 MQT: stat/nspanel1/RESULT = {"CustomSend":"Done"}

**Comment by joBr99** [comment]
`17:50:24.791 WIF: DNS failed for nspanel.pky.eu after 2 ms`

There you go, DNS funktioniert nicht, dein Panel ist nicht in der Lage nspanel.pky.eu zu einer IP aufzulösen.

**Comment by Henry221164** [comment]
Habe dann lokal den Flash ausgeführt,natürlich vorher heruntergeladen
FlashNextion http://192.168.178.111:8123/config/www/HMI/lui-release.tft
Log:
17:57:28.078 HTP: Consoles
17:57:29.673 HTP: Console
17:57:39.485 CMD: FlashNextion http://192.168.178.111:8123/config/www/HMI/lui-release.tft
17:57:39.489 SRC: WebConsole from 192.168.178.234
17:57:39.491 CMD: Grp 0, Cmd 'FLASHNEXTION', Idx 1, Len 58, Pld -99, Data 'http://192.168.178.111:8123/config/www/HMI/lui-release.tft'
17:57:39.504 MQT: stat/nspanel1/RESULT = {"FlashNextion":"Done"}
17:57:39.546 FLH: host: 192.168.178.111, port: 8123, get: /config/www/HMI/lui-release.tft
17:57:39.550 WIF: DNS resolved '192.168.178.111' (192.168.178.111) in 1 ms
17:57:39.566 FLH: Connected:true
17:57:39.672 FLH: Retry 2
17:57:39.835 FLH: HTTP Respose is 200 OK or 206 Partial Content
17:57:39.838 FLH: Flash file size: 9206
17:57:39.842 NXP: Nextion command sent = bytes('4452414B4A485355594447424E434A48474A4B534842444EFFFFFF')
17:57:39.846 NXP: Nextion command sent = bytes('7265636D6F643D30FFFFFF')
17:57:39.850 NXP: Nextion command sent = bytes('7265636D6F643D30FFFFFF')
17:57:39.858 NXP: Nextion command sent = bytes('636F6E6E656374FFFFFF')
17:57:39.867 NXP: Received Raw = bytes('636F6D6F6B20322C33303631342D302C4E5834383332463033355F303131432C...')
17:57:39.922 FLH: Send (High Speed) flash start
17:57:39.927 NXP: Nextion command sent = bytes('77686D692D7772697320393230362C3932313630302C72657330FFFFFF')
17:57:40.272 NXP: Received Raw = bytes('05')
17:57:40.275 FLH: Read block
17:57:40.277 FLH: Buff size 5591
17:57:40.282 FLH: Writing 4096
17:57:40.289 MQT: tele/nspanel1/RESULT = {"Flashing":{"complete": 0, "time_elapsed": 0}}
17:57:40.404 FLH: Total 4096
17:57:59.578 SRC: MQTT
![1684774942855](https://github.com/joBr99/nspanel-lovelace-ui/assets/74856875/83ee0a5c-92a7-4ba6-9aaa-afd65c04cf44)

**Comment by joBr99** [comment]
probier die URL mal in einem Webbrowser, da kommt mit sicherheit irgendeine seite von homeassistant aber keine tft datei

Bei mir sieht die lokale URL so aus: `http://192.168.75.30:8123/local/test.tft`
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/2fe36251-431b-4e6d-a9bd-c931913fe620)

**Comment by joBr99** [comment]
also bei dir dann vermutlich

http://192.168.178.111:8123/local/HMI/lui-release.tft

**Comment by Henry221164** [comment]
Jo,Danke das war es,er flasht jetzt.Mal schauen ob es klappt.
Eine Frage noch wie bekomme ich das Weblog wieder weg?

**Comment by joBr99** [comment]
`weblog 2` in der Konsole, dann ist es wieder normal

**Comment by Henry221164** [comment]
Nochmals Danke für die schnelle Hilfe
