### ISSUE TITLE
[Help] Problem with Problem with the value 9.xx from sensors

### ISSUE THREAD

**Issue by YeeYek** [joBr99/nspanel-lovelace-ui#905]
### PROBLEM DESCRIPTION

Hi
I have implemented to change the colors of the icons depending on the values they take. Overall it works fine except for one issue. When the value is 9.xx color is always red (it doesn't matter if it's temperature, humidity or air quality). 
Anyone have an idea what the error is?

### REQUESTED INFORMATION
 apps.yaml here:

``      entities:

         - entity: weather.dom_2
         #type: 0
           value: '{{states("sensor.dom_temperature") | round(1)}}°C'
         - entity: sensor.dom_caqi
           name: Jak.pow.
           icon: lungs
           color: '{{iif(states("sensor.dom_caqi")<="9", "[22, 176, 11]", iif(states("sensor.dom_caqi")<="25", "[22, 176, 11]", iif(states("sensor.dom_caqi")<="50", "[209, 255, 122]", iif(states("sensor.dom_caqi")<="75", "[201, 149, 4]", iif(states("sensor.dom_caqi")<="100", "[227, 82, 5]", "[163, 3, 9]")))))}}'
         - entity: sensor.dom_humidity
           name: Wilg.Z.
           icon: cloud-percent
           color: '{% set t = states("sensor.dom_temperature") | float %} {% set h = states("sensor.dom_humidity") | float %} {{  "[232, 228, 111]" if t <= 9 and 40 <= h < 80 else "[232, 228, 111]" if t <= 16 and 40 <= h < 70 else "[22, 176, 11]]" if t <= 18 and 60 <= h < 70 else "[232, 228, 111]" if t <= 18 and 40 <= h < 60 else "[232, 228, 111]" if t <= 18 and 70 <= h < 90 else "[22, 176, 11]" if t <= 20 and 45 <= h < 60 else "[232, 228, 111]" if t <= 20 and 20 <= h < 45 else "[232, 228, 111]" if t <= 20 and 60 <= h < 80 else "[22, 176, 11]" if t <= 24 and 40 <= h < 58 else "[232, 228, 111]" if t <= 24 and 20 <= h < 40 else "[232, 228, 111]" if t <= 24 and 55 <= h < 80 else "[232, 228, 111]" if t <= 25 and 20 <= h < 70 else "[9, 55, 219]" }}'
         - entity: sensor.ble_humidity_termometr_kuchnia
           name: Wilg.W.
           icon: water-percent
           color: '{% set t = states("sensor.tasmota_analog_temperature1") | float %} {% set h = states("sensor.ble_humidity_termometr_kuchnia") | float %} {{  "[232, 228, 111]" if t <= 9 and 40 <= h < 80 else "[232, 228, 111]" if t <= 16 and 40 <= h < 70 else "[22, 176, 11]]" if t <= 18 and 60 <= h < 70 else "[232, 228, 111]" if t <= 18 and 40 <= h < 60 else "[232, 228, 111]" if t <= 18 and 70 <= h < 90 else "[22, 176, 11]" if t <= 20 and 45 <= h < 60 else "[232, 228, 111]" if t <= 20 and 20 <= h < 45 else "[232, 228, 111]" if t <= 20 and 60 <= h < 80 else "[22, 176, 11]" if t <= 24 and 40 <= h < 58 else "[232, 228, 111]" if t <= 24 and 20 <= h < 40 else "[232, 228, 111]" if t <= 24 and 55 <= h < 80 else "[232, 228, 111]" if t <= 25 and 20 <= h < 70 else "[9, 55, 219" }}'
         - entity: delete
         - entity: sensor.tasmota_analog_temperature1
           name: T.wewn.
           icon: home-thermometer-outline
           value: '{{states("sensor.tasmota_analog_temperature1") | round(1)}}°C'
           color: '{{iif(states("sensor.tasmota_analog_temperature1")<="08", "[4, 16, 191]", iif(states("sensor.tasmota_analog_temperature1")<"18", "[16, 181, 222]", iif(states("sensor.tasmota_analog_temperature1")<"20", "[184, 219, 9]", iif(states("sensor.tasmota_analog_temperature1")<"24", "[22, 176, 11]", iif(states("sensor.tasmota_analog_temperature1")<"27", "[235, 118, 91]",  "[247, 5, 5]")))))}}'
      
![20230522_114700](https://github.com/joBr99/nspanel-lovelace-ui/assets/77362116/af60abff-9790-4f0d-85ca-4b02722c064e)

### ADDITIONAL INFORMATION

AppDaemon 0.13.0
Lovelace UI 4.1.4

**Comment by joBr99** [comment]
thoose comparisations doesn't look right

`states("sensor.dom_caqi")<="9"`

<= with a string like "9" cannot work, do `states("sensor.dom_caqi")<=9` instead

in case there is an error you need to convert the value from your sensor to a number, so probably something like this:

``(states("sensor.dom_caqi") | float)<=9` `

**Comment by YeeYek** [comment]
I changed the values to:
`           color: '{{iif(states("sensor.dom_caqi" | float)<=9, "[22, 176, 11]", iif(states("sensor.dom_caqi"" | float)<=25, "[22, 176, 11]", iif(states("sensor.dom_caqi"" | float)<=50, "[209, 255, 122]", iif(states("sensor.dom_caqi"" | float)<=75, "[201, 149, 4]", iif(states("sensor.dom_caqi"" | float)<=100, "[227, 82, 5]", "[163, 3, 9]")))))}}'`

Now a whole line on the screen is missing (same as it was without "| float").
I do not understand why with the old notation, i.e. "9" - only for this number there is a problem. For others, everything works great.

**Comment by joBr99** [comment]
```
color: '{{iif(states("sensor.dom_caqi")|float<=9, "[22, 176, 11]", iif(states("sensor.dom_caqi")|float<=25, "[22, 176, 11]", iif(states("sensor.dom_caqi")|float<=50, "[209, 255, 122]", iif(states("sensor.dom_caqi")|float<=75, "[201, 149, 4]", iif(states("sensor.dom_caqi")|float<=100, "[227, 82, 5]", "[163, 3, 9]")))))}}'
```

Stuff in "" are strings, you can use <= on strings, however you are not comparing numbers, not sure what it is doing in jinja2, but it isn't what you want anyways.

states("sensor.dom_caqi")|float converts your string on the left hand side to a float, which you can comare to a number.
