### ISSUE TITLE
Wechsel von PagePower auf PageChart [BUG] 

### ISSUE THREAD

**Issue by tt-tom17** [joBr99/nspanel-lovelace-ui#907]
### PROBLEM DESCRIPTION
beim Wechsel von PagePower auf PageChart kommt es zur fehlerhaften Darstellung der PageChart. Aufgefallen beim Type: ChartLPage. Beim Wechsel von PageChart zu PagePower, alles okay.

### SCREENSHOTS

![IMG_5879](https://github.com/joBr99/nspanel-lovelace-ui/assets/101348966/9ceb3530-4eb0-463f-b839-a2a5f3ed8c4a)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
FlashNextion http://nspanel.pky.eu/lui.tft

Fixed in Development Version

**Comment by tt-tom17** [comment]
Funktioniert jetzt, danke
