### ISSUE TITLE
TFT file can't be downloaded

### ISSUE THREAD

**Issue by marek-vrana** [joBr99/nspanel-lovelace-ui#908]
### PROBLEM DESCRIPTION
I wanted to download the latest tft, but it always gives me Not found. I tried 4.1.0 (as per [manual update instructions](https://github.com/joBr99/nspanel-lovelace-ui/releases/tag/v4.1.4)), also tried to get 4.1.4 to match the release backend version - also not found. 

- https://nspanel.pky.eu/lovelace-ui/github/nspanel-v4.1.0.tft
- https://nspanel.pky.eu/lovelace-ui/github/nspanel-v4.1.4.tft

The only 4.1.x version I found by guessing is 4.1.1.

Did I get the idea right that tft version _must_ match the release version? Or it's just a mistake in release instructions as v4.1.4 references tft 4.1.0?

### SCREENSHOTS
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/30291176/db9975e0-fd73-4fda-91e4-bb785b588a76)

### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
Latest TFT url is 4.1.1, will fix the urls later
