### ISSUE TITLE
[Bug] Auto Update don't work

### ISSUE THREAD

**Issue by antibill51** [joBr99/nspanel-lovelace-ui#91]
Hi, 

I have to update manually Display Driver and Berry Driver after each HACS update.

In debug mode, I see:

```
2022-03-29 09:18:37.290850 DEBUG nspanel-1: call_service: mqtt/publish, {'topic': 'cmnd/NsPanel_7DEE08/GetDriverVersion', 'payload': 'x'}
(...)
2022-03-29 09:18:43.720988 DEBUG nspanel-1: MQTT callback for: {'topic': 'tele/NsPanel_7DEE08/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,startup,20"}'}
2022-03-29 09:18:43.744499 INFO nspanel-1: Received Message from Screen: event,startup,20
2022-03-29 09:18:43.773656 INFO nspanel-1: Update Pre-Check failed Tasmota Driver Version: None Panel Version: 20
```

What can I do to resolve it?

**Comment by joBr99** [comment]
Hey, 
the berry driver usally doesn't change, so you don't have to update it every time

do you have a longer part of the log?

the Pre-Check message should appear a second time after there is the answer form the berry driver

also check if "GetDriverVersion x" is working on the tasmota console

**Comment by antibill51** [comment]
GetDriverVersion X is working : 
```
12:28:42.436 CMD: GetDriverVersion x
12:28:42.450 MQT: tele/NsPanel_7DEE08/RESULT = {"nlui_driver_version":"3"}
```
I'm on "main", I force "FlashNextion http://nspanel.pky.eu/lovelace-ui/github/nspanel-v1.7.0.tft" and restart nspanel : 
nothing happend until a run GetDriverVersion X  in console. Then, and only then, update screen apears

**Comment by joBr99** [comment]
can you check if this is working in an mqtt client?

{'topic': 'cmnd/NsPanel_7DEE08/GetDriverVersion', 'payload': 'x'}

and also capture the mqtt traffic during appdaemon restart, you should see the GetDriverVersion aswell as the nlui_driver_version answer

the nlui_driver_version does trigger the update message

**Comment by antibill51** [comment]
Identical behavior via mqtt, the update is only offered after sending {'topic': 'cmnd/NsPanel_7DEE08/GetDriverVersion', 'payload': 'x'}

How can I capture the mqtt traffic?

**Comment by joBr99** [comment]
interesting, so would like to know if this message acually arrives on mqtt, but I don't see a reason why it shouldn't

`2022-03-29 09:18:37.290850 DEBUG nspanel-1: call_service: mqtt/publish, {'topic': 'cmnd/NsPanel_7DEE08/GetDriverVersion', 'payload': 'x'}`

just subscribe to the topic with an mqttclient, I don't need a acual capture file or something like that

**Comment by joBr99** [comment]
do you see the {"nlui_driver_version": "3"} on tasmota console after you are restarting appdaemon?

customsend messages are not releated to the driver version stuff

**Comment by antibill51** [comment]
Yes, I see it : 
`15:23:30.839 MQT: tele/NsPanel_7DEE08/RESULT = {"CustomRecv":"event,startup,16"}
15:23:36.740 MQT: tele/NsPanel_7DEE08/RESULT = {"CustomRecv":"event,startup,16"}
15:23:42.740 MQT: tele/NsPanel_7DEE08/RESULT = {"CustomRecv":"event,startup,16"}
15:23:43.889 MQT: tele/NsPanel_7DEE08/RESULT = {"nlui_driver_version":"3"}
15:23:43.960 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:23:44.043 MQT: tele/NsPanel_7DEE08/RESULT = {"CustomRecv":"event,startup,16"}
15:23:44.495 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:23:49.939 MQT: tele/NsPanel_7DEE08/RESULT = {"CustomRecv":"event,startup,16"}
15:23:50.348 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:23:50.405 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:23:50.450 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:23:50.499 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:23:50.552 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:23:50.679 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:23:55.839 MQT: tele/NsPanel_7DEE08/RESULT = {"CustomRecv":"event,startup,16"}
15:23:56.253 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:23:56.303 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:23:56.348 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:23:56.396 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:23:56.459 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:23:56.548 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:24:00.998 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:24:02.042 MQT: tele/NsPanel_7DEE08/RESULT = {"CustomRecv":"event,startup,16"}
15:24:02.198 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:24:02.262 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:24:02.302 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:24:02.347 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:24:02.403 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:24:02.497 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:24:07.939 MQT: tele/NsPanel_7DEE08/RESULT = {"CustomRecv":"event,startup,16"}
15:24:08.553 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:24:08.606 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:24:08.644 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:24:08.703 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:24:08.748 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:24:08.846 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:24:13.840 MQT: tele/NsPanel_7DEE08/RESULT = {"CustomRecv":"event,startup,16"}
15:24:14.197 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:24:14.263 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:24:14.303 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:24:14.343 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:24:14.401 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}
15:24:14.496 MQT: stat/NsPanel_7DEE08/RESULT = {"CustomSend":"Done"}`

**Comment by antibill51** [comment]
Perfect, it works.
Thank you ;)

**Comment by joBr99** [comment]
Okay, no clue why doesn't work for you in the normal way, but I guess this is a good fallback.
