### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by lmbalcao** [joBr99/nspanel-lovelace-ui#911]
### FEATURE DESCRIPTION
Change icon on state

### ADDITIONAL CONTEXT
apply to icon: the same options avaliable to color:

example:

color: '{{iif(states("weather.home")<"15", "[0,0,255]", iif(states("weather.home")<"25", "[255,165,0]", "[255,0,0]"))}}'

icon: '{{iif(states("weather.home")<"15", "mdi:sofa", iif(states("weather.home")<"25", "mdi:chair", "mdi:dog"))}}'

### PANEL / FIRMWARE VERION
Tasmota Driver Version: 8 Panel Version: 51 
EU

**Comment by joBr99** [comment]
There is an icon type `ha:` which is rendered as ha template.

https://docs.nspanel.pky.eu/entities/#override-icons-or-names

```
        icon: 'ha:{{ iif(is_state('light.kitchen', 'on'), '<I>mdi:flashlight</I>', '<I>mdi:flashlight-off</I>') }}'
```
