### ISSUE TITLE
[BUG] Entity select - cannot execute from NSPanel

### ISSUE THREAD

**Issue by byniow** [joBr99/nspanel-lovelace-ui#917]
### PROBLEM DESCRIPTION
I have a select option from EspHome. This integrates with HA without problem. EspHome gui and HA can select option and make correct action. When i add this to NsPanel i see coresponding entry, but select not work. On blue color i see actually selected on HA option but cannot select other option from NSPanel. When i change this option on HA then on NSPanel still is old value, to see new value i need exit and enter to select screen.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

Select on ESPHome

```
select:
  - platform: template
    name: Prędkość wentylatorów
    id: fan_speed
    icon: mdi:fan
    options:
      - "Wyłączony"
      - "Niska"
      - "Średnia"
      - "Wysoka"
    initial_option: "Niska"
    optimistic: true
    set_action:
      - logger.log:
          format: "%s"
          args: ["x.c_str()"]
      - lambda: |-
          id(fan_speed).state = x.c_str(); 
    on_value:
      then:
        - lambda: |-
            if ( x == "Wyłączony")
              id( obroty_wentylatorow).set_level(0);
            else if ( x == "Niska")
              id( obroty_wentylatorow).set_level(0.52);
            else if ( x == "Średnia")
              id( obroty_wentylatorow).set_level(0.60);
            else if ( x == "Wysoka")
              id( obroty_wentylatorow).set_level(0.70);
```
             
On apps.yaml
```
    cards:
    
        title: Przełączniki
        entities:
          - entity: select.rekuperator_predkosc_wentylatorow
            name: Rekuperacja prędkość
```

- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:

 2023-06-02 13:02:54.595462 INFO nspanel_salon: MQTT callback for: {'topic': 'tele/nspanel_salon/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,select.rekuperator_predkosc_wentylatorow,mode-select,2"}'}
2023-06-02 13:02:54.600291 INFO nspanel_salon: Received Message from Screen: event,buttonPress2,select.rekuperator_predkosc_wentylatorow,mode-select,2
2023-06-02 13:02:54.605486 INFO nspanel_salon: Button Press Event; entity_id: select.rekuperator_predkosc_wentylatorow; button_type: mode-select; value: 2 

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
Hey,
please update to latest development version; should be fixed.

https://docs.nspanel.pky.eu/faq/#how-to-upgrade-from-a-release-to-the-current-development-version
