### ISSUE TITLE
[Feature Request] statusicon displays temp set by AirCon

### ISSUE THREAD

**Issue by hatran0884** [joBr99/nspanel-lovelace-ui#921]
### FEATURE DESCRIPTION
is it possible for the statusIcon to display the temperature set by the AirCon and only shows up once the AirCon is set ON ? 

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
US Lanscape Inverted

**Comment by joBr99** [comment]
I hope this helps:
```
      statusIcon2:
        entity: climate.kuche_boden
        icon: 'ha:{{iif(state_attr("climate.kuche_boden", "hvac_action")=="heating", "<I>mdi:heat-wave</I> ", "", "")}}'
```

**Comment by hatran0884** [comment]
Thanks, it works well
