### ISSUE TITLE
[BUG] 'value:' Template ° stripped

### ISSUE THREAD

**Issue by Firefly1337** [joBr99/nspanel-lovelace-ui#925]
### PROBLEM DESCRIPTION

Follow-up for #863 and #867 

The suggested solutions work fine for the 'icon:' field but not for 'value:'

### REQUESTED INFORMATION

- [X] Provide your apps.yaml (or your config):
```
          value: >
            {% set start = now().replace(hour=00,minute=00,second=00).isoformat() %}
            {% set end = now().replace(hour=23,minute=59,second=59).isoformat() %}
            {{ state_attr('weather.openweathermap', 'forecast')  | selectattr('datetime', '>=', start) | selectattr('datetime','<=', end) | map(attribute='temperature') | list | max }}
```

I'm using template functions to read out the maximum temperature of the weather forecast for the entire day (i.e. max temp between 00:00 and 23:59). It works fine but I'd like to add the unit of measurement as well (in my case '°C').
The degree character ('°') is not rendered properly and applying to suggested solutions from the above mentioned issues does not work.

### TO REPRODUCE

The following config will just print the String as is, i.e. the 'ha:' is printed as well as `<I>mdi...`.
```
          value: >
            {% set start = now().replace(hour=00,minute=00,second=00).isoformat() %}
            {% set end = now().replace(hour=23,minute=59,second=59).isoformat() %}
            ha:{{ state_attr('weather.openweathermap', 'forecast')  | selectattr('datetime', '>=', start) | selectattr('datetime','<=', end) | map(attribute='temperature') | list | max }}<I>mdi:temperature-celsius</I>
```

This one prints the number followed by a distorted character ('î') as shown in #867:
```
          value: >
            {% set start = now().replace(hour=00,minute=00,second=00).isoformat() %}
            {% set end = now().replace(hour=23,minute=59,second=59).isoformat() %}
            {{ state_attr('weather.openweathermap', 'forecast')  | selectattr('datetime', '>=', start) | selectattr('datetime','<=', end) | map(attribute='temperature') | list | max }}
```

### EXPECTED BEHAVIOUR

The templating functionality in 'value:' should be the same as in 'icon:'.

### PANEL / FIRMWARE VERION

EU v4.1.4

**Comment by joBr99** [comment]
no, the text fields on nspanel that are showing the value aren't capable to display cons, so it doesn't make sense to resolve `ha:` or `<I></I>`

What happens if you append `°C` to your template?

```
          value: >
            {% set start = now().replace(hour=00,minute=00,second=00).isoformat() %}
            {% set end = now().replace(hour=23,minute=59,second=59).isoformat() %}
            {{ state_attr('weather.openweathermap', 'forecast')  | selectattr('datetime', '>=', start) | selectattr('datetime','<=', end) | map(attribute='temperature') | list | max }}°C
```

**Comment by joBr99** [comment]
This worked fine on earlier versions, however if I take a look at my panel it does no longer show the `°`.

This works fine on my Panel:

```
        - entity: sensor.temp_kueche_temperature
          value: '{{states("sensor.temp_kueche_temperature") | round(1)}}°C'
          icon: mdi:home-thermometer-outline
```

**Comment by joBr99** [comment]
Please update to latest development version.
https://docs.nspanel.pky.eu/faq/#how-to-upgrade-from-a-release-to-the-current-development-version

everything after the last `}` are no longer rendered as part of the template, so the `°` char will no longer get screwed up
