### ISSUE TITLE
[BUG] Days displayed in screensaver weather mode are shifted by minus 1

### ISSUE THREAD

**Issue by albxox** [joBr99/nspanel-lovelace-ui#927]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

Days displayed in screensaver weather mode are shifted by minus 1. Meaning today is Thursday but weather days are displayed starting from Wednesday.
  

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:

    screensaver:
     statusIcon1:
      entity: switch.nspanelsw1
      altFont: True
     statusIcon2:
      entity: switch.nspanelsw2
      altFont: True
     entities:
     - entity: sensor.0x00158d000678e737_temperature
       icon: mdi:home-thermometer-outline
     - entity: weather.ims_weather
       type: 0
       theme:
        autoWeather: true
        clear-night:              [150, 150, 100]
        cloudy:                   [75, 75, 75]
        exceptional:              [255, 50, 50]
        fog:                      [150, 150, 150]
        hail:                     [200, 200, 200]
        lightning:                [200, 200, 0]
        lightning-rainy:          [200, 200, 150]
        partlycloudy:             [150, 150, 150]
        pouring:                  [50, 50, 255]
        rainy:                    [100, 100, 255]
        snowy:                    [150, 150, 150]
        snowy-rainy:              [150, 150, 255]
        sunny:                    [255, 255, 0]
        windy:                    [150, 150, 150]
        windy-variant:            [255, 125, 125]
     - entity: weather.ims_weather
       type: 1
       theme:
        autoWeather: true
        clear-night:              [150, 150, 100]
        cloudy:                   [75, 75, 75]
        exceptional:              [255, 50, 50]
        fog:                      [150, 150, 150]
        hail:                     [200, 200, 200]
        lightning:                [200, 200, 0]
        lightning-rainy:          [200, 200, 150]
        partlycloudy:             [150, 150, 150]
        pouring:                  [50, 50, 255]
        rainy:                    [100, 100, 255]
        snowy:                    [150, 150, 150]
        snowy-rainy:              [150, 150, 255]
        sunny:                    [255, 255, 0]
        windy:                    [150, 150, 150]
        windy-variant:            [255, 125, 125]
     - entity: weather.ims_weather
       type: 2
       theme:
        autoWeather: true
        clear-night:              [150, 150, 100]
        cloudy:                   [75, 75, 75]
        exceptional:              [255, 50, 50]
        fog:                      [150, 150, 150]
        hail:                     [200, 200, 200]
        lightning:                [200, 200, 0]
        lightning-rainy:          [200, 200, 150]
        partlycloudy:             [150, 150, 150]
        pouring:                  [50, 50, 255]
        rainy:                    [100, 100, 255]
        snowy:                    [150, 150, 150]
        snowy-rainy:              [150, 150, 255]
        sunny:                    [255, 255, 0]
        windy:                    [150, 150, 150]
        windy-variant:            [255, 125, 125]
     - entity: weather.ims_weather
       type: 3
       theme:
        autoWeather: true
        clear-night:              [150, 150, 100]
        cloudy:                   [75, 75, 75]
        exceptional:              [255, 50, 50]
        fog:                      [150, 150, 150]
        hail:                     [200, 200, 200]
        lightning:                [200, 200, 0]
        lightning-rainy:          [200, 200, 150]
        partlycloudy:             [150, 150, 150]
        pouring:                  [50, 50, 255]
        rainy:                    [100, 100, 255]
        snowy:                    [150, 150, 150]
        snowy-rainy:              [150, 150, 255]
        sunny:                    [255, 255, 0]
        windy:                    [150, 150, 150]
        windy-variant:            [255, 125, 125]
    alternativeLayout: True  
 
```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/80d4d270-60f2-483e-a4f4-4beba2dea7e1)


It's showing what you have configured, the number specified on type is the day shown from the forecast.

Your theme shouldn't be effective configured like this and is ignored.

**Comment by albxox** [comment]
I guess I wasn't clear enough in my explanation, attaching screenshots. days or temperature values are shifted on NSpanel.

![WhatsApp Image 2023-06-16 at 00 17 47 (1)](https://github.com/joBr99/nspanel-lovelace-ui/assets/34959123/6b7bedb2-c6fc-4d6e-b984-9ca0abaf8ca2)
![WhatsApp Image 2023-06-16 at 00 17 47](https://github.com/joBr99/nspanel-lovelace-ui/assets/34959123/44cc3b27-fd7c-4cd9-ac09-f0760444b872)

**Comment by joBr99** [comment]
please send a screenshot from the states of your weather entity from dev tools

**Comment by albxox** [comment]
temperature: 21.9
temperature_unit: °C
humidity: 84
pressure_unit: hPa
wind_bearing: 113
wind_speed: 20
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
forecast:
  - datetime: '2023-06-14T21:00:00+00:00'
    condition: partlycloudy
    temperature: 25
    templow: 20
  - datetime: '2023-06-15T21:00:00+00:00'
    condition: sunny
    temperature: 24
    templow: 20
  - datetime: '2023-06-16T21:00:00+00:00'
    condition: sunny
    temperature: 32
    templow: 22
  - datetime: '2023-06-17T21:00:00+00:00'
    condition: partlycloudy
    temperature: 24
    templow: 21
  - datetime: '2023-06-18T21:00:00+00:00'
    condition: sunny
    temperature: 23
    templow: 20
  - datetime: '2023-06-19T21:00:00+00:00'
    condition: partlycloudy
    temperature: 23
    templow: 20
  - datetime: '2023-06-20T21:00:00+00:00'
    condition: sunny
    temperature: 24
    templow: 21
attribution: Nothing
friendly_name: IMS Weather

**Comment by albxox** [comment]
I see what you mean but actually, it supposed to be 32 on17 JUNE. I just saw the forecast :-)
and in HA it is displayed correctly as you can see at screenshot above.

I see that IMS is actually shifted vs. OpenWeather, strange.

**Comment by joBr99** [comment]
are you on the latest version of the integration? there is an issue talking about forecast for the previous day

https://github.com/t0mer/ims-custom-component/issues/18

**Comment by albxox** [comment]
looks like it is related to IMS weather implementation. thanks for the support!!!!!! :-)
