### ISSUE TITLE
[BUG] Habe seit Java script 7.1.0 folgenden Fehler: ERROR: Operator '>' cannot be applied to types 'number | boolean' and 'number'.

### ISSUE THREAD

**Issue by SurfGargano** [joBr99/nspanel-lovelace-ui#929]
### PROBLEM DESCRIPTION
Habe seit Java script 7.1.0 folgenden Fehler:

14.6.2023, 09:16:30.937	[error]: javascript.0 (12132) script.js.NSPanels.NsPanelTS40514_: TypeScript compilation failed:
        if ((pageItem.useColor || useColors) && ((typeof (value) === 'boolean' && value) || value > (pageItem.minValueBrightness !== undefined ? pageItem.minValueBrightness : 0))) {
                                                                                            ^
ERROR: Operator '>' cannot be applied to types 'number | boolean' and 'number'.

JS wird mehr und mehr restriktiv. Die automatische Typkonvertierung in boolschen Ausdrücken scheint nicht mehr zu gehen.

**Lösung :**
Das funktioniert bei mir :

 if ((pageItem.useColor || useColors) && (typeof (value) === 'boolean' && value) || ((typeof (value) === 'number')  && (value > (pageItem.minValueBrightness !== undefined ? pageItem.minValueBrightness : 0)))) {

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
NSPanel.ts latest.

**Comment by Armilar** [comment]
Code Vorschlag übernommen.
