### ISSUE TITLE
[Feature Request] cardEntities - override action name for navigation entities and scripts

### ISSUE THREAD

**Issue by marek-vrana** [joBr99/nspanel-lovelace-ui#937]
### FEATURE DESCRIPTION
In order to fully localize nspanel, I'd like to have an option to override action name for navigation entities in cardEntities type. I saw it somewhere that it was removed for scripts - that would be really handy as well to replace "press" with other language variant / abbreviation.

### ADDITIONAL CONTEXT
N/A

### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
Which language are you using? Maybe press is missing a translation in the language files.

**Comment by marek-vrana** [comment]
You're totally right! Card -> Button press is missing in [sk.json](https://github.com/joBr99/nspanel-lovelace-ui/blob/main/apps/nspanel-lovelace-ui/luibackend/translations/frontend/sk.json). 
However cs and sk are quite similar, but tbh I do not like such long translations (I peeked into cs.json), so will definitely welcome an option to override / shorten it a bit if possible.

**Comment by joBr99** [comment]
Sure, PR are welcome, but you can post suggestions here as well.

**Comment by marek-vrana** [comment]
With tasmota/esphome panel is fully customizable - each screen, each button, etc. Why to consider localization as written in stone and not letting users to create their own translations? Will be nice. It's just an idea with probably too much effort. So for now, I'll just try to create a PR.

**Comment by joBr99** [comment]
You should be able to override the label of the button by overwriting the value.

try to add `value: test` to your entity
