### ISSUE TITLE
Compatibility with 'old style' weatherforecast

### ISSUE THREAD

**Issue by jeanpaul1977** [joBr99/nspanel-lovelace-ui#94]
The latest version of the panel firmware uses the new weather-icon styles, so 1 big and 4 small icons.
Is it still possible to show the icons 'the old way', or is that unsupported with the latest firmware? 

I'm using V1.7.0 and show more information than just the weather forecast in the screensaver, so for example:
weatherUpdate,?2?19.7 °C?26?46%?Vent.?30?Med.?Energy?4?355W
weatherUpdate,?2?19.7 °C?26?46%?Heating.?28?Low?CO2?24?662

I'm a bit hesitant to update to the latest firmware and take the risk of losing this information.

**Comment by joBr99** [comment]
you can still overwrite the information on the screensaver

with `weatherOverrideForecast1` to `weatherOverrideForecast4`

**Comment by jeanpaul1977** [comment]
Great! Thanks for the prompt reply. 
And please keep that compatibility option in place ;-)

**Comment by joBr99** [comment]
it was never a "compatibility" option, it a feature :) 
however multiple layout of the screensaver page are currently not possible

see #75 for more info around this layout change, it was changed to have some more space for custom sensors on the screensaver

**Comment by joBr99** [comment]
yes, this is true the humidity is lost, currently you are forced to the 4-icon layout

I already migrated the "wake" part of the screensaver to server side (screensaver sends buttonpress bexit on tap and you have to answer with pagetype etc)

 and I'm also planning to move the navigation to the screensaver to server side, that's the point where multiple screensaver layouts will be possible

**Comment by joBr99** [comment]
[nspanel.zip](https://github.com/joBr99/nspanel-lovelace-ui/files/8373682/nspanel.zip)

use this build in the meanwhile, it has all current changes, but the old screensaver layout

**Comment by joBr99** [comment]
hit me up on discord if you've queations to the changes of the serial protcol, it got a bit more compact, to be a bit faster, but also a bit more complex :D

**Comment by joBr99** [comment]
@jeanpaul1977 

current development version has now a alternative layout on the current screensaver page

![image](https://user-images.githubusercontent.com/29555657/161144607-398ca9cd-f4e6-4a7c-82c0-dc1eb5580280.png)

first layout: `weatherUpdate,?20?5.8C?Fri?20?5.1 C?Innen?2?20.99 C?Sun?18?5.2 C?Mon?12?8.1 C?`

second layout: `weatherUpdate,?20?5.8C?Fri?20?5.1 C?Innen?2?20.99 C?Sun?18?5.2 C?Mon?12?8.1 C?15?test`

**Comment by jeanpaul1977** [comment]
This is simply perfect!
