### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by cknief** [joBr99/nspanel-lovelace-ui#940]
hallo
ich habe alles im iobroker eingerichtet und bei starten der nspanel.ts datei bekomme ich immer diesen fehler

javascript.0 (1533037) script.js.EG.Wohnbereich.nspanel: TypeScript compilation failed: if ((pageItem.useColor || useColors) && ((typeof (value) === 'boolean' && value) || value > (pageItem.minValueBrightness !== undefined ? pageItem.minValueBrightness : 0))) { ^ ERROR: Operator '>' cannot be applied to types 'number | boolean' and 'number'.

**Comment by joBr99** [comment]
Hey, könnte etwas mit der Version von dem JavaScript Adapter zu tun haben, aber am Besten fragst du im ioBroker Forum, das lesen etwas mehr leute.

https://forum.iobroker.net/topic/58170/sonoff-nspanel-mit-lovelace-ui/3279

**Comment by Armilar** [comment]
Solange der JS-Adapter <= 7.0.3 (beta) ist, sollte kein Fehler auftauchen. 

6.1.4 wäre aber immer noch stable
