### ISSUE TITLE
[Feature Request] New desing for cardThermo

### ISSUE THREAD

**Issue by soyxan** [joBr99/nspanel-lovelace-ui#941]
### FEATURE DESCRIPTION
I propose to redesign the cardThermo card to make it more similar to the one on HA Lovelace UI:
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/8955206/70766549-7a96-4b6a-b413-520626b2652c)

**Comment by joBr99** [comment]
I tried to implement this design in the beginning of the project, however it's not possible to draw this round solder with dynamic colors on nextion.

**Comment by joBr99** [comment]
It's a set of pictures, which doesn't allow you to change the color of the slider.

**Comment by soyxan** [comment]
My original request was to mimic the card in HA, that is just the round bar representation of the temperature, displaying the current and setpoint temperatures inisde, no need to change the colors.

**Comment by joBr99** [comment]
If you are changing the mode the slider from HA is changing it's color. 
Besides this issue there are many more related to touch, which is also the reason why there are still buttons for up and down in blackymas project.
Nextion just isn't made for creating custom UI elements.

**Comment by soyxan** [comment]
Please check the following video related to the project I linked before, the temperature slider seems to work as expected:
https://youtu.be/3afPFg6kUdc?t=639

**Comment by joBr99** [comment]
I know blackymas and his project, actually this climate page was removed with the latest release and replaced with a simple slider.

https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v3.4

Probably for the exact same reasons this project doesn't have one. There are just to much limitations on nextion to implement a proper round slider.
