### ISSUE TITLE
Show entity on screensaver screen when other entity is in specific state

### ISSUE THREAD

**Issue by JBakers** [joBr99/nspanel-lovelace-ui#948]
### FEATURE DESCRIPTION
(Let me start off with saying: Im not sure if this is a feature request, or just my lack of searching ability, but I tried to best of my ability to find this, but no luck as of yet....)

Feature:
Show entity on screensaver screen when other entity is in specific state.
I would like to show an entity state (sensor.washing_machine_time_left) when the washing machine entity (sensor.washing_machine) itself is in any other state than "off".

### PANEL / FIRMWARE VERION
EU, NSpanel, Tasmota 12.5.0

**Comment by joBr99** [comment]
https://docs.nspanel.pky.eu/entities/#hide-item-based-on-ha-template

You can hide/show entities based on a home assistant template:

```
      - entity: binary_sensor.sensor_kueche_contact
        state_template: '{{ state_attr("sun.sun","azimuth") < 200 }}'
```

**Comment by JBakers** [comment]
Thank you. And my apologies.
