### ISSUE TITLE
[Feature Request] Trigger script from entities page

### ISSUE THREAD

**Issue by hatran0884** [joBr99/nspanel-lovelace-ui#95]
is it possible to add script on an entity page ? i really want to run some scripts of playing a certain playlist using a play_media service but unfortunately the scenes cannot call service, but only change state.

**Comment by joBr99** [comment]
scripts? do you have an example?

**Comment by hatran0884** [comment]
A script will run a number of services like play media playlist from spotify which cannot be done by a scene: example:

# Play media preset
- service: media_player.play_media
  target:
    entity_id: media_player.soundtouch_living_room
  data:
    media_content_id: 1..6
    media_content_type: PLAYLIST

**Comment by joBr99** [comment]
with this change it should be possible to use script, it's calling "turn_on" on the HA API, no clue if this is correct

should work without reflashing of the firmware, (but without the script icon)

https://github.com/joBr99/nspanel-lovelace-ui/commit/8e82c81e8fc2db14aadac20e658db3a1468f794b

**Comment by Dattel** [comment]
seems to work :-D... 
Great idea!!

**Comment by hatran0884** [comment]
i confirm the scripts work like a charm, now i can play my playlist using a certain speaker by just a click. you are rock! thanks a lot
i can do a lots of things with scripts like play a favorites TV channel, ...

**Comment by hatran0884** [comment]
i confirm the scripts work like a charm, now i can play my playlist using a certain speaker by just a click. you are rock! thanks a lot
i can do a lots of things with scripts like play a favorites TV channel, play certain playlist from Spotify,...
![JPEG image 3](https://user-images.githubusercontent.com/58875735/160829987-5ac930b7-0108-41c2-877f-904e7277fc6a.jpeg)

**Comment by joBr99** [comment]
update to v2.1.0 and you will also have an icon there

don't forget to add `model: us-p` to your config

**Comment by hatran0884** [comment]
can i override the script icon by another icon in the library like other page items ?

**Comment by joBr99** [comment]
yes
