### ISSUE TITLE
[BUG] Schedules laufen weiter , auch wenn man das Script stoppt, unkontrolliertes Verhalten.

### ISSUE THREAD

**Issue by SurfGargano** [joBr99/nspanel-lovelace-ui#950]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

Schedules laufen weiter , auch wenn man das Script stoppt. Das führt zu unkontrollierten Verhalten.
z. B. Das die Wetter Infos weiterlaufen, obwohl man diese disabled hat. Restart vom Script nützt da nichts, nur Restart von der JS-Instanz.

Abhilfe schaft die Function onStop im Script.
Dazu muß man jedem schedule oder Interval eine Variable zuweisen und in der onStop clearen.

z.B.:
    var mySchedule = schedule({ ....

onStop (function(){ 
    /* do something when script is stopped */ 
    if (mySchedule!=null) clearSchedule(mySchedule);
}

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by Armilar** [comment]
v4.1.4.2
