### ISSUE TITLE
[Help] Get Nextion screen dim level from Berry script

### ISSUE THREAD

**Issue by soyxan** [joBr99/nspanel-lovelace-ui#952]
Please, can you suggest how to get the current screen dim level (brightness) from a Berry script in Tasmota?. I assume I should send a command to the Nextion driver, but for me is not clear how to do that.

I am planning to use it to tweak the internal temperature sensor in the NsPanel according to the dim level (counteracting the screen heat dissipation), as per the following post:
https://github.com/joBr99/nspanel-lovelace-ui/issues/144#issuecomment-1676401089

Thanks!

**Comment by soyxan** [comment]
Based on the suggestion from @joBr99 on Discord, I have added the following code in `tmSerial `timer object in all screens on Nextion HMI:

```
            if(tInstruction.txt=="getBrightness")
            {
              covx dim,tTmp.txt,0,0
              tSend.txt="event,getBrightnessResponse,"+tTmp.txt
              //send calc crc
              btlen tSend.txt,sys0
              crcrest 1,0xffff // reset CRC
              crcputh 55 bb
              crcputs sys0,2
              crcputs dim,0
              //send cmd
              printh 55 bb
              prints sys0,2
              prints tSend.txt,0
              prints crcval,2
            }
```

With the above code I am able to call the command `CustomSend getBrightness` in order to get the current brightness level.

So far so good, but I was thinking about the other possibility: Instead of polling the brighness level periodically the HMI could send an event whenever the brighness level changes (when dim value is modified in Nextion).

What do you think?

**Comment by joBr99** [comment]
It should be possible to assume the dim level from the existing commands aswell.

~If you are seeing `event,sleepReached,somecard` you can assume that the panel is on the sleep value.~

Even simpler: monitor the pageType Commands sent by the appdaemon backend. 
If the last value of the pagetype is screensaver you can assume that the panel is in the dim value for sleep, on the other values you can assume that it isn't.

**Comment by soyxan** [comment]
The problem is that even I can know that the screensaver is shown, the screensaver brightness could be different based on the configuration.

For instance, I am using the following configuration:
```
    sleepBrightness:
      - time: "sunrise"
        value: 20
      - time: "sunset"
        value: 1
```

Also the `sleepOverride `could modify the brightness level of the screensaver:
```
    sleepOverride:
      entity: light.luces_salon
      brightness: 10
```

**Comment by joBr99** [comment]
yes, but they are sent to the panel though the dimmode command aswell, so you can listen to them aswell

**Comment by soyxan** [comment]
Ok, so you suggest listening to the following commands on the `CustomSend `topic:

`dimmode~10~100~6371` (to know the brightness level, being 10 for screensaver and 100 for screen active)
`pageType~screensaver` (to know that the screensaver is shown, then based on teh above command, brightness = 10)
`pageType~cardXXX`  (to know that the screen is active, then based on the first command, brightness = 100)

Any other command that I should consider?

**Comment by joBr99** [comment]
no, that should be everything you need

**Comment by soyxan** [comment]
BTW, I was checking for the dimmode command, and I saw that it was issued around 20:06 (Spanish time) but the sunset in Madrid is at 21.10. Even the sun entity in HA says that the sun is over the horizon. Where is getting appadaemon the sun status?

My sleepBrightness config is as follows:
```
    sleepBrightness:
      - time: "sunrise"
        value: 20
      - time: "sunset"
        value: 1
```

**Comment by joBr99** [comment]
https://appdaemon.readthedocs.io/en/latest/HASS_TUTORIAL.html#sunrise-sunset-lighting

Not sure, you probably need to check appdaemons source code. But I think it was possible to do stuff like `sunset+1:00`

**Comment by soyxan** [comment]
I started to implement this solution but then I faced the following problem: If I subscribe using `mqtt.subscribe()` to the `cmnd/XXX/CustomSend` topic from my berry script then the command is not received by NsPanel berry script.

Do you think of another way to "sniff" CustomSend command without interfering with your script?

**Comment by joBr99** [comment]
I'm not sure if you can overwrite the CustomSend Command. (If you are using the tapp version of the berry driver, you might be able to write completly seperate autoexec.be and register the CustomSend Command there another time "proxying" the original command.

Switching to the tapp version of the berry driver: `UpdateDriverVersion https://raw.githubusercontent.com/joBr99/nspanel-lovelace-ui/main/tasmota/nsp-lovelace-driver.tapp`

The TAPP version is freeing up the "autoexec.be" and should be loaded before autoexec.be if I remember correctly.

https://github.com/joBr99/nspanel-lovelace-ui/blob/main/tasmota/autoexec.be#L457
https://github.com/joBr99/nspanel-lovelace-ui/blob/main/tasmota/autoexec.be#L463

If you want to modify the existing script you can grab the payload somewhere in the call stack of CustomSend.

**Comment by soyxan** [comment]
Thanks for the suggestion. I was already suing the tapp driver (In fact I was the one who requested that feature :) )

As you suggest I could handle the CustomSend command to my berry script with `tasmota.add_cmd(`) but then, it will no longer be received by your driver. How can i resend the command to your driver without modifying your code?

**Comment by joBr99** [comment]
Did you try calling `nextion.send(payload)` within your overwritten implementation of the CustomSend Command?

**Comment by soyxan** [comment]
Calling `nextion.send()` works, but I finally implemented the app in AppDaemon. I think is the best way to do it that and do not interfere with your commands.

My appDaemon app is just estimating the dim level based on the commands published and then sending the dim value to my berry script.

Thanks for your support.
