### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by oe8bck** [joBr99/nspanel-lovelace-ui#958]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[x] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide a screenshot of your tasmota mqtt configuration:

13:41:46.383 CMD: FlashNextion http://nspanel.pky.eu/lui-release.tft
13:41:46.396 MQT: stat/tasmota_NSPanel/RESULT = {"FlashNextion":"Done"}
13:41:46.488 FLH: host: nspanel.pky.eu, port: 80, get: /lui-release.tft
13:41:47.142 FLH: Send (High Speed) flash start
13:41:47.504 MQT: tele/tasmota_NSPanel/RESULT = {"Flashing":{"complete": 0, "time_elapsed": 0}}
13:41:48.098 FLH: host: nspanel.pky.eu, port: 80, get: /lui-release.tft
13:41:48.596 MQT: tele/tasmota_NSPanel/RESULT = {"Flashing":{"complete": 85, "time_elapsed": 1}}
13:41:49.901 MQT: tele/tasmota_NSPanel/RESULT = {"Flashing":{"complete": 86, "time_elapsed": 2}}
13:41:52.406 MQT: tele/tasmota_NSPanel/RESULT = {"Flashing":{"complete": 87, "time_elapsed": 5}}
13:41:54.601 MQT: tele/tasmota_NSPanel/RESULT = {"Flashing":{"complete": 88, "time_elapsed": 7}}
13:41:56.907 MQT: tele/tasmota_NSPanel/RESULT = {"Flashing":{"complete": 89, "time_elapsed": 9}}
13:41:59.100 MQT: tele/tasmota_NSPanel/RESULT = {"Flashing":{"complete": 90, "time_elapsed": 11}}
13:42:01.601 MQT: tele/tasmota_NSPanel/RESULT = {"Flashing":{"complete": 91, "time_elapsed": 14}}
13:42:03.788 MQT: tele/tasmota_NSPanel/RESULT = {"Flashing":{"complete": 92, "time_elapsed": 16}}
13:42:06.001 MQT: tele/tasmota_NSPanel/RESULT = {"Flashing":{"complete": 93, "time_elapsed": 18}}
13:42:08.487 MQT: tele/tasmota_NSPanel/RESULT = {"Flashing":{"complete": 94, "time_elapsed": 21}}
13:42:10.619 MQT: tele/tasmota_NSPanel/RESULT = {"Flashing":{"complete": 95, "time_elapsed": 23}}
13:42:12.901 MQT: tele/tasmota_NSPanel/RESULT = {"Flashing":{"complete": 96, "time_elapsed": 25}}
13:42:15.101 MQT: tele/tasmota_NSPanel/RESULT = {"Flashing":{"complete": 97, "time_elapsed": 27}}
13:42:17.592 MQT: tele/tasmota_NSPanel/RESULT = {"Flashing":{"complete": 98, "time_elapsed": 30}}
13:42:19.802 MQT: tele/tasmota_NSPanel/RESULT = {"Flashing":{"complete": 99, "time_elapsed": 32}}
13:42:24.580 NXP: Screen Initialized
13:42:24.689 MQT: tele/tasmota_NSPanel/RESULT = {"CustomRecv":"event,startup,51,eu"}
13:42:30.489 MQT: tele/tasmota_NSPanel/RESULT = {"CustomRecv":"event,startup,51,eu"}
13:42:36.387 MQT: tele/tasmota_NSPanel/RESULT = {"CustomRecv":"event,startup,51,eu"}
13:42:42.788 MQT: tele/tasmota_NSPanel/RESULT = {"CustomRecv":"event,startup,51,eu"}

- [ ] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:


I am using ioBroker

- [ ] Provide your apps.yaml:
```
  apps.yaml here:

I am using ioBroker

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:

I am using ioBroker

```

### ADDITIONAL INFORMATION

For me it looks like that the upload to the Nextion starts at 85%, also the time is very short of this uploiad. The first time it worked and took ~5 minutes. Now it's done in some seconds.

Is there a possibility to erase the Nextion flash?

**Comment by joBr99** [comment]
Nextion flash starting at 85% is expected behaviour if there are no changes to the images or fonts within the firmware.

With `{"CustomRecv":"event,startup,51,eu"}` messages in the tasmota log the nextion and berry driver is working fine.

**Comment by joBr99** [comment]
Without further information nobody is going to be able to tell you what's going on. 
You will need to provide some information about the script stuff you configured on iobroker and the mqtt on tasmota. 
I would recommend to ask here, there are way more people looking for ioBroker stuff than here.

https://forum.iobroker.net/topic/58170/sonoff-nspanel-mit-lovelace-ui/3453

**Comment by oe8bck** [comment]
Now I got it set up correctly, I had an issue with the  MQTT setting. The info that this message is normal brought me back on ttrack.

Thanks for your support!
