### ISSUE TITLE
[BUG] Fail to update to v4.2.0: stuck screen, failure logs

### ISSUE THREAD

**Issue by nareddyt** [joBr99/nspanel-lovelace-ui#962]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

When I try to update the NSPanel to the latest TFT via wireless flash, the flash is not successful (see logs below) and the nspanel restarts.

After restart, NSPanel screen is stuck on "Display update available!" screen. UI is responsive to button presses, but nothing actually happens in the backend after pressing the buttons. Seems like the screen is just stuck.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide your apps.yaml (or your config):
```
master-nspanel:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/master-nspanel/RESULT"
    panelSendTopic: "cmnd/master-nspanel/CustomSend"
    model: "us-l"
    dateFormat: "%A, %B %-d %Y"
    timeFormat: "%I:%M   ?%p"
    sleepTimeout: 60
    screensaver:
      entity: weather.home
      weatherUnit: "fahrenheit"
      theme:
        autoWeather: true
    cards:
      - type: cardEntities
        entities:
          - entity: sensor.master_bedroom_temperature_temperature
            name: "Bedroom Temperature"
          - entity: sensor.master_bedroom_temperature_humidity
            name: "Bedroom Humidity"
          - entity: switch.master_nspanel_fan_relay_2
            name: "Fan"
          - entity: light.master_bedroom
            name: "Tap to change colors"
            color: [255, 255, 0]
        title: "Master Bedroom"
```
- [x] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:

Nothing useful in AppDaemon logs as flashing is via manual service call. AppDaemon works fine.

NSPanel device logs:
```
[00:33:57][D][nspanel_lovelace:119]: Sending: DRAKJHSUYDGBNCJHGJKSHBDN
[00:33:57][D][nspanel_lovelace:119]: Sending: recmod=0
[00:33:57][D][nspanel_lovelace:119]: Sending: recmod=0
[00:33:57][D][nspanel_lovelace:119]: Sending: connect
[00:33:57][D][nspanel_lovelace_upload:150]: Connected
[00:33:57][D][nspanel_lovelace_upload:156]: Requesting URL: http://nspanel.pky.eu/lovelace-ui/github/nspanel-us-l-v4.2.0.tft
[00:33:57][D][nspanel_lovelace_upload:188]: Updating Nextion
[00:33:57][D][nspanel_lovelace:119]: Sending: whmi-wris 10000348,921600,1
[00:33:57][C][uart.arduino_esp32:077]: Setting up UART...
[00:33:57][D][nspanel_lovelace_upload:213]: Waiting for upgrade response
[00:33:59][D][nspanel_lovelace_upload:218]: Upgrade response is []
[00:33:59][D][nspanel_lovelace_upload:223]: preparation for tft update failed 0 ""
[00:33:59][D][nspanel_lovelace_upload:276]: Restarting Nextion
[00:33:59][D][nspanel_lovelace:119]: Sending: rest
[00:34:01][D][nspanel_lovelace_upload:279]: Restarting esphome
```

### TO REPRODUCE
_Steps to reproduce the behavior:_

Flash latest release on NSPanel.

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

Flash succeeds like previous releases.

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

- NSPanel initial version
- Integrated via ESPHome using https://github.com/sairon/esphome-nspanel-lovelace-ui, not tasmota
- US-L

**Comment by nareddyt** [comment]
Actually probably has nothing to do with this project, could be an ESPHome issue.

https://github.com/esphome/issues/issues/3519

**Comment by joBr99** [comment]
Not related to this project, maybe you need to use a previous response version or a different framework.

Afaik is the code to flash the TFT copy pasted to the component for Lovelace.

https://github.com/sairon/esphome-nspanel-lovelace-ui

**Comment by joBr99** [comment]
Not really sure why lovelace is mentioned in this esphome issue, sounds like they used tasmota with my project instead of esphome.

Take a look at 

https://github.com/sairon/esphome-nspanel-lovelace-ui/issues/26
and
https://github.com/sairon/esphome-nspanel-lovelace-ui/issues/27
