### ISSUE TITLE
[Feature Request] CardGrid2 - optimize text-width

### ISSUE THREAD

**Issue by kuckuckmann** [joBr99/nspanel-lovelace-ui#964]
### FEATURE DESCRIPTION
With the opportunity of 8 items at CardGrid2 the relation between field width and text-size is unproportunal. 
A minimal text-digit of 4 should be displayable in relation to the field width.
Maybe it's possible to let the text be resized in relation to its digits?
In my specific example I am talking about temperatures with 1 decimal (for example 24.5).

![CardGrid2_Temp1](https://github.com/joBr99/nspanel-lovelace-ui/assets/99131208/0a1355c8-76b1-4b8d-9cc9-812901d84bd7)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU-Panel, Tasmota 12.1, TFT 52

**Comment by joBr99** [comment]
There is no way do dynamically change the font size in nextion.

The only option would be to change the font to a smaller one if the text is longer than X chars. The only downside is that not all of the chars have the same width. So there might be cases where this is changing the font too early or too late.

**Comment by kuckuckmann** [comment]
Well, isn't it the best case to take a wide character and create the width in depency of the amount of digits from 1 digit to 4 digits.
So taking care that 4 digits with the maximum width possible can be displayed well?

**Comment by joBr99** [comment]
for cardgrid2 we would need to change the font to a smaller one if the text is longer than 2 chars

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/9c879681-18d2-4316-8036-714c7c4d8a1e)

**Comment by joBr99** [comment]
I've implemented a way to force the panel to change the font on the icons.

`XXX¬0`
`XXX¬3`
`XXX¬4`

in case the 2nd last char is an `¬` it will pull the number after it and set it as font and then remove the last 2 chars from the string

**Comment by Armilar** [comment]
Implemented in v4.2.1.2 (ioBroker) - User with pageItem-parameter: fontsize (0-4)
