### ISSUE TITLE
[Feature Request]  Hide/Show Elements Based on state

### ISSUE THREAD

**Issue by dannyv1101** [joBr99/nspanel-lovelace-ui#969]
### FEATURE DESCRIPTION
It wold be nice to have a table page, wich can show for example wich batteries are running out of power, or wich windows and doors are open. 
The names of this elements could be pointed out with a little blocky and be saved in a datapoint. So all names (maybe 8) could be shown on the panel and a little icon may an empty batterie or so. 

This would be very good for me to have this!

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/a6c8c8a0-47ac-49c2-8d92-ebd922222fc3)
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/6453c0ef-fcb4-404c-8995-b7117946e6af)
Certainly possible with '%' as unit aswell.

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/09837b55-0e0a-4412-be50-b0f6cbd45ceb)
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/6531ce8c-eeed-4201-9bd2-40ec365f17d8)

**Comment by dannyv1101** [comment]
Yes but there I see all batteries or windows. I just want to see the batteries wich are lower then maybe 10%, or windows wich are open.

**Comment by joBr99** [comment]
This is a feature that has to be implemented on the backend. 

On home assistant this is already implemented:
This will only show the item if the state is equal "open".
```
      - entity: binary_sensor.window1
        state: "open"
      - entity: binary_sensor.window2
        state: "open"
``` 

https://docs.nspanel.pky.eu/entities/#override-icons-or-names

**Comment by Armilar** [comment]
Is there anyone who needs this feature for ioBroker? Is not very trivial due to the assignment of the aliases.

@dannyv1101: Do you use HA or ioBroker? Can't find out here

**Comment by dannyv1101** [comment]
I have iobroker.

**Comment by Armilar** [comment]
In principle one could use the blockly of the garbage script with the alias warning.

**Comment by dannyv1101** [comment]
Ok I will have a look and give it a try.

**Comment by Armilar** [comment]
Super... You can actually better describe your questions in the ioBroker forum. You get support for Blockly questions much faster there than here.

https://forum.iobroker.net/topic/58170/sonoff-nspanel-mit-lovelace-ui/3616?_=1693517785582
