### ISSUE TITLE
[Help] Icon + entity value in the screensaver statusIconX

### ISSUE THREAD

**Issue by soyxan** [joBr99/nspanel-lovelace-ui#970]
Is it possible to show and mdi icon and an entity value for the `statusIconX `in the screensaver.

Something similar to what is shown in the `screensaver2 `example from the docs with the heating icon and 22.3ºC value on the bottom right:

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/8955206/a917edc7-632b-4b4d-a19c-f8f94f396555)

Thanks!

**Comment by joBr99** [comment]
Yes, you need a template that is returning the icon and your value:

So a combination of thoose two examples from the docs.

```
 statusIcon2:
        entity: climate.wohnzimmer_boden
        icon: 'ha:{{ state_attr("climate.wohnzimmer_boden","current_temperature")}}'
```

```
        icon: 'ha:{{ iif(is_state('light.kitchen', 'on'), '<I>mdi:flashlight</I>', '<I>mdi:flashlight-off</I>') }}'
```

https://docs.nspanel.pky.eu/entities/#override-icons-or-names

You can try ha templates in the developer tools of homeassistant.


Your template might looks like this (untested):

```
        icon: 'ha:{{ iif(state_attr("climate.bad_boden", "hvac_action")=="heating", '<I>mdi:flashlight</I>', '') state_attr("climate.bad_boden","current_temperature")}}'
```

**Comment by soyxan** [comment]
Thanks a lot! The only thing you were missing in your template example was the "+" before `state_attr`:

`icon: 'ha:{{ iif(state_attr("climate.bad_boden", "hvac_action")=="heating", '<I>mdi:flashlight</I>', '') + state_attr("climate.bad_boden","current_temperature")}}'`
