### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by 0St0n30** [joBr99/nspanel-lovelace-ui#971]
### FEATURE DESCRIPTION
Show temperature on Screesaver on the statusIcons.
### ADDITIONAL CONTEXT
Now if you add a Temperature to the Screensaver as a statusIcon it only Shows the "Icon".
### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
You can change the icon to the value with a template

https://docs.nspanel.pky.eu/entities/#possible-configuration-values-for-entities-key

Also see #970
