### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by mixedbreed** [joBr99/nspanel-lovelace-ui#974]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._

Show different card by sending mqtt command. E.g only show simpler card with basic functionality when home is in guest mode.
### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
You can change the default Card after exiting the screensaver dynamically with a template:
<html>
<body>


defaultCard | True | string | None | default page after exiting screensaver; only works with top level cards defined in cards; needs to be a navigation item, see subpages (navigate.type_key) This config option will also be evaluated as a HomeAssistant Template.
-- | -- | -- | -- | --



</body>
</html>
https://docs.nspanel.pky.eu/config-screensaver/#possible-configuration-values-for-screensaver-config

And you can hide entiies on pages with state_template aswell: 
https://docs.nspanel.pky.eu/entities/#hide-item-based-on-ha-template

**Comment by mixedbreed** [comment]
I’m uncertain how I can change defaultCard dynamic based on e.g guest mode switch turned on/off. Could you please give an example? Need this specific for a guest/granny mode. Thanks for the help, much appreciated!

**Comment by joBr99** [comment]
You need some entity in homeassistant that you can use to switch between the modes, for example an input boolean. 

```
      defaultCard: '{{ "navigate.card1" if is_state("input_boolean.test", "on") else "navigate.card2" }}'
```

and you need to have `key: card1` / `key: card2` defined on the cards you want to navigate to.

**Comment by mixedbreed** [comment]
Works perfectly! Thanks!
