### ISSUE TITLE
[BUG] Flash TFT 4.3.1 Funktioniert nicht

### ISSUE THREAD

**Issue by Michel83** [joBr99/nspanel-lovelace-ui#979]
Beim Flachen auf die TFT Firmware 4.3.1 folgende Fehlermeldung :

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/36561525/36253973-06c3-422e-9f22-843743e5e286)

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/36561525/6bd9271f-d867-48ba-b118-361a636d0315)

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/36561525/e07d4de5-1d46-4568-b3a9-78d4aa4b951e)

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/36561525/480fcdfd-8e7f-4d9c-b900-a511f87cd7b8)

Nach einem Neustart Funktioniert dass Panel wieder normal.

**Comment by joBr99** [comment]
Bitte Internetverbindung von dem Panel prüfen, da stimmt was nicht entweder Firewall Regel, fehlender DNS Server oder fehlendes Gateway.

**Comment by Michel83** [comment]
Das war es, es Funktioniert ich hatte echt nach allem geschaut. Der DNS war weg................
