### ISSUE TITLE
[BUG] UI Issues after Update to V4.3.1

### ISSUE THREAD

**Issue by tekkiebros** [joBr99/nspanel-lovelace-ui#980]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
Since I updated to version 4.3.1 my NSPanel display does not work anymore, the UI is some kind of broken (see pictures below).
I already downgraded to v4.2.0 but it didn't help. Therefore I decided to reflash Tasmota, but in the end this didn't solve the problem.
Therefore I changed the system from Tasmota to ESPHome but after doing everything successfully, the issue still exists.

Several times I restarted and re-created the AppDeamon Container, but the issue still exists.
I changed my apps.yaml file to very basic version, I expect three simple switch toggles -> same issue.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide your apps.yaml (or your config):
```
  nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel01/RESULT"
    panelSendTopic: "cmnd/nspanel01/CustomSend"
    model: eu
    sleepTimeout: 20
    locale: "de_DE"
    screensaver:
      type: screensaver
      entity: weather.home
    cards:
      - type: cardEntities
        title: Test Entities Card
        entities:
          - entity: input_boolean.sommerbetrieb
          - entity: input_boolean.unterwegs
          - entity: input_boolean.office
        


```
- [x] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
2023-09-27 16:41:54.511352 INFO nspanel-1: MQTT callback for: {'topic': 'tele/nspanel01/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,screensaver,bExit,1"}'}
2023-09-27 16:41:54.511910 INFO nspanel-1: Received Message from Screen: event,buttonPress2,screensaver,bExit,1
2023-09-27 16:41:54.512440 INFO nspanel-1: Button Press Event; entity_id: screensaver; button_type: bExit; value: 1 
2023-09-27 16:41:54.512996 INFO nspanel-1: Started rendering of page 0 with type cardEntities
2023-09-27 16:41:54.513597 INFO nspanel-1: Sending MQTT Message: pageType~cardEntities
2023-09-27 16:41:54.519116 INFO nspanel-1: Sending MQTT Message: entityUpd~Test Entities Card~0|0~switch~input_boolean.sommerbetrieb~���~65222~Sommerbetrieb~1~switch~input_boolean.unterwegs~���~17299~Unterwegs~0~switch~input_boolean.office~���~17299~Office~0



```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

![IMG_5564 Klein](https://github.com/joBr99/nspanel-lovelace-ui/assets/46320286/61530bae-77ad-4a6d-8afb-073f54d97f7b)
![IMG_5563 Klein](https://github.com/joBr99/nspanel-lovelace-ui/assets/46320286/70930c10-736d-4a72-b3bd-156f09a5be82)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

-> EU

**Comment by joBr99** [comment]
Looks like you have a mismatch between your appdaemon backend and the firmware on the nextion display.

Update to the latest version and reflash the firmware on the nextion screen.

On tasmota you can do it with this command:

FlashNextion http://nspanel.pky.eu/lui-release.tft

**Comment by tekkiebros** [comment]
Thanks for your help! You are right, somehow I messed up the appdaemon versions... after I updated nspanel-lovelace-ui folder everything is working again"
