### ISSUE TITLE
[BUG] TypeScript compilation failed // iobroker

### ISSUE THREAD

**Issue by philipp1987** [joBr99/nspanel-lovelace-ui#981]
### PROBLEM DESCRIPTION
the ns panel is frozen. After I made some updates to the system and the iobroker host yesterday evening, the ns panel stopped working. When I start the script I get the error message: 

**script.js.NS_Panel-Wohnbereich.NsPanelTs: TypeScript compilation failed: if ((pageItem.useColor || useColors) && ((typeof (value) === 'boolean' && value) || value > (pageItem.minValueBrightness !== undefined ? pageItem.minValueBrightness : 0))) { ^ERROR: Operator '>' cannot be applied to types 'number | boolean' and 'number'.**

It's been a while since I've dealt with this topic. That's why I'm looking for help here. Thanks in advance

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
I use the iobroker and have restarted the Raspberry and also the responsible instances and the scripts.

### PANEL / FIRMWARE VERION
12.1.1 - US-P

**Comment by Armilar** [comment]
See https://github.com/joBr99/nspanel-lovelace-ui/issues/929

Fixed with v4.1.4.1
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/102996011/3cdfd11a-3141-4463-a39f-78e5056f5691)

Please Use Release > 4.1.4

**Comment by philipp1987** [comment]
> See #929
> 
> Fixed with v4.1.4.1 ![image](https://user-images.githubusercontent.com/102996011/272080877-3cdfd11a-3141-4463-a39f-78e5056f5691.png)
> 
> Please Use Release > 4.1.4

Sorry, I'm not sure what to update. It's been a long time since I set this all up

**Comment by Armilar** [comment]
which script version?

**Comment by philipp1987** [comment]
> which script version?

ah okay, jetzt weiß ich wovon du redest. 
Muss ich nach dem Copy&Past meine Seiten neu anlegen?

**Comment by Armilar** [comment]
Kommt darauf an, welche Version des Scriptes installiert ist. In der Regel (falls die installierte Script Version noch nicht uralt), würde es reichen, den unteren Teil auszutauschen. Daher die Frage nach deiner installierten Version 😉

**Comment by Armilar** [comment]
https://forum.iobroker.net/post/1054903

Erst gestern die gleiche Frage

**Comment by Armilar** [comment]
Kommt darauf an. Wenn es nur um diesen Fehler geht, dann kannst du auch im #929 nachsehen. Code von Gargano suchen und austauschen. Falls du aber auf die v4.3.1.4 möchtest, ist es etwas mehr Arbeit. Am besten kurz zum IoBroker Forum wechseln. Da geht alles schneller. Bin diese Woche nur schwer erreichbar.

**Comment by Armilar** [comment]
TypeScript wird wirklich immer restriktiver. Daher solltest du irgendwann auch das Script-Update vornehmen

**Comment by philipp1987** [comment]
okay, dann werde ich wohl oder übel jetzt den komplizierten weg gehen und habe dann hoffentlich lange ruhe. Vielen Dank auf jeden fall für deinen großartigen support.
