### ISSUE TITLE
[Feature Request] Actionable notification screen

### ISSUE THREAD

**Issue by antibill51** [joBr99/nspanel-lovelace-ui#985]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._
Add action buttons to the notification screen.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
For example, I use a notification reminding me to take the trash out/in for pickup.
It would be nice to be able to confirm the execution of this task, so as to no longer resend the notification several times during the day.

Example : 
```
service: mqtt.publish
data:
  topic: cmnd/NsPanel_7DEE08/Backlog
  payload: >-
    CustomSend pageType~popupNotify; CustomSend entityUpdateDetail~id~{{ title
    }}~2000~~~~~{{ message }}~2000~{{ timeout }}~3~{{ icon }}~2000~{{ button1 }}~{{ event1 }}~{{ button2 }}~{{ event2 }};
```
The event could either be sent directly to HA (event platform), or sent by mqtt and handled on HA by monitoring MQTT messages, or any other way?

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU

**Comment by joBr99** [comment]
You can simply use button1 or button2  for that.

**Comment by antibill51** [comment]
Thanks, is there a way to know if a notification is displayed on the NSPanel from HA to change the assignment of buttons 1 and 2 only in this case?

**Comment by joBr99** [comment]
The text of `event1` and `event2` is sent with the message on clicking the button.
