### ISSUE TITLE
[Help] node-red dev

### ISSUE THREAD

**Issue by laluz742** [joBr99/nspanel-lovelace-ui#986]
### PROBLEM DESCRIPTION

Coded an initial basic implementation for node-red. Though I love it.... I don't have too much time to spare.
Do you want to add my implementation into your lovelace-ui repo thus others can try and contribute?

Sorry about contacting you this way, but didn't find any other way.

Sebastian

**Comment by joBr99** [comment]
This project was actually initially based on a nodered flow, but no put it into your own repo, I'm happy to Link it in the readme.

**Comment by laluz742** [comment]
here it is: 
https://github.com/laluz742/node-red-contrib-nspanel-lui

**Comment by joBr99** [comment]
There is acually another node-red backend:

https://github.com/m-schaeffler/node-red-nspanel

**Comment by laluz742** [comment]
Yeppers, but no nodes implemented yet. Just helpers for scripting
