### ISSUE TITLE
[Feature Request] custom colors on screensaver

### ISSUE THREAD

**Issue by hatran0884** [joBr99/nspanel-lovelace-ui#99]
Hi
in my view, the NSPanel is getting almost perfect. now i will only want to make the screensaver more colorful, i found it a little bit monotonous with black background and while text only, so i am thinking you can colorize the sensor info to distingush it from the forecast info ? or it would be even better if the date can have a different color from the time. i can choose the color we want from the config. 
let me know your view. 
![JPEG image 4](https://user-images.githubusercontent.com/58875735/160831170-a121b113-8b66-42a6-b196-9b65d8eba34f.jpeg)

**Comment by joBr99** [comment]
there is now a serial command for changing the colors on the screensaver (no implementaion in appdamon so far)

`color~background~time~timeAMPM~date~tMainIcon~tMainText~tForecast1~tForecast2~tForecast3~tForecast4~tF1Icon~tF2Icon~tF3Icon~tF4Icon~tForecast1Val~tForecast2Val~tForecast3Val~tForecast4Val~bar~tMainIconAlt~tMainTextAlt~tMRIcon~tMR`

**Comment by hatran0884** [comment]
so I will have to update the berry driver to support this ?

**Comment by joBr99** [comment]
No, you can send this over mqtt with the tasmota CustomSend command

You can try it also on tasmota console just try sending CustomSend~4444~5555~6666

If you want to have something more mature, you could send this command via nodered after you see the timeout command on the mqtt result topic

**Comment by hatran0884** [comment]
but it seems at the moment changing colors is limited to the background of the screensaver, isnt it ?
is it possible to change the color of each item in screensaver like weather, date, time ?

**Comment by joBr99** [comment]
Yes, you can change each item first argument is background, second time and so on

**Comment by joBr99** [comment]
this won't change, I'm not planning to make this persistent

**Comment by Dattel** [comment]
:-( 
so you spend time on a "feature" that never comes alive and no one (except the trash can reminder) will ever use it...
I will persuade you on discord next time :-p

**Comment by joBr99** [comment]
why does it need to be persistent on the screen itself? I can just send the color message at the time where I send the weatherUpd Message

**Comment by woody166** [comment]
HI, can you provide an example of how you would use the CommandSend to change the colour of an item, when I use the example above "CustomSend~color~4444~5555~6666" from the tasmota console, it doesn't seem to do anything.

**Comment by joBr99** [comment]
There is a space after custom send stead of a ~

**Comment by joBr99** [comment]
screensaver config supports now a config option to set the colors

```
    screensaver:
      entity: weather.k3ll3r
      color: "4444~5555~6666"
```

It is sending the configured string as it is to the panel on rendering of the screensaver, there is no fancy config option for each color.

`background~time~timeAMPM~date~tMainIcon~tMainText~tForecast1~tForecast2~tForecast3~tForecast4~tF1Icon~tF2Icon~tF3Icon~tF4Icon~tForecast1Val~tForecast2Val~tForecast3Val~tForecast4Val~bar~tMainIconAlt~tMainTextAlt~tMRIcon~tMR`

The colors have to be RGB565 in decimal.
