### ISSUE TITLE
[BUG] Timezone config not working

### ISSUE THREAD

**Issue by mathis92** [joBr99/nspanel-lovelace-ui#991]
### PROBLEM DESCRIPTION
I an not able to configure time to be correctly shown on screensaver. It still shows the UTC and doesn't take the TZ configures on RPI, running in docker. Homeassistant is showing correct time. 

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
![Capture3](https://github.com/joBr99/nspanel-lovelace-ui/assets/6921946/25aa6f87-125d-48aa-aff2-fecd7654db4b)
![Capture4](https://github.com/joBr99/nspanel-lovelace-ui/assets/6921946/51dc1586-8f01-4cc9-bab3-99408eb0fe8b)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
timezone of the home assistant container doesn't matter, check the timezone of the app daemon container

**Comment by rwagoner** [comment]
I had the same issue. The fix was to set the timezone in appdaemon.yaml
```
appdaemon:
  time_zone: America/New_York
```

**Comment by joBr99** [comment]
It's one of thoose two things:

Timezone in appdaemon.yaml

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/95d963b1-5741-4f6f-8872-a0bd99a39357)

or in case of a standalone docker container without Homeassistant OS, it could be the docker container itself aswell:

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/78b05155-3cb4-45fd-8f88-744cc9515fae)

**Comment by W3AXL** [comment]
Having a similar issue with my NSPanel - AppDaemon (via docker) is using the right time for the container but is sending the wrong time via MQTT to the panel:

Current time is 20:29 as seen by the log timestamp, but the app is still sending 01:29 (UTC) for some reason:
```
2023-11-05 20:29:00.708999 INFO nspanel-lr: Sending MQTT Message: time~01:29~
```

AppDaemon config shows the correct timezone:
```yaml
appdaemon:
  ...
  time_zone: America/Indiana/Indianapolis
  ...
```

And I'm also passing the TZ variable to the HA docker container as well. Not sure where else the issue could be.

**Comment by joBr99** [comment]
try adding this volume to your docker container:

```
-v /etc/localtime:/etc/localtime:ro
```

https://appdaemon.readthedocs.io/en/dev/DOCKER_TUTORIAL.html#timezones

**Comment by W3AXL** [comment]
That did it! I had that on the HA container but not the appdaemon container. Interesting that the log timestamps were still correct inside the container despite that missing, unless those timestamps are added from the host's local time.

Thanks!
