### ISSUE TITLE
[Feature Request] Add swipe to change pages

### ISSUE THREAD

**Issue by rwagoner** [joBr99/nspanel-lovelace-ui#992]
### FEATURE DESCRIPTION
Add the ability to change pages by using swipe as an alternative to the back and forward buttons. This in my opinion would give the interface navigation a modern feel.

### PANEL / FIRMWARE VERION
US-P

**Comment by joBr99** [comment]
You can swipe from the edges, as there are invisible buttons placed at the edges of the screen.

A real swipe isn't supported by the nextion panel.
