### ISSUE TITLE
[BUG] Text is being truncated if long entity names are used

### ISSUE THREAD

**Issue by rossi75** [joBr99/nspanel-lovelace-ui#999]
### PROBLEM DESCRIPTION
using four long-named entities on an EntitiesCard, the last one is not being displayed. Took a look into the AppDaemon logs, the last entry is still being sent. Took a look into the Console log, the last entry arrives at the NSPanel completely. Shorting the naming for the action [A|B|C|D] results in cutting the name entry, see Screenshot attached.
Anyway, pressing the unseen entry performs the desired action.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:
===============================================================
      - type: cardEntities
        title: Elemente Reset
        key: CardBrunhilde_3
        navItem1:
          entity: navigate.Home
          icon: mdi:home
        navItem2:
          entity: navigate.CardBrunhilde_1
          icon: mdi:arrow-right-bold
        entities:
          - entity: button.roborock_s7_pro_ultra_reset_side_brush_consumable
            icon: mdi:brush
            name: 'Hauptbürste {{ int(states("sensor.roborock_s7_pro_ultra_main_brush_left")) // 10800 }}%'
            value: 'A'
          - entity: button.roborock_s7_pro_ultra_reset_side_brush_consumable
            icon: mdi:star-three-points
            name: 'Seitenbürste {{ int(states("sensor.roborock_s7_pro_ultra_side_brush_left")) // 7200 }}%'
            value: 'B'
          - entity: button.roborock_s7_pro_ultra_reset_filter_consumable
            icon: mdi:air-filter
            name: 'Staubfilter {{ int(states("sensor.roborock_s7_pro_ultra_filter_left")) // 5400 }}%'
            value: 'C'
          - entity: button.roborock_s7_pro_ultra_reset_sensor_consumable
            icon: mdi:eye-outline
            name: 'Sensoren {{ int(states("sensor.roborock_s7_pro_ultra_sensor_dirty_left")) // 1080 }}%'
            value: 'D'

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
2023-10-24 12:01:06.650234 INFO nspanel: Sending MQTT Message: entityUpd~Elemente Reset~button~navigate.Home~���~17299~Thea & Olly~Dr��cken~button~navigate.CardBrunhilde_1~���~17299~Brunhilde II - Aktionen~Dr��cken~button~button.roborock_s7_pro_ultra_reset_side_brush_consumable~���~17299~Hauptb��rste 97%~A~button~button.roborock_s7_pro_ultra_reset_side_brush_consumable~���~17299~Seitenb��rste 95%~B~button~button.roborock_s7_pro_ultra_reset_filter_consumable~���~17299~Staubfilter 94%~C~button~button.roborock_s7_pro_ultra_reset_sensor_consumable~���~17299~Sensoren 100%~D

MQTT-Log from NSPanel Console:
----------------------------------------------------------------
11:36:45.707 SRC: MQTT
11:36:45.709 CMD: Grp 0, Cmd 'CUSTOMSEND', Idx 1, Len 508, Pld -99, Data 'entityUpd~Elemente Reset~button~navigate.Home~~17299~Thea & Olly~Drücken~button~navigate.CardBrunhilde_1~~17299~Restzeiten Bürsten~Drücken~button~button.roborock_s7_pro_ultra_reset_side_brush_consumable~~17299~Hauptbürste 97%~A~button~button.roborock_s7_pro_ultra_reset_side_brush_consumable~~17299~Seitenbürste 95%~B~button~button.roborock_s7_pro_ultra_reset_filter_consumable~~17299~Staubfilter 94%~C~button~button.roborock_s7_pro_ultra_reset_sensor_consumable~~17299~Sensoren 100%~D'
11:36:45.726 BRY: GC from 27738 to 18455 bytes, objects freed 146/248 (in 3 ms) - slots from 365/381 to 172/304
11:36:45.777 BRY: GC from 28727 to 18455 bytes, objects freed 214/248 (in 2 ms) - slots from 493/504 to 172/350
11:36:45.826 BRY: GC from 28727 to 18455 bytes, objects freed 214/248 (in 3 ms) - slots from 493/504 to 172/350
11:36:45.875 BRY: GC from 28727 to 18455 bytes, objects freed 214/248 (in 2 ms) - slots from 493/504 to 172/350
11:36:45.926 BRY: GC from 28727 to 18455 bytes, objects freed 214/248 (in 3 ms) - slots from 493/504 to 172/350
11:36:45.998 NXP: payload sent = bytes('55BBFC01656E746974795570647E456C656D656E74652052657365747E627574...')
11:36:46.006 MQT: stat/tasmota_62D204/RESULT = {"CustomSend":"Done"}

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
see above

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
to not truncate the entries

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._
![DSC_1004](https://github.com/joBr99/nspanel-lovelace-ui/assets/91349581/7b7f61e7-e950-4eca-bdaa-90149de62b93)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
using
- HomeAssistant 2023.10.5
- AppsDaemon 0.13.6
- Tasmota 12.3.1 for NSPanel
- NSPanel Lovelace UI 4.3.1

_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
4.3.1 EU

**Comment by joBr99** [comment]
This is a memory limitation on the nextion display.

There is already a abstraction layer implemented in the backend to replace the entity names with something shorter, however it's currently only used for light entities.

https://github.com/joBr99/nspanel-lovelace-ui/blob/40d17f96413ec35893492314f3c98deadb7fb690/apps/nspanel-lovelace-ui/luibackend/pages.py#L400

You can change Line 400 in pages.py to 
```
        if entityType in ["light", "button"]:
```

to use it for buttons aswell.

**Comment by rossi75** [comment]
Works like a charm. Thanks for the hint and for your fast response
